post_install() {
  cat << "EOM"
  ####
  #  Installation done
  #  - Change default configuration in:
  #    /etc/ajenti/config.json
  #
  #  - Launch the server with:
  #    systemctl start ajenti
  #
  #  - WebUI is available at http://<ip>:8000
  ####
EOM
}

post_remove() {
  echo 'Perhaps you want to look in /var/backups , /var/lib/ajenti'
  echo '/etc/ajenti for leftover files. This is where ajenti stores'
  echo 'backups of configuration files and plugins.'
}
