pre_install() {
  /bin/true
}

post_install() {
  echo "-- Don't forget to install gtk or/and gtk2 packages to enable librcc"
  echo "   gui features"
  echo "-- Also you may change /usr/bin/rcc-config symlink to switch between"
  echo "   gtk and gtk2 (rcc-gtk-config and rcc-gtk2-config)"
  /bin/true
}

pre_upgrade() {
  /bin/true
}

post_upgrade() {
  /bin/true
}

pre_remove() {
  /bin/true
}

post_remove() {
  /bin/true
}

