# arg 1:  the new package version
post_install() {
    echo " ::> Please see documentation on CxxTest at"
    echo " ::>   <http://cxxtest.sourceforge.net>"
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  /bin/true
}

# arg 1:  the old package version
pre_remove() {
  /bin/true
}

# arg 1:  the old package version
post_remove() {
  /bin/true
}

op=$1
shift
$op $*
