post_install() {
  cat << EOF
==> To set up Emacs to automatically edit files ending in .lua using Lua-mode
    add the following to your ~/.emacs file (GNU Emacs) or ~/.xemacs/init.el
    file (XEmacs):
    (setq auto-mode-alist (cons '("\\.lua$" . lua-mode) auto-mode-alist))
    (autoload 'lua-mode "lua-mode" "Lua editing mode." t)
EOF
}

post_upgrade() {
  post_install $1
}

op=$1
shift

$op $*
