# arg 1:  the new package version
# arg 2:  the old package version

KERNEL_NAME=-gameshell
KERNEL_VERSION=5.4.0-rc6-1-gs

post_install () {
  # updating module dependencies
  echo ">>> Updating module dependencies. Please wait ..."
  depmod ${KERNEL_VERSION}
}

post_upgrade() {
  # updating module dependencies
  echo ">>> Updating module dependencies. Please wait ..."
  depmod ${KERNEL_VERSION}
}

post_remove() {
  rm -f boot/initramfs-linux.img
}
