# vim: syntax=sh

post_install() {
  post_upgrade $1 ''

  if [ "$(uname -m)" != "x86_64" ]
  then
    echo '==> Warning: the 32 bit version of MongoDB is limited to about 2GB of data.'
    echo '==> See http://blog.mongodb.org/post/137788967/32-bit-limitations'
  fi
}

post_upgrade() {
  if ! getent passwd mongodb >/dev/null
  then
    useradd -r -g daemon -d /var/lib/mongodb -s /bin/bash mongodb
  fi
  chown -R mongodb:daemon /var/lib/mongodb
  chown -R mongodb:daemon /var/log/mongodb
}
