post_upgrade() {
  post_remove $1
}

post_remove() {
  if test -e /usr/lib/python2.6/site-packages/sitecustomize.py
  then
    sed -i -e '/import sys/d' \
	usr/lib/python2.6/site-packages/sitecustomize.py
    sed -i -e '/sys.setappdefaultencoding = sys.setdefaultencoding/d' \
	usr/lib/python2.6/site-packages/sitecustomize.py
    if test ! -s /usr/lib/python2.6/site-packages/sitecustomize.py
    then
      rm /usr/lib/python2.6/site-packages/sitecustomize.py
    fi
  fi
}
