post_install() {
    cat << EOF

Starting with python2-matplotlib 2.2.3-3, the Python 2.7 version of matplotlib
now defaults to 'Agg' backend. This is a rendering only backend with no GUI.
If you want to use a GUI backend, install the required optdepends and set the
backend value in your matplotlibrc.

EOF
}

post_upgrade() {
    if [ $(vercmp $2 2.2.3-3) -lt 0 ] ; then
        post_install
    fi
}
