#!/bin/bash

# source application-specific settings
GPM_ARGS=
[ -f /etc/conf.d/gpm ] && . /etc/conf.d/gpm

. /etc/rc.conf
. /etc/rc.d/functions

PID=$(pidof -o %PPID /usr/sbin/gpm)
case "$1" in
  start)
    stat_busy "Starting GPM Daemon"
    [ -z "$PID" ] && /usr/sbin/gpm ${GPM_ARGS}
    PID=$(pidof -o %PPID /usr/sbin/gpm)
    if [ -z "$PID" ]; then
      stat_fail
    else
      add_daemon gpm
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping GPM Daemon"
    [ ! -z "$PID" ]  && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon gpm
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
