post_install() {
	xdg-icon-resource install --context mimetypes --size 64 \
	/usr/share/gambas2/mime/application-x-gambas.png application-x-gambas
	xdg-mime install /usr/share/gambas2/mime/application-x-gambas.xml
}

pre_remove() {
	xdg-icon-resource uninstall --context mimetypes --size 64 application-x-gambas
	xdg-mime uninstall /usr/share/gambas2/mime/application-x-gambas.xml
}

# vim:set ts=2 sw=2 et:
