pkgname=policykit-gnome

## arg 1:  the new package version
post_install() {
  usr/sbin/gconfpkg --install ${pkgname}
}

## arg 1:  the new package version
## arg 2:  the old package version
pre_upgrade() {
  pre_remove $1
}

## arg 1:  the new package version
## arg 2:  the old package version
post_upgrade() {
  post_install $1
}

## arg 1:  the old package version
pre_remove() {
  usr/sbin/gconfpkg --uninstall ${pkgname}
}
