#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions
. /etc/conf.d/ypbind

case "$1" in
  start)
    stat_busy "Starting NIS Bind Daemon"
    [ -f /etc/defaultdomain ] && /bin/domainname -F /etc/defaultdomain
    /usr/sbin/ypbind $YPBIND_ARGS
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon ypbind
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping NIS Bind Daemon"
    killall -q /usr/sbin/ypbind
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon ypbind
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
