#!/bin/bash

daemon_name=lastmp

. /etc/rc.conf
. /etc/rc.d/functions

get_pid() {
  pidof -x -o %PPID -o $$ -o $PPID $daemon_name
}

case "$1" in
  start)
    stat_busy "Starting LastMP"
    PID=$(get_pid)
    if [ -z "$PID" ]; then
      [ -f /var/run/$daemon_name.pid ] && rm -f /var/run/$daemon_name.pid
      /usr/bin/$daemon_name
      if [ $? -gt 0 ]; then
        stat_fail
        exit 1
      else
        echo $(get_pid) >/var/run/lastfm/$daemon_name.pid
        add_daemon $daemon_name
        stat_done
      fi
    fi
    ;;

  stop)
    stat_busy "Stopping LastMP"
    PID=$(get_pid)
    [ ! -z "$PID" ]  && kill $PID &>/dev/null
    if [ $? -gt 0 ]; then
      stat_fail
      exit 1
    else
      rm -f /var/run/$daemon_name.pid &> /dev/null
      rm_daemon $daemon_name
      stat_done
    fi
    ;;

  restart)
    $0 stop
    sleep 3
    $0 start
    ;;

  status)
    stat_busy "Checking $daemon_name status";
    ck_status $daemon_name
    ;;

  *)
    echo "usage: $0 {start|stop|restart|status}"
esac

exit 0
