#!/bin/bash

ADS_HOME="`dirname $0`/../lib/datastudio"

for j in ${ADS_HOME}/lib/*.jar; do
  export CLASSPATH="${j}:${CLASSPATH}"
done
unset j

if test x${JDBC_DIR} = x; then
  JDBC_DIR="/usr/local/lib/jdbc"
fi

if test `ls ${JDBC_DIR}/*.jar 2>/dev/null | wc -l` != 0; then
  for j in ${JDBC_DIR}/*.jar; do
    export CLASSPATH=${j}:${CLASSPATH}
  done
fi
unset j

exec java ${JAVA_OPTS} -cp "${CLASSPATH}" com.aquafold.datastudio.DataStudio
