post_install() {
  echo "Setting up PlugUI.."
  echo "Synchronizing database.."
  python2 /opt/PlugUI/manage.py syncdb --noinput
  
  echo "Running maintenance system.."
  /opt/PlugUI/plugmaintenance.py > /dev/null 2>&1

  echo ""
  echo "To start PlugUI type: /etc/rc.d/plugui start"
  echo ""
  echo "Add 'plugui' to the end of the DAEMONS list in /etc/rc.conf to start on boot."
}

post_upgrade() {
  post_install
}
