#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

PID=`pidof -o %PPID /usr/sbin/cupsd`
case "$1" in
  start)
    stat_busy "Starting CUPS Daemon"
    [ -z "$PID" ] && /usr/sbin/cupsd
    if [ $? -gt 0 ]; then
      stat_fail
    else
      echo $(pidof -o %PPID -x /usr/sbin/cupsd) > /var/run/cups.pid
      add_daemon cups
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping CUPS Daemon"
    [ ! -z "$PID" ]  && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm /var/run/cups.pid
      rm_daemon cups
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
