post_install() {
  echo " Bootchart usage : "
  echo "  make sure to append init=/sbin/bootchartd to your"
  echo "  kernel parameters (it is recommended that you "
  echo "  create another entry specifically for bootchart"
  echo "  logging)."
  echo "  Run bootchart-render to render your bootchart"

  /bin/true
}

post_upgrade() {
  /bin/true
}

pre_remove() {
  /bin/true
}

post_remove() {
  /bin/true
}

op=$1
shift
$op $*
