#!/bin/sh

WIDTH=1024
HEIGHT=768
[ -f /etc/conf.d/sauerbraten ] && . /etc/conf.d/sauerbraten

cd /opt/sauerbraten
if [ -f /usr/bin/aoss ]; then
	aoss bin/linux_client -w$WIDTH -h$HEIGHT -q${HOME}/.config/sauerbraten -r
else
	bin/linux_client -w$WIDTH -h$HEIGHT -q${HOME}/.config/sauerbraten -r
fi


