post_install() {
  cat << EOF
==> To use keytouch:
o Add keytouch to your DAEMONS line in /etc/rc.conf
o Add:
  /etc/X11/Xsession
to your ~/.xinitrc
o You'll need to have either gksu (pacman -S gksu) or kdesu (pacman -S kdebase) installed.

==> If your keyboard is not supported "out of the box":
o Go to http://keytouch.sourceforge.net/dl-keyboards.html to see if your keyboard has been added
  or install keytouch-editor to make your custom keyboard file.
EOF
}
