pre_install() {
  echo "-- Edit config.h in PKGBUILD's directory (generally /var/abs/community/x11/dwm/)"
  echo "-- and rebuild package if you want to change settings."
  /bin/true
}

post_install() {
  /bin/true
}

pre_upgrade() {
  echo "-- Edit config.h in PKGBUILD's directory (generally /var/abs/community/x11/dwm/)"
  echo "-- and rebuild package if you want to change settings."
  /bin/true
}

post_upgrade() {
  /bin/true
}

pre_remove() {
  /bin/true
}

post_remove() {
  /bin/true
}

