#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

PID=`pidof -o %PPID /usr/sbin/entranced`
case "$1" in
  start)
    stat_busy "Starting Entrance"
    [ -z "$PID" ] && /usr/sbin/entranced &>/dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon entranced
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping Entrance"
    if [ -n "$PID" ]; then
	kill $PID &> /dev/null
        if [ $? -gt 0 ]; then
           stat_fail
        else
           rm_daemon entranced
           stat_done
        fi
    else
	stat_done
    fi
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0

