#!/bin/sh
JAVA_HEAP_SIZE=128
for name in /usr/share/java/jump/* ; do
  CP=$name:$CP
done
CP=$CP:/usr/share/java/xerces2/xercesImpl.jar
CP=$CP:/usr/share/java/xerces2/xml-apis.jar
CP=$CP:/usr/share/java/junit/junit.jar

/opt/java/jre/bin/java -mx${JAVA_HEAP_SIZE}m \
	-cp $CP \
	com.vividsolutions.jump.workbench.JUMPWorkbench \
	-properties /etc/jump/workbench-properties.xml \
	-plug-in-directory /etc/jump/plugins
