#!/bin/sh

## the root window should have this color
xsetroot -solid "#223377" -cursor_name left_ptr

## these are all optional
/etc/X11/xdm/archlinux/buttons -geometry -0-0 &
xclock -geometry +0-0 &
# xconsole -daemon -geometry 640x200-0+0
