KERNEL_NAME=-olinuxino
KERNEL_VERSION=3.7.2-8-ARCH

## arg 1:  the new package version
post_install() {
  # updating module dependencies
  echo ">>> Updating module dependencies. Please wait ..."
  depmod ${KERNEL_VERSION}

}

## arg 1:  the new package version
## arg 2:  the old package version
post_upgrade() {
  # updating module dependencies
  echo ">>> Updating module dependencies. Please wait ..."
  depmod ${KERNEL_VERSION}
}
