info_dir=/usr/share/info
info_files=(octave.info octave.info-1 octave.info-2 octave.info-3 octave.info-4 octave.info-5)

post_install() {
  for f in ${info_files[@]}; do
    install-info ${info_dir}/$f.gz ${info_dir}/dir 2> /dev/null
  done
}

post_upgrade() {
	post_install
}

pre_remove() {
  for f in ${info_files[@]}; do
    install-info --delete ${info_dir}/$f.gz ${info_dir}/dir 2> /dev/null
  done
}
