post_install() {
  echo "recreating monodoc index ... this could take a while..."
  monodoc --make-index > /dev/null 2>&1 
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  post_install $1
}

pre_remove() {
  /bin/true
}

post_remove() {
  echo "recreating monodoc index ... this could take a while..."
  monodoc --make-index > /dev/null 2>&1 
}

op=$1
shift

$op $*
