#!/bin/bash -e

die() {
  echo >&2 "$@"
  exit 1
}

(( $# == 2 )) || die "Usage: $0 TOKEN-FILE SYMBOL-ARCHIVE"
[[ -f $1 && -s $1 ]] || die "Invalid TOKEN-FILE ${1@Q}"
[[ $(file -Ebi "$2") == application/zip* ]] || die "Invalid SYMBOL-ARCHIVE ${2@Q}"

echo >&2 "Uploading ${2@Q} ..."
exec curl -X POST -H "Auth-Token: $(<"$1")" -F "${2##*/}=@$2" \
  https://crash-stats.mozilla.com/symbols/upload
