KERNEL_NAME=-armv5-test
KERNEL_VERSION=3.13.0-rc1-1-ARCH

post_install () {
  # updating module dependencies
  echo " -=WARNING=- -=WARNING=- -=WARNING=- -=WARNING=-"
  echo ""
  echo " You have just installed an alpha untested kernel."
  echo " If you don't know how to recover from a failed"
  echo " kernel upgrade, go BACK to linux-armv5 NOW!"
  echo ""
  echo " -=WARNING=- -=WARNING=- -=WARNING=- -=WARNING=-"
  echo ""
  echo ">>> Updating module dependencies. Please wait ..."
  depmod ${KERNEL_VERSION}
}

post_upgrade() {
  # updating module dependencies
  echo " -=WARNING=- -=WARNING=- -=WARNING=- -=WARNING=-"
  echo ""
  echo " You have just installed an alpha untested kernel."
  echo " If you don't know how to recover from a failed"
  echo " kernel upgrade, go BACK to linux-armv5 NOW!"
  echo ""
  echo " -=WARNING=- -=WARNING=- -=WARNING=- -=WARNING=-"
  echo ""
  echo ">>> Updating module dependencies. Please wait ..."
  depmod ${KERNEL_VERSION}
}
