post_install() {
  echo "****************************************************************"
  echo "Make sure the following lines are added to /boot/config.txt"
  echo "   gpu_mem=320"
  echo "   dtoverlay=vc4-fkms-v3d"
  echo "   dtparam=audio=on"
  echo
  echo "To optionally enable 4K playback add: hdmi_enable_4kp60=1"
  echo "****************************************************************"
}

post_remove() {
  echo "==> Optionally remove /var/lib/kodi/"
}
