#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

start() {
  stat_busy "Starting Monit"
  /usr/bin/monit &> /dev/null
  if [ $? -gt 0 ]; then
    stat_fail
  else
    add_daemon monit
    stat_done
  fi
}

stop() {
  stat_busy "Stopping Monit"
  /usr/bin/monit quit &> /dev/null
  if [ $? -gt 0 ]; then
    stat_fail
  else
    rm_daemon monit
    stat_done
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
esac
exit 0
