post_install() {
	cat <<INSTALL
	If running from internal NAND, run:
	/usr/share/plugapps/kernel/README-* --nandkernel
	 
	If running from SD/MMC/USB, run:
	/usr/share/plugapps/kernel/README-* --rootkernel
	and then copy the kernel to /boot/uImage.
	 
	Also, check the U-Boot environment variables and reboot.
INSTALL
}

post_upgrade() {
	post_install
}

post_remove() {
  KERNEL_VERSION=.*
}

op=$1
shift
$op $*
