#!/bin/bash
(
_pyver=$(expac %v python | grep -oP '^[0-9]+\.[0-9]+')
pacman -Fq /usr/lib/python${_pyver}/ | grep -v archlinuxcn | cut -d / -f 2
sogrep all libpython${_pyver}m.so
printf "%s\n" boost vim
) | sort -u
