#!/bin/bash

 . /etc/rc.conf
 . /etc/rc.d/functions
 PID=`pidof -o %PPID /usr/sbin/thttpd`

 case "$1" in
     start)
       stat_busy "Starting thttpd"
       /usr/sbin/thttpd -C /usr/www/thttpd_config
       if [ $? -gt 0 ]; then
           stat_fail
       else
           add_daemon thttpd
           stat_done
       fi
       ;;
     stop)
       stat_busy "Stopping thttpd"
       [ ! -z "$PID" ] && kill $PID &>/dev/null
       if [ $? -gt 0 ]; then
           stat_fail
       else
           rm_daemon thttpd
           stat_done
       fi
       ;;
     restart)
       $0 stop
       sleep 5
       $0 start
       ;;
     *)
       echo "Usage $0 {start|stop|restart}"
       ;;
 esac



