# arg 1:  the new package version
# arg 2:  the old package version

KERNEL_NAME=-parallella
KERNEL_VERSION=3.14.12-parallella-2-ARCH

post_install () {
  # updating module dependencies
  echo ">>> Updating module dependencies. Please wait ..."
  depmod ${KERNEL_VERSION}
}

post_upgrade() {
  # updating module dependencies
  echo ">>> Updating module dependencies. Please wait ..."
  depmod ${KERNEL_VERSION}
}
