# arg 1:  the new package version
post_install() {
	echo "=> If you are upgrading from SpamAssassin 2.x, 3.0.x or 3.1.x, please see"
	echo "=> http://svn.apache.org/repos/asf/spamassassin/tags/spamassassin_current_release_3.2.x/UPGRADE"
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
	post_install
}

# arg 1:  the old package version
pre_remove() {
  /bin/true
}

# arg 1:  the old package version
post_remove() {
  /bin/true
}

op=$1
shift
$op $*
