diff -Naur tclgeomap-2.11.3.orig/unix/Makefile.in tclgeomap-2.11.3.new/unix/Makefile.in
--- tclgeomap-2.11.3.orig/unix/Makefile.in	2006-12-20 16:38:04.000000000 -0500
+++ tclgeomap-2.11.3.new/unix/Makefile.in	2007-06-23 18:09:27.000000000 -0400
@@ -115,11 +115,11 @@
 
 # Directory in which to install manual entries for Tcl's C library
 # procedures:
-MAN3_INSTALL_DIR	= $(mandir)/man3
+MAN3_INSTALL_DIR	= $(DESTDIR)$(mandir)/man3
 
 # Directory in which to install manual entries for the built-in
 # Tcl commands:
-MANN_INSTALL_DIR	= $(mandir)/mann
+MANN_INSTALL_DIR	= $(DESTDIR)$(mandir)/mann
 
 pkgdatadir = $(datadir)/@PACKAGE_NAME@
 pkgincludedir = $(includedir)/@PACKAGE_NAME@@PACKAGE_VERSION@
@@ -246,20 +246,20 @@
 #========================================================================
 
 install-libraries: libraries
-	$(mkinstalldirs) $(includedir)
-	$(mkinstalldirs) $(pkgincludedir)
+	$(mkinstalldirs) $(DESTDIR)$(includedir)
+	$(mkinstalldirs) $(DESTDIR)$(pkgincludedir)
 	echo "Installing header files in $(pkgincludedir)"
 	@for i in $(GENERIC_HDRS) ; do \
 	    echo "Installing $$i" ; \
-	    $(INSTALL_DATA) $$i $(pkgincludedir) ; \
+	    $(INSTALL_DATA) $$i $(DESTDIR)$(pkgincludedir) ; \
 	done;
-	@for i in `ls $(pkgincludedir)` ; do \
-	    rm -f $(includedir)/$$i ; \
+	@for i in `ls $(DESTDIR)$(pkgincludedir)` ; do \
+	    rm -f $(DESTDIR)$(includedir)/$$i ; \
 	done;
-	echo Making $(pkglibdir)
-	$(mkinstalldirs) $(pkglibdir)
-	echo "Installing tclgeomap_procs.tcl in $(pkglibdir)"
-	$(INSTALL_DATA) $(TOP_DIR)/library/tclgeomap_procs.tcl $(pkglibdir)
+	echo Making $(DESTDIR)$(pkglibdir)
+	$(mkinstalldirs) $(DESTDIR)$(pkglibdir)
+	echo "Installing tclgeomap_procs.tcl in $(DESTDIR)$(pkglibdir)"
+	$(INSTALL_DATA) $(TOP_DIR)/library/tclgeomap_procs.tcl $(DESTDIR)$(pkglibdir)
 
 #========================================================================
 # Install documentation.  Unix manpages should go in the $(mandir)
@@ -419,16 +419,16 @@
 	  if test -f $$p; then \
 	    ext=`echo $$p|sed -e "s/.*\.//"`; \
 	    if test "x$$ext" = "xdll"; then \
-	        echo " $(INSTALL_DATA) $$p $(bindir)/$$p"; \
-	        $(INSTALL_DATA) $$p $(bindir)/$$p; \
+	        echo " $(INSTALL_DATA) $$p $(DESTDIR)$(bindir)/$$p"; \
+	        $(INSTALL_DATA) $$p $(DESTDIR)$(bindir)/$$p; \
 		lib=`basename $$p|sed -e 's/.[^.]*$$//'`.lib; \
 		if test -f $$lib; then \
-		    echo " $(INSTALL_DATA) $$lib $(libdir)/$$lib"; \
-	            $(INSTALL_DATA) $$lib $(libdir)/$$lib; \
+		    echo " $(INSTALL_DATA) $$lib $(DESTDIR)$(libdir)/$$lib"; \
+	            $(INSTALL_DATA) $$lib $(DESTDIR)$(libdir)/$$lib; \
 		fi; \
 	    else \
-		echo " $(INSTALL_DATA) $$p $(libdir)/$$p"; \
-	        $(INSTALL_DATA) $$p $(libdir)/$$p; \
+		echo " $(INSTALL_DATA) $$p $(DESTDIR)$(libdir)/$$p"; \
+	        $(INSTALL_DATA) $$p $(DESTDIR)$(libdir)/$$p; \
 	    fi; \
 	  else :; fi; \
 	done
@@ -438,7 +438,7 @@
 	    $(RANLIB) $(libdir)/$$p; \
 	  else :; fi; \
 	done
-	$(INSTALL_DATA) pkgIndex.tcl $(pkglibdir)
+	$(INSTALL_DATA) pkgIndex.tcl $(DESTDIR)$(pkglibdir)
 
 #========================================================================
 # Install binary executables (e.g. .exe files)
@@ -449,8 +449,8 @@
 install-bin-binaries: installdirs
 	@list='$(bin_BINARIES)'; for p in $$list; do \
 	  if test -f $$p; then \
-	    echo " $(INSTALL_DATA) $$p $(bindir)/$$p"; \
-	    $(INSTALL_DATA) $$p $(bindir)/$$p; \
+	    echo " $(INSTALL_DATA) $$p $(DESTDIR)$(bindir)/$$p"; \
+	    $(INSTALL_DATA) $$p $(DESTDIR)$(bindir)/$$p; \
 	  else :; fi; \
 	done
 
@@ -473,9 +473,9 @@
 	done
 
 installdirs:
-	$(mkinstalldirs)  $(libdir)
-	$(mkinstalldirs)  $(bindir)
-	$(mkinstalldirs)  $(pkglibdir)
+	$(mkinstalldirs)  $(DESTDIR)$(libdir)
+	$(mkinstalldirs)  $(DESTDIR)$(bindir)
+	$(mkinstalldirs)  $(DESTDIR)$(pkglibdir)
 
 .PHONY: all binaries clean depend distclean doc install installdirs \
 libraries test
