#!/bin/bash

# general config
. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
  start)
    stat_busy "Starting nsvsd"
	/usr/sbin/nsvsd -f /etc/nsvsd.conf
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon nsvsd
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping nsvsd"
    kill `cat /var/run/nsvsd.pid` &>/dev/null
    rm -f /var/run/nsvsd.pid
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon nsvsd
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 3
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
