.TH umurmur 1 "2010 July 17"
.SH NAME
uMurmur \- minimalistic Mumble VoIP server.
.SH SYNOPSIS
.B umurmurd
.RI [ options ]
.SH DESCRIPTION
uMurmur is a minimalistic Mumble server primarily targeted to run on routers with an open OS like OpenWRT. The server part of Mumble is called Murmur, hence the name uMurmur.
.SH OPTIONS
.TP
.B \-h, \-\-help
Show a summary of the options.
.TP
.BI \-c \ "configfile"
Specify which configuration file to use.
.TP
.BI \-p \ "pidfile"
Write uMurmur PID to this file.
.TP
.BI \-d
Run in the foreground (do not fork).
.br
This is very usefull for debugging.
.TP
.BI \-r
Run with realtime priority.
.SH SEE ALSO
.BR mumble (1),
.br
.SH AUTHOR
Written by Martin Johansson <martin@fatbob.nu>.
Mumble and Murmurd was written by Thorvald Natvig <slicer@users.sourceforge.net>. 
