# arg 1:  the new package version
post_install() {
  # create docker group (FS#38029)
  getent group docker >/dev/null || groupadd -g 142 docker
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  (( $(vercmp $2 '1:0.7.1-1') < 0 )) &&  post_install "$1" || true
}

# arg 1:  the old package version
post_remove() {
  groupdel docker >/dev/null 2>&1 || true
}

# vim:set ts=2 sw=2 et:
