#!/bin/sh

if [ ! -e $HOME/.nestopia ]; then
  echo "Running NEStopia for the first time..."
  echo "Copying required files to ~/.nestopia..."
  mkdir $HOME/.nestopia
  cp /usr/share/nestopia/{nstcontrols,NstDatabase.xml} $HOME/.nestopia/
fi

nestopia-bin "$@"
