pkgname=muine

post_install() {
  usr/sbin/gconfpkg --install ${pkgname}
  update-desktop-database -q
  gtk-update-icon-cache -f -t -q usr/share/icons/hicolor

}

pre_upgrade() {
  pre_remove $1
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  usr/sbin/gconfpkg --uninstall ${pkgname}
}

post_remove() {
  gtk-update-icon-cache -f -t -q /usr/share/icons/hicolor
  update-desktop-database -q
}
