#!/bin/bash

# source application-specific settings
[ -f /etc/conf.d/exim ] && . /etc/conf.d/exim

# general config
. /etc/rc.conf
. /etc/rc.d/functions

PID=`pidof -o %PPID /usr/sbin/exim`

case "$1" in
  start)
    stat_busy "Starting Exim"
    [ -z "$PID" ] && /usr/sbin/exim $EXIM_ARGS
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon exim
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping Exim"
    [ ! -z "$PID" ]  && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm /var/run/exim.pid
      rm_daemon exim
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 2
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
