#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

get_pid() {
	pidof /usr/sbin/ircservices
}

case "$1" in
  start)
    stat_busy "Starting IRC services"

    [ -f /var/run/ircd/ircservices.pid ] && rm -f /var/run/ircd/ircservices.pid
    PID=`get_pid`
    if [ -z "$PID" ]; then
      su -c '/usr/sbin/ircservices -dir=/var/lib/ircd/ -remote=127.0.0.1:6667 -log=/var/log/ircd/ircservices.log' ircd 1>>/var/log/ircd/stdout.log 2>>/var/log/ircd/sterr.log
      if [ $? -gt 0 ]; then
        stat_fail
        exit 1
      else
        add_daemon ircservices
        stat_done
      fi
    else
      stat_fail
      exit 1
    fi
    ;;

  stop)
    stat_busy "Stopping IRC services"
    PID=`get_pid`
    [ ! -z "$PID" ] && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
      exit 1
    else
      rm -f /var/run/ircd/ircservices.pid &> /dev/null
      rm_daemon ircservices
      stat_done
    fi
    ;;

  restart)
    $0 stop
    sleep 3
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
