#!/bin/bash

. /opt/etc/rc.conf
. /opt/etc/rc.d/functions
. /opt/etc/conf.d/sshd

PID=`cat /opt/var/run/sshd.pid 2>/dev/null`
case "$1" in
  start)
    stat_busy "Starting Secure Shell Daemon"
    [ -f /opt/etc/ssh/ssh_host_key ] || { /opt/bin/ssh-keygen -t rsa1 -N "" -f /opt/etc/ssh/ssh_host_key >/dev/null; }
    [ -f /opt/etc/ssh/ssh_host_rsa_key ] || { /opt/bin/ssh-keygen -t rsa -N "" -f /opt/etc/ssh/ssh_host_rsa_key >/dev/null; }
    [ -f /opt/etc/ssh/ssh_host_dsa_key ] || { /opt/bin/ssh-keygen -t dsa -N "" -f /opt/etc/ssh/ssh_host_dsa_key >/dev/null; }
    [ -z "$PID" ] && /opt/sbin/sshd $SSHD_ARGS
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon sshd
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping Secure Shell Daemon"
    [ ! -z "$PID" ]  && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon sshd
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
