# shellcheck disable=SC2059
post_upgrade() {
  local orange='\033[1;33m'
  local reset='\033[0m'
  if (( $(vercmp "$2" 4.8.0-1) < 0)); then
    printf "$orange"
    printf "NOTE: As of package version 4.8.0-1, syslog-ng ships with a configuration\n"
    printf "      where all logging is disabled. To re-enable logging with syslog-ng,\n"
    printf "      please update your configuration in /etc/syslog-ng/syslog-ng.conf.\n"
    printf "$reset"
  fi
}
