[libretro-mupen64plus-next]
source = "jq"
url = "https://api.github.com/repos/libretro/mupen64plus-libretro-nx/commits/develop"
filter = '(.commit.committer.date | fromdateiso8601 | strftime("%Y%m%d.%H%M%S")) + ".g" + (.sha[0:12])'
