pkgname=awn

post_install() {
  echo ""
  echo "It is safe to ignore the SCHEMA warnings below"
  echo ""

  usr/sbin/gconfpkg --install ${pkgname}
  update-desktop-database -q
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  echo ""
  echo "It is safe to ignore the SCHEMA warnings below"
  echo ""

  usr/sbin/gconfpkg --uninstall ${pkgname}
}

post_remove() {
  update-desktop-database -q
}

op=$1
shift

$op $*
