[libreoffice-still]
source = "regex"
regex = 'LibreOffice \d+\.\d+\.\d+ \(.*?\) - Previous Branch'
url = "https://www.libreoffice.org/release-notes/"
prefix = "LibreOffice "
from_pattern = '(\d+\.\d+\.\d+) \(.*?\) - Previous Branch'
to_pattern = '\1'
