[libreoffice-still]
source = "regex"
#regex = "libreoffice-([\\d.]+)\\."
regex = "([\\d.]+) release notes"
include_regex = "7.*"
url = "https://www.libreoffice.org/download/download-libreoffice/"
#from_pattern = '(\d+).(\d+).(\d+).(\d+)'
#to_pattern = '\1.\2.\3'

#source = "git"
#git = "https://git.libreoffice.org/core"
#include_regex = ".*7.*"
#use_max_tag = true
##ignored = "suse-4.0-27 "
#exclude_regex =".*(suse|ooo|mimo).*"
#prefix = "libreoffice-"
#from_pattern = '(\d+).(\d+).(\d+).(\d+)'
#to_pattern = '\1.\2.\3'
