# arg 1:  the new package version
# arg 2:  the old package version

KERNEL_NAME=-boundary
KERNEL_VERSION=3.10.17-1-ARCH

post_install () {
  # updating module dependencies
  echo ">>> Updating module dependencies. Please wait ..."
  depmod ${KERNEL_VERSION}
}

post_upgrade() {
  # updating module dependencies
  echo ">>> Updating module dependencies. Please wait ..."
  depmod ${KERNEL_VERSION}
}
