version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
    "0001-Use-reproducible-data-for-build-user-and-host.patch",
    "0002-Adjust-hardcoded-font-paths-for-ttf-dejavu.patch",
    "0003-Adjust-includes-for-build-with-gstreamer-1.28.patch",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"
