# arg 1:  the new package version
post_install() {
getent group camera >/dev/null || usr/sbin/groupadd -g 97 camera
	/bin/cat <<THEEND
NOTE
----
Add your user to group 'camera' to use camera devices.
THEEND
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  post_install $1
}

# arg 1:  the old package version
pre_remove() {
  usr/sbin/groupdel camera &>/dev/null
}
