#!/bin/bash

NAMED_ARGS=
[ -f /etc/conf.d/named ] && . /etc/conf.d/named

. /etc/rc.conf
. /etc/rc.d/functions

PID=`pidof -o %PPID /usr/sbin/named`
case "$1" in
  start)
    stat_busy "Starting DNS"
    [ -z "$PID" ] && /usr/sbin/named ${NAMED_ARGS}
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon named
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping DNS"
    [ ! -z "$PID" ]  && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon named
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
