# arg 1:  the new package version
post_install() {
#  echo "If you get a BOSS_ANT error trying to run abuse, copy /usr/share/games/abuse/gamma.lsp to ~/.abuse"
   echo "Abuse uses the original game levels by default.  To use the frabs levels"
   echo "use '-datadir' or set 'datadir' in the abuserc to /usr/share/abuse/frabs"
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
	post_install
}

