#!/bin/sh

fastboot flash partition gpt_both0.bin
fastboot flash hyp hyp.mbn
fastboot flash modem NON-HLOS.bin
fastboot flash rpm rpm.mbn
fastboot flash sbl1 sbl1.mbn
fastboot flash tz tz-psci.mbn

fastboot erase boot
fastboot erase rootfs
fastboot erase devinfo

fastboot flash aboot emmc_appsboot.mbn
fastboot flash boot u-boot.img
