flash_uboot() {
  echo "A new U-Boot version needs to be flashed onto /dev/mmcblk0p8."
  echo "Do you want to do this now? [y|N]"
  read -r shouldwe
  if [[ $shouldwe =~ ^([yY][eE][sS]|[yY])$ ]]; then
    dd if=/boot/u-boot.img of=/dev/mmcblk0p8
  else
    echo "You can do this later by running:"
    echo "# dd if=/boot/u-boot.img of=/dev/mmcblk0p8"
  fi
}

post_install() {
  flash_uboot
}

post_upgrade() {
  flash_uboot
}
