# arg 1:  the new package version
post_install() {
  echo "NOTE:"
  echo "  This build is without gtk1 frontend."
  echo "  For gtk2 frontend please add 'gtk2' package."
  echo "  Default X11 frontend is set to gtk2. "
  echo ""
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
 post_install $1
}

# arg 1:  the old package version
pre_remove() {
  /bin/true
}

# arg 1:  the old package version
post_remove() {
  /bin/true
}

op=$1
shift
$op $*
