pkgname=gnochm

post_install() {
  usr/sbin/gconfpkg --install ${pkgname}  
  update-desktop-database -q
  update-mime-database usr/share/mime >/dev/null 2>&1
}

pre_upgrade() {
  pre_remove $1
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  usr/sbin/gconfpkg --uninstall ${pkgname}
}

post_remove() {
  update-desktop-database -q
  update-mime-database usr/share/mime >/dev/null 2>&1
}

op=$1
shift

$op $*
