#!/bin/bash
# Update our hwclock for system drift

. /etc/rc.conf

HWCLOCK_PARAMS="--adjust"
case $HARDWARECLOCK in
    UTC) HWCLOCK_PARAMS+=" --utc";;
    localtime) HWCLOCK_PARAMS+=" --localtime";;
    *) HWCLOCK_PARAMS="";;
esac

if [[ $HWCLOCK_PARAMS && -f /run/daemons/hwclock ]]; then
    /sbin/hwclock $HWCLOCK_PARAMS
fi
