post_upgrade() {
  if [ "$(vercmp $2 2009.07)" -lt 0 ]; then
    echo "==> Adjusting /etc/inittab for transition to /dev/tty standard."
    echo "==> Original file saved as /etc/inittab.pacsave"
    sed -i'.pacsave' 's#vc/\([0-9]\)#tty\1#' /etc/inittab
  fi
  if [ "$(vercmp $2 2011.06.1)" -lt 0 ]; then
    echo "Blacklisting of modules is no longer supported in rc.conf,"
    echo "please add blacklist entries to /etc/modprobe.d/ instead."
  fi
}
