#!/bin/bash

# sourcing our current rc.conf requires this to be a bash script
. /etc/rc.conf
. /etc/rc.d/functions

rc=0

case "$1" in
	start)
		stat_busy "Mounting Network Filesystems"
		/bin/mount -a -t nfs,nfs4,smbfs,codafs,ncpfs,cifs,shfs,glusterfs,fuse,fuseblk,fuse.glusterfs,davfs
		rc=$?
		/bin/mount -a -O _netdev
		if ((rc + $? > 0)); then
			stat_fail
		else
			add_daemon netfs
			stat_done
		fi
		;;
	stop)
		stat_busy "Unmounting Network Filesystems"
		/bin/umount -a -O _netdev
		rc=$?
		/bin/umount -a -t nfs,nfs4,smbfs,codafs,ncpfs,cifs,shfs,glusterfs,fuse,fuseblk,fuse.glusterfs,davfs
		if ((rc + $? > 0)); then
			stat_fail
		else
			rm_daemon netfs
			stat_done
		fi
		;;
	restart)
		$0 stop
		sleep 1
		$0 start
		;;
	*)
		echo "usage: $0 {start|stop|restart}"  
esac

# vim: set ts=2 noet:
