#!/bin/sh

# This file is a user shortcut to the Sick Beard program.
# It should only be used for simple debugging and checking the Sick Beard arguments.
# The initscript and unit use the longer command found here to prevent problems with PIDs.

/usr/bin/env python2 /opt/sickbeard/SickBeard.py "$@"

