diff -urN a/Makefile b/Makefile
--- a/Makefile	2016-03-08 13:48:07.000000000 -0700
+++ b/Makefile	2016-04-19 19:03:42.200343001 -0600
@@ -288,7 +288,7 @@
 	$(QUIET)rm -f $(DESTDIR)$(APPDATAPREFIX)/$(PROJECT).appdata.xml
 	$(MAKE) -C po uninstall
 
-DEPENDS = ${DEPENDDIRS:^=${DEPENDDIR}/}$(addprefix ${DEPENDDIR}/,${OBJECTS:.o=.o.dep})
+DEPENDS = ${DEPENDDIRS:^=${DEPENDDIR}/}$(addprefix ${DEPENDDIR}/,${OBJECTS:.o=.dep})
 -include ${DEPENDS}
 
 .PHONY: all options clean doc debug valgrind gdb dist doc install uninstall \
