pre_install() {
  pre_upgrade
  /bin/true
}

post_install() {
  /bin/true
}

pre_upgrade() {
  echo "-- Change /etc/man.conf"
  echo "-- NROFF iconv -f utf8 -t koi8r | /usr/bin/nroff -Tlatin1 -mandoc -c | iconv -f koi8r -t utf8"
  echo "-- and"
  echo "-- export LESSCHARSET=UTF-8"
  /bin/true
}

post_upgrade() {
  echo "-- Since 0.98-3 version manpages use UTF-8!"
  /bin/true
}

pre_remove() {
  /bin/true
}

post_remove() {
  /bin/true
}

op=$1
shift
$op $*
