#! /bin/sh

mount -t proc none /proc
mount -t sysfs none /sys
mount -t devpts none /dev/pts
mount -t tmpfs none /tmp
mount /dev/mtdblock3 /usr
mkdir /tmp/var

echo "/tmp/core_%e_%t" > /proc/sys/kernel/core_pattern

hostname Pogoplug

ifconfig lo 127.0.0.1
ifconfig eth0 169.254.37.133
udhcpc -h 'Pogoplug'

telnetd
/etc/init.d/db
ntpd -g

/etc/init.d/hbmgr.sh start

#/bin/mount -a
