#!/bin/sh

# osdbattery start/stop script - best bound to a keyboard combo

PID=`pidof -o %PPID /usr/bin/osdbattery`
if [ -z "$PID" ] ; then
	/usr/bin/osdbattery &
	echo $PID > /var/run/osdbattery.pid
elif [ ! -z "$PID" ] ; then
	kill $PID &> /dev/null
	rm /var/run/osdbattery.pid
fi
