post_install () {
  echo ">>> hardening-wrapper is deprecated and will be dropped from the repositories"
  echo ">>>"
  echo ">>> The standard Arch Linux Clang / GCC have adopted PIE / SSP by default"
  echo ">>>"
  echo ">>> RELRO and BIND_NOW are defaults in makepkg LDFLAGS and will become linker defaults soon"
  echo ">>>"
  echo ">>> -fstack-check will be enabled by default once GCC ships their new implementation"
}

post_upgrade() {
  post_install
}
