--- fdm-1,6/GNUmakefile	2008-12-22 21:50:05.000000000 +0530
+++ fdm-1.6/GNUmakefile	2009-05-09 19:07:21.000000000 +0530
@@ -8,10 +8,7 @@
 
 #DEBUG= 1
 
-PREFIX?= /usr/local
-
-BIN_OWNER= bin
-BIN_GROUP= root
+PREFIX?= /usr
 
 CC= gcc
 
@@ -27,8 +24,8 @@
 endif
 
 INSTALLDIR= install -d
-INSTALLBIN= install -g $(BIN_OWNER) -o $(BIN_GROUP) -m 555
-INSTALLMAN= install -g $(BIN_OWNER) -o $(BIN_GROUP) -m 444
+INSTALLBIN= install -m 0755
+INSTALLMAN= install -m 0644
 
 SRCS= fdm.c \
       attach.c buffer.c cleanup.c command.c connect.c io.c log.c netrc.c \
@@ -72,7 +69,7 @@
 endif
 
 OBJS= $(patsubst %.c,%.o,$(SRCS))
-CPPFLAGS+= $(DEFS) -I. -I- $(INCDIRS)
+CPPFLAGS+= $(DEFS) -I. -iquote. $(INCDIRS)
 ifdef DEBUG
 CFLAGS+= -g -ggdb -DDEBUG
 LDFLAGS+= -rdynamic
@@ -115,10 +112,10 @@
 install:
 	$(INSTALLDIR) $(DESTDIR)$(PREFIX)/bin
 	$(INSTALLBIN) $(PROG) $(DESTDIR)$(PREFIX)/bin/$(PROG)
-	$(INSTALLDIR) $(DESTDIR)$(PREFIX)/man/man1
-	$(INSTALLMAN) $(PROG).1 $(DESTDIR)$(PREFIX)/man/man1/$(PROG).1
-	$(INSTALLDIR) $(DESTDIR)$(PREFIX)/man/man5
-	$(INSTALLMAN) $(PROG).conf.5 $(DESTDIR)$(PREFIX)/man/man5/$(PROG).conf.5
+	$(INSTALLDIR) $(DESTDIR)$(PREFIX)/share/man/man1
+	$(INSTALLMAN) $(PROG).1 $(DESTDIR)$(PREFIX)/share/man/man1/$(PROG).1
+	$(INSTALLDIR) $(DESTDIR)$(PREFIX)/share/man/man5
+	$(INSTALLMAN) $(PROG).conf.5 $(DESTDIR)$(PREFIX)/share/man/man5/$(PROG).conf.5
 
 clean:
 	rm -f $(CLEANFILES)
