#!/bin/bash

. /etc/conf.d/smbnetfs
. /etc/rc.conf
. /etc/rc.d/functions

get_pid() {
	echo `pidof smbnetfs`
}

case "$1" in
  start)
    stat_busy "Starting smbnetfs"

    [ -f /var/run/smbnetfs.pid ] && rm -f /var/run/smbnetfs.pid
    PID=`get_pid`
    if [ -z "$PID" ]; then
      cd /tmp && \
	[ -d $SMBNETFS_MOUNT_POINT ] && \
	sudo -u nobody -- bash -c "HOME=/etc/smbnetfs exec smbnetfs -o allow_other $SMBNETFS_MOUNT_POINT" &>/dev/null
      if [ $? -gt 0 ]; then
        stat_fail
        exit 1
      else
        echo `get_pid` > /var/run/smbnetfs.pid
        add_daemon smbnetfs
        stat_done
      fi
    else
      stat_fail
      exit 1
    fi
    ;;

  stop)
    stat_busy "Stopping smbnetfs daemon"

    fusermount -u $SMBNETFS_MOUNT_POINT &> /dev/null
    rm -f /var/run/smbnetfs.pid &> /dev/null
    rm_daemon smbnetfs
    stat_done
    ;;

  restart)
    $0 stop
    sleep 3
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
