_libvirt_setup() {
  systemd-tmpfiles --create libvirt.conf
}

post_install() {
  _libvirt_setup || return 1
  groupadd -r -f libvirt
  echo ">>> libvirt runs qemu from nobody:kvm by default"
  echo ">>> change the USER if desired in /etc/libvirt/qemu.conf"
  echo ">>> See https://wiki.archlinux.org/index.php/Libvirt for more info"
}

post_upgrade() {
  _libvirt_setup || return 1
  echo ">>> You may need to run 'rm -rf ~/.libvirt'"
}
