post_install() {
cat <<EOF
To install game data (*.wad files), there are two main locations for
the engine to easily find them:
 * For all users: /usr/share/games/doom
 * For a single user: ~/.local/share/games/doom

Files such as doom2.wad, heretic.wad, hexen.wad, and strife1.wad are
appropriate for installation and usage with Chocolate engines.
These must be lower-case file names, unless on a case-insensitive
file system.
EOF
}
