#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

PID=$(pidof -o %PPID /usr/sbin/cnid_metad)
case "$1" in
  start)
    stat_busy "Starting cnid Daemon"
    [ -z "$PID" ] && /usr/sbin/cnid_metad
    if [ $? -gt 0 ]; then
      stat_fail
    else
      PID=$(pidof -o %PPID /usr/sbin/cnid_metad)
      echo "$PID" > /var/run/cnid.pid
      add_daemon cnid
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping cnid Daemon"
    [ ! -z "$PID" ]  && kill "$PID" &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon cnid
      rm /var/run/cnid.pid
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
