pre_install() {
cat << EOM

In order to actually use ecb you have to follow some more steps:
1. Add the new ECB-directory to your emacs load-path variable.
For example you may add this line into your ~/.emacs file:
(add-to-list 'load-path "/usr/share/emacs/site-lisp/ecb")

2. To load ecb at startup:
(require 'ecb)
- or -
To load ecb first after starting it by ecb-activate:
(require 'ecb-autoloads)

EOM
}
