#!/usr/bin/ash

run_hook() {
    local pvdev

    modprobe -q dm-mod >/dev/null 2>&1

    # If the lvmwait= parameter has been specified on the command line
    # wait for the device(s) before trying to activate the volume group(s)
    for pvdev in ${lvmwait//,/ }; do
        poll_device ${pvdev} ${rootdelay}
    done

    msg "Activating logical volumes..."
    [ -d /etc/lvm ] && lvm vgscan

    if [ -n "$quiet" ]; then
      lvm vgchange --sysinit -a y >/dev/null
    else
      lvm vgchange --sysinit -a y
    fi
}

# vim: set ft=sh ts=4 sw=4 et:
