post_install() {
  if [ ! "`grep /bin/ksh etc/shells`" ]; then
    echo "updating /etc/shells... done."
    sed -i "s|/bin/bash|/bin/bash\n/bin/ksh|" etc/shells
  else
    sed -i "s|/usr/bin/ksh|/bin/ksh|" etc/shells

    echo ""
    echo ">> WARNING: /usr/bin/ksh has moved to /bin/ksh,"
    echo ">> please update your user accounts as needed"
    echo ""
  fi
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  echo -ne "\nupdating /etc/shells... "
  sed -i "s|/bin/ksh||" etc/shells
}
