## arg 1:  the new package version
post_install() {
	if [ -z $(</etc/iscsi/initiatorname.iscsi) ]; then
		name=$(iscsi-iname)
	  echo
	  echo ">>> Setting Initiatorname '$name'"
	  echo "InitiatorName=$name" > /etc/iscsi/initiatorname.iscsi
	fi
	echo
	echo "Configure /etc/conf.d/open-iscsi to enable:"
	echo " - portal discovery"
	echo " - automatic login to available targets"
	echo " - automount of targets"
	echo
}

post_upgrade() {
	post_install
}
