## arg 1:  the new package version
post_install() {
  echo
  echo "The open-iscsi package contains the userland tools of the"
  echo "Open-iSCSI project. It depends on iSCSI modules which are already"
  echo "present in current (>= 2.6.16) kernels and must be present on"
  echo "your system or statically compiled inside your kernel image."
  echo
  echo ">>> Setting Initiatorname ..."
  echo "InitiatorName=$(iscsi-iname)" > /etc/iscsi/initiatorname.iscsi
  echo
}
