#!/bin/bash

. /opt/etc/rc.conf
. /opt/etc/rc.d/functions

case "$1" in
  start)
    stat_busy "Starting rsyncd"
    [ ! -f /opt/var/run/daemons/rsyncd ] && /opt/bin/rsync --daemon
    if [ $? -gt 0 ]; then
      stat_fail
    else
      pgrep -of "/opt/bin/rsync --daemon" > /opt/var/run/rsyncd.pid
      add_daemon rsyncd
      stat_done
    fi
    ;;

  stop)
    stat_busy "Stopping rsyncd"
    [ -f /opt/var/run/rsyncd.pid ] && kill `cat /opt/var/run/rsyncd.pid`
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon rsyncd
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
esac
exit 0
