

------------------------------------------------------------------------------
Arch Linux
SYSLINUX BOOT
created with 'mksyslinux' by Tobias Powalowski <tpowa@archlinux.org>

Press ENTER or type 'arch' to boot image.

If you wish to change your defaults to boot into your existing system,
type 'vmlinuz initrd=initrd.img <any_other_boot_option>'
Use the F2 key for troubleshooting and options.
------------------------------------------------------------------------------

