#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions
. /etc/conf.d/ntp-client.conf

PID=`pidof -o %PPID /usr/bin/ntpd`
case "$1" in
  start)
    stat_busy "Starting NTP Daemon"
    if [ -z "$PID" ]; then 
       /usr/bin/ntpd $NTPD_ARGS &
    fi
    if [ ! -z "$PID" -o $? -gt 0 ]; then
      stat_fail
    else
      PID=`pidof -o %PPID /usr/bin/ntpd`
      echo $PID > /var/run/ntpd.pid
      add_daemon ntpd
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping NTP Daemon"
    [ ! -z "$PID" ]  && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon ntpd
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
