#!/bin/sh

generate_uboot_ramdisk()
{
  local ramdisk=$1
  if [ -f "$ramdisk" ]; then
      mkimage -A arm64 -T ramdisk -n "U-boot ramdisk" \
          -d $ramdisk ${ramdisk}.uboot
  fi
}

case $1 in
    add)
        generate_uboot_ramdisk /boot/initramfs-linux.img
        generate_uboot_ramdisk /boot/initramfs-linux-fallback.img
    remove)
        rm -f -- /boot/initramfs-linux-fallback.img.uboot \
                 /boot/initramfs-linux.img.uboot
esac
# vim: set ft=sh ts=4 sw=4 et:
