pre_upgrade() {
  if [[ ${1%-*} != ${2%-*} ]]; then
    [[ -d /usr/share/haskell ]] && find /usr/share/haskell -maxdepth 2 -name 'unregister.sh' -exec {} \;
  fi
}

post_upgrade() {
  if [[ ${1%-*} != ${2%-*} ]]; then
    echo '==> If you have custom packages installed, you will need to reinstall them now.'
    echo "==> See /usr/lib/ghc-${2%-*}/package.conf.d/ for a tentative list of affected packages."
  fi
}
