54,60c54,56
< 	install -d $(DESTDIR)/share/beaver/bin
< 	install beaver $(DESTDIR)/share/beaver/bin
< 	$(CP) $(DESTDIR)/share/beaver/bin/beaver $(DESTDIR)/share/beaver/bin/beaver.orig
< 	echo "#!/bin/bash" > $(DESTDIR)/share/beaver/bin/beaver
< 	echo "cd $(DESTDIR)/share/beaver/bin/" >> $(DESTDIR)/share/beaver/bin/beaver
< 	echo "./beaver.orig" >> $(DESTDIR)/share/beaver/bin/beaver
< 	ln -sf $(DESTDIR)/share/beaver/bin/beaver $(DESTDIR)/bin/beaver
---
> 	install -d $(DESTDIR)/bin
> 	install -Dm755 beaver $(DESTDIR)/bin
> 	
62c58,61
< 	$(CP) ../bl/*.bl $(DESTDIR)/share/beaver/bl
---
> 	install -Dm644 ../bl/example1.bl $(DESTDIR)/share/beaver/bl/example1.bl
> 	install -Dm644 ../bl/example2.bl $(DESTDIR)/share/beaver/bl/example2.bl
> 	install -Dm644 ../bl/glib.bl $(DESTDIR)/share/beaver/bl/glib.bl
> 	
64,71c63,68
< 	$(CP) ../pixmaps/beaver.png $(DESTDIR)/share/beaver/pixmaps
< 	$(CP) ../pixmaps/about.xpm $(DESTDIR)/share/beaver/pixmaps
< 	chmod 644 $(DESTDIR)/share/beaver/pixmaps/beaver.png
< 	chmod 644 $(DESTDIR)/share/beaver/pixmaps/about.xpm
< 	install -d $(DESTDIR)/share/applications
< 	$(CP) ../beaver.desktop $(DESTDIR)/share/applications/beaver.desktop
< 	chmod 644 $(DESTDIR)/share/applications/beaver.desktop
< 	sed -i $(DESTDIR)/share/applications/beaver.desktop -e "s/Icon=/Icon=`echo $(DESTDIR) | sed -e 's/\//\\\\\//g'`\/share\/beaver\/pixmaps\//g" 
---
> 	install -Dm644 ../pixmaps/beaver.png $(DESTDIR)/share/beaver/pixmaps/beaver.png
> 	install -Dm644 ../pixmaps/about.xpm $(DESTDIR)/share/beaver/pixmaps/about.xpm
> 	
> 	install -Dm644 ../beaver.desktop $(DESTDIR)/share/applications/beaver.desktop
> 	sed -i $(DESTDIR)/share/applications/beaver.desktop -e "s/Icon=/Icon=\/usr\/share\/beaver\/pixmaps\//g" 
> 	
73,93c70
< 	install -d $(DESTDIR)/man/man1
< 	$(CP) ../beaver.1x.gz $(DESTDIR)/man/man1
< 	chmod 644 $(DESTDIR)/man/man1/beaver.1x.gz
< 	@echo
< 	@echo "Files installed :"
< 	@echo "-----------------"
< 	@echo
< 	@echo "$(DESTDIR)/bin/beaver"
< 	@echo "$(DESTDIR)/bin/beaver.orig"
< 	@echo "$(DESTDIR)/share/beaver/bin/beaver"
< 	@echo "$(DESTDIR)/share/beaver/bl/example1.bl"
< 	@echo "$(DESTDIR)/share/beaver/bl/example2.bl"
< 	@echo "$(DESTDIR)/share/beaver/bl/glib.bl"
< 	@echo "$(DESTDIR)/share/beaver/pixmaps/beaver.png"
< 	@echo "$(DESTDIR)/share/beaver/pixmaps/about.xpm"
< 	@echo "$(DESTDIR)/share/applications/beaver.desktop"
< 	@echo "$(DESTDIR)/man/man1/beaver.1x.gz"
< 	@echo
< 	@echo ",----------------------------------."
< 	@echo "| Beaver succesfully installed ^_^ |"
< 	@echo "\`----------------------------------'"
---
> 	install -Dm644 ../beaver.1x.gz $(DESTDIR)/man/man1/beaver.1x.gz
