version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "arch_linux_profile.xml",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "0001-mysql-workbench-no-check-for-updates.patch",
    "0002-disable-unsupported-operating-system-warning.patch",
    "0004-replace-deprecated-python-modules-pipes-with-shlex.patch",
    "0006-swig.patch",
    "0007-python.patch",
    "0008-C++20.patch",
]
SPDX-FileCopyrightText = "mysql-workbench contributors"
SPDX-License-Identifier = "GPL-2.0-or-later"
