#! /bin/bash
#
# xterm_title - print the contents of the xterm title bar
#
# Derived from http://www.clark.net/pub/dickey/xterm/xterm.faq.html#how2_title
#
P=${0##*/}
[ -z "$DISPLAY" ] && {
	echo "${P}: not running X" >&2
	exit 1
}

if [ -z "$TERM" ] || [ "$TERM" != "xterm" ]; then
	echo "${P}: not running in an xterm" >&2
	exit 1
fi

exec </dev/tty
old=$(stty -g)
stty raw -echo min 0  time ${1-10}
echo -e "\033[21t\c" > /dev/tty
IFS='' read -r a
stty $old
b=${a#???}
echo "${b%??}"

exit 0
