pre_install() {
  /bin/true
}

post_install() {
    groupadd irc
    useradd -G irc -d /var/lib/ircd ircd
    chown -R ircd.irc /var/log/ircd
    chown -R ircd.irc /var/lib/ircd
    chown -R ircd.irc /var/run/ircd
}

pre_upgrade() {
  /bin/true
}

post_upgrade() {
    chown -R ircd.irc /var/log/ircd
    chown -R ircd.irc /var/lib/ircd
    chown -R ircd.irc /var/run/ircd
}

pre_remove() {
  /bin/true
}

post_remove() {
    userdel ircd
    groupdel irc
}

op=$1
shift
$op $*
