post_install() {
	gtk-update-icon-cache -f -t /usr/share/icons/hicolor
	echo ""
	echo "	-----------------------------------------------------------------------"
	echo "	Please edit the "Friendly Name" in /etc/conf.d/gmediarender"
	echo "	-----------------------------------------------------------------------"
	echo "	start the service by running (as root):"
	echo "		systemctl start gmediarender"
	echo "	-----------------------------------------------------------------------"
	echo "	enable the service by running (as root):" 
	echo "		systemctl enable gmediarender"
	echo "	-----------------------------------------------------------------------"
	echo ""
}

post_upgrade() {
	post_install
}

post_remove() {
	post_install
}
