#!/bin/bash

. /opt/etc/rc.conf
. /opt/etc/rc.d/functions

PID=`pidof -o %PPID /opt/sbin/xinetd`
case "$1" in
  start)
    stat_busy "Starting xinetd"
    [ -z "$PID" ] && /opt/sbin/xinetd -stayalive -pidfile /opt/var/run/xinetd.pid
    if [ $? -gt 0 ]; then
      stat_fail
    else
      echo $PID > /opt/var/run/xinetd.pid
      add_daemon xinetd
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping xinetd"
    [ ! -z "$PID" ]  && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm -f /opt/var/run/xinetd.pid
      rm_daemon xinetd
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
