post_install() {
  echo ">> To enable libtrash at login:"
  echo ">>   chmod 755 /etc/profile.d/libtrash.sh"
  echo ">> To enable libtrash at any moment:"
  echo ">>   . /etc/profile.d/libtrash.sh"
  echo ">> To disable libtrash at any moment:"
  echo ">>   unset LD_PRELOAD"
  echo ">> WARNING: fakeroot will not work while libtrash is enabled."
  echo ">> Disable libtrash before using fakeroot!"
}

post_upgrade() {
  post_install
}

op=$1
shift
$op $*
