# arg 1:  the new package version
post_install() {
  groupadd -g 80 mailman &>/dev/null
  useradd -u 80 -g mailman -d /home/mailman -s /bin/false mailman &>/dev/null
  cd /home/mailman && bin/check_perms -f >/dev/null 2>&1
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  post_install $1
}

# arg 1:  the old package version
pre_remove() {
  userdel mailman &>/dev/null
  groupdel mailman &>/dev/null
}

op=$1
shift

$op $*
