post_install() {
  if [ ! "`grep ^ntp /etc/group`" ]; then
    echo "adding new group: ntp"
    /usr/sbin/groupadd -g 87 ntp
  fi
                    
  if [ ! "`grep ^ntp /etc/passwd`" ]; then
    echo "adding new user: ntp"
    /usr/sbin/useradd -g ntp -u 87 -d /var/empty -s /bin/false -c 'Network Time Protocol' ntp
  fi
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  /bin/true
}

post_remove() {
  /bin/true
}

op=$1
shift

$op $*
# vim: ts=2 sw=2 et ft=sh
