post_install() {

echo "==> To launch bluemote, you'll need to create the directory ~/.bluemote"
echo "==> and copy /etc/bluemote/bluemote.cfg to ~/.bluemote/bluemote.cfg."
echo "==> Edit that file to your liking (more info in /etc/bluemote/config.txt."
echo "==> Bluemote will not start if the directory and the config file do not exist."
echo "==> Add your user to the "tty" group in order to have access to /dev/rfcomm0"
}

post_upgrade() {
  groupdel bluetooth
}

op=$1
shift
$op $*
