[boinc]
source = "git"
git = "https://github.com/BOINC/boinc.git"
include_regex = '^client_release/[0-9]+(\.[0-9]+)?/[0-9]+(\.[0-9]+){2}$'
from_pattern = '^client_release/[0-9]+(\.[0-9]+)?/'
to_pattern = ''
