# Copied/modified from frandom.install

# arg 1: the new package version
# arg 2: the old package version

post_install () {
  echo ">> Place 'vhba' in MODULES= in /etc/rc.conf to enable vhba on system boot."
  echo ">> This module needs to be recompiled for every kernel version upgrade."
  depmod -a
}

pre_remove () {
  rmmod vhba 2> /dev/null
}

post_remove () {
  depmod -a
}

op=$1
shift
$op $*
