#!/bin/bash

pyver=$(pacman -S --print-format %v python | grep -oP '^[0-9]+\.[0-9]+')
exclude=('pypy3\?' 'cuda' 'cuda-tools' 'metasploit' 'ghidra' 'polymake')

{
pacman -Fq /usr/lib/python${pyver}/ | grep -v archlinuxcn | cut -d / -f 2
pacman -Fxq "\.cpython-${pyver/.}.pyc$" | grep -v archlinuxcn | cut -d / -f 2
sogrep all libpython${pyver}.so
ssh build.archlinux.org "parallel \"zstdgrep -q 'Py_Initialize\|PyInit_\|PyModule_Create2\|#!.*python${pyver}' {} && pacman -Qpq {}\" ::: /srv/ftp/pool/packages/*.zst"
} | grep -xvf <(printf "%s\n" "${exclude[@]}") | sort -u
