#!/bin/bash

pyver=$(pacman -S --print-format %v python | grep -oP '^[0-9]+\.[0-9]+')
exclude=('pypy3\?' 'cuda' 'cuda-tools' 'metasploit' 'ghidra' 'polymake' 'nvidia-settings')
current_time=$(date +%s)
file_time=$(stat --format=%Y "/var/lib/pacman/sync/core.files")

if [ $((current_time - file_time)) -gt 86400 ]; then
	echo "pacman files database is out of date, please run pacman -Fy"
	exit 1
fi

{
pacman -Fq /usr/lib/python${pyver}/ | grep -v archlinuxcn | cut -d / -f 2
pacman -Fxq "\.cpython-${pyver/.}.pyc$" | grep -v archlinuxcn | cut -d / -f 2
sogrep all libpython${pyver}.so
ssh build.archlinux.org "parallel \"zstdgrep -q 'Py_Initialize\|PyInit_\|PyModule_Create2\|#!.*python${pyver}' {} && pacman -Qpq {}\" ::: /srv/ftp/pool/packages/*.zst"
} | grep -xvf <(printf "%s\n" "${exclude[@]}") | sort -u
