# arg 1:  the new package version
# arg 2:  the old package version

KERNEL_VERSION=4.1.0-1

post_install () {
  # updating module dependencies
  echo ">>> Updating module dependencies. Please wait ..."
  depmod ${KERNEL_VERSION}

  echo "NOTE: Using this kernel requires an updated U-Boot!"
}

post_upgrade() {
  # updating module dependencies
  echo ">>> Updating module dependencies. Please wait ..."
  depmod ${KERNEL_VERSION}
}
