CFLAGS := $(CFLAGS) -D_FORTIFY_SOURCE=2 -Wall -W $(shell pkg-config --cflags glib-2.0)
LDFLAGS := $(shell pkg-config --libs glib-2.0)

OBJS = bitmap.o irqbalance.o cputree.o procinterrupts.o irqlist.o \
	placement.o activate.o network.o powermode.o numa.o classify.o

all: irqbalance

irqbalance: $(OBJS)
	$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)

clean:
	rm -f irqbalance *~ *.o
