post_install() {
  cat <<MSG
>>> This package replaces murmur!
    Stop murmur.service, move /var/db/murmur/murmur.sqlite
    to /var/lib/mumble-server/mumble-server.sqlite and
    consolidate /etc/murmur.ini with /etc/mumble/mumble-server.ini.
    When starting with a new database, create a superuser password
    before starting mumble-server.service, by running the following
    as the _mumble-server user:
    mumble-server -ini /etc/mumble/mumble-server.ini -supw <password>
MSG
}
