post_install() {
  echo "==> Check /etc/yaourtrc, syntax of configuration file changes."
  echo "  -> man yaourtrc"
  echo "==> To use yaourt as a user, add these entries to /etc/sudoers:"
  echo "  -> user ALL=NOPASSWD: /usr/bin/pacman"
  echo "  -> user ALL=NOPASSWD: /usr/bin/pacdiffviewer"
  echo "     (Please, use sudo carefully.)"
  echo "==> For fully colorized output via pacman-color:"
  echo "  -> Set the PacmanBin option in /etc/yaourtrc"
}

post_upgrade() {
  post_install $1
}
