#!/bin/bash

# general config
. /opt/etc/rc.conf
. /opt/etc/rc.d/functions

case "$1" in
    start)
        stat_busy "Starting D-BUS system messagebus"
	if [ ! -x /opt/var/run/dbus ] ; then
	    install -m755 -g 81 -o 81 -d /opt/var/run/dbus
	fi
        if [ -x /opt/bin/dbus-uuidgen ] ; then
            /opt/bin/dbus-uuidgen --ensure
        fi

        /opt/bin/dbus-daemon --system
        if [ $? -gt 0 ]; then
            stat_fail
        else
            add_daemon dbus
            stat_done
        fi
        ;;
    stop)
        stat_busy "Stopping D-BUS system messagebus"
	[ -f /opt/var/run/dbus.pid ] && kill `cat /opt/var/run/dbus.pid` >/dev/null 2>&1
        if [ $? -gt 0 ]; then
            stat_fail
        else
	    rm -f /opt/var/run/dbus.pid
            rm_daemon dbus
            stat_done
        fi
        ;;
    restart)
        $0 stop
	sleep 1
        $0 start
        ;;
    reload)
        stat_busy "Reloading D-BUS configuration"
        [ -f /opt/var/run/dbus.pid ] && /opt/bin/dbus-send \
                --system --type=method_call \
                --dest=org.freedesktop.DBus \
                / org.freedesktop.DBus.ReloadConfig
        if [ $? -gt 0 ]; then
            stat_fail
        else
            stat_done
        fi
        ;;
    *)
        echo "usage: $0 {start|stop|restart|reload}"
	;;
esac
exit 0
