pkgname=evince

post_install() {
  usr/sbin/gconfpkg --install ${pkgname}
  gtk-update-icon-cache -q -f -t usr/share/icons/hicolor
  update-desktop-database -q
}

pre_upgrade() {
  pre_remove $1
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  usr/sbin/gconfpkg --uninstall ${pkgname}
}

post_remove() {
  update-desktop-database -q
  gtk-update-icon-cache -q -f -t usr/share/icons/hicolor
}
