post_install() {
  if [ -z "$(grep ^proxy: /etc/group)" ]; then
    groupadd -g 15 proxy &>/dev/null
  fi

  id proxy &>/dev/null || \
    useradd -u 15 -g proxy -d /var/empty proxy

  chown proxy.proxy var/{cache,log}/squid

#  cat << EOF
#Release notes:  http://www.squid-cache.org/Versions/v3/3.1/RELEASENOTES.html
#EOF
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  userdel proxy &> /dev/null
  if [ ! -z "$(grep ^proxy: /etc/group)" ]; then
    groupdel proxy &>/dev/null
  fi
}

