
#TODO the addition of other implementation support should be added here. We
# can/should generate catalogs for mzscheme, drscheme, whatever else we can

post_upgrade () {
    echo ":: Building guile catalog"
    /usr/bin/guile -c "((use-modules (ice-9 slib))(require 'new-catalog)(quit))"
}
post_install() {
    post_upgrade $1
}

pre_remove() {
    echo ":: Removing guile catalog"
    rm /usr/share/guile/site/slibcat
}
