#!/bin/bash

# 0 = Don't enable SPI. Use default boot.txt.
# 1 = Enable SPI. This disables HDMI functionality.
ENABLE_SPI=0

if [[ ! -x /usr/bin/mkimage ]]; then
  echo "mkimage not found. Please install uboot-tools:"
  echo "  pacman -S uboot-tools"
  exit 1
fi

if [[ ${ENABLE_SPI} -eq 0 ]]; then
  cp boot.txt.default boot.txt
else
  cp boot.txt.spi boot.txt
fi

mkimage -A arm -O linux -T script -C none -n "U-Boot boot script" -d boot.txt boot.scr
