#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
  start)
    stat_busy "Starting system-tools-backends"
    /usr/bin/system-tools-backends
    if [ $? -gt 0 ]; then
      stat_fail
    else
      stat_done
      add_daemon stbd
    fi
    ;;
  stop)
    stat_busy "Stopping system-tools-backends"
    killall system-tools-backends
    if [ $? -gt 0 ]; then
      stat_fail
    else
      stat_done
      rm_daemon stbd
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
