# This PKGBUILD was generated by cpan4pacman via CPANPLUS::Dist::Pacman
# Maintainer : Aaron Griffin <aaron@archlinux.org>

pkgname=perl-text-wrapi18n
_realname=Text-WrapI18N
pkgver=0.06
pkgrel=3
pkgdesc="Line wrapping module with support for multibyte, fullwidth, and combining characters and languages without whitespaces between words"
arch=(i686 x86_64)
license=('GPL' 'PerlArtistic')
url="http://search.cpan.org/dist/${_realname}/"
depends=('perl>=5.10.0')
source=(http://search.cpan.org/CPAN/authors/id/K/KU/KUBOTA/${_realname}-${pkgver}.tar.gz)
options=(!emptydirs)
md5sums=('0799c16a00926e6c18d400c2e2861d5f')

build()
{
  cd  $startdir/src/${_realname}-${pkgver}
  # install module in vendor directories.
  /usr/bin/perl Makefile.PL INSTALLDIRS=vendor || return 1
  /usr/bin/make || return 1
  /usr/bin/make DESTDIR=${startdir}/pkg install

  # remove perllocal.pod, .packlist, and empty dirs:
  /usr/bin/find ${startdir}/pkg -name '.packlist' -delete
  /usr/bin/find ${startdir}/pkg -name 'perllocal.pod' -delete
}
