# arg 1:  the new package version
post_install() {
  echo "Before starting klogwatch the log file to be monitored must be
readable. For example as root: chown 644 /var/log/<logfile>
To make the permissions to be set on boot edit /etc/syslog-ng.conf
and add perm(644) after the log file to be monitored 
For example:
destination iptables { file("/var/log/iptables.log" perm(644)); }"
  /bin/true
}

op=$1
shift
$op $*
