post_install() {
  install-info usr/share/info/xboard.info.gz usr/share/info/dir 2> /dev/null
  install-info usr/share/info/copyright.info.gz usr/share/info/dir 2> /dev/null
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  install-info --delete usr/share/info/xboard.info.gz usr/share/info/dir 2> /dev/null
  install-info --delete usr/share/info/copyright.info.gz usr/share/info/dir 2> /dev/null
}
