pkgname=rhythmbox

post_install() {
  usr/sbin/gconfpkg --install ${pkgname}
  update-desktop-database -q
  gtk-update-icon-cache -f -q -t usr/share/icons/hicolor
}

pre_upgrade() {
  pre_remove
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  usr/sbin/gconfpkg --uninstall ${pkgname}
}

post_remove() {
  update-desktop-database -q
  gtk-update-icon-cache -f -q -t usr/share/icons/hicolor
}
