post_upgrade() {
  if (($(vercmp 5.8.0-1 $2) > 0)); then
    echo "
    Strongswan 5.8.0-1 introduced new names for the systemd unit files:

    strongswan.service got renamed to strongswan-starter.service
    strongswan-swanctl.service got renamed to strongswan.service

    If you use the legacy ipsec.conf, you need to enable
    strongswan-starter.service from now on.

    If you use swanctl, you need to enable strongswan.service from now on.
    EOF
    "
  fi
}
