infodir=/usr/share/info
filelist=(heimdal hx509)

post_install() {
  for file in ${filelist[@]}; do
    install-info $infodir/$file.info.gz $infodir/dir 2> /dev/null
    ln -s /usr/lib/libhx509.so.5 /usr/lib/libhx509.so.4
  done
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  for file in ${filelist[@]}; do
    install-info --delete $infodir/$file.info.gz $infodir/dir 2> /dev/null
    rm /usr/lib/libhx509.so.4
  done
}

