pre_upgrade() {
    if [ "$(vercmp $2 2.3.2-1)" -lt 0 ]; then
        echo "==> Fixing potential ABS tree permission issues (this may take a while...)"
    
        for dir in core extra community testing; do
            if [ -d /var/abs/$dir ]; then
                find /var/abs/$dir -type d -exec chown root:root {} \;
                find /var/abs/$dir -type d -exec chmod 755 {} \;
            fi
        done
    fi
}
