flash_uboot() {
  echo "A new U-Boot version is available to be flashed."
  echo "Replace 'mmcblkX' with your boot drive to flash SD or eMMC:"
  echo "  dd if=/boot/u-boot-rockchip.bin of=/dev/mmcblkX seek=64 bs=512 conv=notrunc,fsync"
  echo "To update SPI flash:"
  echo "  flashcp -p /boot/idbloader-spi.img /dev/mtd0"
  echo "  flashcp -p /boot/u-boot.itb /dev/mtd2"
  echo "  flash_erase /dev/mtd1 0 0"
}

post_install() {
  flash_uboot
}

post_upgrade() {
  flash_uboot
}
