#! /bin/bash
#
# pmtop - poor man's `top' for SunOS 4.x
#

CLEAR=clear	# could also be 'tput clear'
HEADER="USER       PID %CPU %MEM   SZ  RSS TT STAT START  TIME COMMAND"

if [ -n "$LINES" ]; then
	SS=$(( $LINES - 2 ))
else
	SS=20
fi

while :
do
	$CLEAR
	echo "$HEADER"
	ps -aux | sort -nr -k 3 | sed ${SS}q
	sleep 5
done

exit 0

	
