post_install() {
cat << EOF
Note:
==> In case you experience access permission error for the attached Garmin GPS device,
==> see http://wiki.openstreetmap.org/wiki/USB_Garmin_on_GNU/Linux for more details.
==> Disable garmin_gps module and see included example udev rule:
==> echo "blacklist garmin_gps" > /etc/modprobe.d/garmindev.conf
==> cd /etc/udev/rules.d ; ln -s /usr/share/garmindev/51-garmin.rules 51-garmin.rules
EOF
}
