flash_uboot() {
  echo "A new U-Boot version is available to be flashed."
  echo "Replace 'mmcblkX' with your boot drive to update:"
  echo "  dd if=/home/leming/source/u-boot.bin.sd.bin of=/dev/mmcblkX conv=fsync,notrunc bs=512 skip=1 seek=1
  echo "  dd if=/home/leming/source/u-boot.bin.sd.bin of=/dev/mmcblkX conv=fsync,notrunc bs=1 count=440"
}

post_install() {
  flash_uboot
}

post_upgrade() {
  flash_uboot
}
