# arg 1:  the new package version
post_install() {
    echo "Place menu.xml and rc.xml in ~/.config/openbox"
    echo "They can both be found in /etc/xdg/openbox"
    /bin/true
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  post_install $1
}

# arg 1:  the old package version
pre_remove() {
  /bin/true
}

# arg 1:  the old package version
post_remove() {
  /bin/true
}

op=$1
shift
$op $*
