# arg 1: the new package version 
post_install() {
  echo -n "Updating font cache... " 
  fc-cache -f > /dev/null
  mkfontscale /usr/share/fonts/local
  mkfontdir /usr/share/fonts/local
  echo "done."
  echo "Note: terminus-font is in /usr/share/fonts/local/"
}

# # arg 1: the new package version 
# # arg 2: the old package version 
post_upgrade() { 
  post_install $1 
} 
#
# # arg 1: the old package version 
post_remove() { 
  post_install $1
} 

op=$1 
shift 

$op $*
