# CMake generated Testfile for 
# Source directory: /home/dave/git/PKGBUILDs-1/community/supercollider/src/SuperCollider-Source/testsuite/sclang
# Build directory: /home/dave/git/PKGBUILDs-1/community/supercollider/src/SuperCollider-Source/bld/testsuite/sclang
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(/home/dave/git/PKGBUILDs-1/community/supercollider/src/SuperCollider-Source/testsuite/sclang/sclang_crash_1.scd_run "/home/dave/git/PKGBUILDs-1/community/supercollider/src/SuperCollider-Source/bld/testsuite/sclang/../../lang/sclang" "-l" "/home/dave/git/PKGBUILDs-1/community/supercollider/src/SuperCollider-Source/bld/testsuite/sclang/../../build_sclang.cfg" "/home/dave/git/PKGBUILDs-1/community/supercollider/src/SuperCollider-Source/testsuite/sclang/sclang_crash_1.scd")
ADD_TEST(/home/dave/git/PKGBUILDs-1/community/supercollider/src/SuperCollider-Source/testsuite/sclang/sclang_crash_2.scd_run "/home/dave/git/PKGBUILDs-1/community/supercollider/src/SuperCollider-Source/bld/testsuite/sclang/../../lang/sclang" "-l" "/home/dave/git/PKGBUILDs-1/community/supercollider/src/SuperCollider-Source/bld/testsuite/sclang/../../build_sclang.cfg" "/home/dave/git/PKGBUILDs-1/community/supercollider/src/SuperCollider-Source/testsuite/sclang/sclang_crash_2.scd")
ADD_TEST(/home/dave/git/PKGBUILDs-1/community/supercollider/src/SuperCollider-Source/testsuite/sclang/sclang_crash_deprecated.scd_run "/home/dave/git/PKGBUILDs-1/community/supercollider/src/SuperCollider-Source/bld/testsuite/sclang/../../lang/sclang" "-l" "/home/dave/git/PKGBUILDs-1/community/supercollider/src/SuperCollider-Source/bld/testsuite/sclang/../../build_sclang.cfg" "/home/dave/git/PKGBUILDs-1/community/supercollider/src/SuperCollider-Source/testsuite/sclang/sclang_crash_deprecated.scd")
ADD_TEST(/home/dave/git/PKGBUILDs-1/community/supercollider/src/SuperCollider-Source/testsuite/sclang/sclang_crash_3.scd_run "/home/dave/git/PKGBUILDs-1/community/supercollider/src/SuperCollider-Source/bld/testsuite/sclang/../../lang/sclang" "-l" "/home/dave/git/PKGBUILDs-1/community/supercollider/src/SuperCollider-Source/bld/testsuite/sclang/../../build_sclang.cfg" "/home/dave/git/PKGBUILDs-1/community/supercollider/src/SuperCollider-Source/testsuite/sclang/sclang_crash_3.scd")
