post_install() {
  echo "-> Bitlbee can run through xinetd or as a daemon for now."
  if [ ! `grep bitlbee /etc/group` ]; then
    groupadd -g 65 bitlbee &>/dev/null;
  fi

  id bitlbee &>/dev/null || \
    useradd -u 65 -g bitlbee -d /var/lib/bitlbee -s /bin/false bitlbee
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  userdel bitlbee &> /dev/null
  groupdel bitlbee &> /dev/null
}

post_remove() {
  /bin/true
}

op=$1
shift

$op $*
# vim: ts=2 sw=2 et ft=sh
