
# This schema file defines the preferences parameters of the profiles service
# For the moment all we have is a dict of (str -> int)
# The strings are the profiles name.
# The int have no meaning, it will be replaced by a real structure later

profiles:
    type: list
