#! /bin/sh
#
# run-minimal - a version of run-all for shells configured with
#		--enable-minimal-config
#
PATH=.:$PATH	# just to get the right version of printenv
export PATH

# unset BASH_ENV only if it is set
[ "${BASH_ENV+set}" = "set" ] && unset BASH_ENV
# ditto for SHELLOPTS
#[ "${SHELLOPTS+set}" = "set" ] && unset SHELLOPTS

: ${THIS_SH:=../bash}
export THIS_SH

${THIS_SH} ./version.mini

rm -f /tmp/xx

echo Testing ${THIS_SH}
echo Any output from any test, unless otherwise noted, indicates a possible anomaly
for x in run-*
do
	case $x in
	$0)	;;
	*.orig|*~) ;;
	run-dollars|run-execscript|run-func|run-getopts|run-heredoc) echo $x ; sh $x ;;
	run-ifs-tests|run-input-test|run-invert|run-more-exp|run-nquote) echo $x ; sh $x ;;
	run-ifs-posix|run-posix2|run-posixpat) echo $x ; sh $x ;;
	run-precedence|run-quote|run-read|run-rhs-exp|run-strip|run-tilde) echo $x ; sh $x ;;
	*)	;;
	esac
done

exit 0
