pre_install() {
  if [ ! -e var/games/xbill/scores ]; then
    [ -e usr/var/xbill/scores ] && mv usr/var/xbill/scores var/games/xbill/scores
  fi
}

post_install() {
  touch var/games/xbill/scores
  chown root:games var/games/xbill/scores
  chmod 664 var/games/xbill/scores
}

pre_upgrade() {
  pre_install $1
}

post_upgrade() {
  post_install $1
}

post_remove() {
  if [ -e var/games/xbill/scores ]; then
    mv var/games/xbill/scores var/games/xbill/scores.pacsave
  fi
}
