pkgname=ghc

pre_upgrade() {
    cat << EOF
    ==> Unregistering cabalized packages...
EOF
    cd /usr/share/haskell/ && (for a in *; do ghc-pkg unregister --force $a &> /dev/null; done; cd - > /dev/null )
    cat << EOF
    ==> Done.
EOF
    
}

post_upgrade() {
    cat << EOF
    ==> All cabalized and yaourt-installed packages need to be reinstalled now.
    ==> See /usr/share/haskell/ and ghc-pkg list --user for a tentative list of affected packages.
EOF
}

op=$1
shift
