post_install () {
  # Check user/group incron exists
  getent group incron > /dev/null || groupadd incron
  getent passwd incron > /dev/null || useradd -c "Incron system" -g incron -s /bin/false -d /var/spool/incron incron
  # Fix permissions
  chown incron.incron -R /var/spool/incron
}

pre_remove() {
  [ -h /var/service/incron ] && rm /var/service/incron
  /etc/rc.d/incron stop
  usr/sbin/userdel incron >& /dev/null
  usr/sbin/groupdel incron >& /dev/null
}

