#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
  start)
    stat_busy "Starting NIS Password Daemon"
    /usr/sbin/rpc.yppasswdd
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon yppasswd
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping NIS Password Daemon"
    killall -q /usr/sbin/rpc.yppasswdd
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon yppasswd
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
