#!/bin/bash
_pkgver=`grep -Po "_pkgver=\K.*" PKGBUILD`
_chromiumver=`curl -s https://code.qt.io/cgit/qt/qtwebengine.git/plain/CHROMIUM_VERSION?h=$_pkgver | grep -Po "Based on Chromium version:\s+\K\d+"`
_commit=`git ls-remote https://code.qt.io/qt/qtwebengine-chromium.git $_chromiumver-based | cut -f1`
sed -r "s|_chromium=.*|_chromium=$_commit|" -i PKGBUILD
