#!/bin/bash
_pkgver=`grep -Po "_pkgver=\K.*" PKGBUILD`
_chromiumver=`curl -s https://raw.githubusercontent.com/qt/qtwebengine/refs/heads/$_pkgver/CHROMIUM_VERSION | grep -Po "Based on Chromium version:\s+\K\d+"`
_commit=`git ls-remote https://github.com/qt/qtwebengine-chromium.git $_chromiumver-based | cut -f1`
sed -r "s|_chromium=.*|_chromium=$_commit|" -i PKGBUILD
