#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

PID=`pidof -x -o %PPID /usr/bin/denyhosts.py`
case "$1" in
  start)
    stat_busy "Starting denyhosts"
    [ -z "$PID" ] && /usr/bin/denyhosts.py --daemon
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon denyhosts
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping denyhosts"
    [ ! -z "$PID" ] && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon denyhosts
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 3
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
esac
exit 0			
