#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
  start)
    stat_busy "Writing SysStat restart record"
    /usr/lib/sa/sadc -L -F -
    if [ $? -gt 0 ]; then
      stat_fail
    else
      stat_done
    fi
    ;;
  stop)
    ;;
  *)
    echo "usage: $0 {start|stop}"  
esac
exit 0
