pkgname=ownCloud

post_install() {
   echo "Add the following lines into /etc/httpd/conf/httpd.conf:"
   echo "Include /etc/httpd/conf/extra/owncloud.conf"
   echo "LoadModule php5_module modules/libphp5.so"
   echo "Include conf/extra/php5_module.conf"
   echo
   echo "Uncomment extensions xmlrpc.so zip.so gd.so"
   echo "and either sqlite.so sqlite3.so (for the SQLite backend) or mysql.so mysqli.so (for the MySQL backend)"
   echo "in /etc/php/php.ini"
}
