pkgname=gnome-system-tools

post_install() {
  usr/sbin/gconfpkg --install ${pkgname}
  scrollkeeper-update -q -p var/lib/scrollkeeper
  update-desktop-database -q
}

pre_upgrade() {
  pre_remove $1
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  usr/sbin/gconfpkg --uninstall ${pkgname}
}

post_remove() {
  update-desktop-database -q
  scrollkeeper-update -q -p var/lib/scrollkeeper
}

op=$1
shift

$op $*
