KERNEL_NAME=
KERNEL_VERSION=2.6.38-6-ARCH

post_install() {
# ARM doesn't use mkinitcpio or anything like that
# so we skip it here
echo -e "\033[1mNotice\033[0m"
echo "To complete the installation you will have to copy"
echo "/boot/uImage to the proper location, e.g. /dev/mmcblk0p1"
echo ""
echo "This package is built for the TrimSlice."
echo ""
/sbin/depmod ${KERNEL_VERSION}
}

post_upgrade() {
	post_install
}

op=$1
shift
$op $*
