pre_install() {
  /bin/true
}

post_install() {
  cat << EOF
--
-- You can switch keymaps in /etc/rc.conf
--
-- KEYMAP="ru-utf"
--     Right Control switch languages
--
-- KEYMAP="ru-utf-menu-swapcaps"
--     Menu key switch languages
--     Swap CapsLock and Left Control
--
EOF
  /bin/true
}

pre_upgrade() {
  /bin/true
}

post_upgrade() {
  /bin/true
}

pre_remove() {
  /bin/true
}

post_remove() {
  /bin/true
}

op=$1
shift
$op $*
