#!/bin/bash

# source application-specific settings
[ -f /etc/conf.d/saslauthd ] && . /etc/conf.d/saslauthd

. /etc/rc.conf
. /etc/rc.d/functions

DAEMON_NAME="saslauthd"
SASLAUTHD_BIN=/usr/sbin/saslauthd
SASLAUTHD_PID=`pidof -o %PPID $SASLAUTHD_BIN`

case "$1" in
  start)
    stat_busy "Starting $DAEMON_NAME"
    [ -z "$SASLAUTHD_PID" ] && $SASLAUTHD_BIN $SASLAUTHD_OPTS
    if [ $? -gt 0 ]; then
      stat_fail
      exit 1
    else
      echo `pidof -o %PPID $SASLAUTHD_BIN` > /var/run/$DAEMON_NAME.pid
    fi
    add_daemon $DAEMON_NAME
    stat_done
    ;;

  stop)
    stat_busy "Stopping $DAEMON_NAME"
    [ ! -z "$SASLAUTHD_PID" ]  && kill $SASLAUTHD_PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
      exit 1
    else
      rm /var/run/$DAEMON_NAME.pid &> /dev/null
    fi
    rm_daemon $DAEMON_NAME
    stat_done
    ;;

  restart)
    $0 stop
    sleep 1
    $0 start
    ;;

  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
# vim: ts=2 sw=2 et ft=sh
