#!/bin/sh
# BROKEN FOR NOW, I don't have enough time to finish it...
#
# This script deletes packages from the aur PKGBUILD folder we have in git,
# redownloads all packages from a list, and extracts them to git again.
#
# This is to keep our [aur] repo up-to-date.
#
GITDIR=/build/alarm
AURTARBALLURL=https://aur.archlinux.org/cgit/aur.git/snapshot/

# Only the following packages will be deleted and re-downloaded
declare -a PKGLIST=('yaourt' 'open-iscsi');

cd $GITDIR/aur

for PKG in "${PKGLIST[@]}"
do
rm -rf $PKG
wget $AURTARBALLURL/$PKG.tar.gz
tar xzf $PKG.tar.gz
rm -rf $PKG.tar.gz
done