#!/bin/sh
# BROKEN FOR NOW, I don't have enough time to finish it...
#
# This script deletes packages from the aur PKGBUILD folder we have in git,
# redownloads all packages from a list, and extracts them to git again.
#
# This is to keep our [aur] repo up-to-date.
#
GITDIR=/build/plugapps
AURTARBALLURL=http://aur.archlinux.org/packages/

# Only the following packages will be deleted and re-downloaded
PKGLIST=yaourt open-iscsi

# Main loop
cd $GITDIR/aur

rm -rf $PKGLIST

#wget $AURTARBALLURL/$PKGLIST/$PKGLIST.tar.gz

#tar xzf $PKGLIST.tar.gz
