#!/bin/sh
# Set me to where you want packages
cd /media/usb/builder/pkg/core
echo $1
pacman -Ssq $1
if [ $? = 0 ] 
then
{
  echo $1 "already exists."
}
else
{
  if [ ! -d ./$1 ]
  then
  {
    cp -r /media/usb/builder/abs/core/$1 .
    # You might want to change me too
  }
  fi
  cd $1
  f=`find . -name *.pkg.tar*`
  echo $f
  if [ -z $f  ]
  then
    echo $1
    makepkg --ignorearch --asroot --clean --syncdeps --noconfirm --rmdeps 2> $1-`date +%s`.log
  fi
}
fi
