infodir=/opt/share/info
filelist=(gcrypt.info)

post_install() {
  [ -x opt/bin/install-info ] || return 0
  for file in ${filelist[@]}; do
    install-info $infodir/$file $infodir/dir 2> /dev/null
  done
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  [ -x opt/bin/install-info ] || return 0
  for file in ${filelist[@]}; do
    install-info --delete $infodir/$file $infodir/dir 2> /dev/null
  done
}
