post_install() {
	xdg-icon-resource forceupdate --theme hicolor &> /dev/null
	ggz-config -i -f -m usr/share/ggz/kreversi.dsc >& /dev/null
}

pre_remove() {
	if [ -f usr/share/ggz/kreversi.dsc ]; then
		ggz-config -r -m usr/share/ggz/kreversi.dsc >& /dev/null
	fi
}

pre_upgrade() {
	pre_remove
}

post_upgrade() {
	post_install
}

post_remove() {
	xdg-icon-resource forceupdate --theme hicolor &> /dev/null
}
