post_install() {
  # Friendly message for new users
  echo
  echo 'The "liteide" package provides an IDE for editing and building Go projects.'
  echo
  echo 'Example use of the "go" tool:'
  echo
  echo '    mkdir ~/go'
  echo '    export GOPATH=~/go'
  echo '    export PATH=$PATH:~/go/bin'
  echo '    go get code.google.com/p/go-tour/gotour'
  echo
  ####
  post_upgrade
}

post_upgrade() {
  # See FS#41561
  go install std 
}

# vim:set ts=2 sw=2 et:
