#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

get_pid() {
	echo `pidof epmd; pidof beam; pidof ssl_esock; pidof epmd.smp; pidof beam.smp`
}

case "$1" in
  start)
    stat_busy "Starting ejabber daemon"

    [ -f /var/run/ejabber.pid ] && rm -f /var/run/ejabber.pid
    PID=`get_pid`
    if [ -z "$PID" ]; then
      su ejabberd -s /bin/bash - -c 'erl -pa /usr/lib/ejabberd/ebin -sname ejabberd -s ejabberd -ejabberd config \"/etc/ejabberd/ejabberd.cfg\" log_path \"/var/log/ejabberd/ejabberd.log\" -sasl sasl_error_logger \{file,\"/var/log/ejabberd/sasl.log\"\} -mnesia dir \"/var/spool/ejabberd\" -detached -kernel inetrc \"/etc/ejabberd/inetrc\"'
      if [ $? -gt 0 ]; then
        stat_fail
        exit 1
      else
        echo `get_pid` > /var/run/ejabberd.pid
        add_daemon ejabberd
        stat_done
      fi
    else
      stat_fail
      exit 1
    fi
    ;;

  stop)
    stat_busy "Stopping ejabber daemon"
    PID=`get_pid`
    [ ! -z "$PID" ] && su ejabberd -s /bin/bash - -c "kill $PID" &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
      exit 1
    else
      rm -f /var/run/ejabberd.pid &> /dev/null
      rm_daemon ejabberd
      stat_done
    fi
    ;;

  restart)
    $0 stop
    sleep 3
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
