post_install() {
	echo "
	==> By default, Listen comes with mp3 and ogg-vorbis support.
	==> For flac support: pacman -S gstreamer0.10-flac
	==> For musepack support: pacman -S gstreamer0.10-musepack
	==> For mp4 & m4a support: pacman -S gstreamer0.10-faad
	==> For iPod support: pacman -S libgpod
	==> For musicbrainz & Audio CD support: pacman -S python-musicbrainz2
	==> For hal support: pacman -S hal and start the hal daemon"
}

post_upgrade() {
	post_install $1
}

