#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
  start)
    stat_busy "Starting ADSL Connection"
    /usr/sbin/pppoe-start &>/dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon adsl
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping ADSL Connection"
    /usr/sbin/pppoe-stop &>/dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon adsl
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
