[libreoffice-fresh]
source = "regex"
regex = "libreoffice-([\\d.]+)\\."
url = "https://www.libreoffice.org/download/download-libreoffice/"
from_pattern = '(\d+).(\d+).(\d+).(\d+)'
to_pattern = '\1.\2.\3'
