post_install() {
  xdg-icon-resource forceupdate --theme hicolor
  update-desktop-database -q
  update-mime-database usr/share/mime > /dev/null 2>&1
  
#  echo "> LibreOffice now uses highly experimental gtk3 vcl by default"
#  echo "> on some desktops. To use stable gtk2 vcl uncomment"
#  echo "> it in /etc/profile.d/libreoffice-fresh.{sh,csh}"
}

post_upgrade() {
  post_install $1
}

post_remove() {
  post_install $1
}
