
post_install() {
  echo ">>> NOTE"
  echo ">>> You must add 'timidity++' to your DAEMONS array in your /etc/rc.conf"
  echo ">>> as well as adding 'snd-seq' to your MODULES array"
  echo ">>> otherwize noteedit will not launch or you won't hear any sound"
  echo ">>> "
  echo ">>> Don't forget to download midi soundfonts from http://www.hammersound.net/"
  echo ">>> Check /etc/timidity++/timidity.cfg for more information"
}

op=$1
shift

$op $*
