diff --git a/Makefile b/Makefile
index d8a0e01..9596d6c 100644
--- a/Makefile
+++ b/Makefile
@@ -3022,8 +3022,8 @@ install-headers_c:
 
 install-headers_cxx:
 	$(E) "[INSTALL] Installing public C++ headers"
-	$(Q) $(foreach h, $(PUBLIC_HEADERS_CXX), $(INSTALL) -d $(prefix)/$(dir $(h)) && ) exit 0 || exit 1
-	$(Q) $(foreach h, $(PUBLIC_HEADERS_CXX), $(INSTALL) $(h) $(prefix)/$(h) && ) exit 0 || exit 1
+	$(Q) DIRS="$(shell dirname $(PUBLIC_HEADERS_CXX) | uniq )"; 		for d in $$DIRS; do [ ! -d $(prefix)/$$d ] && $(INSTALL) -d $(prefix)/$$d || : ; done
+	$(Q) for f in $(PUBLIC_HEADERS_CXX); do $(INSTALL) $$f $(prefix)/$$f ; done
 
 install-static: install-static_c install-static_cxx
 
