[glibc]
source = "git"
git = "https://sourceware.org/git/glibc.git"
prefix = "glibc-"
# There are also open branch tags ending with .90 but they moved on
# to sticky with .9000 only.
include_regex = "^glibc-[.0-9]+$"
exclude_regex = ".*\\.9000$"
