infodir=usr/share/info
filelist=(libc.info{,-1,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11})

post_upgrade() {
  locale-gen

  ldconfig -r .
  
  [[ -x usr/bin/install-info ]] || return 0
  for file in ${filelist[@]}; do
    install-info $infodir/$file.gz $infodir/dir 2> /dev/null
  done
}

pre_remove() {
  [[ -x usr/bin/install-info ]] || return 0
  for file in ${filelist[@]}; do
    install-info --delete $infodir/$file.gz $infodir/dir 2> /dev/null
  done
}
