#!/bin/bash

. /opt/etc/rc.conf
. /opt/etc/rc.d/functions

PID=`pidof -o %PPID /opt/sbin/nscd`
case "$1" in
  start)
    stat_busy "Starting nscd"
    # create necessary directories if they don't already exist
    mkdir -p /opt/var/run/nscd /opt/var/db/nscd 2>/dev/null
    # remove stale files
    rm -f /opt/var/db/nscd/* /opt/var/run/nscd/* 2>/dev/null
    [ -z "$PID" ] && /opt/sbin/nscd
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon nscd
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping nscd"
    [ ! -z "$PID" ]  && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon nscd
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
