# Shadow Stack
# With 55d63e731253de82e96ed4ddca2e294076cd0bc5 CET is disabled by default.
# To enabled Shadow Stack at all, uncomment

# glibc.cpu.hwcaps=SHSTK

# Tunable glibc.cpu.x86_shstk
# The glibc.cpu.x86_shstk tunable allows the user to control how
# the shadow stack (SHSTK) should be enabled.  Accepted values are
# `on`, `off` and `permissive`. `on` always turns on
# SHSTK regardless of whether SHSTK is enabled in the executable and its
# dependent shared libraries. `off` always turns off SHSTK regardless
# of whether SHSTK is enabled in the executable and its dependent shared
# libraries. `permissive` changes how dlopen works on non-CET shared
# libraries. By default, when SHSTK is enabled, dlopening a non-CET shared
# library returns an error. With `permissive` it turns off SHSTK
# instead.
# BEWARE! A multi threaded process in permissive mode can not disable shstk on the
# other threads so it will trigger a fast fail and terminates the entire process.

# glibc.cpu.x86_shstk=on

# Disable shstk for a certain app by creating
#
# /etc/tunables.conf.d/<app>.conf:
#
# [proc:/usr/bin/app]
# glibc.cpu.x86_shstk=off
#
# Then run ldconfig -X as root

