pkgname=mail-notification

post_install() {
  usr/sbin/gconfpkg --install ${pkgname}
  kill -s HUP `pidof bonobo-activation-server` > /dev/null 2>&1
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}

pre_upgrade() {
  pre_remove $1
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  usr/sbin/gconfpkg --uninstall ${pkgname}
}

post_remove() {
  kill -s HUP `pidof bonobo-activation-server` > /dev/null 2>&1
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}
