#!/bin/bash

build() {
    local rules tool

    map add_binary \
        '/usr/lib/systemd/systemd-udevd' \
        '/usr/bin/udevadm' \
        '/usr/bin/systemd-tmpfiles'

    map add_udev_rule \
        '50-udev-default.rules' \
        '60-persistent-storage.rules' \
        '64-btrfs.rules' \
        '80-drivers.rules'
    
    map add_file \
        '/usr/lib/udev/ata_id' \
        '/usr/lib/udev/scsi_id'

    add_runscript
}

help() {
    cat <<HELPEOF
This hook adds the udev daemon to the initramfs, allowing for dynamic loading
of modules and reliable detection of the root device via tags (e.g. UUID or
LABEL). Do not remove this hook unless you are using the systemd hook, or you
know what you're doing.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
