# arg 1:  the new package version
post_install() {
  echo
  echo "==> The microcode update is volatile and needs to be uploaded"
  echo "==> on each system boot i.e. It doesn't reflash your cpu"
  echo "==> permanently, reboot and it reverts back to the old"
  echo "==> microcode."
  echo "==> Add 'microcode' to the list of daemons in /etc/rc.conf if"
  echo "==> you want to update the microcode automatically at startup"
  echo
}

op=$1
shift
$op $*
