#!/bin/bash

 . /etc/rc.conf
 . /etc/rc.d/functions

 case "$1" in

   start)
     stat_busy "Starting smartd"
     /usr/sbin/smartd &>/dev/null
     if [ $? -ne 0 ]; then
       stat_fail
     else
       add_daemon smartd
       stat_done
     fi
   ;;

   stop)
     stat_busy "Stopping smartd"
     kill -9 `pidof /usr/sbin/smartd` &>/dev/null
     rm_daemon smartd
     stat_done
   ;;

   restart)
     stat_busy "Restarting smartd ..."
     $0 stop
     $0 start
     stat_done
   ;;

   *)
     echo "usage: $0 {start|stop|restart}"
 esac
