[java-openjdk]
source = "regex"
url = "https://api.adoptium.net/v3/info/release_versions?release_type=ga&page_size=1"
regex = '"openjdk_version"\s*:\s*"([^"]+)"'
from_pattern = '^([0-9.]+)\+([0-9]+)(?:-LTS)?$'
to_pattern = '\1.u\2'
