#! /bin/bash
#
# original from
# @(#) lowercase.ksh 1.0 92/10/08
# 92/10/08 john h. dubois iii (john@armory.com)
#
# conversion to bash v2 syntax done by Chet Ramey

lowercase()
{
	for file; do
		[ -f "$file" ] || continue
		filename=${file##*/}
		case "$file" in
		*/*)    dirname=${file%/*} ;;
		*) dirname=.;;
		esac
		nf=$(echo $filename | tr A-Z a-z)
		newname="${dirname}/${nf}"
		if [ "$nf" != "$filename" ]; then
			mv "$file" "$newname"
			echo "lowercase: $file -> $newname"
		else
			echo "lowercase: $file not changed."
		fi
	done
}
