post_install() {
cat << EOF
==> In order to use Muse,  add the following lines to your ~/.emacs file
==> depending on the styles you wish to use (see manual for more details):

(require 'muse-mode)     ; load authoring mode
     
(require 'muse-html)     ; load publishing styles I use
(require 'muse-latex)
(require 'muse-context)
    
(require 'muse-project)  ; publish files in projects
EOF
}

post_upgrade() {
  post_install $1
}

op=$1
shift
$op $*
