# arg 1:  the new package version
post_install() {
	# we need to ldconfig first, in case xfree86's libs aren't
	# in ld.so.cache yet
	sbin/ldconfig -r .
	usr/bin/pango-querymodules >etc/pango/pango.modules
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
	if [ -f usr/etc/pango/pango.modules ]; then
		rm usr/etc/pango/pango.modules
	fi
	post_install $1
}

# arg 1:  the old package version
pre_remove() {
	rm etc/pango/pango.modules
}

op=$1
shift

$op $*
