#!/bin/bash
# This file belongs in /etc/rc.d
#
###############################################################################

#inserting certain functions (like stat_busy)
. /etc/rc.conf
. /etc/rc.d/functions

PARTIMAGE=/usr/sbin/

# Check the file is there and is executable.
[ -x $PARTIMAGE/partimaged ] || exit 0

PID=`pidof -o %PPID /usr/sbin/partimaged`

# See how we were called.
case "$1" in
  start)
	stat_busy "Starting Partimage Daemon "
	if [ -z "$PID" ]; then 
	   /usr/sbin/partimaged -D &>/dev/null
	   RETVAL=$? #storing the status of the last command to RETVAL
	   if [ $? -gt 0 ]; then #if the status was other than 0, the command failed
	      stat_fail
	      exit 1
           else			
	      add_daemon partimaged
	      stat_done
	   fi
	else
	   stat_fail
	   echo ":: Daemon already started as pid $PID"
	   exit 1
	fi			    
	;;
  stop)
	stat_busy "Stopping Partimage Daemon "
	if [ "$PID" != "" ]; then #if PID exists
	   kill -KILL $PID &>/dev/null
	   stat_done
	   if [ $? -gt 0 ]; then
	      stat_fail
	      exit 1
	   else		  
	      RETVAL=$?
	      rm_daemon partimaged
      	   fi
  	 else   
	   stat_fail
	   echo ":: Daemon already stopped"
	   exit 1
   	fi
	;;
  restart|reload)
	$0 stop
	$0 start
	RETVAL=$?
	;;
  *)
	echo "Usage: partimaged {start|stop|restart|reload}"
	exit 1
esac
exit $RETVAL
