post_install() {
  cd /usr/share/mc/syntax
  sed -i 's#file \.\\\* unknown##      
s#include unknown.syntax##' Syntax
  cat >>Syntax <<EOF
file PKGBUILD Arch\\sPKGBUILD
include PKGBUILD.syntax

file \\.install$ Arch\\sinstall
include sh.syntax

file .\\* unknown
include unknown.syntax
EOF
}

pre_remove() {
  cd /usr/share/mc/syntax
  sed -i 's#file PKGBUILD Arch\\sPKGBUILD##
s#include PKGBUILD\.syntax##
s#file \\\.install$ Arch\\sinstall##
s#include sh\.syntax##' Syntax
}
