#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

test -f /usr/sbin/laptop_mode || exit 0

case "$1" in
  start)
    stat_busy "Starting laptop-mode"
    touch /var/run/laptop-mode-tools/enabled
    /usr/sbin/laptop_mode auto >/dev/null 2>&1
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon laptop-mode
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping laptop-mode"
    rm -f /var/run/laptop-mode-tools/enabled
    /usr/sbin/laptop_mode stop >/dev/null 2>&1
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon laptop-mode
      stat_done
    fi
    ;;
  restart)
    stat_busy "Restarting laptop-mode"
    rm -f /var/run/laptop-mode-tools/enabled
    /usr/sbin/laptop_mode stop >/dev/null 2>&1

    if [ $? -gt 0 ]; then
      stat_fail
      rm_daemon laptop-mode
    else
      rm -f /var/run/laptop-mode-tools/*
      touch /var/run/laptop-mode-tools/enabled
      /usr/sbin/laptop_mode auto force >/dev/null 2>&1
      if [ $? -gt 0 ]; then
        stat_fail
        rm_daemon laptop-mode
      else
        stat_done
      fi
    fi
    ;;
  status)
    /usr/sbin/laptop_mode status
    ;;
  *)
      echo "Usage: $0 {stop|start|restart|status}"
    ;;
esac
exit 0
