diff -Naur sbackup-0.10.5-orig/Makefile sbackup-0.10.4/Makefile
--- sbackup-0.10.5-orig/Makefile	2007-06-04 02:20:44.000000000 -0400
+++ sbackup-0.10.5/Makefile	2007-06-04 02:23:39.000000000 -0400
@@ -1,21 +1,18 @@
 PO = pt_BR lv nl es sv fr
 
-ifndef DESTDIR
-	DESTDIR = /usr/local
-endif 
-
 PREFIX = /usr/local
-BIN = $(DESTDIR)/sbin/
-SUPPORT = $(DESTDIR)/share/sbackup/
-DOC = $(DESTDIR)/share/doc/sbackup/
-PIXDIR = $(DESTDIR)/share/pixmaps/
+BIN = $(DESTDIR)$(PREFIX)/sbin/
+SUPPORT = $(DESTDIR)$(PREFIX)/share/sbackup/
+DOC = $(DESTDIR)$(PREFIX)/share/doc/sbackup/
+PIXDIR = $(DESTDIR)$(PREFIX)/share/pixmaps/
+DESKTOPDIR = $(DESTDIR)$(PREFIX)/share/applications/
 
 all:
 
 default:
 
 install: po-data install-po 
-	install -d $(BIN) $(SUPPORT) $(DOC) $(PIXDIR) $(DESTDIR)/share/applications $(DESTDIR)/etc
+	install -d $(BIN) $(SUPPORT) $(DOC) $(PIXDIR) $(DESKTOPDIR) $(DESTDIR)/etc
 	install ./sbackupd.py $(SUPPORT)
 	ln -s ../share/sbackup/sbackupd.py $(BIN)/sbackupd
 	install ./simple-backup-config.py $(SUPPORT)
@@ -30,16 +27,14 @@
 	install -m644 -D simple-backup-config.glade $(SUPPORT)
 	install -m644 -D sbackup-conf.png $(PIXDIR)
 	install -m644 -D sbackup-restore.png $(PIXDIR)
-	install -m644 -D sbackup.desktop $(DESTDIR)/share/applications/
-	install -m644 -D srestore.desktop $(DESTDIR)/share/applications/
+	install -m644 -D sbackup.desktop $(DESKTOPDIR)
+	install -m644 -D srestore.desktop $(DESKTOPDIR)
 	install -m644 -D simple-restore.glade $(SUPPORT)
 	install ./sbackup $(SUPPORT)
 #	install -m644 -D simple-backup-tocd.glade $(SUPPORT)
-ifeq ($(DESTDIR),/usr/local/)
-	install -b -m600 sbackup.conf.example /etc/sbackup.conf
-	@echo "[places]" >> /etc/sbackup.conf
-	@echo "prefix=$(PREFIX)" >> /etc/sbackup.conf
-endif
+	install -b -m600 sbackup.conf.example $(DESTDIR)/etc/sbackup.conf
+	@echo "[places]" >> $(DESTDIR)/etc/sbackup.conf
+	@echo "prefix=$(PREFIX)" >> $(DESTDIR)/etc/sbackup.conf
 
 uninstall:
 	rm -f $(BIN)/sbackupd
@@ -49,8 +44,8 @@
 	rm -f $(BIN)/upgrade_backups.py
 	rm -rf $(SUPPORT)
 	rm -rf $(DOC)
-	rm -f $(DESTDIR)/share/applications/sbackup.desktop
-	rm -f $(DESTDIR)/share/applications/srestore.desktop
+	rm -f $(DESKTOPDIR)/sbackup.desktop
+	rm -f $(DESKTOPDIR)/srestore.desktop
 	rm -f $(DESTDIR)/etc/sbackup.conf
 
 clean:
@@ -61,8 +56,8 @@
 	-rm -f *~ *.bak
 
 install-po:
-	for lang in $(PO); do install -d $(DESTDIR)/share/locale/$$lang/LC_MESSAGES/ ; done
-	for lang in $(PO); do install -m 644 po/$$lang/LC_MESSAGES/* $(DESTDIR)/share/locale/$$lang/LC_MESSAGES/ ; done
+	for lang in $(PO); do install -d $(DESTDIR)$(PREFIX)/share/locale/$$lang/LC_MESSAGES/ ; done
+	for lang in $(PO); do install -m 644 po/$$lang/LC_MESSAGES/* $(DESTDIR)$(PREFIX)/share/locale/$$lang/LC_MESSAGES/ ; done
 
 po-dir:
 	for lang in $(PO); do mkdir -p po/$$lang/LC_MESSAGES/ ; done
