#!/bin/bash

JAVA=$(which java)

cd /usr/share/java/limewire
export J2SE_PREEMPTCLOSE=1

$JAVA -Dorg.apache.commons.logging.Log=org.apache.commons.logging.impl.NoOpLog -Djava.library.path=. -jar LimeWire.jar
