post_install() {
  getent group polkitd >/dev/null || groupadd -g 102 polkitd
  getent passwd polkitd >/dev/null || useradd -c 'Policy Kit Daemon' -u 102 -g polkitd -G proc -d '/' -s /bin/nologin polkitd
  passwd -l polkitd &>/dev/null
  chown root:102 "$pkgdir"/{etc,usr/share}/polkit-1/rules.d
  chmod 750      "$pkgdir"/{etc,usr/share}/polkit-1/rules.d
}

post_upgrade() {
  post_install
  if (( $(vercmp $2 0.113-2) < 0 )); then
    usermod -aG proc -s /usr/bin/nologin polkitd
  fi
}
