#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

PID=`pidof -o %PPID /usr/bin/mythbackend`
case "$1" in
  start)
    stat_busy "Starting MythTV Backend"
    [ -z "$PID" ] && /usr/bin/mythbackend -d -l /var/log/mythbackend.log -v important 
    if [ $? -gt 0 ]; then
      stat_fail
    else
      echo $PID > /var/run/mythbackend.pid
      add_daemon mythbackend
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping MythTV Backend"
    [ ! -z "$PID" ]  && kill $PID &>/dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon mythbackend
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1s 
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
esac
exit 0
