KERNEL_NAME=-omap
KERNEL_VERSION=2.6.38

post_install() {
# ARM doesn't use mkinitcpio or anything like that
# so we skip it here
echo -e "\033[1mNotice\033[0m"
echo "To complete the installation you will have to copy"
echo "/boot/uImage to the proper location, e.g. /dev/mmcblk0p1"
echo ""
echo "This package is for OMAP3/4 devices, including BeagleBoard and PandaBoard"
echo ""
/sbin/depmod 2.6.38
}

post_upgrade() {
	post_install
}

op=$1
shift
$op $*
