post_install() {
  getent group kodi > /dev/null || groupadd -r kodi
  getent passwd kodi > /dev/null || useradd -r -m -d /var/lib/kodi -g kodi -s /usr/bin/nologin kodi
  usermod -a -G kodi,audio,video,power,network,optical,storage,disk,tty,input kodi
  mkdir -p var/lib/kodi
  chown -R kodi:kodi var/lib/kodi
}

post_upgrade() {
  post_install $1
}

post_remove() {
  getent passwd kodi > /dev/null && userdel kodi
}
