.TH "__cxxabiv1::__forced_unwind" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__cxxabiv1::__forced_unwind \- Thrown as part of forced unwinding.
.PP
A magic placeholder class that can be caught by reference to recognize forced unwinding.  

.PP
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Thrown as part of forced unwinding.
.PP
A magic placeholder class that can be caught by reference to recognize forced unwinding. 
.PP
Definition at line 41 of file cxxabi-forced.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
