.TH "__gnu_parallel::PMWMSSortingData" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::PMWMSSortingData \- Data accessed by all threads.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef traits_type::difference_type \fBdifference_type\fP"
.br
.ti -1c
.RI "typedef \fBstd::iterator_traits\fP< RandomAccessIterator > \fBtraits_type\fP"
.br
.ti -1c
.RI "typedef traits_type::value_type \fBvalue_type\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBthread_index_t\fP \fBnum_threads\fP"
.br
.ti -1c
.RI "difference_type * \fBoffsets\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< \fBPiece\fP< difference_type > > * \fBpieces\fP"
.br
.ti -1c
.RI "value_type * \fBsamples\fP"
.br
.ti -1c
.RI "RandomAccessIterator \fBsource\fP"
.br
.ti -1c
.RI "difference_type * \fBstarts\fP"
.br
.ti -1c
.RI "value_type ** \fBtemporary\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename RandomAccessIterator> struct __gnu_parallel::PMWMSSortingData< RandomAccessIterator >"
Data accessed by all threads. 

PMWMS = parallel multiway mergesort 
.PP
Definition at line 62 of file multiway_mergesort.h.
.SH "Member Data Documentation"
.PP 
.SS "template<typename RandomAccessIterator> \fBthread_index_t\fP \fB__gnu_parallel::PMWMSSortingData\fP< RandomAccessIterator >::\fBnum_threads\fP"
.PP
Number of threads involved. 
.PP
Definition at line 69 of file multiway_mergesort.h.
.PP
Referenced by __gnu_parallel::parallel_sort_mwms(), and __gnu_parallel::parallel_sort_mwms_pu().
.SS "template<typename RandomAccessIterator> difference_type* \fB__gnu_parallel::PMWMSSortingData\fP< RandomAccessIterator >::\fBoffsets\fP"
.PP
Offsets to add to the found positions. 
.PP
Definition at line 84 of file multiway_mergesort.h.
.PP
Referenced by __gnu_parallel::parallel_sort_mwms().
.SS "template<typename RandomAccessIterator> \fBstd::vector\fP<\fBPiece\fP<difference_type> >* \fB__gnu_parallel::PMWMSSortingData\fP< RandomAccessIterator >::\fBpieces\fP"
.PP
Pieces of data to merge \fC\fP[thread][sequence]. 
.PP
Definition at line 87 of file multiway_mergesort.h.
.PP
Referenced by __gnu_parallel::parallel_sort_mwms(), and __gnu_parallel::parallel_sort_mwms_pu().
.SS "template<typename RandomAccessIterator> value_type* \fB__gnu_parallel::PMWMSSortingData\fP< RandomAccessIterator >::\fBsamples\fP"
.PP
Samples. 
.PP
Definition at line 81 of file multiway_mergesort.h.
.PP
Referenced by __gnu_parallel::determine_samples(), and __gnu_parallel::parallel_sort_mwms().
.SS "template<typename RandomAccessIterator> RandomAccessIterator \fB__gnu_parallel::PMWMSSortingData\fP< RandomAccessIterator >::\fBsource\fP"
.PP
Input begin. 
.PP
Definition at line 72 of file multiway_mergesort.h.
.PP
Referenced by __gnu_parallel::determine_samples(), __gnu_parallel::parallel_sort_mwms(), and __gnu_parallel::parallel_sort_mwms_pu().
.SS "template<typename RandomAccessIterator> difference_type* \fB__gnu_parallel::PMWMSSortingData\fP< RandomAccessIterator >::\fBstarts\fP"
.PP
Start indices, per thread. 
.PP
Definition at line 75 of file multiway_mergesort.h.
.PP
Referenced by __gnu_parallel::determine_samples(), __gnu_parallel::parallel_sort_mwms(), and __gnu_parallel::parallel_sort_mwms_pu().
.SS "template<typename RandomAccessIterator> value_type** \fB__gnu_parallel::PMWMSSortingData\fP< RandomAccessIterator >::\fBtemporary\fP"
.PP
Storage in which to sort. 
.PP
Definition at line 78 of file multiway_mergesort.h.
.PP
Referenced by __gnu_parallel::parallel_sort_mwms(), and __gnu_parallel::parallel_sort_mwms_pu().

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
