.TH "__gnu_parallel::count_selector" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::count_selector \- std::count() selector.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fBgeneric_for_each_selector< It >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename Val > Diff \fBoperator()\fP (Val &v, It i)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "It \fBfinish_iterator\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename It, typename Diff> struct __gnu_parallel::count_selector< It, Diff >"
std::count() selector. 
.PP
Definition at line 182 of file for_each_selectors.h.
.SH "Member Function Documentation"
.PP 
.SS "template<typename It, typename Diff> template<typename Val > Diff \fB__gnu_parallel::count_selector\fP< It, Diff >::operator() (Val & v, It i)\fC [inline]\fP"
.PP
Functor execution. 
.PP
\fBParameters:\fP
.RS 4
\fIv\fP Current value. 
.br
\fIi\fP Iterator referencing object. 
.RE
.PP
\fBReturns:\fP
.RS 4
1 if count, 0 if does not count. 
.RE
.PP

.PP
Definition at line 190 of file for_each_selectors.h.
.SH "Member Data Documentation"
.PP 
.SS "It  \fB__gnu_parallel::generic_for_each_selector\fP< It  >::\fBfinish_iterator\fP\fC [inherited]\fP"
.PP
Iterator on last element processed; needed for some algorithms (e. g. std::transform()). 
.PP
Definition at line 48 of file for_each_selectors.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
