.TH "__gnu_cxx::character" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_cxx::character \- A POD class that serves as a \fBcharacter\fP abstraction class.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBcharacter\fP< V, I, S > \fBchar_type\fP"
.br
.ti -1c
.RI "typedef I \fBint_type\fP"
.br
.ti -1c
.RI "typedef S \fBstate_type\fP"
.br
.ti -1c
.RI "typedef V \fBvalue_type\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename V2 > static \fBchar_type\fP \fBfrom\fP (const V2 &v)"
.br
.ti -1c
.RI "template<typename V2 > static V2 \fBto\fP (const \fBchar_type\fP &c)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "value_type \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename V, typename I, typename S = std::mbstate_t> struct __gnu_cxx::character< V, I, S >"
A POD class that serves as a \fBcharacter\fP abstraction class. 
.PP
Definition at line 45 of file pod_char_traits.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
