__gnu_debug
NAME
__gnu_debug - GNU debug classes for public use.
SYNOPSIS
Classes
struct __is_same
class _After_nth_from
class _Not_equal_to
class _Safe_iterator
Safe iterator wrapper.
class _Safe_iterator_base
Basic functionality for a 'safe' iterator.
class _Safe_sequence
Base class for constructing a 'safe' sequence type that tracks iterators that reference it.
class _Safe_sequence_base
Base class that supports tracking of iterators that reference a sequence.
Typedefs
typedef basic_string< char > string
typedef basic_string< wchar_t > wstring
Enumerations
enum _Debug_msg_id { __msg_valid_range, __msg_insert_singular, __msg_insert_different, __msg_erase_bad, __msg_erase_different, __msg_subscript_oob, __msg_empty, __msg_unpartitioned, __msg_unpartitioned_pred, __msg_unsorted, __msg_unsorted_pred, __msg_not_heap, __msg_not_heap_pred, __msg_bad_bitset_write, __msg_bad_bitset_read, __msg_bad_bitset_flip, __msg_self_splice, __msg_splice_alloc, __msg_splice_bad, __msg_splice_other, __msg_splice_overlap, __msg_init_singular, __msg_init_copy_singular, __msg_init_const_singular, __msg_copy_singular, __msg_bad_deref, __msg_bad_inc, __msg_bad_dec, __msg_iter_subscript_oob, __msg_advance_oob, __msg_retreat_oob, __msg_iter_compare_bad, __msg_compare_different, __msg_iter_order_bad, __msg_order_different, __msg_distance_bad, __msg_distance_different, __msg_deref_istream, __msg_inc_istream, __msg_output_ostream, __msg_deref_istreambuf, __msg_inc_istreambuf }
Functions
template<typename _Iterator , typename _Sequence > bool __check_dereferenceable (const _Safe_iterator< _Iterator, _Sequence > &__x)
template<typename _Tp > bool __check_dereferenceable (const _Tp *__ptr)
template<typename _Iterator > bool __check_dereferenceable (_Iterator &)
template<typename _ForwardIterator , typename _Tp , typename _Pred > bool __check_partitioned_lower (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__value, _Pred __pred)
template<typename _ForwardIterator , typename _Tp > bool __check_partitioned_lower (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__value)
template<typename _ForwardIterator , typename _Tp , typename _Pred > bool __check_partitioned_upper (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__value, _Pred __pred)
template<typename _ForwardIterator , typename _Tp > bool __check_partitioned_upper (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__value)
template<typename _Iterator , typename _Sequence > bool __check_singular (const _Safe_iterator< _Iterator, _Sequence > &__x)
template<typename _Tp > bool __check_singular (const _Tp *__ptr)
template<typename _Iterator > bool __check_singular (_Iterator &__x)
bool __check_singular_aux (const _Safe_iterator_base *__x)
bool __check_singular_aux (const void *)
template<typename _InputIterator , typename _Predicate > bool __check_sorted (const _InputIterator &__first, const _InputIterator &__last, _Predicate __pred)
template<typename _InputIterator > bool __check_sorted (const _InputIterator &__first, const _InputIterator &__last)
template<typename _ForwardIterator , typename _Predicate > bool __check_sorted_aux (_ForwardIterator __first, _ForwardIterator __last, _Predicate __pred, std::forward_iterator_tag)
template<typename _InputIterator , typename _Predicate > bool __check_sorted_aux (const _InputIterator &, const _InputIterator &, _Predicate, std::input_iterator_tag)
template<typename _ForwardIterator > bool __check_sorted_aux (_ForwardIterator __first, _ForwardIterator __last, std::forward_iterator_tag)
template<typename _InputIterator > bool __check_sorted_aux (const _InputIterator &, const _InputIterator &, std::input_iterator_tag)
template<typename _InputIterator1 , typename _InputIterator2 , typename _Predicate > bool __check_sorted_set (const _InputIterator1 &__first, const _InputIterator1 &__last, const _InputIterator2 &, _Predicate __pred)
template<typename _InputIterator1 , typename _InputIterator2 > bool __check_sorted_set (const _InputIterator1 &__first, const _InputIterator1 &__last, const _InputIterator2 &)
template<typename _InputIterator , typename _Predicate > bool __check_sorted_set_aux (const _InputIterator &, const _InputIterator &, _Predicate, std::__false_type)
template<typename _InputIterator , typename _Predicate > bool __check_sorted_set_aux (const _InputIterator &__first, const _InputIterator &__last, _Predicate __pred, std::__true_type)
template<typename _InputIterator > bool __check_sorted_set_aux (const _InputIterator &, const _InputIterator &, std::__false_type)
template<typename _InputIterator > bool __check_sorted_set_aux (const _InputIterator &__first, const _InputIterator &__last, std::__true_type)
template<typename _CharT > const _CharT * __check_string (const _CharT *__s)
template<typename _CharT , typename _Integer > const _CharT * __check_string (const _CharT *__s, const _Integer &__n __attribute__((__unused__)))
template<typename _InputIterator > _InputIterator __check_valid_range (const _InputIterator &__first, const _InputIterator &__last __attribute__((__unused__)))
template<typename _Iterator , typename _Sequence > bool __valid_range (const _Safe_iterator< _Iterator, _Sequence > &__first, const _Safe_iterator< _Iterator, _Sequence > &__last)
template<typename _InputIterator > bool __valid_range (const _InputIterator &__first, const _InputIterator &__last)
template<typename _InputIterator > bool __valid_range_aux (const _InputIterator &__first, const _InputIterator &__last, std::__false_type)
template<typename _Integral > bool __valid_range_aux (const _Integral &, const _Integral &, std::__true_type)
template<typename _InputIterator > bool __valid_range_aux2 (const _InputIterator &, const _InputIterator &, std::input_iterator_tag)
template<typename _RandomAccessIterator > bool __valid_range_aux2 (const _RandomAccessIterator &__first, const _RandomAccessIterator &__last, std::random_access_iterator_tag)
template<typename _CharT , typename _Traits , typename _Allocator > std::basic_istream< _CharT, _Traits > & getline (std::basic_istream< _CharT, _Traits > &__is, basic_string< _CharT, _Traits, _Allocator > &__str)
template<typename _CharT , typename _Traits , typename _Allocator > std::basic_istream< _CharT, _Traits > & getline (std::basic_istream< _CharT, _Traits > &__is, basic_string< _CharT, _Traits, _Allocator > &__str, _CharT __delim)
template<typename _Iterator , typename _Sequence > bool operator!= (const _Safe_iterator< _Iterator, _Sequence > &__lhs, const _Safe_iterator< _Iterator, _Sequence > &__rhs)
template<typename _IteratorL , typename _IteratorR , typename _Sequence > bool operator!= (const _Safe_iterator< _IteratorL, _Sequence > &__lhs, const _Safe_iterator< _IteratorR, _Sequence > &__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > bool operator!= (const basic_string< _CharT, _Traits, _Allocator > &__lhs, const _CharT *__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > bool operator!= (const _CharT *__lhs, const basic_string< _CharT, _Traits, _Allocator > &__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > bool operator!= (const basic_string< _CharT, _Traits, _Allocator > &__lhs, const basic_string< _CharT, _Traits, _Allocator > &__rhs)
template<typename _Iterator , typename _Sequence > _Safe_iterator< _Iterator, _Sequence > operator+ (typename _Safe_iterator< _Iterator, _Sequence >::difference_type __n, const _Safe_iterator< _Iterator, _Sequence > &__i)
template<typename _CharT , typename _Traits , typename _Allocator > basic_string< _CharT, _Traits, _Allocator > operator+ (const basic_string< _CharT, _Traits, _Allocator > &__lhs, _CharT __rhs)
template<typename _CharT , typename _Traits , typename _Allocator > basic_string< _CharT, _Traits, _Allocator > operator+ (const basic_string< _CharT, _Traits, _Allocator > &__lhs, const _CharT *__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > basic_string< _CharT, _Traits, _Allocator > operator+ (_CharT __lhs, const basic_string< _CharT, _Traits, _Allocator > &__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > basic_string< _CharT, _Traits, _Allocator > operator+ (const _CharT *__lhs, const basic_string< _CharT, _Traits, _Allocator > &__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > basic_string< _CharT, _Traits, _Allocator > operator+ (const basic_string< _CharT, _Traits, _Allocator > &__lhs, const basic_string< _CharT, _Traits, _Allocator > &__rhs)
template<typename _Iterator , typename _Sequence > _Safe_iterator< _Iterator, _Sequence >::difference_type operator- (const _Safe_iterator< _Iterator, _Sequence > &__lhs, const _Safe_iterator< _Iterator, _Sequence > &__rhs)
template<typename _IteratorL , typename _IteratorR , typename _Sequence > _Safe_iterator< _IteratorL, _Sequence >::difference_type operator- (const _Safe_iterator< _IteratorL, _Sequence > &__lhs, const _Safe_iterator< _IteratorR, _Sequence > &__rhs)
template<typename _Iterator , typename _Sequence > bool operator< (const _Safe_iterator< _Iterator, _Sequence > &__lhs, const _Safe_iterator< _Iterator, _Sequence > &__rhs)
template<typename _IteratorL , typename _IteratorR , typename _Sequence > bool operator< (const _Safe_iterator< _IteratorL, _Sequence > &__lhs, const _Safe_iterator< _IteratorR, _Sequence > &__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > bool operator< (const basic_string< _CharT, _Traits, _Allocator > &__lhs, const _CharT *__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > bool operator< (const _CharT *__lhs, const basic_string< _CharT, _Traits, _Allocator > &__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > bool operator< (const basic_string< _CharT, _Traits, _Allocator > &__lhs, const basic_string< _CharT, _Traits, _Allocator > &__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const basic_string< _CharT, _Traits, _Allocator > &__str)
template<typename _Iterator , typename _Sequence > bool operator<= (const _Safe_iterator< _Iterator, _Sequence > &__lhs, const _Safe_iterator< _Iterator, _Sequence > &__rhs)
template<typename _IteratorL , typename _IteratorR , typename _Sequence > bool operator<= (const _Safe_iterator< _IteratorL, _Sequence > &__lhs, const _Safe_iterator< _IteratorR, _Sequence > &__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > bool operator<= (const basic_string< _CharT, _Traits, _Allocator > &__lhs, const _CharT *__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > bool operator<= (const _CharT *__lhs, const basic_string< _CharT, _Traits, _Allocator > &__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > bool operator<= (const basic_string< _CharT, _Traits, _Allocator > &__lhs, const basic_string< _CharT, _Traits, _Allocator > &__rhs)
template<typename _Iterator , typename _Sequence > bool operator== (const _Safe_iterator< _Iterator, _Sequence > &__lhs, const _Safe_iterator< _Iterator, _Sequence > &__rhs)
template<typename _IteratorL , typename _IteratorR , typename _Sequence > bool operator== (const _Safe_iterator< _IteratorL, _Sequence > &__lhs, const _Safe_iterator< _IteratorR, _Sequence > &__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > bool operator== (const basic_string< _CharT, _Traits, _Allocator > &__lhs, const _CharT *__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > bool operator== (const _CharT *__lhs, const basic_string< _CharT, _Traits, _Allocator > &__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > bool operator== (const basic_string< _CharT, _Traits, _Allocator > &__lhs, const basic_string< _CharT, _Traits, _Allocator > &__rhs)
template<typename _Iterator , typename _Sequence > bool operator> (const _Safe_iterator< _Iterator, _Sequence > &__lhs, const _Safe_iterator< _Iterator, _Sequence > &__rhs)
template<typename _IteratorL , typename _IteratorR , typename _Sequence > bool operator> (const _Safe_iterator< _IteratorL, _Sequence > &__lhs, const _Safe_iterator< _IteratorR, _Sequence > &__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > bool operator> (const basic_string< _CharT, _Traits, _Allocator > &__lhs, const _CharT *__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > bool operator> (const _CharT *__lhs, const basic_string< _CharT, _Traits, _Allocator > &__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > bool operator> (const basic_string< _CharT, _Traits, _Allocator > &__lhs, const basic_string< _CharT, _Traits, _Allocator > &__rhs)
template<typename _Iterator , typename _Sequence > bool operator>= (const _Safe_iterator< _Iterator, _Sequence > &__lhs, const _Safe_iterator< _Iterator, _Sequence > &__rhs)
template<typename _IteratorL , typename _IteratorR , typename _Sequence > bool operator>= (const _Safe_iterator< _IteratorL, _Sequence > &__lhs, const _Safe_iterator< _IteratorR, _Sequence > &__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > bool operator>= (const basic_string< _CharT, _Traits, _Allocator > &__lhs, const _CharT *__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > bool operator>= (const _CharT *__lhs, const basic_string< _CharT, _Traits, _Allocator > &__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > bool operator>= (const basic_string< _CharT, _Traits, _Allocator > &__lhs, const basic_string< _CharT, _Traits, _Allocator > &__rhs)
template<typename _CharT , typename _Traits , typename _Allocator > std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, basic_string< _CharT, _Traits, _Allocator > &__str)
template<typename _CharT , typename _Traits , typename _Allocator > void swap (basic_string< _CharT, _Traits, _Allocator > &__lhs, basic_string< _CharT, _Traits, _Allocator > &__rhs)
Detailed Description
GNU debug classes for public use.
Function Documentation
template<typename _Iterator , typename _Sequence > bool __gnu_debug::__check_dereferenceable (const _Safe_iterator< _Iterator, _Sequence > & __x) [inline]
Safe iterators know if they are singular.
Definition at line 82 of file functions.h.
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_dereferenceable().
template<typename _Tp > bool __gnu_debug::__check_dereferenceable (const _Tp * __ptr) [inline]
Non-NULL pointers are dereferenceable.
Definition at line 76 of file functions.h.
template<typename _Iterator > bool __gnu_debug::__check_dereferenceable (_Iterator &) [inline]
Assume that some arbitrary iterator is dereferenceable, because we can't prove that it isn't.
Definition at line 70 of file functions.h.
template<typename _Iterator , typename _Sequence > bool __gnu_debug::__check_singular (const _Safe_iterator< _Iterator, _Sequence > & __x) [inline]
Safe iterators know if they are singular.
Definition at line 63 of file functions.h.
References __gnu_debug::_Safe_iterator_base::_M_singular().
template<typename _Tp > bool __gnu_debug::__check_singular (const _Tp * __ptr) [inline]
Non-NULL pointers are nonsingular.
Definition at line 57 of file functions.h.
bool __gnu_debug::__check_singular_aux (const _Safe_iterator_base * __x) [inline]
Iterators that derive from _Safe_iterator_base but that aren't _Safe_iterators can be determined singular or non-singular via _Safe_iterator_base.
Definition at line 48 of file safe_iterator.h.
References __gnu_debug::_Safe_iterator_base::_M_singular().
template<typename _CharT > const _CharT* __gnu_debug::__check_string (const _CharT * __s) [inline]
Checks that __s is non-NULL and then returns __s.
Definition at line 176 of file functions.h.
template<typename _CharT , typename _Integer > const _CharT* __gnu_debug::__check_string (const _CharT * __s, const _Integer &__n __attribute__(__unused__)) [inline]
Checks that __s is non-NULL or __n == 0, and then returns __s.
Definition at line 164 of file functions.h.
template<typename _Iterator , typename _Sequence > bool __gnu_debug::__valid_range (const _Safe_iterator< _Iterator, _Sequence > & __first, const _Safe_iterator< _Iterator, _Sequence > & __last) [inline]
Safe iterators know how to check if they form a valid range.
Definition at line 143 of file functions.h.
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_valid_range().
template<typename _InputIterator > bool __gnu_debug::__valid_range (const _InputIterator & __first, const _InputIterator & __last) [inline]
Don't know what these iterators are, or if they are even iterators (we may get an integral type for InputIterator), so see if they are integral and pass them on to the next phase otherwise.
Definition at line 134 of file functions.h.
References __valid_range_aux().
template<typename _InputIterator > bool __gnu_debug::__valid_range_aux (const _InputIterator & __first, const _InputIterator & __last, std::__false_type) [inline]
We have iterators, so figure out what kind of iterators that are to see if we can check the range ahead of time.
Definition at line 119 of file functions.h.
References __valid_range_aux2().
template<typename _Integral > bool __gnu_debug::__valid_range_aux (const _Integral &, const _Integral &, std::__true_type) [inline]
We say that integral types for a valid range, and defer to other routines to realize what to do with integral types instead of iterators.
Definition at line 111 of file functions.h.
Referenced by __valid_range().
template<typename _InputIterator > bool __gnu_debug::__valid_range_aux2 (const _InputIterator &, const _InputIterator &, std::input_iterator_tag) [inline]
Can't test for a valid range with input iterators, because iteration may be destructive. So we just assume that the range is valid.
Definition at line 101 of file functions.h.
template<typename _RandomAccessIterator > bool __gnu_debug::__valid_range_aux2 (const _RandomAccessIterator & __first, const _RandomAccessIterator & __last, std::random_access_iterator_tag) [inline]
If the distance between two random access iterators is nonnegative, assume the range is valid.
Definition at line 90 of file functions.h.
Referenced by __valid_range_aux().
Author
Generated automatically by Doxygen for libstdc++ from the source code.