.TH "__gnu_cxx::new_allocator" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_cxx::new_allocator \- An allocator that uses global new, as per [20.4].
.PP
This is precisely the allocator defined in the C++ Standard.
.IP "\(bu" 2
all allocation calls operator new
.IP "\(bu" 2
all deallocation calls operator delete. 
.PP
 

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef const _Tp * \fBconst_pointer\fP"
.br
.ti -1c
.RI "typedef const _Tp & \fBconst_reference\fP"
.br
.ti -1c
.RI "typedef ptrdiff_t \fBdifference_type\fP"
.br
.ti -1c
.RI "typedef _Tp * \fBpointer\fP"
.br
.ti -1c
.RI "typedef _Tp & \fBreference\fP"
.br
.ti -1c
.RI "typedef size_t \fBsize_type\fP"
.br
.ti -1c
.RI "typedef _Tp \fBvalue_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const_pointer \fBaddress\fP (const_reference __x) const "
.br
.ti -1c
.RI "pointer \fBaddress\fP (reference __x) const "
.br
.ti -1c
.RI "pointer \fBallocate\fP (size_type __n, const void *=0)"
.br
.ti -1c
.RI "template<typename... _Args> void \fBconstruct\fP (pointer __p, _Args &&...__args)"
.br
.ti -1c
.RI "void \fBconstruct\fP (pointer __p, const _Tp &__val)"
.br
.ti -1c
.RI "void \fBdeallocate\fP (pointer __p, size_type)"
.br
.ti -1c
.RI "void \fBdestroy\fP (pointer __p)"
.br
.ti -1c
.RI "size_type \fBmax_size\fP () const   throw ()"
.br
.ti -1c
.RI "template<typename _Tp1 > \fBnew_allocator\fP (const \fBnew_allocator\fP< _Tp1 > &)  throw ()"
.br
.ti -1c
.RI "\fBnew_allocator\fP (const \fBnew_allocator\fP &)  throw ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> class __gnu_cxx::new_allocator< _Tp >"
An allocator that uses global new, as per [20.4].
.PP
This is precisely the allocator defined in the C++ Standard.
.IP "\(bu" 2
all allocation calls operator new
.IP "\(bu" 2
all deallocation calls operator delete. 
.PP

.PP
Definition at line 51 of file new_allocator.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
