.TH "__gnu_cxx::_Invalid_type" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_cxx::_Invalid_type \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
The specialization on this type helps resolve the problem of reference to void, and eliminates the need to specialize \fB_Pointer_adapter\fP for cases of void*, const void*, and so on. 
.PP
Definition at line 195 of file pointer.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
