.TH "__gnu_internal" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_internal \- GNU implemenation details, not for public use or export. Used only when anonymous namespaces cannot be substituted.  

.PP
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
GNU implemenation details, not for public use or export. Used only when anonymous namespaces cannot be substituted. 
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
