.TH "__gnu_parallel::Piece" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::Piece \- Subsequence description.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _DifferenceTp \fBdifference_type\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "difference_type \fBbegin\fP"
.br
.ti -1c
.RI "difference_type \fBend\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _DifferenceTp> struct __gnu_parallel::Piece< _DifferenceTp >"
Subsequence description. 
.PP
Definition at line 47 of file multiway_mergesort.h.
.SH "Member Data Documentation"
.PP 
.SS "template<typename _DifferenceTp > difference_type \fB__gnu_parallel::Piece\fP< _DifferenceTp >::\fBbegin\fP"
.PP
Begin of subsequence. 
.PP
Definition at line 52 of file multiway_mergesort.h.
.SS "template<typename _DifferenceTp > difference_type \fB__gnu_parallel::Piece\fP< _DifferenceTp >::\fBend\fP"
.PP
End of subsequence. 
.PP
Definition at line 55 of file multiway_mergesort.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
