.TH "__gnu_cxx::__detail::_Ffit_finder" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_cxx::__detail::_Ffit_finder \- The class which acts as a predicate for applying the first-fit memory allocation policy for the bitmap allocator.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fBunary_function< std::pair< _Tp, _Tp >, bool >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBstd::pair\fP< _Tp, _Tp > \fBargument_type\fP"
.br
.ti -1c
.RI "typedef bool \fBresult_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "size_t * \fB_M_get\fP () const   throw ()"
.br
.ti -1c
.RI "_Counter_type \fB_M_offset\fP () const   throw ()"
.br
.ti -1c
.RI "bool \fBoperator()\fP (\fB_Block_pair\fP __bp)  throw ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> class __gnu_cxx::__detail::_Ffit_finder< _Tp >"
The class which acts as a predicate for applying the first-fit memory allocation policy for the bitmap allocator. 
.PP
Definition at line 356 of file bitmap_allocator.h.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef \fBstd::pair\fP< _Tp, _Tp >  \fBstd::unary_function\fP< \fBstd::pair\fP< _Tp, _Tp > , bool  >::\fBargument_type\fP\fC [inherited]\fP"
.PP
\fCargument_type\fP is the type of the argument (no surprises here) 
.PP
Definition at line 102 of file stl_function.h.
.SS "typedef bool  \fBstd::unary_function\fP< \fBstd::pair\fP< _Tp, _Tp > , bool  >::\fBresult_type\fP\fC [inherited]\fP"
.PP
\fCresult_type\fP is the return type 
.PP
Definition at line 105 of file stl_function.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
