.TH "__gnu_parallel::void_functor" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::void_functor \- Functor that does \fBnothing\fP.  

.PP
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SS "template<typename _ValueTp> class __gnu_parallel::void_functor< _ValueTp >"
Functor that does \fBnothing\fP. 
.PP
Definition at line 428 of file base.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
