__gnu_debug::_Safe_iterator
NAME
__gnu_debug::_Safe_iterator - Safe iterator wrapper.
SYNOPSIS
Inherits __gnu_debug::_Safe_iterator_base.
Public Types
typedef _Iterator _Base_iterator
typedef _Traits::difference_type difference_type
typedef _Traits::iterator_category iterator_category
typedef _Traits::pointer pointer
typedef _Traits::reference reference
typedef _Traits::value_type value_type
Public Member Functions
void _M_attach (_Safe_sequence_base *__seq, bool __constant)
void _M_attach (const _Sequence *__seq)
void _M_attach_single (_Safe_sequence_base *__seq, bool __constant)
void _M_attach_single (const _Sequence *__seq)
bool _M_attached_to (const _Safe_sequence_base *__seq) const
bool _M_can_advance (const difference_type &__n) const
bool _M_can_compare (const _Safe_iterator_base &__x) const
bool _M_decrementable () const
bool _M_dereferenceable () const
void _M_detach ()
void _M_detach_single ()
const _Sequence * _M_get_sequence () const
bool _M_incrementable () const
void _M_invalidate ()
void _M_invalidate_single ()
bool _M_is_begin () const
bool _M_is_end () const
bool _M_singular () const
template<typename _Other > bool _M_valid_range (const _Safe_iterator< _Other, _Sequence > &__rhs) const
template<typename _MutableIterator > _Safe_iterator (const _Safe_iterator< _MutableIterator, typename __gnu_cxx::__enable_if<(std::__are_same< _MutableIterator, typename _Sequence::iterator::_Base_iterator >::__value), _Sequence >::__type > &__x)
_Safe_iterator (const _Safe_iterator &__x)
_Safe_iterator (const _Iterator &__i, const _Sequence *__seq)
_Safe_iterator ()
_Iterator base () const
operator _Iterator () const
reference operator* () const
_Safe_iterator operator+ (const difference_type &__n) const
_Safe_iterator operator++ (int)
_Safe_iterator & operator++ ()
_Safe_iterator & operator+= (const difference_type &__n)
_Safe_iterator operator- (const difference_type &__n) const
_Safe_iterator operator-- (int)
_Safe_iterator & operator-- ()
_Safe_iterator & operator-= (const difference_type &__n)
pointer operator-> () const
_Safe_iterator & operator= (const _Safe_iterator &__x)
reference operator[] (const difference_type &__n) const
Static Public Member Functions
template<typename _Iterator1 , typename _Iterator2 > static std::pair< difference_type, _Distance_precision > _M_get_distance (const _Iterator1 &__lhs, const _Iterator2 &__rhs, std::forward_iterator_tag)
template<typename _Iterator1 , typename _Iterator2 > static std::pair< difference_type, _Distance_precision > _M_get_distance (const _Iterator1 &__lhs, const _Iterator2 &__rhs, std::random_access_iterator_tag)
template<typename _Iterator1 , typename _Iterator2 > static std::pair< difference_type, _Distance_precision > _M_get_distance (const _Iterator1 &__lhs, const _Iterator2 &__rhs)
Public Attributes
_Safe_iterator_base * _M_next
_Safe_iterator_base * _M_prior
_Safe_sequence_base * _M_sequence
unsigned int _M_version
Protected Member Functions
__gnu_cxx::__mutex & _M_get_mutex ()
Detailed Description
template<typename _Iterator, typename _Sequence> class __gnu_debug::_Safe_iterator< _Iterator, _Sequence >
Safe iterator wrapper.
The class template _Safe_iterator is a wrapper around an iterator that tracks the iterator's movement among sequences and checks that operations performed on the 'safe' iterator are legal. In additional to the basic iterator operations (which are validated, and then passed to the underlying iterator), _Safe_iterator has member functions for iterator invalidation, attaching/detaching the iterator from sequences, and querying the iterator's state.
Definition at line 63 of file safe_iterator.h.
Constructor & Destructor Documentation
template<typename _Iterator, typename _Sequence> __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_Safe_iterator () [inline]
Postcondition:
the iterator is singular and unattached
Definition at line 99 of file safe_iterator.h.
template<typename _Iterator, typename _Sequence> __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_Safe_iterator (const _Iterator & __i, const _Sequence * __seq) [inline]
Safe iterator construction from an unsafe iterator and its sequence.
Precondition:
seq is not NULL
Postcondition:
this is not singular
Definition at line 108 of file safe_iterator.h.
References _GLIBCXX_DEBUG_VERIFY, and __gnu_debug::_Safe_iterator_base::_M_singular().
template<typename _Iterator, typename _Sequence> __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_Safe_iterator (const _Safe_iterator< _Iterator, _Sequence > & __x) [inline]
Copy construction.
Precondition:
x is not singular
Definition at line 120 of file safe_iterator.h.
References _GLIBCXX_DEBUG_VERIFY, and __gnu_debug::_Safe_iterator_base::_M_singular().
template<typename _Iterator, typename _Sequence> template<typename _MutableIterator > __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_Safe_iterator (const _Safe_iterator< _MutableIterator, typename __gnu_cxx::__enable_if<(std::__are_same< _MutableIterator, typename _Sequence::iterator::_Base_iterator >::__value), _Sequence >::__type > & __x) [inline]
Converting constructor from a mutable iterator to a constant iterator.
Precondition:
x is not singular
Definition at line 136 of file safe_iterator.h.
References _GLIBCXX_DEBUG_VERIFY.
Member Function Documentation
void __gnu_debug::_Safe_iterator_base::_M_attach (_Safe_sequence_base * __seq, bool __constant) [inherited]
Attaches this iterator to the given sequence, detaching it from whatever sequence it was attached to originally. If the new sequence is the NULL pointer, the iterator is left unattached.
Referenced by __gnu_debug::_Safe_iterator_base::_Safe_iterator_base().
template<typename _Iterator, typename _Sequence> void __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_attach (const _Sequence * __seq) [inline]
Attach iterator to the given sequence.
Definition at line 317 of file safe_iterator.h.
Referenced by __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator=().
void __gnu_debug::_Safe_iterator_base::_M_attach_single (_Safe_sequence_base * __seq, bool __constant) [inherited]
Likewise, but not thread-safe.
template<typename _Iterator, typename _Sequence> void __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_attach_single (const _Sequence * __seq) [inline]
Likewise, but not thread-safe.
Definition at line 325 of file safe_iterator.h.
bool __gnu_debug::_Safe_iterator_base::_M_attached_to (const _Safe_sequence_base * __seq) const [inline, inherited]
Determines if we are attached to the given sequence.
Definition at line 130 of file safe_base.h.
References __gnu_debug::_Safe_iterator_base::_M_sequence.
bool __gnu_debug::_Safe_iterator_base::_M_can_compare (const _Safe_iterator_base & __x) const [inherited]
Can we compare this iterator to the given iterator __x? Returns true if both iterators are nonsingular and reference the same sequence.
template<typename _Iterator, typename _Sequence> bool __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_dereferenceable () const [inline]
Is the iterator dereferenceable?
Definition at line 341 of file safe_iterator.h.
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_end(), and __gnu_debug::_Safe_iterator_base::_M_singular().
Referenced by __gnu_debug::__check_dereferenceable(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_incrementable(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator*(), and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator->().
void __gnu_debug::_Safe_iterator_base::_M_detach () [inherited]
Detach the iterator for whatever sequence it is attached to, if any.
void __gnu_debug::_Safe_iterator_base::_M_detach_single () [inherited]
Likewise, but not thread-safe.
template<typename _Iterator, typename _Sequence> template<typename _Iterator1 , typename _Iterator2 > static std::pair<difference_type, _Distance_precision> __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_get_distance (const _Iterator1 & __lhs, const _Iterator2 & __rhs) [inline, static]
Determine the distance between two iterators with some known precision.
Definition at line 371 of file safe_iterator.h.
__gnu_cxx::__mutex& __gnu_debug::_Safe_iterator_base::_M_get_mutex () [protected, inherited]
For use in _Safe_iterator.
Referenced by __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_invalidate().
template<typename _Iterator, typename _Sequence> bool __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_incrementable () const [inline]
Is the iterator incrementable?
Definition at line 346 of file safe_iterator.h.
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_dereferenceable().
Referenced by __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator++().
template<typename _Iterator , typename _Sequence > void __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_invalidate () [inline]
Invalidate the iterator, making it singular.
Definition at line 106 of file safe_iterator.tcc.
References __gnu_debug::_Safe_iterator_base::_M_get_mutex(), and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_invalidate_single().
template<typename _Iterator , typename _Sequence > void __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_invalidate_single () [inline]
Likewise, but not thread-safe.
Definition at line 115 of file safe_iterator.tcc.
References __gnu_debug::_Safe_sequence_base::_M_const_iterators, __gnu_debug::_Safe_sequence_base::_M_iterators, __gnu_debug::_Safe_iterator_base::_M_next, __gnu_debug::_Safe_iterator_base::_M_sequence, __gnu_debug::_Safe_iterator_base::_M_singular(), __gnu_debug::_Safe_iterator_base::_M_version, and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::base().
Referenced by __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_invalidate().
template<typename _Iterator, typename _Sequence> bool __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_begin () const [inline]
Is this iterator equal to the sequence's begin() iterator?
Definition at line 396 of file safe_iterator.h.
References __gnu_debug::_Safe_iterator_base::_M_sequence.
template<typename _Iterator, typename _Sequence> bool __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_end () const [inline]
Is this iterator equal to the sequence's end() iterator?
Definition at line 400 of file safe_iterator.h.
References __gnu_debug::_Safe_iterator_base::_M_sequence.
Referenced by __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_dereferenceable().
bool __gnu_debug::_Safe_iterator_base::_M_singular () const [inherited]
Is this iterator singular?
Referenced by __gnu_debug::__check_singular(), __gnu_debug::__check_singular_aux(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_dereferenceable(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_invalidate_single(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_Safe_iterator(), and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator=().
template<typename _Iterator, typename _Sequence> _Iterator __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::base () const [inline]
Return the underlying iterator.
Definition at line 307 of file safe_iterator.h.
Referenced by __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_invalidate_single(), and __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_iter().
template<typename _Iterator, typename _Sequence> __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator _Iterator () const [inline]
Conversion to underlying non-debug iterator to allow better interaction with non-debug containers.
Definition at line 313 of file safe_iterator.h.
template<typename _Iterator, typename _Sequence> reference __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator* () const [inline]
Iterator dereference.
Precondition:
iterator is dereferenceable
Definition at line 170 of file safe_iterator.h.
References _GLIBCXX_DEBUG_VERIFY, and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_dereferenceable().
template<typename _Iterator, typename _Sequence> _Safe_iterator __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator++ (int) [inline]
Iterator postincrement.
Precondition:
iterator is incrementable
Definition at line 214 of file safe_iterator.h.
References _GLIBCXX_DEBUG_VERIFY, and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_incrementable().
template<typename _Iterator, typename _Sequence> _Safe_iterator& __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator++ () [inline]
Iterator preincrement.
Precondition:
iterator is incrementable
Definition at line 200 of file safe_iterator.h.
References _GLIBCXX_DEBUG_VERIFY, and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_incrementable().
template<typename _Iterator, typename _Sequence> _Safe_iterator __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator-- (int) [inline]
Iterator postdecrement.
Precondition:
iterator is decrementable
Definition at line 244 of file safe_iterator.h.
References _GLIBCXX_DEBUG_VERIFY.
template<typename _Iterator, typename _Sequence> _Safe_iterator& __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator-- () [inline]
Iterator predecrement.
Precondition:
iterator is decrementable
Definition at line 230 of file safe_iterator.h.
References _GLIBCXX_DEBUG_VERIFY.
template<typename _Iterator, typename _Sequence> pointer __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator-> () const [inline]
Iterator dereference.
Precondition:
iterator is dereferenceable
Todo
Make this correct w.r.t. iterators that return proxies
Use addressof() instead of & operator
Definition at line 186 of file safe_iterator.h.
References _GLIBCXX_DEBUG_VERIFY, and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_dereferenceable().
template<typename _Iterator, typename _Sequence> _Safe_iterator& __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator= (const _Safe_iterator< _Iterator, _Sequence > & __x) [inline]
Copy assignment.
Precondition:
x is not singular
Definition at line 154 of file safe_iterator.h.
References _GLIBCXX_DEBUG_VERIFY, __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_attach(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_current, __gnu_debug::_Safe_iterator_base::_M_sequence, and __gnu_debug::_Safe_iterator_base::_M_singular().
Member Data Documentation
_Safe_iterator_base* __gnu_debug::_Safe_iterator_base::_M_next [inherited]
Pointer to the next iterator in the sequence's list of iterators. Only valid when _M_sequence != NULL.
Definition at line 73 of file safe_base.h.
Referenced by __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_invalidate_single().
_Safe_iterator_base* __gnu_debug::_Safe_iterator_base::_M_prior [inherited]
Pointer to the previous iterator in the sequence's list of iterators. Only valid when _M_sequence != NULL.
Definition at line 69 of file safe_base.h.
_Safe_sequence_base* __gnu_debug::_Safe_iterator_base::_M_sequence [inherited]
The sequence this iterator references; may be NULL to indicate a singular iterator.
Definition at line 56 of file safe_base.h.
Referenced by __gnu_debug::_Safe_iterator_base::_M_attached_to(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_invalidate_single(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_begin(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_end(), __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_iter(), __gnu_debug::_Safe_iterator_base::_Safe_iterator_base(), and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator=().
unsigned int __gnu_debug::_Safe_iterator_base::_M_version [inherited]
The version number of this iterator. The sentinel value 0 is used to indicate an invalidated iterator (i.e., one that is singular because of an operation on the container). This version number must equal the version number in the sequence referenced by _M_sequence for the iterator to be non-singular.
Definition at line 65 of file safe_base.h.
Referenced by __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_invalidate_single().
Author
Generated automatically by Doxygen for libstdc++ from the source code.