.TH "__gnu_pbds::sequence_tag" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_pbds::sequence_tag \- Basic sequence.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fB__gnu_pbds::container_tag\fP.
.PP
.SH "Detailed Description"
.PP 
Basic sequence. 
.PP
Definition at line 99 of file tag_and_trait.hpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
