.TH "__gnu_parallel::LoserTreeBase::Loser" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::LoserTreeBase::Loser \- Internal representation of a \fBLoserTree\fP element.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T \fBkey\fP"
.br
.ti -1c
.RI "int \fBsource\fP"
.br
.ti -1c
.RI "bool \fBsup\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T, typename Comparator> struct __gnu_parallel::LoserTreeBase< T, Comparator >::Loser"
Internal representation of a \fBLoserTree\fP element. 
.PP
Definition at line 61 of file losertree.h.
.SH "Member Data Documentation"
.PP 
.SS "template<typename T, typename Comparator> T \fB__gnu_parallel::LoserTreeBase\fP< T, Comparator >::\fBLoserTreeBase::Loser::key\fP"
.PP
key of the element in the \fBLoserTree\fP. 
.PP
Definition at line 68 of file losertree.h.
.PP
Referenced by __gnu_parallel::LoserTreeBase< T, Comparator >::insert_start().
.SS "template<typename T, typename Comparator> int \fB__gnu_parallel::LoserTreeBase\fP< T, Comparator >::\fBLoserTreeBase::Loser::source\fP"
.PP
index of the source sequence. 
.PP
Definition at line 66 of file losertree.h.
.PP
Referenced by __gnu_parallel::LoserTreeBase< T, Comparator >::get_min_source(), and __gnu_parallel::LoserTreeBase< T, Comparator >::insert_start().
.SS "template<typename T, typename Comparator> bool \fB__gnu_parallel::LoserTreeBase\fP< T, Comparator >::\fBLoserTreeBase::Loser::sup\fP"
.PP
flag, true iff this is a 'maximum' sentinel. 
.PP
Definition at line 64 of file losertree.h.
.PP
Referenced by __gnu_parallel::LoserTreeBase< T, Comparator >::insert_start().

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
