.TH "__gnu_parallel::generic_find_selector" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::generic_find_selector \- Base class of all \fB__gnu_parallel::find_template\fP selectors.  

.PP
.SH SYNOPSIS
.br
.PP
Inherited by \fB__gnu_parallel::adjacent_find_selector\fP, \fB__gnu_parallel::find_first_of_selector< ForwardIterator >\fP, \fB__gnu_parallel::find_if_selector\fP, and \fB__gnu_parallel::mismatch_selector\fP.
.PP
.SH "Detailed Description"
.PP 
Base class of all \fB__gnu_parallel::find_template\fP selectors. 
.PP
Definition at line 43 of file find_selectors.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
