.TH "__gnu_parallel::binder1st" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::binder1st \- Similar to \fBstd::binder1st\fP, but giving the argument types explicitly.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fBunary_function< second_argument_type, result_type >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef second_argument_type \fBargument_type\fP"
.br
.ti -1c
.RI "typedef \fBresult_type\fP \fBresult_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbinder1st\fP (const _Operation &__x, const first_argument_type &__y)"
.br
.ti -1c
.RI "\fBresult_type\fP \fBoperator()\fP (second_argument_type &__x) const "
.br
.ti -1c
.RI "\fBresult_type\fP \fBoperator()\fP (const second_argument_type &__x)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "_Operation \fBop\fP"
.br
.ti -1c
.RI "first_argument_type \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Operation, typename first_argument_type, typename second_argument_type, typename result_type> class __gnu_parallel::binder1st< _Operation, first_argument_type, second_argument_type, result_type >"
Similar to \fBstd::binder1st\fP, but giving the argument types explicitly. 
.PP
Definition at line 196 of file base.h.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef second_argument_type  \fBstd::unary_function\fP< second_argument_type , \fBresult_type\fP  >::\fBargument_type\fP\fC [inherited]\fP"
.PP
\fCargument_type\fP is the type of the argument (no surprises here) 
.PP
Definition at line 102 of file stl_function.h.
.SS "typedef \fBresult_type\fP  \fBstd::unary_function\fP< second_argument_type , \fBresult_type\fP  >::\fBresult_type\fP\fC [inherited]\fP"
.PP
\fCresult_type\fP is the return type 
.PP
Definition at line 105 of file stl_function.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
