.TH "__gnu_cxx::__pool_base" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_cxx::__pool_base \- Base class for pool object.  

.PP
.SH SYNOPSIS
.br
.PP
Inherited by \fB__gnu_cxx::__pool< false >\fP, and \fB__gnu_cxx::__pool< true >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef unsigned short int \fB_Binmap_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__pool_base\fP (const _Tune &__options)"
.br
.ti -1c
.RI "bool \fB_M_check_threshold\fP (size_t __bytes)"
.br
.ti -1c
.RI "size_t \fB_M_get_align\fP ()"
.br
.ti -1c
.RI "size_t \fB_M_get_binmap\fP (size_t __bytes)"
.br
.ti -1c
.RI "const _Tune & \fB_M_get_options\fP () const "
.br
.ti -1c
.RI "void \fB_M_set_options\fP (_Tune __t)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "_Binmap_type * \fB_M_binmap\fP"
.br
.ti -1c
.RI "bool \fB_M_init\fP"
.br
.ti -1c
.RI "_Tune \fB_M_options\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Base class for pool object. 
.PP
Definition at line 47 of file mt_allocator.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
