.TH "__gnu_pbds::container_traits" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_pbds::container_traits \- \fBcontainer_traits\fP  

.PP
.SH SYNOPSIS
.br
.PP
Inherits container_traits_base<Cntnr::container_category>.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBorder_preserving\fP, \fBerase_can_throw\fP, \fBsplit_join_can_throw\fP, \fBreverse_iteration\fP }"
.br
.ti -1c
.RI "typedef container_traits_base< container_category > \fBbase_type\fP"
.br
.ti -1c
.RI "typedef Cntnr::container_category \fBcontainer_category\fP"
.br
.ti -1c
.RI "typedef Cntnr \fBcontainer_type\fP"
.br
.SH "Detailed Description"
.PP 

.SS "template<typename Cntnr> struct __gnu_pbds::container_traits< Cntnr >"
\fBcontainer_traits\fP 
.PP
Definition at line 345 of file tag_and_trait.hpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
