.TH "__gnu_pbds::splay_tree_tag" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_pbds::splay_tree_tag \- Splay tree.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fB__gnu_pbds::tree_tag\fP.
.PP
.SH "Detailed Description"
.PP 
Splay tree. 
.PP
Definition at line 123 of file tag_and_trait.hpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
