.TH "__gnu_parallel::find_tag" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::find_tag \- Base class for for std::find() variants.  

.PP
.SH SYNOPSIS
.br
.PP
Inherited by \fB__gnu_parallel::constant_size_blocks_tag\fP, \fB__gnu_parallel::equal_split_tag\fP, and \fB__gnu_parallel::growing_blocks_tag\fP.
.PP
.SH "Detailed Description"
.PP 
Base class for for std::find() variants. 
.PP
Definition at line 110 of file tags.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
