.TH "__gnu_cxx::_Unqualified_type" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_cxx::_Unqualified_type \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _Tp \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> struct __gnu_cxx::_Unqualified_type< _Tp >"
This structure accomodates the way in which std::iterator_traits<> is normally specialized for const T*, so that value_type is still T. 
.PP
Definition at line 222 of file pointer.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
