.TH "__gnu_cxx::unary_compose" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_cxx::unary_compose \- An \fBSGI extension \fP.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fBstd::unary_function<_Operation2::argument_type, _Operation1::result_type>\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _Arg \fBargument_type\fP"
.br
.ti -1c
.RI "typedef _Result \fBresult_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "_Operation1::result_type \fBoperator()\fP (const typename _Operation2::argument_type &__x) const "
.br
.ti -1c
.RI "\fBunary_compose\fP (const _Operation1 &__x, const _Operation2 &__y)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "_Operation1 \fB_M_fn1\fP"
.br
.ti -1c
.RI "_Operation2 \fB_M_fn2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class _Operation1, class _Operation2> class __gnu_cxx::unary_compose< _Operation1, _Operation2 >"
An \fBSGI extension \fP. 
.PP
Definition at line 125 of file ext/functional.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename _Arg, typename _Result> typedef _Arg \fBstd::unary_function\fP< _Arg, _Result >::\fBargument_type\fP\fC [inherited]\fP"
.PP
\fCargument_type\fP is the type of the argument (no surprises here) 
.PP
Definition at line 102 of file stl_function.h.
.SS "template<typename _Arg, typename _Result> typedef _Result \fBstd::unary_function\fP< _Arg, _Result >::\fBresult_type\fP\fC [inherited]\fP"
.PP
\fCresult_type\fP is the return type 
.PP
Definition at line 105 of file stl_function.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
