.TH "__gnu_parallel::DRandomShufflingGlobalData" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::DRandomShufflingGlobalData \- Data known to every thread participating in \fB__gnu_parallel::parallel_random_shuffle()\fP.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef traits_type::difference_type \fBdifference_type\fP"
.br
.ti -1c
.RI "typedef \fBstd::iterator_traits\fP< RandomAccessIterator > \fBtraits_type\fP"
.br
.ti -1c
.RI "typedef traits_type::value_type \fBvalue_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDRandomShufflingGlobalData\fP (RandomAccessIterator &_source)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBthread_index_t\fP * \fBbin_proc\fP"
.br
.ti -1c
.RI "difference_type ** \fBdist\fP"
.br
.ti -1c
.RI "int \fBnum_bins\fP"
.br
.ti -1c
.RI "int \fBnum_bits\fP"
.br
.ti -1c
.RI "RandomAccessIterator & \fBsource\fP"
.br
.ti -1c
.RI "difference_type * \fBstarts\fP"
.br
.ti -1c
.RI "value_type ** \fBtemporaries\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename RandomAccessIterator> struct __gnu_parallel::DRandomShufflingGlobalData< RandomAccessIterator >"
Data known to every thread participating in \fB__gnu_parallel::parallel_random_shuffle()\fP. 
.PP
Definition at line 52 of file random_shuffle.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename RandomAccessIterator> \fB__gnu_parallel::DRandomShufflingGlobalData\fP< RandomAccessIterator >::\fBDRandomShufflingGlobalData\fP (RandomAccessIterator & _source)\fC [inline]\fP"
.PP
Constructor. 
.PP
Definition at line 83 of file random_shuffle.h.
.SH "Member Data Documentation"
.PP 
.SS "template<typename RandomAccessIterator> \fBthread_index_t\fP* \fB__gnu_parallel::DRandomShufflingGlobalData\fP< RandomAccessIterator >::\fBbin_proc\fP"
.PP
Number of the thread that will further process the corresponding bin. 
.PP
Definition at line 74 of file random_shuffle.h.
.PP
Referenced by __gnu_parallel::parallel_random_shuffle_drs().
.SS "template<typename RandomAccessIterator> difference_type** \fB__gnu_parallel::DRandomShufflingGlobalData\fP< RandomAccessIterator >::\fBdist\fP"
.PP
Two-dimensional array to hold the thread-bin distribution. 
.PP
Dimensions (num_threads + 1) x (num_bins + 1). 
.PP
Definition at line 67 of file random_shuffle.h.
.PP
Referenced by __gnu_parallel::parallel_random_shuffle_drs(), and __gnu_parallel::parallel_random_shuffle_drs_pu().
.SS "template<typename RandomAccessIterator> int \fB__gnu_parallel::DRandomShufflingGlobalData\fP< RandomAccessIterator >::\fBnum_bins\fP"
.PP
Number of bins to distribute to. 
.PP
Definition at line 77 of file random_shuffle.h.
.PP
Referenced by __gnu_parallel::parallel_random_shuffle_drs(), and __gnu_parallel::parallel_random_shuffle_drs_pu().
.SS "template<typename RandomAccessIterator> int \fB__gnu_parallel::DRandomShufflingGlobalData\fP< RandomAccessIterator >::\fBnum_bits\fP"
.PP
Number of bits needed to address the bins. 
.PP
Definition at line 80 of file random_shuffle.h.
.PP
Referenced by __gnu_parallel::parallel_random_shuffle_drs(), and __gnu_parallel::parallel_random_shuffle_drs_pu().
.SS "template<typename RandomAccessIterator> RandomAccessIterator& \fB__gnu_parallel::DRandomShufflingGlobalData\fP< RandomAccessIterator >::\fBsource\fP"
.PP
Begin iterator of the source. 
.PP
Definition at line 59 of file random_shuffle.h.
.SS "template<typename RandomAccessIterator> difference_type* \fB__gnu_parallel::DRandomShufflingGlobalData\fP< RandomAccessIterator >::\fBstarts\fP"
.PP
Start indexes of the threads' chunks. 
.PP
Definition at line 70 of file random_shuffle.h.
.PP
Referenced by __gnu_parallel::parallel_random_shuffle_drs(), and __gnu_parallel::parallel_random_shuffle_drs_pu().
.SS "template<typename RandomAccessIterator> value_type** \fB__gnu_parallel::DRandomShufflingGlobalData\fP< RandomAccessIterator >::\fBtemporaries\fP"
.PP
Temporary arrays for each thread. 
.PP
Definition at line 62 of file random_shuffle.h.
.PP
Referenced by __gnu_parallel::parallel_random_shuffle_drs().

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
