.TH "__gnu_pbds::associative_container_tag" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_pbds::associative_container_tag \- Basic associative-container.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fB__gnu_pbds::container_tag\fP.
.PP
Inherited by \fB__gnu_pbds::basic_hash_tag\fP, \fB__gnu_pbds::basic_tree_tag\fP, and \fB__gnu_pbds::list_update_tag\fP.
.PP
.SH "Detailed Description"
.PP 
Basic associative-container. 
.PP
Definition at line 102 of file tag_and_trait.hpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
