.TH "__gnu_debug::_Not_equal_to" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_debug::_Not_equal_to \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB_Not_equal_to\fP (const _Type &__v)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (const _Type &__x) const "
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Type> class __gnu_debug::_Not_equal_to< _Type >"
A simple function object that returns true if the passed-in value is not equal to the stored value. It saves typing over using both bind1st and not_equal. 
.PP
Definition at line 48 of file safe_sequence.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
