.TH "__gnu_parallel::sampling_sorter" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::sampling_sorter \- Stable sorting functor.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBoperator()\fP (RandomAccessIterator first, RandomAccessIterator last, StrictWeakOrdering comp)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<bool stable, class RandomAccessIterator, class StrictWeakOrdering> struct __gnu_parallel::sampling_sorter< stable, RandomAccessIterator, StrictWeakOrdering >"
Stable sorting functor. 

Used to reduce code instanciation in multiway_merge_sampling_splitting. 
.PP
Definition at line 1072 of file multiway_merge.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
