.TH "__gnu_parallel::for_each_selector" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::for_each_selector \- std::for_each() selector.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fBgeneric_for_each_selector< It >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename Op > bool \fBoperator()\fP (Op &o, It i)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "It \fBfinish_iterator\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename It> struct __gnu_parallel::for_each_selector< It >"
std::for_each() selector. 
.PP
Definition at line 54 of file for_each_selectors.h.
.SH "Member Function Documentation"
.PP 
.SS "template<typename It> template<typename Op > bool \fB__gnu_parallel::for_each_selector\fP< It >::operator() (Op & o, It i)\fC [inline]\fP"
.PP
Functor execution. 
.PP
\fBParameters:\fP
.RS 4
\fIo\fP Operator. 
.br
\fIi\fP Iterator referencing object. 
.RE
.PP

.PP
Definition at line 61 of file for_each_selectors.h.
.SH "Member Data Documentation"
.PP 
.SS "It  \fB__gnu_parallel::generic_for_each_selector\fP< It  >::\fBfinish_iterator\fP\fC [inherited]\fP"
.PP
Iterator on last element processed; needed for some algorithms (e. g. std::transform()). 
.PP
Definition at line 48 of file for_each_selectors.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
