.TH "__gnu_cxx::select1st" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_cxx::select1st \- An \fBSGI extension \fP.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits std::_Select1st<_Pair>.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _Pair \fBargument_type\fP"
.br
.ti -1c
.RI "typedef _Pair::first_type \fBresult_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const _Pair::first_type & \fBoperator()\fP (const _Pair &__x) const "
.br
.ti -1c
.RI "_Pair::first_type & \fBoperator()\fP (_Pair &__x) const "
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class _Pair> struct __gnu_cxx::select1st< _Pair >"
An \fBSGI extension \fP. 
.PP
Definition at line 199 of file ext/functional.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef _Pair  \fBstd::unary_function\fP< _Pair , _Pair::first_type  >::\fBargument_type\fP\fC [inherited]\fP"
.PP
\fCargument_type\fP is the type of the argument (no surprises here) 
.PP
Definition at line 102 of file stl_function.h.
.SS "typedef _Pair::first_type  \fBstd::unary_function\fP< _Pair , _Pair::first_type  >::\fBresult_type\fP\fC [inherited]\fP"
.PP
\fCresult_type\fP is the return type 
.PP
Definition at line 105 of file stl_function.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
