.TH "__gnu_cxx::throw_allocator_base" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_cxx::throw_allocator_base \- Base class.  

.PP
.SH SYNOPSIS
.br
.PP
Inherited by \fB__gnu_cxx::throw_allocator< T >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP (unsigned long seed)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBempty\fP ()"
.br
.ti -1c
.RI "static double \fBget_throw_prob\fP ()"
.br
.ti -1c
.RI "static void \fBset_label\fP (size_t l)"
.br
.ti -1c
.RI "static void \fBset_throw_prob\fP (double throw_prob)"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static void \fBcheck_allocated\fP (size_t)"
.br
.ti -1c
.RI "static void \fBcheck_allocated\fP (void *, size_t)"
.br
.ti -1c
.RI "static void \fBerase\fP (void *, size_t)"
.br
.ti -1c
.RI "static void \fBinsert\fP (void *, size_t)"
.br
.ti -1c
.RI "static void \fBthrow_conditionally\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBstd::ostream\fP & \fBoperator<<\fP (\fBstd::ostream\fP &, const \fBthrow_allocator_base\fP &)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Base class. 
.PP
Definition at line 95 of file throw_allocator.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
