.TH "__gnu_cxx::__detail::_Bitmap_counter" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_cxx::__detail::_Bitmap_counter \- The bitmap counter which acts as the bitmap manipulator, and manages the bit-manipulation functions and the searching and identification functions on the bit-map.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB_Bitmap_counter\fP (\fB_BPVector\fP &Rvbp, long __index=-1)"
.br
.ti -1c
.RI "pointer \fB_M_base\fP () const   throw ()"
.br
.ti -1c
.RI "bool \fB_M_finished\fP () const   throw ()"
.br
.ti -1c
.RI "size_t * \fB_M_get\fP () const   throw ()"
.br
.ti -1c
.RI "_Index_type \fB_M_offset\fP () const   throw ()"
.br
.ti -1c
.RI "void \fB_M_reset\fP (long __index=-1)  throw ()"
.br
.ti -1c
.RI "void \fB_M_set_internal_bitmap\fP (size_t *__new_internal_marker)  throw ()"
.br
.ti -1c
.RI "_Index_type \fB_M_where\fP () const   throw ()"
.br
.ti -1c
.RI "\fB_Bitmap_counter\fP & \fBoperator++\fP ()  throw ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> class __gnu_cxx::__detail::_Bitmap_counter< _Tp >"
The bitmap counter which acts as the bitmap manipulator, and manages the bit-manipulation functions and the searching and identification functions on the bit-map. 
.PP
Definition at line 425 of file bitmap_allocator.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
