.TH "__gnu_cxx::encoding_state" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_cxx::encoding_state \- Extension to use iconv for dealing with \fBcharacter\fP encodings.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef iconv_t \fBdescriptor_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBcharacter_ratio\fP () const "
.br
.ti -1c
.RI "\fBencoding_state\fP (const \fBencoding_state\fP &__obj)"
.br
.ti -1c
.RI "\fBencoding_state\fP (const char *__int, const char *__ext, int __ibom=0, int __ebom=0, int __bytes=1)"
.br
.ti -1c
.RI "int \fBexternal_bom\fP () const "
.br
.ti -1c
.RI "const \fBstd::string\fP \fBexternal_encoding\fP () const "
.br
.ti -1c
.RI "bool \fBgood\fP () const   throw ()"
.br
.ti -1c
.RI "const descriptor_type & \fBin_descriptor\fP () const "
.br
.ti -1c
.RI "int \fBinternal_bom\fP () const "
.br
.ti -1c
.RI "const \fBstd::string\fP \fBinternal_encoding\fP () const "
.br
.ti -1c
.RI "\fBencoding_state\fP & \fBoperator=\fP (const \fBencoding_state\fP &__obj)"
.br
.ti -1c
.RI "const descriptor_type & \fBout_descriptor\fP () const "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBconstruct\fP (const \fBencoding_state\fP &__obj)"
.br
.ti -1c
.RI "void \fBdestroy\fP ()  throw ()"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fB_M_bytes\fP"
.br
.ti -1c
.RI "int \fB_M_ext_bom\fP"
.br
.ti -1c
.RI "\fBstd::string\fP \fB_M_ext_enc\fP"
.br
.ti -1c
.RI "descriptor_type \fB_M_in_desc\fP"
.br
.ti -1c
.RI "int \fB_M_int_bom\fP"
.br
.ti -1c
.RI "\fBstd::string\fP \fB_M_int_enc\fP"
.br
.ti -1c
.RI "descriptor_type \fB_M_out_desc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Extension to use iconv for dealing with \fBcharacter\fP encodings. 
.PP
Definition at line 49 of file codecvt_specializations.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
