.TH "__gnu_cxx::free_list" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_cxx::free_list \- The free list class for managing chunks of memory to be given to and returned by the \fBbitmap_allocator\fP.  

.PP
.SH SYNOPSIS
.br
.PP
Inherited by \fB__gnu_cxx::bitmap_allocator< _Tp >\fP\fC [private]\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fB_M_clear\fP ()"
.br
.ti -1c
.RI "size_t * \fB_M_get\fP (size_t __sz)  throw (std::bad_alloc)"
.br
.ti -1c
.RI "void \fB_M_insert\fP (size_t *__addr)  throw ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
The free list class for managing chunks of memory to be given to and returned by the \fBbitmap_allocator\fP. 
.PP
Definition at line 546 of file bitmap_allocator.h.
.SH "Member Function Documentation"
.PP 
.SS "void __gnu_cxx::free_list::_M_clear ()"
.PP
This function just clears the internal Free List, and gives back all the memory to the OS. 
.PP
.SS "size_t* __gnu_cxx::free_list::_M_get (size_t __sz)  throw (\fBstd::bad_alloc\fP)"
.PP
This function gets a block of memory of the specified size from the free list. 
.PP
\fBParameters:\fP
.RS 4
\fI__sz\fP The size in bytes of the memory required.
.RE
.PP
\fBReturns:\fP
.RS 4
A pointer to the new memory block of size at least equal to that requested. 
.RE
.PP

.SS "void __gnu_cxx::free_list::_M_insert (size_t * __addr)  throw ()\fC [inline]\fP"
.PP
This function returns the block of memory to the internal free list. 
.PP
\fBParameters:\fP
.RS 4
\fI__addr\fP The pointer to the memory block that was given by a call to the _M_get function. 
.RE
.PP

.PP
Definition at line 654 of file bitmap_allocator.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
