.TH "__gnu_parallel::dummy_reduct" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::dummy_reduct \- Reduction function doing \fBnothing\fP.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (bool, bool) const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Reduction function doing \fBnothing\fP. 
.PP
Definition at line 299 of file for_each_selectors.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
