.TH "__gnu_cxx::debug_allocator" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_cxx::debug_allocator \- A meta-allocator with debugging bits, as per [20.4].
.PP
This is precisely the allocator defined in the C++ Standard.
.IP "\(bu" 2
all allocation calls operator new
.IP "\(bu" 2
all deallocation calls operator delete. 
.PP
 

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _Alloc::const_pointer \fBconst_pointer\fP"
.br
.ti -1c
.RI "typedef _Alloc::const_reference \fBconst_reference\fP"
.br
.ti -1c
.RI "typedef _Alloc::difference_type \fBdifference_type\fP"
.br
.ti -1c
.RI "typedef _Alloc::pointer \fBpointer\fP"
.br
.ti -1c
.RI "typedef _Alloc::reference \fBreference\fP"
.br
.ti -1c
.RI "typedef _Alloc::size_type \fBsize_type\fP"
.br
.ti -1c
.RI "typedef _Alloc::value_type \fBvalue_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "pointer \fBallocate\fP (size_type __n, const void *__hint)"
.br
.ti -1c
.RI "pointer \fBallocate\fP (size_type __n)"
.br
.ti -1c
.RI "void \fBdeallocate\fP (pointer __p, size_type __n)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Alloc> class __gnu_cxx::debug_allocator< _Alloc >"
A meta-allocator with debugging bits, as per [20.4].
.PP
This is precisely the allocator defined in the C++ Standard.
.IP "\(bu" 2
all allocation calls operator new
.IP "\(bu" 2
all deallocation calls operator delete. 
.PP

.PP
Definition at line 61 of file debug_allocator.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
