.TH "__gnu_pbds::trie_tag" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_pbds::trie_tag \- trie.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fB__gnu_pbds::basic_tree_tag\fP.
.PP
Inherited by \fB__gnu_pbds::pat_trie_tag\fP.
.PP
.SH "Detailed Description"
.PP 
trie. 
.PP
Definition at line 129 of file tag_and_trait.hpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
