__gnu_debug::_Safe_iterator_base
NAME
__gnu_debug::_Safe_iterator_base - Basic functionality for a 'safe' iterator.
SYNOPSIS
Inherited by __gnu_debug::_Safe_iterator< _Iterator, _Sequence >, and std::__debug::bitset< _Nb >::bitset::reference.
Public Member Functions
void _M_attach (_Safe_sequence_base *__seq, bool __constant)
void _M_attach_single (_Safe_sequence_base *__seq, bool __constant)
bool _M_attached_to (const _Safe_sequence_base *__seq) const
bool _M_can_compare (const _Safe_iterator_base &__x) const
void _M_detach ()
void _M_detach_single ()
bool _M_singular () const
Public Attributes
_Safe_iterator_base * _M_next
_Safe_iterator_base * _M_prior
_Safe_sequence_base * _M_sequence
unsigned int _M_version
Protected Member Functions
__gnu_cxx::__mutex & _M_get_mutex ()
_Safe_iterator_base (const _Safe_iterator_base &)
_Safe_iterator_base (const _Safe_iterator_base &__x, bool __constant)
_Safe_iterator_base (const _Safe_sequence_base *__seq, bool __constant)
_Safe_iterator_base ()
_Safe_iterator_base & operator= (const _Safe_iterator_base &)
Detailed Description
Basic functionality for a 'safe' iterator.
The _Safe_iterator_base base class implements the functionality of a safe iterator that is not specific to a particular iterator type. It contains a pointer back to the sequence it references along with iterator version information and pointers to form a doubly-linked list of iterators referenced by the container.
This class must not perform any operations that can throw an exception, or the exception guarantees of derived iterators will be broken.
Definition at line 51 of file safe_base.h.
Constructor & Destructor Documentation
__gnu_debug::_Safe_iterator_base::_Safe_iterator_base () [inline, protected]
Initializes the iterator and makes it singular.
Definition at line 77 of file safe_base.h.
__gnu_debug::_Safe_iterator_base::_Safe_iterator_base (const _Safe_sequence_base * __seq, bool __constant) [inline, protected]
Initialize the iterator to reference the sequence pointed to by . __constant is true when we are initializing a constant iterator, and false if it is a mutable iterator. Note that __seq may be NULL, in which case the iterator will be singular. Otherwise, the iterator will reference __seq and be nonsingular.
Definition at line 88 of file safe_base.h.
References _M_attach().
__gnu_debug::_Safe_iterator_base::_Safe_iterator_base (const _Safe_iterator_base & __x, bool __constant) [inline, protected]
Initializes the iterator to reference the same sequence that __x does. __constant is true if this is a constant iterator, and false if it is mutable.
Definition at line 95 of file safe_base.h.
References _M_attach(), and _M_sequence.
Member Function Documentation
void __gnu_debug::_Safe_iterator_base::_M_attach (_Safe_sequence_base * __seq, bool __constant)
Attaches this iterator to the given sequence, detaching it from whatever sequence it was attached to originally. If the new sequence is the NULL pointer, the iterator is left unattached.
Referenced by _Safe_iterator_base().
void __gnu_debug::_Safe_iterator_base::_M_attach_single (_Safe_sequence_base * __seq, bool __constant)
Likewise, but not thread-safe.
bool __gnu_debug::_Safe_iterator_base::_M_attached_to (const _Safe_sequence_base * __seq) const [inline]
Determines if we are attached to the given sequence.
Definition at line 130 of file safe_base.h.
References _M_sequence.
bool __gnu_debug::_Safe_iterator_base::_M_can_compare (const _Safe_iterator_base & __x) const
Can we compare this iterator to the given iterator __x? Returns true if both iterators are nonsingular and reference the same sequence.
void __gnu_debug::_Safe_iterator_base::_M_detach ()
Detach the iterator for whatever sequence it is attached to, if any.
void __gnu_debug::_Safe_iterator_base::_M_detach_single ()
Likewise, but not thread-safe.
__gnu_cxx::__mutex& __gnu_debug::_Safe_iterator_base::_M_get_mutex () [protected]
For use in _Safe_iterator.
Referenced by __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_invalidate().
bool __gnu_debug::_Safe_iterator_base::_M_singular () const
Is this iterator singular?
Referenced by __gnu_debug::__check_singular(), __gnu_debug::__check_singular_aux(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_dereferenceable(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_invalidate_single(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_Safe_iterator(), and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator=().
Member Data Documentation
_Safe_iterator_base* __gnu_debug::_Safe_iterator_base::_M_next
Pointer to the next iterator in the sequence's list of iterators. Only valid when _M_sequence != NULL.
Definition at line 73 of file safe_base.h.
Referenced by __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_invalidate_single().
_Safe_iterator_base* __gnu_debug::_Safe_iterator_base::_M_prior
Pointer to the previous iterator in the sequence's list of iterators. Only valid when _M_sequence != NULL.
Definition at line 69 of file safe_base.h.
_Safe_sequence_base* __gnu_debug::_Safe_iterator_base::_M_sequence
The sequence this iterator references; may be NULL to indicate a singular iterator.
Definition at line 56 of file safe_base.h.
Referenced by _M_attached_to(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_invalidate_single(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_begin(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_end(), __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_iter(), _Safe_iterator_base(), and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator=().
unsigned int __gnu_debug::_Safe_iterator_base::_M_version
The version number of this iterator. The sentinel value 0 is used to indicate an invalidated iterator (i.e., one that is singular because of an operation on the container). This version number must equal the version number in the sequence referenced by _M_sequence for the iterator to be non-singular.
Definition at line 65 of file safe_base.h.
Referenced by __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_invalidate_single().
Author
Generated automatically by Doxygen for libstdc++ from the source code.