.TH "__gnu_debug::_After_nth_from" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_debug::_After_nth_from \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB_After_nth_from\fP (const difference_type &__n, const _Iterator &__base)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (const _Iterator &__x) const "
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Iterator> class __gnu_debug::_After_nth_from< _Iterator >"
A function object that returns true when the given random access iterator is at least \fCn\fP steps away from the given iterator. 
.PP
Definition at line 63 of file safe_sequence.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
