.TH "__gnu_parallel::multiway_merge_k_variant_sentinel_switch" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::multiway_merge_k_variant_sentinel_switch \- Switch for k-way merging with sentinels turned on.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "RandomAccessIterator3 \fBoperator()\fP (RandomAccessIteratorIterator seqs_begin, RandomAccessIteratorIterator seqs_end, RandomAccessIterator3 target, const typename \fBstd::iterator_traits\fP< typename \fBstd::iterator_traits\fP< RandomAccessIteratorIterator >::value_type::first_type >::value_type &sentinel, _DifferenceTp length, Comparator comp)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<bool sentinels, bool stable, typename RandomAccessIteratorIterator, typename RandomAccessIterator3, typename _DifferenceTp, typename Comparator> struct __gnu_parallel::multiway_merge_k_variant_sentinel_switch< sentinels, stable, RandomAccessIteratorIterator, RandomAccessIterator3, _DifferenceTp, Comparator >"
Switch for k-way merging with sentinels turned on. 
.PP
Definition at line 895 of file multiway_merge.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
