__gnu_debug::_Safe_sequence_base
NAME
__gnu_debug::_Safe_sequence_base - Base class that supports tracking of iterators that reference a sequence.
SYNOPSIS
Inherited by __gnu_debug::_Safe_sequence< _Sequence >, __gnu_debug::_Safe_sequence< basic_string< _CharT, _Traits, _Allocator > >, __gnu_debug::_Safe_sequence< deque< _Tp, _Allocator > >, __gnu_debug::_Safe_sequence< list< _Tp, _Allocator > >, __gnu_debug::_Safe_sequence< map< _Key, _Tp, _Compare, _Allocator > >, __gnu_debug::_Safe_sequence< multimap< _Key, _Tp, _Compare, _Allocator > >, __gnu_debug::_Safe_sequence< multiset< _Key, _Compare, _Allocator > >, __gnu_debug::_Safe_sequence< set< _Key, _Compare, _Allocator > >, __gnu_debug::_Safe_sequence< unordered_map< _Key, _Tp, _Hash, _Pred, _Alloc > >, __gnu_debug::_Safe_sequence< unordered_multimap< _Key, _Tp, _Hash, _Pred, _Alloc > >, __gnu_debug::_Safe_sequence< unordered_multiset< _Value, _Hash, _Pred, _Alloc > >, __gnu_debug::_Safe_sequence< unordered_set< _Value, _Hash, _Pred, _Alloc > >, __gnu_debug::_Safe_sequence< vector< _Tp, _Allocator > >, and std::__debug::bitset< _Nb >.
Public Member Functions
void _M_invalidate_all () const
Public Attributes
_Safe_iterator_base * _M_const_iterators
_Safe_iterator_base * _M_iterators
unsigned int _M_version
Protected Member Functions
void _M_detach_all ()
void _M_detach_singular ()
__gnu_cxx::__mutex & _M_get_mutex ()
void _M_revalidate_singular ()
void _M_swap (_Safe_sequence_base &__x)
~_Safe_sequence_base ()
Detailed Description
Base class that supports tracking of iterators that reference a sequence.
The _Safe_sequence_base class provides basic support for tracking iterators into a sequence. Sequences that track iterators must derived from _Safe_sequence_base publicly, so that safe iterators (which inherit _Safe_iterator_base) can attach to them. This class contains two linked lists of iterators, one for constant iterators and one for mutable iterators, and a version number that allows very fast invalidation of all iterators that reference the container.
This class must ensure that no operation on it may throw an exception, otherwise 'safe' sequences may fail to provide the exception-safety guarantees required by the C++ standard.
Definition at line 159 of file safe_base.h.
Constructor & Destructor Documentation
__gnu_debug::_Safe_sequence_base::~_Safe_sequence_base () [inline, protected]
Notify all iterators that reference this sequence that the sequence is being destroyed.
Definition at line 179 of file safe_base.h.
References _M_detach_all().
Member Function Documentation
void __gnu_debug::_Safe_sequence_base::_M_detach_all () [protected]
Detach all iterators, leaving them singular.
Referenced by ~_Safe_sequence_base().
void __gnu_debug::_Safe_sequence_base::_M_detach_singular () [protected]
Detach all singular iterators.
Postcondition:
for all iterators i attached to this sequence, i->_M_version == _M_version.
__gnu_cxx::__mutex& __gnu_debug::_Safe_sequence_base::_M_get_mutex () [protected]
For use in _Safe_sequence.
Referenced by __gnu_debug::_Safe_sequence< _Sequence >::_M_invalidate_if(), and __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_iter().
void __gnu_debug::_Safe_sequence_base::_M_invalidate_all () const [inline]
Invalidates all iterators.
Definition at line 215 of file safe_base.h.
References _M_version.
void __gnu_debug::_Safe_sequence_base::_M_revalidate_singular () [protected]
Revalidates all attached singular iterators. This method may be used to validate iterators that were invalidated before (but for some reason, such as an exception, need to become valid again).
void __gnu_debug::_Safe_sequence_base::_M_swap (_Safe_sequence_base & __x) [protected]
Swap this sequence with the given sequence. This operation also swaps ownership of the iterators, so that when the operation is complete all iterators that originally referenced one container now reference the other container.
Member Data Documentation
_Safe_iterator_base* __gnu_debug::_Safe_sequence_base::_M_const_iterators
The list of constant iterators that reference this container.
Definition at line 166 of file safe_base.h.
Referenced by __gnu_debug::_Safe_sequence< _Sequence >::_M_invalidate_if(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_invalidate_single(), and __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_iter().
_Safe_iterator_base* __gnu_debug::_Safe_sequence_base::_M_iterators
The list of mutable iterators that reference this container.
Definition at line 163 of file safe_base.h.
Referenced by __gnu_debug::_Safe_sequence< _Sequence >::_M_invalidate_if(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_invalidate_single(), and __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_iter().
unsigned int __gnu_debug::_Safe_sequence_base::_M_version [mutable]
The container version number. This number may never be 0.
Definition at line 169 of file safe_base.h.
Referenced by _M_invalidate_all().
Author
Generated automatically by Doxygen for libstdc++ from the source code.