.TH "__gnu_parallel::split_consistently" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::split_consistently \- Split consistently.  

.PP
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SS "template<bool exact, typename RandomAccessIterator, typename Comparator, typename SortingPlacesIterator> struct __gnu_parallel::split_consistently< exact, RandomAccessIterator, Comparator, SortingPlacesIterator >"
Split consistently. 
.PP
Definition at line 122 of file multiway_mergesort.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
