.TH "__gnu_cxx::_Char_types" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_cxx::_Char_types \- Mapping from \fBcharacter\fP type to associated types.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef unsigned long \fBint_type\fP"
.br
.ti -1c
.RI "typedef \fBstd::streamoff\fP \fBoff_type\fP"
.br
.ti -1c
.RI "typedef \fBstd::streampos\fP \fBpos_type\fP"
.br
.ti -1c
.RI "typedef std::mbstate_t \fBstate_type\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _CharT> struct __gnu_cxx::_Char_types< _CharT >"
Mapping from \fBcharacter\fP type to associated types. 

\fBNote:\fP
.RS 4
This is an implementation class for the generic version of \fBchar_traits\fP. It defines int_type, off_type, pos_type, and state_type. By default these are unsigned long, streamoff, streampos, and mbstate_t. Users who need a different set of types, but who don't need to change the definitions of any function defined in \fBchar_traits\fP, can specialize \fB__gnu_cxx::_Char_types\fP while leaving \fB__gnu_cxx::char_traits\fP alone. 
.RE
.PP

.PP
Definition at line 65 of file char_traits.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
