.TH "__gnu_pbds::binary_heap_tag" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_pbds::binary_heap_tag \- Binary-heap (array-based).  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fB__gnu_pbds::priority_queue_tag\fP.
.PP
.SH "Detailed Description"
.PP 
Binary-heap (array-based). 
.PP
Definition at line 150 of file tag_and_trait.hpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
