.TH "__gnu_parallel::replace_selector" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::replace_selector \- std::replace() selector.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fBgeneric_for_each_selector< It >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (T &v, It i)"
.br
.ti -1c
.RI "\fBreplace_selector\fP (const T &\fBnew_val\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "It \fBfinish_iterator\fP"
.br
.ti -1c
.RI "const T & \fBnew_val\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename It, typename T> struct __gnu_parallel::replace_selector< It, T >"
std::replace() selector. 
.PP
Definition at line 134 of file for_each_selectors.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename It , typename T > \fB__gnu_parallel::replace_selector\fP< It, T >::\fBreplace_selector\fP (const T & new_val)\fC [inline, explicit]\fP"
.PP
Constructor. 
.PP
\fBParameters:\fP
.RS 4
\fInew_val\fP Value to replace with. 
.RE
.PP

.PP
Definition at line 142 of file for_each_selectors.h.
.SH "Member Function Documentation"
.PP 
.SS "template<typename It , typename T > bool \fB__gnu_parallel::replace_selector\fP< It, T >::operator() (T & v, It i)\fC [inline]\fP"
.PP
Functor execution. 
.PP
\fBParameters:\fP
.RS 4
\fIv\fP Current value. 
.br
\fIi\fP Iterator referencing object. 
.RE
.PP

.PP
Definition at line 148 of file for_each_selectors.h.
.PP
References __gnu_parallel::replace_selector< It, T >::new_val.
.SH "Member Data Documentation"
.PP 
.SS "It  \fB__gnu_parallel::generic_for_each_selector\fP< It  >::\fBfinish_iterator\fP\fC [inherited]\fP"
.PP
Iterator on last element processed; needed for some algorithms (e. g. std::transform()). 
.PP
Definition at line 48 of file for_each_selectors.h.
.SS "template<typename It , typename T > const T& \fB__gnu_parallel::replace_selector\fP< It, T >::\fBnew_val\fP"
.PP
Value to replace with. 
.PP
Definition at line 137 of file for_each_selectors.h.
.PP
Referenced by __gnu_parallel::replace_selector< It, T >::operator()().

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
