.TH "__gnu_pbds::rc_binomial_heap_tag" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_pbds::rc_binomial_heap_tag \- Redundant-counter binomial-heap.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fB__gnu_pbds::priority_queue_tag\fP.
.PP
.SH "Detailed Description"
.PP 
Redundant-counter binomial-heap. 
.PP
Definition at line 147 of file tag_and_trait.hpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
