.TH "__gnu_parallel::sequential_tag" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::sequential_tag \- Forces sequential execution at compile time.  

.PP
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Forces sequential execution at compile time. 
.PP
Definition at line 42 of file tags.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
