__gnu_debug::_Safe_sequence
NAME
__gnu_debug::_Safe_sequence - Base class for constructing a 'safe' sequence type that tracks iterators that reference it.
SYNOPSIS
Inherits __gnu_debug::_Safe_sequence_base.
Public Member Functions
void _M_invalidate_all () const
template<typename _Predicate > void _M_invalidate_if (_Predicate __pred)
template<typename _Iterator > void _M_transfer_iter (const _Safe_iterator< _Iterator, _Sequence > &__x)
Public Attributes
_Safe_iterator_base * _M_const_iterators
_Safe_iterator_base * _M_iterators
unsigned int _M_version
Protected Member Functions
void _M_detach_all ()
void _M_detach_singular ()
__gnu_cxx::__mutex & _M_get_mutex ()
void _M_revalidate_singular ()
void _M_swap (_Safe_sequence_base &__x)
Detailed Description
template<typename _Sequence> class __gnu_debug::_Safe_sequence< _Sequence >
Base class for constructing a 'safe' sequence type that tracks iterators that reference it.
The class template _Safe_sequence simplifies the construction of 'safe' sequences that track the iterators that reference the sequence, so that the iterators are notified of changes in the sequence that may affect their operation, e.g., if the container invalidates its iterators or is destructed. This class template may only be used by deriving from it and passing the name of the derived class as its template parameter via the curiously recurring template pattern. The derived class must have iterator and types that are instantiations of class template _Safe_iterator for this sequence. Iterators will then be tracked automatically.
Definition at line 97 of file safe_sequence.h.
Member Function Documentation
void __gnu_debug::_Safe_sequence_base::_M_detach_all () [protected, inherited]
Detach all iterators, leaving them singular.
Referenced by __gnu_debug::_Safe_sequence_base::~_Safe_sequence_base().
void __gnu_debug::_Safe_sequence_base::_M_detach_singular () [protected, inherited]
Detach all singular iterators.
Postcondition:
for all iterators i attached to this sequence, i->_M_version == _M_version.
__gnu_cxx::__mutex& __gnu_debug::_Safe_sequence_base::_M_get_mutex () [protected, inherited]
For use in _Safe_sequence.
Referenced by __gnu_debug::_Safe_sequence< _Sequence >::_M_invalidate_if(), and __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_iter().
void __gnu_debug::_Safe_sequence_base::_M_invalidate_all () const [inline, inherited]
Invalidates all iterators.
Definition at line 215 of file safe_base.h.
References __gnu_debug::_Safe_sequence_base::_M_version.
template<typename _Sequence > template<typename _Predicate > void __gnu_debug::_Safe_sequence< _Sequence >::_M_invalidate_if (_Predicate __pred) [inline]
Invalidates all iterators x that reference this sequence, are not singular, and for which pred(x) returns true. The user of this routine should be careful not to make copies of the iterators passed to pred, as the copies may interfere with the invalidation.
Definition at line 121 of file safe_sequence.h.
References __gnu_debug::_Safe_sequence_base::_M_const_iterators, __gnu_debug::_Safe_sequence_base::_M_get_mutex(), and __gnu_debug::_Safe_sequence_base::_M_iterators.
void __gnu_debug::_Safe_sequence_base::_M_revalidate_singular () [protected, inherited]
Revalidates all attached singular iterators. This method may be used to validate iterators that were invalidated before (but for some reason, such as an exception, need to become valid again).
void __gnu_debug::_Safe_sequence_base::_M_swap (_Safe_sequence_base & __x) [protected, inherited]
Swap this sequence with the given sequence. This operation also swaps ownership of the iterators, so that when the operation is complete all iterators that originally referenced one container now reference the other container.
template<typename _Sequence> template<typename _Iterator > void __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_iter (const _Safe_iterator< _Iterator, _Sequence > & __x) [inline]
Transfers all iterators that reference this memory location to this sequence from whatever sequence they are attached to.
Definition at line 154 of file safe_sequence.h.
References __gnu_debug::_Safe_sequence_base::_M_const_iterators, __gnu_debug::_Safe_sequence_base::_M_get_mutex(), __gnu_debug::_Safe_sequence_base::_M_iterators, __gnu_debug::_Safe_iterator_base::_M_sequence, and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::base().
Member Data Documentation
_Safe_iterator_base* __gnu_debug::_Safe_sequence_base::_M_const_iterators [inherited]
The list of constant iterators that reference this container.
Definition at line 166 of file safe_base.h.
Referenced by __gnu_debug::_Safe_sequence< _Sequence >::_M_invalidate_if(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_invalidate_single(), and __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_iter().
_Safe_iterator_base* __gnu_debug::_Safe_sequence_base::_M_iterators [inherited]
The list of mutable iterators that reference this container.
Definition at line 163 of file safe_base.h.
Referenced by __gnu_debug::_Safe_sequence< _Sequence >::_M_invalidate_if(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_invalidate_single(), and __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_iter().
unsigned int __gnu_debug::_Safe_sequence_base::_M_version [mutable, inherited]
The container version number. This number may never be 0.
Definition at line 169 of file safe_base.h.
Referenced by __gnu_debug::_Safe_sequence_base::_M_invalidate_all().
Author
Generated automatically by Doxygen for libstdc++ from the source code.