.TH "__gnu_parallel::iterator_pair" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::iterator_pair \- A pair of iterators. The usual iterator operations are applied to both child iterators.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fBpair< Iterator1, Iterator2 >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef traits_type::difference_type \fBdifference_type\fP"
.br
.ti -1c
.RI "typedef Iterator1 \fBfirst_type\fP"
.br
.ti -1c
.RI "typedef IteratorCategory \fBiterator_category\fP"
.br
.ti -1c
.RI "typedef \fBtype\fP * \fBpointer\fP"
.br
.ti -1c
.RI "typedef \fBtype\fP & \fBreference\fP"
.br
.ti -1c
.RI "typedef Iterator2 \fBsecond_type\fP"
.br
.ti -1c
.RI "typedef \fBstd::iterator_traits\fP< Iterator1 > \fBtraits_type\fP"
.br
.ti -1c
.RI "typedef void \fBvalue_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBiterator_pair\fP (const Iterator1 &\fBfirst\fP, const Iterator2 &\fBsecond\fP)"
.br
.ti -1c
.RI "\fBoperator Iterator2\fP () const "
.br
.ti -1c
.RI "\fBtype\fP \fBoperator+\fP (difference_type delta) const "
.br
.ti -1c
.RI "const \fBtype\fP \fBoperator++\fP (int)"
.br
.ti -1c
.RI "\fBtype\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "difference_type \fBoperator-\fP (const \fBtype\fP &other) const "
.br
.ti -1c
.RI "const \fBtype\fP \fBoperator--\fP (int)"
.br
.ti -1c
.RI "\fBtype\fP & \fBoperator--\fP ()"
.br
.ti -1c
.RI "\fBtype\fP & \fBoperator=\fP (const \fBtype\fP &other)"
.br
.ti -1c
.RI "void \fBswap\fP (pair &&__p)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Iterator1 \fBfirst\fP"
.br
.ti -1c
.RI "Iterator2 \fBsecond\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Iterator1, typename Iterator2, typename IteratorCategory> class __gnu_parallel::iterator_pair< Iterator1, Iterator2, IteratorCategory >"
A pair of iterators. The usual iterator operations are applied to both child iterators. 
.PP
Definition at line 44 of file iterator.h.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef Iterator1  \fBstd::pair\fP< Iterator1 , Iterator2  >::\fBfirst_type\fP\fC [inherited]\fP"
.PP
\fCfirst_type\fP is the first bound type 
.PP
Definition at line 69 of file stl_pair.h.
.SS "typedef Iterator2  \fBstd::pair\fP< Iterator1 , Iterator2  >::\fBsecond_type\fP\fC [inherited]\fP"
.PP
\fCsecond_type\fP is the second bound type 
.PP
Definition at line 70 of file stl_pair.h.
.SH "Member Data Documentation"
.PP 
.SS "Iterator1  \fBstd::pair\fP< Iterator1 , Iterator2  >::\fBfirst\fP\fC [inherited]\fP"
.PP
\fCfirst\fP is a copy of the first object 
.PP
Definition at line 72 of file stl_pair.h.
.SS "Iterator2  \fBstd::pair\fP< Iterator1 , Iterator2  >::\fBsecond\fP\fC [inherited]\fP"
.PP
\fCsecond\fP is a copy of the second object 
.PP
Definition at line 73 of file stl_pair.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
