.TH "__gnu_parallel::min_element_reduct" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::min_element_reduct \- Reduction for finding the maximum element, using a comparator.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmin_element_reduct\fP (Comp &c)"
.br
.ti -1c
.RI "It \fBoperator()\fP (It x, It y)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Comp & \fBcomp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Comp, typename It> struct __gnu_parallel::min_element_reduct< Comp, It >"
Reduction for finding the maximum element, using a comparator. 
.PP
Definition at line 308 of file for_each_selectors.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
