.TH "__gnu_pbds::rb_tree_tag" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_pbds::rb_tree_tag \- Red-black tree.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fB__gnu_pbds::tree_tag\fP.
.PP
.SH "Detailed Description"
.PP 
Red-black tree. 
.PP
Definition at line 120 of file tag_and_trait.hpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
