.TH "__gnu_parallel::generic_for_each_selector" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::generic_for_each_selector \- Generic selector for embarrassingly parallel functions.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "It \fBfinish_iterator\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename It> struct __gnu_parallel::generic_for_each_selector< It >"
Generic selector for embarrassingly parallel functions. 
.PP
Definition at line 43 of file for_each_selectors.h.
.SH "Member Data Documentation"
.PP 
.SS "template<typename It> It \fB__gnu_parallel::generic_for_each_selector\fP< It >::\fBfinish_iterator\fP"
.PP
Iterator on last element processed; needed for some algorithms (e. g. std::transform()). 
.PP
Definition at line 48 of file for_each_selectors.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
