.TH "__gnu_parallel::equal_split_tag" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::equal_split_tag \- Selects the equal splitting variant for std::find().  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fB__gnu_parallel::find_tag\fP.
.PP
.SH "Detailed Description"
.PP 
Selects the equal splitting variant for std::find(). 

\fBSee also:\fP
.RS 4
\fB_GLIBCXX_FIND_EQUAL_SPLIT\fP 
.RE
.PP

.PP
Definition at line 188 of file tags.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
