.TH "__gnu_parallel::nothing" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::nothing \- Functor doing \fBnothing\fP.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename It > void \fBoperator()\fP (It i)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Functor doing \fBnothing\fP. 

For some reduction tasks (this is not a function object, but is passed as selector dummy parameter. 
.PP
Definition at line 289 of file for_each_selectors.h.
.SH "Member Function Documentation"
.PP 
.SS "template<typename It > void __gnu_parallel::nothing::operator() (It i)\fC [inline]\fP"
.PP
Functor execution. 
.PP
\fBParameters:\fP
.RS 4
\fIi\fP Iterator referencing object. 
.RE
.PP

.PP
Definition at line 295 of file for_each_selectors.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
