.TH "__gnu_parallel::accumulate_binop_reduct" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::accumulate_binop_reduct \- General reduction, using a binary operator.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBaccumulate_binop_reduct\fP (BinOp &b)"
.br
.ti -1c
.RI "template<typename Result , typename Addend > Result \fBoperator()\fP (const Result &x, const Addend &y)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "BinOp & \fBbinop\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename BinOp> struct __gnu_parallel::accumulate_binop_reduct< BinOp >"
General reduction, using a binary operator. 
.PP
Definition at line 346 of file for_each_selectors.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
