.TH "__gnu_pbds::tree_tag" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_pbds::tree_tag \- tree.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fB__gnu_pbds::basic_tree_tag\fP.
.PP
Inherited by \fB__gnu_pbds::ov_tree_tag\fP, \fB__gnu_pbds::rb_tree_tag\fP, and \fB__gnu_pbds::splay_tree_tag\fP.
.PP
.SH "Detailed Description"
.PP 
tree. 
.PP
Definition at line 117 of file tag_and_trait.hpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
