.TH "__gnu_parallel::lexicographic" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::lexicographic \- Compare a pair of types lexicographically, ascending.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fBbinary_function< std::pair< T1, T2 >, std::pair< T1, T2 >, bool >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBstd::pair\fP< T1, T2 > \fBfirst_argument_type\fP"
.br
.ti -1c
.RI "typedef bool \fBresult_type\fP"
.br
.ti -1c
.RI "typedef \fBstd::pair\fP< T1, T2 > \fBsecond_argument_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlexicographic\fP (Comparator &_comp)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBstd::pair\fP< T1, T2 > &p1, const \fBstd::pair\fP< T1, T2 > &p2) const "
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T1, typename T2, typename Comparator> class __gnu_parallel::lexicographic< T1, T2, Comparator >"
Compare a pair of types lexicographically, ascending. 
.PP
Definition at line 55 of file multiseq_selection.h.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef \fBstd::pair\fP< T1, T2 >  \fBstd::binary_function\fP< \fBstd::pair\fP< T1, T2 > , \fBstd::pair\fP< T1, T2 > , bool  >::\fBfirst_argument_type\fP\fC [inherited]\fP"
.PP
the type of the first argument (no surprises here) 
.PP
Definition at line 114 of file stl_function.h.
.SS "typedef bool  \fBstd::binary_function\fP< \fBstd::pair\fP< T1, T2 > , \fBstd::pair\fP< T1, T2 > , bool  >::\fBresult_type\fP\fC [inherited]\fP"
.PP
type of the return type 
.PP
Definition at line 118 of file stl_function.h.
.SS "typedef \fBstd::pair\fP< T1, T2 >  \fBstd::binary_function\fP< \fBstd::pair\fP< T1, T2 > , \fBstd::pair\fP< T1, T2 > , bool  >::\fBsecond_argument_type\fP\fC [inherited]\fP"
.PP
the type of the second argument 
.PP
Definition at line 117 of file stl_function.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
