.TH "__gnu_parallel::unbalanced_tag" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::unbalanced_tag \- Recommends parallel execution using static load-balancing at compile time.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fB__gnu_parallel::parallel_tag\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBthread_index_t\fP \fBget_num_threads\fP ()"
.br
.ti -1c
.RI "void \fBset_num_threads\fP (\fBthread_index_t\fP num_threads)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Recommends parallel execution using static load-balancing at compile time. 
.PP
Definition at line 98 of file tags.h.
.SH "Member Function Documentation"
.PP 
.SS "\fBthread_index_t\fP __gnu_parallel::parallel_tag::get_num_threads ()\fC [inline, inherited]\fP"
.PP
Find out desired number of threads. 
.PP
\fBReturns:\fP
.RS 4
Desired number of threads. 
.RE
.PP

.PP
Definition at line 67 of file tags.h.
.PP
Referenced by __gnu_parallel::parallel_sort().
.SS "void __gnu_parallel::parallel_tag::set_num_threads (\fBthread_index_t\fP num_threads)\fC [inline, inherited]\fP"
.PP
Set the desired number of threads. 
.PP
\fBParameters:\fP
.RS 4
\fInum_threads\fP Desired number of threads. 
.RE
.PP

.PP
Definition at line 77 of file tags.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
