.TH "__gnu_parallel::growing_blocks_tag" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::growing_blocks_tag \- Selects the growing block size variant for std::find().  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fB__gnu_parallel::find_tag\fP.
.PP
.SH "Detailed Description"
.PP 
Selects the growing block size variant for std::find(). 

\fBSee also:\fP
.RS 4
\fB_GLIBCXX_FIND_GROWING_BLOCKS\fP 
.RE
.PP

.PP
Definition at line 180 of file tags.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
