.TH "__gnu_parallel::LoserTreePointerUnguarded" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::LoserTreePointerUnguarded \- Stable unguarded \fBLoserTree\fP variant storing pointers.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fBLoserTreePointerUnguardedBase< T, Comparator >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBdelete_min_insert\fP (const T &key, bool sup)"
.br
.ti -1c
.RI "int \fBget_min_source\fP ()"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "unsigned int \fBinit_winner\fP (unsigned int root)"
.br
.ti -1c
.RI "void \fBinsert_start\fP (const T &key, int source, bool)"
.br
.ti -1c
.RI "\fBLoserTreePointerUnguarded\fP (unsigned int _k, const T &_sentinel, Comparator _comp=\fBstd::less\fP< T >())"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "Comparator \fBcomp\fP"
.br
.ti -1c
.RI "unsigned int \fBik\fP"
.br
.ti -1c
.RI "unsigned int \fBk\fP"
.br
.ti -1c
.RI "Loser * \fBlosers\fP"
.br
.ti -1c
.RI "unsigned int \fBoffset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<bool stable, typename T, typename Comparator> class __gnu_parallel::LoserTreePointerUnguarded< stable, T, Comparator >"
Stable unguarded \fBLoserTree\fP variant storing pointers. 

Unstable variant is implemented below using partial specialization. 
.PP
Definition at line 853 of file losertree.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
