.TH "__gnu_cxx::__scoped_lock" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_cxx::__scoped_lock \- Scoped lock idiom.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef __mutex \fB__mutex_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__scoped_lock\fP (__mutex_type &__name)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Scoped lock idiom. 
.PP
Definition at line 241 of file concurrence.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
