.TH "__gnu_cxx::__common_pool_policy" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_cxx::__common_pool_policy \- Policy for shared __pool objects.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits __common_pool_base<_PoolTp, _Thread>.
.PP
.SH "Detailed Description"
.PP 

.SS "template<template< bool > class _PoolTp, bool _Thread> struct __gnu_cxx::__common_pool_policy< _PoolTp, _Thread >"
Policy for shared __pool objects. 
.PP
Definition at line 456 of file mt_allocator.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
