.TH "__gnu_cxx::constant_unary_fun" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_cxx::constant_unary_fun \- An \fBSGI extension \fP.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits __gnu_cxx::_Constant_unary_fun<_Result, _Argument>.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _Argument \fBargument_type\fP"
.br
.ti -1c
.RI "typedef _Result \fBresult_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBconstant_unary_fun\fP (const _Result &__v)"
.br
.ti -1c
.RI "const result_type & \fBoperator()\fP (const _Argument &) const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "result_type \fB_M_val\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class _Result, class _Argument = _Result> struct __gnu_cxx::constant_unary_fun< _Result, _Argument >"
An \fBSGI extension \fP. 
.PP
Definition at line 308 of file ext/functional.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
