.TH "__gnu_parallel::LoserTreePointerBase::Loser" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::LoserTreePointerBase::Loser \- Internal representation of \fBLoserTree\fP elements.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const T * \fBkeyp\fP"
.br
.ti -1c
.RI "int \fBsource\fP"
.br
.ti -1c
.RI "bool \fBsup\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T, typename Comparator> struct __gnu_parallel::LoserTreePointerBase< T, Comparator >::Loser"
Internal representation of \fBLoserTree\fP elements. 
.PP
Definition at line 347 of file losertree.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
