.TH "__gnu_cxx::typelist" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_cxx::typelist \- GNU \fBtypelist\fP extensions for public compile-time use.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename Fn , typename Typelist > void \fBapply\fP (Fn &, Typelist)"
.br
.ti -1c
.RI "template<typename Fn , typename TypelistT , typename TypelistV > void \fBapply_generator\fP (Fn &fn, TypelistT, TypelistV)"
.br
.ti -1c
.RI "template<typename Fn , typename Typelist > void \fBapply_generator\fP (Fn &fn, Typelist)"
.br
.ti -1c
.RI "template<typename Gn , typename TypelistT , typename TypelistV > void \fBapply_generator\fP (Gn &, TypelistT, TypelistV)"
.br
.ti -1c
.RI "template<typename Gn , typename Typelist > void \fBapply_generator\fP (Gn &, Typelist)"
.br
.in -1c
.SH "Detailed Description"
.PP 
GNU \fBtypelist\fP extensions for public compile-time use. 
.PP
.SH "Function Documentation"
.PP 
.SS "template<typename Gn , typename Typelist > void __gnu_cxx::typelist::apply_generator (Gn &, Typelist)\fC [inline]\fP"
.PP
Apply all \fBtypelist\fP types to generator functor. 
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
