.TH "__gnu_cxx::_ExtPtr_allocator" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_cxx::_ExtPtr_allocator \- An example allocator which uses a non-standard pointer type.
.PP
This allocator specifies that containers use a 'relative pointer' as it's pointer type. (See \fBext/pointer.h\fP) Memory allocation in this example is still performed using \fBstd::allocator\fP.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fB_Pointer_adapter\fP< \fB_Relative_pointer_impl\fP< const _Tp > > \fBconst_pointer\fP"
.br
.ti -1c
.RI "typedef const _Tp & \fBconst_reference\fP"
.br
.ti -1c
.RI "typedef std::ptrdiff_t \fBdifference_type\fP"
.br
.ti -1c
.RI "typedef \fB_Pointer_adapter\fP< \fB_Relative_pointer_impl\fP< _Tp > > \fBpointer\fP"
.br
.ti -1c
.RI "typedef _Tp & \fBreference\fP"
.br
.ti -1c
.RI "typedef std::size_t \fBsize_type\fP"
.br
.ti -1c
.RI "typedef _Tp \fBvalue_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename _Up > \fB_ExtPtr_allocator\fP (const \fB_ExtPtr_allocator\fP< _Up > &__rarg)  throw ()"
.br
.ti -1c
.RI "\fB_ExtPtr_allocator\fP (const \fB_ExtPtr_allocator\fP &__rarg)  throw ()"
.br
.ti -1c
.RI "const \fBstd::allocator\fP< _Tp > & \fB_M_getUnderlyingImp\fP () const "
.br
.ti -1c
.RI "\fBconst_pointer\fP \fBaddress\fP (const_reference __x) const "
.br
.ti -1c
.RI "\fBpointer\fP \fBaddress\fP (reference __x) const "
.br
.ti -1c
.RI "\fBpointer\fP \fBallocate\fP (size_type __n, void *__hint=0)"
.br
.ti -1c
.RI "template<typename... _Args> void \fBconstruct\fP (\fBpointer\fP __p, _Args &&...__args)"
.br
.ti -1c
.RI "void \fBconstruct\fP (\fBpointer\fP __p, const _Tp &__val)"
.br
.ti -1c
.RI "void \fBdeallocate\fP (\fBpointer\fP __p, size_type __n)"
.br
.ti -1c
.RI "void \fBdestroy\fP (\fBpointer\fP __p)"
.br
.ti -1c
.RI "size_type \fBmax_size\fP () const   throw ()"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fB_ExtPtr_allocator\fP &__rarg)"
.br
.ti -1c
.RI "template<typename _Up > bool \fBoperator!=\fP (const \fB_ExtPtr_allocator\fP< _Up > &__rarg)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fB_ExtPtr_allocator\fP &__rarg)"
.br
.ti -1c
.RI "template<typename _Up > bool \fBoperator==\fP (const \fB_ExtPtr_allocator\fP< _Up > &__rarg)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "template<typename _Up > void \fBswap\fP (\fB_ExtPtr_allocator\fP< _Up > &, \fB_ExtPtr_allocator\fP< _Up > &)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> class __gnu_cxx::_ExtPtr_allocator< _Tp >"
An example allocator which uses a non-standard pointer type.
.PP
This allocator specifies that containers use a 'relative pointer' as it's pointer type. (See \fBext/pointer.h\fP) Memory allocation in this example is still performed using \fBstd::allocator\fP. 
.PP
Definition at line 52 of file extptr_allocator.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
