.TH "__gnu_parallel::DRSSorterPU" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::DRSSorterPU \- Local data for a thread participating in \fB__gnu_parallel::parallel_random_shuffle()\fP.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBbin_index\fP \fBbins_begin\fP"
.br
.ti -1c
.RI "\fBbin_index\fP \fBbins_end\fP"
.br
.ti -1c
.RI "int \fBnum_threads\fP"
.br
.ti -1c
.RI "\fBDRandomShufflingGlobalData\fP< RandomAccessIterator > * \fBsd\fP"
.br
.ti -1c
.RI "\fBuint32\fP \fBseed\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename RandomAccessIterator, typename RandomNumberGenerator> struct __gnu_parallel::DRSSorterPU< RandomAccessIterator, RandomNumberGenerator >"
Local data for a thread participating in \fB__gnu_parallel::parallel_random_shuffle()\fP. 
.PP
Definition at line 91 of file random_shuffle.h.
.SH "Member Data Documentation"
.PP 
.SS "template<typename RandomAccessIterator, typename RandomNumberGenerator> \fBbin_index\fP \fB__gnu_parallel::DRSSorterPU\fP< RandomAccessIterator, RandomNumberGenerator >::\fBbins_begin\fP"
.PP
Begin index for bins taken care of by this thread. 
.PP
Definition at line 97 of file random_shuffle.h.
.PP
Referenced by __gnu_parallel::parallel_random_shuffle_drs().
.SS "template<typename RandomAccessIterator, typename RandomNumberGenerator> \fBbin_index\fP \fB__gnu_parallel::DRSSorterPU\fP< RandomAccessIterator, RandomNumberGenerator >::\fBbins_end\fP"
.PP
End index for bins taken care of by this thread. 
.PP
Definition at line 100 of file random_shuffle.h.
.PP
Referenced by __gnu_parallel::parallel_random_shuffle_drs().
.SS "template<typename RandomAccessIterator, typename RandomNumberGenerator> int \fB__gnu_parallel::DRSSorterPU\fP< RandomAccessIterator, RandomNumberGenerator >::\fBnum_threads\fP"
.PP
Number of threads participating in total. 
.PP
Definition at line 94 of file random_shuffle.h.
.PP
Referenced by __gnu_parallel::parallel_random_shuffle_drs(), and __gnu_parallel::parallel_random_shuffle_drs_pu().
.SS "template<typename RandomAccessIterator, typename RandomNumberGenerator> \fBDRandomShufflingGlobalData\fP<RandomAccessIterator>* \fB__gnu_parallel::DRSSorterPU\fP< RandomAccessIterator, RandomNumberGenerator >::\fBsd\fP"
.PP
Pointer to global data. 
.PP
Definition at line 106 of file random_shuffle.h.
.PP
Referenced by __gnu_parallel::parallel_random_shuffle_drs(), and __gnu_parallel::parallel_random_shuffle_drs_pu().
.SS "template<typename RandomAccessIterator, typename RandomNumberGenerator> \fBuint32\fP \fB__gnu_parallel::DRSSorterPU\fP< RandomAccessIterator, RandomNumberGenerator >::\fBseed\fP"
.PP
Random seed for this thread. 
.PP
Definition at line 103 of file random_shuffle.h.
.PP
Referenced by __gnu_parallel::parallel_random_shuffle_drs(), and __gnu_parallel::parallel_random_shuffle_drs_pu().

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
