.TH "__gnu_cxx::constant_binary_fun" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_cxx::constant_binary_fun \- An \fBSGI extension \fP.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits __gnu_cxx::_Constant_binary_fun<_Result, _Arg1, _Arg2>.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _Arg1 \fBfirst_argument_type\fP"
.br
.ti -1c
.RI "typedef _Result \fBresult_type\fP"
.br
.ti -1c
.RI "typedef _Arg2 \fBsecond_argument_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBconstant_binary_fun\fP (const _Result &__v)"
.br
.ti -1c
.RI "const result_type & \fBoperator()\fP (const _Arg1 &, const _Arg2 &) const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "_Result \fB_M_val\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class _Result, class _Arg1 = _Result, class _Arg2 = _Arg1> struct __gnu_cxx::constant_binary_fun< _Result, _Arg1, _Arg2 >"
An \fBSGI extension \fP. 
.PP
Definition at line 316 of file ext/functional.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
