.TH "__gnu_sequential" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_sequential \- GNU sequential classes for public use.  

.PP
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
GNU sequential classes for public use. 
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
