.TH "__gnu_parallel::pseudo_sequence_iterator" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::pseudo_sequence_iterator \- Iterator associated with \fB__gnu_parallel::pseudo_sequence\fP. If features the usual random-access iterator functionality.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _DifferenceTp \fBdifference_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "difference_type \fBoperator!=\fP (const \fBtype\fP &i2)"
.br
.ti -1c
.RI "const T & \fBoperator*\fP () const "
.br
.ti -1c
.RI "const \fBtype\fP \fBoperator++\fP (int)"
.br
.ti -1c
.RI "\fBtype\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "difference_type \fBoperator-\fP (const \fBtype\fP &i2)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBtype\fP &i2)"
.br
.ti -1c
.RI "const T & \fBoperator[]\fP (difference_type) const "
.br
.ti -1c
.RI "\fBpseudo_sequence_iterator\fP (const T &val, difference_type pos)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T, typename _DifferenceTp> class __gnu_parallel::pseudo_sequence_iterator< T, _DifferenceTp >"
Iterator associated with \fB__gnu_parallel::pseudo_sequence\fP. If features the usual random-access iterator functionality. 

\fBParameters:\fP
.RS 4
\fIT\fP Sequence value type. 
.br
\fIdifference_type\fP Sequence difference type. 
.RE
.PP

.PP
Definition at line 338 of file base.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
