.TH "__gnu_pbds::list_update_tag" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_pbds::list_update_tag \- List-update.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fB__gnu_pbds::associative_container_tag\fP.
.PP
.SH "Detailed Description"
.PP 
List-update. 
.PP
Definition at line 135 of file tag_and_trait.hpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
