.TH "__gnu_pbds::basic_tree_tag" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_pbds::basic_tree_tag \- Basic tree.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fB__gnu_pbds::associative_container_tag\fP.
.PP
Inherited by \fB__gnu_pbds::tree_tag\fP, and \fB__gnu_pbds::trie_tag\fP.
.PP
.SH "Detailed Description"
.PP 
Basic tree. 
.PP
Definition at line 114 of file tag_and_trait.hpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
