.TH "abi" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
abi \- The cross-vendor C++ Application Binary Interface. A namespace alias to __cxxabiv1, but user programs should use the alias `abi'.  

.PP
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
The cross-vendor C++ Application Binary Interface. A namespace alias to __cxxabiv1, but user programs should use the alias `abi'. 

A brief overview of an ABI is given in the libstdc++ FAQ, question 5.8 (you may have a copy of the FAQ locally, or you can view the online version at http://gcc.gnu.org/onlinedocs/libstdc++/faq/index.html#5_8).
.PP
GCC subscribes to a cross-vendor ABI for C++, sometimes called the IA64 ABI because it happens to be the native ABI for that platform. It is summarized at http://www.codesourcery.com/cxx-abi/ along with the current specification.
.PP
For users of GCC greater than or equal to 3.x, entry points are available in <\fBcxxabi.h\fP>, which notes, \fI'It is not normally necessary for user programs to include this header, or use the entry points directly. However, this header is available should that be needed.'\fP 
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
