.TH "Algorithms" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Algorithms \- 
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBMutating Algorithms\fP"
.br
.ti -1c
.RI "\fBNon-Mutating Algorithms\fP"
.br
.ti -1c
.RI "\fBSorting Algorithms\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Components for performing algorithmic operations. Includes non-modifying sequence, modifying (mutating) sequence, sorting, searching, merge, partition, heap, \fBset\fP, minima, maxima, and permutation operations. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
