.TH "Arithmetic Classes" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arithmetic Classes \- 
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBstd::divides< _Tp >\fP"
.br
.RI "\fIOne of the \fBmath functors\fP. \fP"
.ti -1c
.RI "struct \fBstd::minus< _Tp >\fP"
.br
.RI "\fIOne of the \fBmath functors\fP. \fP"
.ti -1c
.RI "struct \fBstd::modulus< _Tp >\fP"
.br
.RI "\fIOne of the \fBmath functors\fP. \fP"
.ti -1c
.RI "struct \fBstd::multiplies< _Tp >\fP"
.br
.RI "\fIOne of the \fBmath functors\fP. \fP"
.ti -1c
.RI "struct \fBstd::negate< _Tp >\fP"
.br
.RI "\fIOne of the \fBmath functors\fP. \fP"
.ti -1c
.RI "struct \fBstd::plus< _Tp >\fP"
.br
.RI "\fIOne of the \fBmath functors\fP. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Because basic math often needs to be done during an algorithm, the library provides functors for those operations. See the documentation for \fBthe base classes\fP for examples of their use. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
