.TH "Associative Containers" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Associative Containers \- 
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBstd::map< _Key, _Tp, _Compare, _Alloc >\fP"
.br
.RI "\fIA standard container made up of (key,value) pairs, which can be retrieved based on a key, in logarithmic time. \fP"
.ti -1c
.RI "class \fBstd::multimap< _Key, _Tp, _Compare, _Alloc >\fP"
.br
.RI "\fIA standard container made up of (key,value) pairs, which can be retrieved based on a key, in logarithmic time. \fP"
.ti -1c
.RI "class \fBstd::multiset< _Key, _Compare, _Alloc >\fP"
.br
.RI "\fIA standard container made up of elements, which can be retrieved in logarithmic time. \fP"
.ti -1c
.RI "class \fBstd::set< _Key, _Compare, _Alloc >\fP"
.br
.RI "\fIA standard container made up of unique keys, which can be retrieved in logarithmic time. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Associative containers allow fast retrieval of data based on keys.
.PP
Each container type is parameterized on a \fCKey\fP type, and an ordering relation used to sort the elements of the container.
.PP
All associative containers must meet certain requirements, summarized in \fCtables\fP. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
