.TH "bitset" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bitset \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBstd::_Base_bitset< _Nw >\fP"
.br
.ti -1c
.RI "struct \fBstd::_Base_bitset< 0 >\fP"
.br
.ti -1c
.RI "struct \fBstd::_Base_bitset< 1 >\fP"
.br
.ti -1c
.RI "class \fBstd::bitset< _Nb >\fP"
.br
.RI "\fIThe bitset class represents a \fIfixed-size\fP sequence of bits. \fP"
.ti -1c
.RI "class \fBstd::bitset< _Nb >::bitset::reference\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBstd\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB_GLIBCXX_BITSET\fP"
.br
.ti -1c
.RI "#define \fB_GLIBCXX_BITSET_BITS_PER_WORD\fP"
.br
.ti -1c
.RI "#define \fB_GLIBCXX_BITSET_WORDS\fP(__n)"
.br
.in -1c
.SS "Functions"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "template<size_t _Nb> bitset< _Nb > \fBstd::operator&\fP (const bitset< _Nb > &__x, const bitset< _Nb > &__y)"
.br
.ti -1c
.RI "template<size_t _Nb> bitset< _Nb > \fBstd::operator^\fP (const bitset< _Nb > &__x, const bitset< _Nb > &__y)"
.br
.ti -1c
.RI "template<size_t _Nb> bitset< _Nb > \fBstd::operator|\fP (const bitset< _Nb > &__x, const bitset< _Nb > &__y)"
.br
.in -1c
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "template<class _CharT , class _Traits , size_t _Nb> \fBstd::basic_ostream\fP< _CharT, _Traits > & \fBstd::operator<<\fP (\fBstd::basic_ostream\fP< _CharT, _Traits > &__os, const bitset< _Nb > &__x)"
.br
.ti -1c
.RI "template<class _CharT , class _Traits , size_t _Nb> \fBstd::basic_istream\fP< _CharT, _Traits > & \fBstd::operator>>\fP (\fBstd::basic_istream\fP< _CharT, _Traits > &__is, bitset< _Nb > &__x)"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
This is a Standard C++ Library header. 
.PP
Definition in file \fBbitset\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
