.TH "cfloat" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cfloat \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB_GLIBCXX_CFLOAT\fP"
.br
.ti -1c
.RI "#define \fBDECIMAL_DIG\fP"
.br
.ti -1c
.RI "#define \fBFLT_EVAL_METHOD\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is a Standard C++ Library file. You should \fCinclude\fP this file in your programs, rather than any of the '*.h' implementation files.
.PP
This is the C++ version of the Standard C Library header \fC\fBfloat.h\fP\fP, and its contents are (mostly) the same as that header, but are all contained in the namespace \fC\fBstd\fP\fP (except for names which are defined as macros in C). 
.PP
Definition in file \fBcfloat\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
