Complex Numbers
NAME
Complex Numbers -
Classes
struct std::complex< _Tp >
Functions
template<typename _Tp > _Tp std::__complex_abs (const complex< _Tp > &__z)
template<typename _Tp > std::complex< _Tp > std::__complex_acos (const std::complex< _Tp > &__z)
template<typename _Tp > std::complex< _Tp > std::__complex_acosh (const std::complex< _Tp > &__z)
template<typename _Tp > _Tp std::__complex_arg (const complex< _Tp > &__z)
template<typename _Tp > std::complex< _Tp > std::__complex_asin (const std::complex< _Tp > &__z)
template<typename _Tp > std::complex< _Tp > std::__complex_asinh (const std::complex< _Tp > &__z)
template<typename _Tp > std::complex< _Tp > std::__complex_atan (const std::complex< _Tp > &__z)
template<typename _Tp > std::complex< _Tp > std::__complex_atanh (const std::complex< _Tp > &__z)
template<typename _Tp > complex< _Tp > std::__complex_cos (const complex< _Tp > &__z)
template<typename _Tp > complex< _Tp > std::__complex_cosh (const complex< _Tp > &__z)
template<typename _Tp > complex< _Tp > std::__complex_exp (const complex< _Tp > &__z)
template<typename _Tp > complex< _Tp > std::__complex_log (const complex< _Tp > &__z)
template<typename _Tp > complex< _Tp > std::__complex_pow (const complex< _Tp > &__x, const complex< _Tp > &__y)
template<typename _Tp > complex< _Tp > std::__complex_sin (const complex< _Tp > &__z)
template<typename _Tp > complex< _Tp > std::__complex_sinh (const complex< _Tp > &__z)
template<typename _Tp > complex< _Tp > std::__complex_sqrt (const complex< _Tp > &__z)
template<typename _Tp > complex< _Tp > std::__complex_tan (const complex< _Tp > &__z)
template<typename _Tp > complex< _Tp > std::__complex_tanh (const complex< _Tp > &__z)
template<typename _Tp > _Tp std::abs (const complex< _Tp > &)
template<typename _Tp > std::complex< _Tp > std::acos (const std::complex< _Tp > &__z)
template<typename _Tp > std::complex< _Tp > std::acosh (const std::complex< _Tp > &__z)
template<typename _Tp > __gnu_cxx::__promote< _Tp >::__type std::arg (_Tp __x)
template<typename _Tp > _Tp std::arg (const complex< _Tp > &)
template<typename _Tp > std::complex< _Tp > std::asin (const std::complex< _Tp > &__z)
template<typename _Tp > std::complex< _Tp > std::asinh (const std::complex< _Tp > &__z)
template<typename _Tp > std::complex< _Tp > std::atan (const std::complex< _Tp > &__z)
template<typename _Tp > std::complex< _Tp > std::atanh (const std::complex< _Tp > &__z)
std::complex< double >::complex (const complex< long double > &)
std::complex< float >::complex (const complex< long double > &)
std::complex< float >::complex (const complex< double > &)
template<typename _Tp > std::complex< typename __gnu_cxx::__promote< _Tp >::__type > std::conj (_Tp __x)
template<typename _Tp > complex< _Tp > std::conj (const complex< _Tp > &)
template<typename _Tp > complex< _Tp > std::cos (const complex< _Tp > &)
template<typename _Tp > complex< _Tp > std::cosh (const complex< _Tp > &)
template<typename _Tp > complex< _Tp > std::exp (const complex< _Tp > &)
template<typename _Tp > _Tp std::fabs (const std::complex< _Tp > &__z)
template<typename _Tp > __gnu_cxx::__promote< _Tp >::__type std::imag (_Tp)
template<typename _Tp > _Tp std::imag (const complex< _Tp > &__z)
template<typename _Tp > complex< _Tp > std::log (const complex< _Tp > &)
template<typename _Tp > complex< _Tp > std::log10 (const complex< _Tp > &)
template<typename _Tp > __gnu_cxx::__promote< _Tp >::__type std::norm (_Tp __x)
template<typename _Tp > _Tp std::norm (const complex< _Tp > &)
template<typename _Up > complex< _Tp > & std::complex::operator*= (const complex< _Up > &)
complex< _Tp > & std::complex::operator*= (const _Tp &)
template<typename _Tp > complex< _Tp > std::operator+ (const complex< _Tp > &__x)
template<typename _Up > complex< _Tp > & std::complex::operator+= (const complex< _Up > &)
template<typename _Tp > complex< _Tp > std::operator- (const complex< _Tp > &__x)
template<typename _Up > complex< _Tp > & std::complex::operator-= (const complex< _Up > &)
template<typename _Up > complex< _Tp > & std::complex::operator/= (const complex< _Up > &)
complex< _Tp > & std::complex::operator/= (const _Tp &)
template<typename _Tp , typename _CharT , class _Traits > basic_ostream< _CharT, _Traits > & std::operator<< (basic_ostream< _CharT, _Traits > &__os, const complex< _Tp > &__x)
template<typename _Up > complex< _Tp > & std::complex::operator= (const complex< _Up > &)
complex< _Tp > & std::complex::operator= (const _Tp &)
template<typename _Tp , typename _CharT , class _Traits > basic_istream< _CharT, _Traits > & std::operator>> (basic_istream< _CharT, _Traits > &__is, complex< _Tp > &__x)
template<typename _Tp > complex< _Tp > std::polar (const _Tp &, const _Tp &=0)
template<typename _Tp , typename _Up > std::complex< typename __gnu_cxx::__promote_2< _Tp, _Up >::__type > std::pow (const std::complex< _Tp > &__x, const std::complex< _Up > &__y)
template<typename _Tp , typename _Up > std::complex< typename __gnu_cxx::__promote_2< _Tp, _Up >::__type > std::pow (const _Tp &__x, const std::complex< _Up > &__y)
template<typename _Tp , typename _Up > std::complex< typename __gnu_cxx::__promote_2< _Tp, _Up >::__type > std::pow (const std::complex< _Tp > &__x, const _Up &__y)
template<typename _Tp > complex< _Tp > std::pow (const _Tp &, const complex< _Tp > &)
template<typename _Tp > complex< _Tp > std::pow (const complex< _Tp > &, const complex< _Tp > &)
template<typename _Tp > complex< _Tp > std::pow (const complex< _Tp > &, const _Tp &)
template<typename _Tp > __gnu_cxx::__promote< _Tp >::__type std::real (_Tp __x)
template<typename _Tp > _Tp std::real (const complex< _Tp > &__z)
template<typename _Tp > complex< _Tp > std::sin (const complex< _Tp > &)
template<typename _Tp > complex< _Tp > std::sinh (const complex< _Tp > &)
template<typename _Tp > complex< _Tp > std::sqrt (const complex< _Tp > &)
template<typename _Tp > complex< _Tp > std::tan (const complex< _Tp > &)
template<typename _Tp > complex< _Tp > std::tanh (const complex< _Tp > &)
template<typename _Tp > bool std::operator!= (const _Tp &__x, const complex< _Tp > &__y)
template<typename _Tp > bool std::operator!= (const complex< _Tp > &__x, const _Tp &__y)
template<typename _Tp > bool std::operator!= (const complex< _Tp > &__x, const complex< _Tp > &__y)
template<typename _Tp > complex< _Tp > std::operator* (const _Tp &__x, const complex< _Tp > &__y)
template<typename _Tp > complex< _Tp > std::operator* (const complex< _Tp > &__x, const _Tp &__y)
template<typename _Tp > complex< _Tp > std::operator* (const complex< _Tp > &__x, const complex< _Tp > &__y)
template<typename _Tp > complex< _Tp > std::operator+ (const _Tp &__x, const complex< _Tp > &__y)
template<typename _Tp > complex< _Tp > std::operator+ (const complex< _Tp > &__x, const _Tp &__y)
template<typename _Tp > complex< _Tp > std::operator+ (const complex< _Tp > &__x, const complex< _Tp > &__y)
template<typename _Tp > complex< _Tp > std::operator- (const _Tp &__x, const complex< _Tp > &__y)
template<typename _Tp > complex< _Tp > std::operator- (const complex< _Tp > &__x, const _Tp &__y)
template<typename _Tp > complex< _Tp > std::operator- (const complex< _Tp > &__x, const complex< _Tp > &__y)
template<typename _Tp > complex< _Tp > std::operator/ (const _Tp &__x, const complex< _Tp > &__y)
template<typename _Tp > complex< _Tp > std::operator/ (const complex< _Tp > &__x, const _Tp &__y)
template<typename _Tp > complex< _Tp > std::operator/ (const complex< _Tp > &__x, const complex< _Tp > &__y)
template<typename _Tp > bool std::operator== (const _Tp &__x, const complex< _Tp > &__y)
template<typename _Tp > bool std::operator== (const complex< _Tp > &__x, const _Tp &__y)
template<typename _Tp > bool std::operator== (const complex< _Tp > &__x, const complex< _Tp > &__y)
Detailed Description
Classes and functions for complex numbers.
Function Documentation
template<typename _Tp > _Tp std::abs (const complex< _Tp > & __z) [inline]
Return magnitude of z.
Definition at line 594 of file complex.
Referenced by std::tr1::__detail::__airy(), std::tr1::__detail::__bessel_ik(), std::tr1::__detail::__bessel_jn(), std::tr1::__detail::__comp_ellint_1(), std::tr1::__detail::__comp_ellint_2(), std::tr1::__detail::__comp_ellint_3(), std::tr1::__detail::__conf_hyperg_luke(), std::tr1::__detail::__conf_hyperg_series(), std::tr1::__detail::__cyl_bessel_ij_series(), std::tr1::__detail::__ellint_1(), std::tr1::__detail::__ellint_2(), std::tr1::__detail::__ellint_3(), std::tr1::__detail::__ellint_rc(), std::tr1::__detail::__ellint_rd(), std::tr1::__detail::__ellint_rf(), std::tr1::__detail::__ellint_rj(), std::tr1::__detail::__expint_asymp(), std::tr1::__detail::__expint_E1_asymp(), std::tr1::__detail::__expint_E1_series(), std::tr1::__detail::__expint_En_cont_frac(), std::tr1::__detail::__expint_En_series(), std::tr1::__detail::__expint_large_n(), std::tr1::__detail::__gamma_temme(), std::tr1::__detail::__hurwitz_zeta_glob(), std::tr1::__detail::__hyperg(), std::tr1::__detail::__hyperg_luke(), std::tr1::__detail::__hyperg_reflect(), std::tr1::__detail::__hyperg_series(), std::tr1::__detail::__log_gamma(), std::tr1::__detail::__poly_laguerre_hyperg(), std::tr1::__detail::__psi(), std::tr1::__detail::__psi_asymp(), std::tr1::__detail::__psi_series(), std::tr1::__detail::__riemann_zeta_alt(), std::tr1::__detail::__riemann_zeta_glob(), std::fabs(), std::binomial_distribution< _IntType, _RealType >::operator()(), and std::poisson_distribution< _IntType, _RealType >::operator()().
template<typename _Tp > std::complex< _Tp > std::acos (const std::complex< _Tp > & __z) [inline]
acos(__z) [8.1.2].
Definition at line 86 of file tr1_impl/complex.
template<typename _Tp > std::complex< _Tp > std::acosh (const std::complex< _Tp > & __z) [inline]
acosh(__z) [8.1.5].
Definition at line 205 of file tr1_impl/complex.
template<typename _Tp > __gnu_cxx::__promote<_Tp>::__type std::arg (_Tp __x) [inline]
Additional overloads [8.1.9].
Definition at line 311 of file tr1_impl/complex.
References std::arg().
template<typename _Tp > _Tp std::arg (const complex< _Tp > & __z) [inline]
Return phase angle of z.
Definition at line 621 of file complex.
Referenced by std::arg().
template<typename _Tp > std::complex< _Tp > std::asin (const std::complex< _Tp > & __z) [inline]
asin(__z) [8.1.3].
Definition at line 122 of file tr1_impl/complex.
template<typename _Tp > std::complex< _Tp > std::asinh (const std::complex< _Tp > & __z) [inline]
asinh(__z) [8.1.6].
Definition at line 244 of file tr1_impl/complex.
template<typename _Tp > std::complex< _Tp > std::atan (const std::complex< _Tp > & __z) [inline]
atan(__z) [8.1.4].
Definition at line 166 of file tr1_impl/complex.
template<typename _Tp > std::complex< _Tp > std::atanh (const std::complex< _Tp > & __z) [inline]
atanh(__z) [8.1.7].
Definition at line 288 of file tr1_impl/complex.
template<typename _Tp > complex< _Tp > std::conj (const complex< _Tp > & __z) [inline]
Return complex conjugate of z.
Definition at line 667 of file complex.
References std::complex< _Tp >::imag(), and std::complex< _Tp >::real().
template<typename _Tp > complex< _Tp > std::cos (const complex< _Tp > & __z) [inline]
Return complex cosine of z.
Definition at line 699 of file complex.
Referenced by std::tr1::__detail::__cyl_bessel_jn_asymp(), std::tr1::__detail::__ellint_1(), std::tr1::__detail::__ellint_2(), std::tr1::__detail::__ellint_3(), std::tr1::__detail::__psi(), std::tr1::__detail::__sph_legendre(), and std::polar().
template<typename _Tp > complex< _Tp > std::cosh (const complex< _Tp > & __z) [inline]
Return complex hyperbolic cosine of z.
Definition at line 729 of file complex.
Referenced by std::tr1::__detail::__bessel_ik(), and std::tr1::__detail::__bessel_jn().
template<typename _Tp > complex< _Tp > std::exp (const complex< _Tp > & __z) [inline]
Return complex base e exponential of z.
Definition at line 755 of file complex.
Referenced by std::tr1::__detail::__bessel_ik(), std::tr1::__detail::__bessel_jn(), std::tr1::__detail::__beta_lgamma(), std::tr1::__detail::__bincoef(), std::tr1::__detail::__conf_hyperg(), std::tr1::__detail::__cyl_bessel_ij_series(), std::tr1::__detail::__expint(), std::tr1::__detail::__expint_asymp(), std::tr1::__detail::__expint_E1_asymp(), std::tr1::__detail::__expint_Ei_asymp(), std::tr1::__detail::__expint_En_cont_frac(), std::tr1::__detail::__expint_En_recursion(), std::tr1::__detail::__expint_large_n(), std::tr1::__detail::__gamma(), std::tr1::__detail::__hurwitz_zeta_glob(), std::tr1::__detail::__hyperg_reflect(), std::tr1::__detail::__poly_laguerre_large_n(), std::tr1::__detail::__psi(), std::tr1::__detail::__riemann_zeta(), std::tr1::__detail::__riemann_zeta_glob(), std::tr1::__detail::__sph_legendre(), std::gamma_distribution< _RealType >::operator()(), and std::pow().
template<typename _Tp > _Tp std::fabs (const std::complex< _Tp > & __z) [inline]
fabs(__z) [8.1.8].
Definition at line 301 of file tr1_impl/complex.
References std::abs().
template<typename _Tp > complex< _Tp > std::log (const complex< _Tp > & __z) [inline]
Return complex natural logarithm of z.
Definition at line 782 of file complex.
Referenced by std::tr1::__detail::__bessel_ik(), std::tr1::__detail::__bessel_jn(), std::tr1::__detail::__bincoef(), std::tr1::__detail::__cyl_bessel_ij_series(), std::tr1::__detail::__expint_E1_series(), std::tr1::__detail::__expint_Ei(), std::tr1::__detail::__expint_Ei_series(), std::tr1::__detail::__expint_En_series(), std::tr1::__detail::__hurwitz_zeta_glob(), std::tr1::__detail::__hyperg_reflect(), std::tr1::__detail::__log_bincoef(), std::tr1::__detail::__log_gamma(), std::tr1::__detail::__log_gamma_bernoulli(), std::tr1::__detail::__log_gamma_lanczos(), std::tr1::__detail::__poly_laguerre_large_n(), std::tr1::__detail::__psi_asymp(), std::tr1::__detail::__riemann_zeta_glob(), std::tr1::__detail::__sph_legendre(), std::log10(), std::gamma_distribution< _RealType >::operator()(), std::normal_distribution< _RealType >::operator()(), std::binomial_distribution< _IntType, _RealType >::operator()(), std::poisson_distribution< _IntType, _RealType >::operator()(), and std::pow().
template<typename _Tp > complex< _Tp > std::log10 (const complex< _Tp > & __z) [inline]
Return complex base 10 logarithm of z.
Definition at line 787 of file complex.
References std::log().
template<typename _Tp > _Tp std::norm (const complex< _Tp > & __z) [inline]
Return z magnitude squared.
Definition at line 654 of file complex.
Referenced by std::complex< _Tp >::operator/=().
template<typename _Tp > bool std::operator!= (const _Tp & __x, const complex< _Tp > & __y) [inline]
Return false if x is equal to y.
Definition at line 479 of file complex.
References std::complex< _Tp >::imag(), and std::complex< _Tp >::real().
template<typename _Tp > bool std::operator!= (const complex< _Tp > & __x, const _Tp & __y) [inline]
Return false if x is equal to y.
Definition at line 474 of file complex.
References std::complex< _Tp >::imag(), and std::complex< _Tp >::real().
template<typename _Tp > bool std::operator!= (const complex< _Tp > & __x, const complex< _Tp > & __y) [inline]
Return false if x is equal to y.
Definition at line 469 of file complex.
References std::complex< _Tp >::imag(), and std::complex< _Tp >::real().
template<typename _Tp > complex<_Tp> std::operator* (const _Tp & __x, const complex< _Tp > & __y) [inline]
Return new complex value x times y.
Definition at line 397 of file complex.
template<typename _Tp > complex<_Tp> std::operator* (const complex< _Tp > & __x, const _Tp & __y) [inline]
Return new complex value x times y.
Definition at line 388 of file complex.
template<typename _Tp > complex<_Tp> std::operator* (const complex< _Tp > & __x, const complex< _Tp > & __y) [inline]
Return new complex value x times y.
Definition at line 379 of file complex.
Referenced by std::ostreambuf_iterator< _CharT, _Traits >::operator*(), std::istreambuf_iterator< _CharT, _Traits >::operator*(), std::insert_iterator< _Container >::operator*(), std::front_insert_iterator< _Container >::operator*(), std::back_insert_iterator< _Container >::operator*(), std::reverse_iterator< _Iterator >::operator*(), std::auto_ptr< _Tp >::operator*(), and std::reverse_iterator< _Iterator >::operator->().
template<typename _Tp > template<typename _Up > complex< _Tp > & std::complex< _Tp >::operator*= (const complex< _Up > & __z) [inline, inherited]
Multiply this complex number by z.
Definition at line 292 of file complex.
References std::complex< _Tp >::imag(), and std::complex< _Tp >::real().
template<typename _Tp > complex< _Tp > & std::complex< _Tp >::operator*= (const _Tp & __t) [inline, inherited]
Multiply this complex number by t.
Definition at line 238 of file complex.
template<typename _Tp > complex<_Tp> std::operator+ (const complex< _Tp > & __x) [inline]
Return x.
Definition at line 438 of file complex.
template<typename _Tp > complex<_Tp> std::operator+ (const _Tp & __x, const complex< _Tp > & __y) [inline]
Return new complex value x plus y.
Definition at line 337 of file complex.
template<typename _Tp > complex<_Tp> std::operator+ (const complex< _Tp > & __x, const _Tp & __y) [inline]
Return new complex value x plus y.
Definition at line 328 of file complex.
template<typename _Tp > complex<_Tp> std::operator+ (const complex< _Tp > & __x, const complex< _Tp > & __y) [inline]
Return new complex value x plus y.
Definition at line 319 of file complex.
template<typename _Tp > template<typename _Up > complex< _Tp > & std::complex< _Tp >::operator+= (const complex< _Up > & __z) [inline, inherited]
Add z to this complex number.
Definition at line 269 of file complex.
References std::complex< _Tp >::imag(), and std::complex< _Tp >::real().
template<typename _Tp > complex<_Tp> std::operator- (const complex< _Tp > & __x) [inline]
Return complex negation of x.
Definition at line 444 of file complex.
References std::complex< _Tp >::imag(), and std::complex< _Tp >::real().
template<typename _Tp > complex<_Tp> std::operator- (const _Tp & __x, const complex< _Tp > & __y) [inline]
Return new complex value x minus y.
Definition at line 367 of file complex.
References std::complex< _Tp >::imag(), and std::complex< _Tp >::real().
template<typename _Tp > complex<_Tp> std::operator- (const complex< _Tp > & __x, const _Tp & __y) [inline]
Return new complex value x minus y.
Definition at line 358 of file complex.
template<typename _Tp > complex<_Tp> std::operator- (const complex< _Tp > & __x, const complex< _Tp > & __y) [inline]
Return new complex value x minus y.
Definition at line 349 of file complex.
Referenced by std::operator-(), std::reverse_iterator< _Iterator >::operator-(), and std::fpos< _StateT >::operator-().
template<typename _Tp > template<typename _Up > complex< _Tp > & std::complex< _Tp >::operator-= (const complex< _Up > & __z) [inline, inherited]
Subtract z from this complex number.
Definition at line 280 of file complex.
References std::complex< _Tp >::imag(), and std::complex< _Tp >::real().
template<typename _Tp > complex<_Tp> std::operator/ (const _Tp & __x, const complex< _Tp > & __y) [inline]
Return new complex value x divided by y.
Definition at line 427 of file complex.
template<typename _Tp > complex<_Tp> std::operator/ (const complex< _Tp > & __x, const _Tp & __y) [inline]
Return new complex value x divided by y.
Definition at line 418 of file complex.
template<typename _Tp > complex<_Tp> std::operator/ (const complex< _Tp > & __x, const complex< _Tp > & __y) [inline]
Return new complex value x divided by y.
Definition at line 409 of file complex.
template<typename _Tp > template<typename _Up > complex< _Tp > & std::complex< _Tp >::operator/= (const complex< _Up > & __z) [inline, inherited]
Divide this complex number by z.
Definition at line 305 of file complex.
References std::complex< _Tp >::imag(), std::norm(), and std::complex< _Tp >::real().
template<typename _Tp > complex< _Tp > & std::complex< _Tp >::operator/= (const _Tp & __t) [inline, inherited]
Divide this complex number by t.
Definition at line 248 of file complex.
template<typename _Tp , typename _CharT , class _Traits > basic_ostream<_CharT, _Traits>& std::operator<< (basic_ostream< _CharT, _Traits > & __os, const complex< _Tp > & __x) [inline]
Insertion operator for complex values.
Definition at line 519 of file complex.
References std::ios_base::flags(), std::basic_ios< _CharT, _Traits >::imbue(), std::ios_base::precision(), and std::basic_ostringstream< _CharT, _Traits, _Alloc >::str().
template<typename _Tp > template<typename _Up > complex< _Tp > & std::complex< _Tp >::operator= (const complex< _Up > & __z) [inline, inherited]
Assign this complex number to complex z.
Definition at line 258 of file complex.
References std::complex< _Tp >::imag(), and std::complex< _Tp >::real().
template<typename _Tp > complex< _Tp > & std::complex< _Tp >::operator= (const _Tp & __t) [inline, inherited]
Assign this complex number to scalar t.
Definition at line 228 of file complex.
template<typename _Tp > bool std::operator== (const _Tp & __x, const complex< _Tp > & __y) [inline]
Return true if x is equal to y.
Definition at line 461 of file complex.
References std::complex< _Tp >::imag(), and std::complex< _Tp >::real().
template<typename _Tp > bool std::operator== (const complex< _Tp > & __x, const _Tp & __y) [inline]
Return true if x is equal to y.
Definition at line 456 of file complex.
References std::complex< _Tp >::imag(), and std::complex< _Tp >::real().
template<typename _Tp > bool std::operator== (const complex< _Tp > & __x, const complex< _Tp > & __y) [inline]
Return true if x is equal to y.
Definition at line 451 of file complex.
References std::complex< _Tp >::imag(), and std::complex< _Tp >::real().
template<typename _Tp , typename _CharT , class _Traits > basic_istream<_CharT, _Traits>& std::operator>> (basic_istream< _CharT, _Traits > & __is, complex< _Tp > & __x) [inline]
Extraction operator for complex values.
Definition at line 486 of file complex.
References std::ios_base::failbit, std::basic_istream< _CharT, _Traits >::putback(), and std::basic_ios< _CharT, _Traits >::setstate().
template<typename _Tp > complex< _Tp > std::polar (const _Tp & __rho, const _Tp & __theta = 0) [inline]
Return complex with magnitude rho and angle theta.
Definition at line 662 of file complex.
References std::cos(), and std::sin().
Referenced by std::pow().
template<typename _Tp > complex< _Tp > std::pow (const _Tp & __x, const complex< _Tp > & __y) [inline]
Return x to the y'th power.
Definition at line 1009 of file complex.
References std::complex< _Tp >::imag(), std::log(), std::polar(), std::pow(), and std::complex< _Tp >::real().
template<typename _Tp > complex< _Tp > std::pow (const complex< _Tp > & __x, const complex< _Tp > & __y) [inline]
Return x to the y'th power.
Definition at line 1003 of file complex.
References std::pow().
template<typename _Tp > complex< _Tp > std::pow (const complex< _Tp > & __x, const _Tp & __y) [inline]
Return x to the y'th power.
Definition at line 964 of file complex.
References std::exp(), std::complex< _Tp >::imag(), std::log(), std::polar(), std::pow(), and std::complex< _Tp >::real().
Referenced by std::tr1::__detail::__bernoulli_series(), std::tr1::__detail::__conf_hyperg_luke(), std::tr1::__detail::__ellint_rc(), std::tr1::__detail::__ellint_rd(), std::tr1::__detail::__ellint_rf(), std::tr1::__detail::__ellint_rj(), std::tr1::__detail::__hurwitz_zeta_glob(), std::tr1::__detail::__hyperg(), std::tr1::__detail::__hyperg_luke(), std::tr1::__detail::__riemann_zeta(), std::tr1::__detail::__riemann_zeta_alt(), std::tr1::__detail::__riemann_zeta_glob(), std::tr1::__detail::__riemann_zeta_product(), std::tr1::__detail::__riemann_zeta_sum(), std::gamma_distribution< _RealType >::operator()(), std::tr1::pow(), and std::pow().
template<typename _Tp > complex< _Tp > std::sin (const complex< _Tp > & __z) [inline]
Return complex sine of z.
Definition at line 817 of file complex.
Referenced by std::tr1::__detail::__bessel_ik(), std::tr1::__detail::__bessel_jn(), std::tr1::__detail::__cyl_bessel_jn_asymp(), std::tr1::__detail::__ellint_1(), std::tr1::__detail::__ellint_2(), std::tr1::__detail::__ellint_3(), std::tr1::__detail::__log_gamma(), std::tr1::__detail::__log_gamma_sign(), std::tr1::__detail::__poly_laguerre_large_n(), std::tr1::__detail::__psi(), std::tr1::__detail::__riemann_zeta(), std::tr1::__detail::__riemann_zeta_glob(), and std::polar().
template<typename _Tp > complex< _Tp > std::sinh (const complex< _Tp > & __z) [inline]
Return complex hyperbolic sine of z.
Definition at line 847 of file complex.
Referenced by std::tr1::__detail::__bessel_ik(), and std::tr1::__detail::__bessel_jn().
template<typename _Tp > complex< _Tp > std::sqrt (const complex< _Tp > & __z) [inline]
Return complex square root of z.
Definition at line 891 of file complex.
Referenced by std::tr1::__detail::__airy(), std::tr1::__detail::__assoc_legendre_p(), std::tr1::__detail::__bessel_ik(), std::tr1::__detail::__bessel_jn(), std::tr1::__detail::__cyl_bessel_jn_asymp(), std::tr1::__detail::__ellint_rc(), std::tr1::__detail::__ellint_rd(), std::tr1::__detail::__ellint_rf(), std::tr1::__detail::__ellint_rj(), std::tr1::__detail::__poly_laguerre_large_n(), std::tr1::__detail::__sph_bessel_ik(), std::tr1::__detail::__sph_bessel_jn(), std::tr1::__detail::__sph_legendre(), and std::normal_distribution< _RealType >::operator()().
template<typename _Tp > complex< _Tp > std::tan (const complex< _Tp > & __z) [inline]
Return complex tangent of z.
Definition at line 918 of file complex.
template<typename _Tp > complex< _Tp > std::tanh (const complex< _Tp > & __z) [inline]
Return complex hyperbolic tangent of z.
Definition at line 946 of file complex.
Author
Generated automatically by Doxygen for libstdc++ from the source code.