.TH "Comparison Classes" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Comparison Classes \- 
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBstd::equal_to< _Tp >\fP"
.br
.RI "\fIOne of the \fBcomparison functors\fP. \fP"
.ti -1c
.RI "struct \fBstd::greater< _Tp >\fP"
.br
.RI "\fIOne of the \fBcomparison functors\fP. \fP"
.ti -1c
.RI "struct \fBstd::greater_equal< _Tp >\fP"
.br
.RI "\fIOne of the \fBcomparison functors\fP. \fP"
.ti -1c
.RI "struct \fBstd::less< _Tp >\fP"
.br
.RI "\fIOne of the \fBcomparison functors\fP. \fP"
.ti -1c
.RI "struct \fBstd::less_equal< _Tp >\fP"
.br
.RI "\fIOne of the \fBcomparison functors\fP. \fP"
.ti -1c
.RI "struct \fBstd::not_equal_to< _Tp >\fP"
.br
.RI "\fIOne of the \fBcomparison functors\fP. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The library provides six wrapper functors for all the basic comparisons in C++, like \fC<\fP. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
