.TH "condition_variable" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
condition_variable \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBstd::condition_variable\fP"
.br
.RI "\fI\fBcondition_variable\fP \fP"
.ti -1c
.RI "class \fBstd::condition_variable_any\fP"
.br
.RI "\fI\fBcondition_variable_any\fP \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBstd\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB_GLIBCXX_CONDITION_VARIABLE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is a Standard C++ Library header. 
.PP
Definition in file \fBcondition_variable\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
