.TH "exception" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
exception \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBstd::bad_exception\fP"
.br
.ti -1c
.RI "class \fBstd::exception\fP"
.br
.RI "\fIBase class for all library exceptions. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fB__gnu_cxx\fP"
.br
.ti -1c
.RI "namespace \fBstd\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void(* \fBstd::terminate_handler\fP )()"
.br
.ti -1c
.RI "typedef void(* \fBstd::unexpected_handler\fP )()"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fB__gnu_cxx::__verbose_terminate_handler\fP ()"
.br
.ti -1c
.RI "terminate_handler \fBstd::set_terminate\fP (terminate_handler)  throw ()"
.br
.ti -1c
.RI "unexpected_handler \fBstd::set_unexpected\fP (unexpected_handler)  throw ()"
.br
.ti -1c
.RI "void \fBstd::terminate\fP () __attribute__((__noreturn__))"
.br
.ti -1c
.RI "bool \fBstd::uncaught_exception\fP ()  throw ()"
.br
.ti -1c
.RI "void \fBstd::unexpected\fP () __attribute__((__noreturn__))"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is a Standard C++ Library header. 
.PP
Definition in file \fBexception\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
