.TH "Extensions" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Extensions \- 
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBSGI STL extensions\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Components generally useful that are not part of any standard. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
