.TH "hash_map" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hash_map \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB__gnu_cxx::hash_map< _Key, _Tp, _HashFn, _EqualKey, _Alloc >\fP"
.br
.ti -1c
.RI "class \fB__gnu_cxx::hash_multimap< _Key, _Tp, _HashFn, _EqualKey, _Alloc >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fB__gnu_cxx\fP"
.br
.ti -1c
.RI "namespace \fBstd\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB_HASH_MAP\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<class _Key , class _Tp , class _HF , class _EqKey , class _Alloc > bool \fB__gnu_cxx::operator!=\fP (const hash_multimap< _Key, _Tp, _HF, _EqKey, _Alloc > &__hm1, const hash_multimap< _Key, _Tp, _HF, _EqKey, _Alloc > &__hm2)"
.br
.ti -1c
.RI "template<class _Key , class _Tp , class _HashFn , class _EqlKey , class _Alloc > bool \fB__gnu_cxx::operator!=\fP (const hash_map< _Key, _Tp, _HashFn, _EqlKey, _Alloc > &__hm1, const hash_map< _Key, _Tp, _HashFn, _EqlKey, _Alloc > &__hm2)"
.br
.ti -1c
.RI "template<class _Key , class _Tp , class _HF , class _EqKey , class _Alloc > bool \fB__gnu_cxx::operator==\fP (const hash_multimap< _Key, _Tp, _HF, _EqKey, _Alloc > &__hm1, const hash_multimap< _Key, _Tp, _HF, _EqKey, _Alloc > &__hm2)"
.br
.ti -1c
.RI "template<class _Key , class _Tp , class _HashFn , class _EqlKey , class _Alloc > bool \fB__gnu_cxx::operator==\fP (const hash_map< _Key, _Tp, _HashFn, _EqlKey, _Alloc > &__hm1, const hash_map< _Key, _Tp, _HashFn, _EqlKey, _Alloc > &__hm2)"
.br
.ti -1c
.RI "template<class _Key , class _Tp , class _HashFn , class _EqlKey , class _Alloc > void \fB__gnu_cxx::swap\fP (hash_multimap< _Key, _Tp, _HashFn, _EqlKey, _Alloc > &__hm1, hash_multimap< _Key, _Tp, _HashFn, _EqlKey, _Alloc > &__hm2)"
.br
.ti -1c
.RI "template<class _Key , class _Tp , class _HashFn , class _EqlKey , class _Alloc > void \fB__gnu_cxx::swap\fP (hash_map< _Key, _Tp, _HashFn, _EqlKey, _Alloc > &__hm1, hash_map< _Key, _Tp, _HashFn, _EqlKey, _Alloc > &__hm2)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file is a GNU extension to the Standard C++ Library (possibly containing extensions from the HP/SGI STL subset). 
.PP
Definition in file \fBhash_map\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
