.TH "initializer_list" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
initializer_list \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBstd::initializer_list< _E >\fP"
.br
.RI "\fI\fBinitializer_list\fP \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBstd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is a Standard C++ Library header. 
.PP
Definition in file \fBinitializer_list\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
