.TH "iomanip" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iomanip \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBstd\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB_GLIBCXX_IOMANIP\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename _CharT , typename _Traits > basic_ostream< _CharT, _Traits > & \fBstd::operator<<\fP (basic_ostream< _CharT, _Traits > &__os, _Setw __f)"
.br
.ti -1c
.RI "template<typename _CharT , typename _Traits > basic_ostream< _CharT, _Traits > & \fBstd::operator<<\fP (basic_ostream< _CharT, _Traits > &__os, _Setprecision __f)"
.br
.ti -1c
.RI "template<typename _CharT , typename _Traits > basic_ostream< _CharT, _Traits > & \fBstd::operator<<\fP (basic_ostream< _CharT, _Traits > &__os, _Setfill< _CharT > __f)"
.br
.ti -1c
.RI "template<typename _CharT , typename _Traits > basic_ostream< _CharT, _Traits > & \fBstd::operator<<\fP (basic_ostream< _CharT, _Traits > &__os, _Setbase __f)"
.br
.ti -1c
.RI "template<typename _CharT , typename _Traits > basic_ostream< _CharT, _Traits > & \fBstd::operator<<\fP (basic_ostream< _CharT, _Traits > &__os, _Setiosflags __f)"
.br
.ti -1c
.RI "template<typename _CharT , typename _Traits > basic_ostream< _CharT, _Traits > & \fBstd::operator<<\fP (basic_ostream< _CharT, _Traits > &__os, _Resetiosflags __f)"
.br
.ti -1c
.RI "template<typename _CharT , typename _Traits > basic_istream< _CharT, _Traits > & \fBstd::operator>>\fP (basic_istream< _CharT, _Traits > &__is, _Setw __f)"
.br
.ti -1c
.RI "template<typename _CharT , typename _Traits > basic_istream< _CharT, _Traits > & \fBstd::operator>>\fP (basic_istream< _CharT, _Traits > &__is, _Setprecision __f)"
.br
.ti -1c
.RI "template<typename _CharT , typename _Traits > basic_istream< _CharT, _Traits > & \fBstd::operator>>\fP (basic_istream< _CharT, _Traits > &__is, _Setfill< _CharT > __f)"
.br
.ti -1c
.RI "template<typename _CharT , typename _Traits > basic_istream< _CharT, _Traits > & \fBstd::operator>>\fP (basic_istream< _CharT, _Traits > &__is, _Setbase __f)"
.br
.ti -1c
.RI "template<typename _CharT , typename _Traits > basic_istream< _CharT, _Traits > & \fBstd::operator>>\fP (basic_istream< _CharT, _Traits > &__is, _Setiosflags __f)"
.br
.ti -1c
.RI "template<typename _CharT , typename _Traits > basic_istream< _CharT, _Traits > & \fBstd::operator>>\fP (basic_istream< _CharT, _Traits > &__is, _Resetiosflags __f)"
.br
.ti -1c
.RI "_Resetiosflags \fBstd::resetiosflags\fP (ios_base::fmtflags __mask)"
.br
.ti -1c
.RI "_Setbase \fBstd::setbase\fP (int __base)"
.br
.ti -1c
.RI "template<typename _CharT > _Setfill< _CharT > \fBstd::setfill\fP (_CharT __c)"
.br
.ti -1c
.RI "_Setiosflags \fBstd::setiosflags\fP (ios_base::fmtflags __mask)"
.br
.ti -1c
.RI "_Setprecision \fBstd::setprecision\fP (int __n)"
.br
.ti -1c
.RI "_Setw \fBstd::setw\fP (int __n)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is a Standard C++ Library header. 
.PP
Definition in file \fBiomanip\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
