.TH "iosfwd" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iosfwd \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBstd\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB_GLIBCXX_IOSFWD\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef basic_filebuf< char > \fBstd::filebuf\fP"
.br
.ti -1c
.RI "typedef basic_fstream< char > \fBstd::fstream\fP"
.br
.ti -1c
.RI "typedef basic_ifstream< char > \fBstd::ifstream\fP"
.br
.ti -1c
.RI "typedef basic_ios< char > \fBstd::ios\fP"
.br
.ti -1c
.RI "typedef basic_iostream< char > \fBstd::iostream\fP"
.br
.ti -1c
.RI "typedef basic_istream< char > \fBstd::istream\fP"
.br
.ti -1c
.RI "typedef basic_istringstream< char > \fBstd::istringstream\fP"
.br
.ti -1c
.RI "typedef basic_ofstream< char > \fBstd::ofstream\fP"
.br
.ti -1c
.RI "typedef basic_ostream< char > \fBstd::ostream\fP"
.br
.ti -1c
.RI "typedef basic_ostringstream< char > \fBstd::ostringstream\fP"
.br
.ti -1c
.RI "typedef basic_streambuf< char > \fBstd::streambuf\fP"
.br
.ti -1c
.RI "typedef basic_stringbuf< char > \fBstd::stringbuf\fP"
.br
.ti -1c
.RI "typedef basic_stringstream< char > \fBstd::stringstream\fP"
.br
.ti -1c
.RI "typedef basic_filebuf< wchar_t > \fBstd::wfilebuf\fP"
.br
.ti -1c
.RI "typedef basic_fstream< wchar_t > \fBstd::wfstream\fP"
.br
.ti -1c
.RI "typedef basic_ifstream< wchar_t > \fBstd::wifstream\fP"
.br
.ti -1c
.RI "typedef basic_ios< wchar_t > \fBstd::wios\fP"
.br
.ti -1c
.RI "typedef basic_iostream< wchar_t > \fBstd::wiostream\fP"
.br
.ti -1c
.RI "typedef basic_istream< wchar_t > \fBstd::wistream\fP"
.br
.ti -1c
.RI "typedef basic_istringstream< wchar_t > \fBstd::wistringstream\fP"
.br
.ti -1c
.RI "typedef basic_ofstream< wchar_t > \fBstd::wofstream\fP"
.br
.ti -1c
.RI "typedef basic_ostream< wchar_t > \fBstd::wostream\fP"
.br
.ti -1c
.RI "typedef basic_ostringstream< wchar_t > \fBstd::wostringstream\fP"
.br
.ti -1c
.RI "typedef basic_streambuf< wchar_t > \fBstd::wstreambuf\fP"
.br
.ti -1c
.RI "typedef basic_stringbuf< wchar_t > \fBstd::wstringbuf\fP"
.br
.ti -1c
.RI "typedef basic_stringstream< wchar_t > \fBstd::wstringstream\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is a Standard C++ Library header. 
.PP
Definition in file \fBiosfwd\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
