.TH "iostream" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iostream \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBstd\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB_GLIBCXX_IOSTREAM\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static ios_base::Init \fBstd::__ioinit\fP"
.br
.in -1c
.PP
.RI "\fBStandard Stream Objects\fP"
.br
The <iostream> header declares the eight \fIstandard stream objects\fP. For other declarations, see http://gcc.gnu.org/onlinedocs/libstdc++/manual/bk01pt11ch24.html and the \fBI/O forward declarations \fP
.PP
They are required by default to cooperate with the global C library's \fCFILE\fP streams, and to be available during program startup and termination. For more information, see the HOWTO linked to above. 
.PP
.in +1c
.in +1c
.ti -1c
.RI "ostream \fBstd::cerr\fP"
.br
.ti -1c
.RI "istream \fBstd::cin\fP"
.br
.ti -1c
.RI "ostream \fBstd::clog\fP"
.br
.ti -1c
.RI "ostream \fBstd::cout\fP"
.br
.ti -1c
.RI "wostream \fBstd::wcerr\fP"
.br
.ti -1c
.RI "wistream \fBstd::wcin\fP"
.br
.ti -1c
.RI "wostream \fBstd::wclog\fP"
.br
.ti -1c
.RI "wostream \fBstd::wcout\fP"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
This is a Standard C++ Library header. 
.PP
Definition in file \fBiostream\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
