.TH "Boolean Operations Classes" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Boolean Operations Classes \- 
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBstd::logical_and< _Tp >\fP"
.br
.RI "\fIOne of the \fBBoolean operations functors\fP. \fP"
.ti -1c
.RI "struct \fBstd::logical_not< _Tp >\fP"
.br
.RI "\fIOne of the \fBBoolean operations functors\fP. \fP"
.ti -1c
.RI "struct \fBstd::logical_or< _Tp >\fP"
.br
.RI "\fIOne of the \fBBoolean operations functors\fP. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Here are wrapper functors for Boolean operations: \fC&&\fP, \fC||\fP, and \fC!\fP. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
