.TH "Memory" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Memory \- 
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBPointer Abstractions\fP"
.br
.ti -1c
.RI "\fBAllocators\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Components for memory allocation, deallocation, and management. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
