.TH "Type Traits" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Type Traits \- 
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBstd::__is_member_pointer_helper< _Tp >\fP"
.br
.RI "\fIis_member_pointer \fP"
.ti -1c
.RI "struct \fBstd::add_const< _Tp >\fP"
.br
.RI "\fI\fBadd_const\fP \fP"
.ti -1c
.RI "struct \fBstd::add_cv< _Tp >\fP"
.br
.RI "\fI\fBadd_cv\fP \fP"
.ti -1c
.RI "struct \fBstd::add_lvalue_reference< _Tp >\fP"
.br
.RI "\fI\fBadd_lvalue_reference\fP \fP"
.ti -1c
.RI "struct \fBstd::add_pointer< _Tp >\fP"
.br
.RI "\fI\fBadd_pointer\fP \fP"
.ti -1c
.RI "struct \fBstd::add_rvalue_reference< _Tp >\fP"
.br
.RI "\fI\fBadd_rvalue_reference\fP \fP"
.ti -1c
.RI "struct \fBstd::add_volatile< _Tp >\fP"
.br
.RI "\fI\fBadd_volatile\fP \fP"
.ti -1c
.RI "struct \fBstd::alignment_of< _Tp >\fP"
.br
.RI "\fI\fBalignment_of\fP \fP"
.ti -1c
.RI "struct \fBstd::extent< typename, _Uint >\fP"
.br
.RI "\fI\fBextent\fP \fP"
.ti -1c
.RI "struct \fBstd::has_virtual_destructor< _Tp >\fP"
.br
.RI "\fI\fBhas_virtual_destructor\fP \fP"
.ti -1c
.RI "struct \fBstd::integral_constant< _Tp, __v >\fP"
.br
.RI "\fI\fBintegral_constant\fP \fP"
.ti -1c
.RI "struct \fBstd::is_abstract< _Tp >\fP"
.br
.RI "\fI\fBis_abstract\fP \fP"
.ti -1c
.RI "struct \fBstd::is_arithmetic< _Tp >\fP"
.br
.RI "\fI\fBis_arithmetic\fP \fP"
.ti -1c
.RI "struct \fBstd::is_array< typename >\fP"
.br
.RI "\fI\fBis_array\fP \fP"
.ti -1c
.RI "struct \fBstd::is_class< _Tp >\fP"
.br
.RI "\fI\fBis_class\fP \fP"
.ti -1c
.RI "struct \fBstd::is_compound< _Tp >\fP"
.br
.RI "\fI\fBis_compound\fP \fP"
.ti -1c
.RI "struct \fBstd::is_const< typename >\fP"
.br
.RI "\fI\fBis_const\fP \fP"
.ti -1c
.RI "struct \fBstd::is_empty< _Tp >\fP"
.br
.RI "\fI\fBis_empty\fP \fP"
.ti -1c
.RI "struct \fBstd::is_enum< _Tp >\fP"
.br
.RI "\fI\fBis_enum\fP \fP"
.ti -1c
.RI "struct \fBstd::is_floating_point< _Tp >\fP"
.br
.RI "\fI\fBis_floating_point\fP \fP"
.ti -1c
.RI "struct \fBstd::is_function< typename >\fP"
.br
.RI "\fI\fBis_function\fP \fP"
.ti -1c
.RI "struct \fBstd::is_fundamental< _Tp >\fP"
.br
.RI "\fI\fBis_fundamental\fP \fP"
.ti -1c
.RI "struct \fBstd::is_integral< _Tp >\fP"
.br
.RI "\fI\fBis_integral\fP \fP"
.ti -1c
.RI "struct \fBstd::is_lvalue_reference< typename >\fP"
.br
.RI "\fI\fBis_lvalue_reference\fP \fP"
.ti -1c
.RI "struct \fBstd::is_member_function_pointer< _Tp >\fP"
.br
.RI "\fI\fBis_member_function_pointer\fP \fP"
.ti -1c
.RI "struct \fBstd::is_member_object_pointer< _Tp >\fP"
.br
.RI "\fI\fBis_member_object_pointer\fP \fP"
.ti -1c
.RI "struct \fBstd::is_object< _Tp >\fP"
.br
.RI "\fI\fBis_object\fP \fP"
.ti -1c
.RI "struct \fBstd::is_pointer< _Tp >\fP"
.br
.RI "\fI\fBis_pointer\fP \fP"
.ti -1c
.RI "struct \fBstd::is_polymorphic< _Tp >\fP"
.br
.RI "\fI\fBis_polymorphic\fP \fP"
.ti -1c
.RI "struct \fBstd::is_reference< _Tp >\fP"
.br
.RI "\fI\fBis_reference\fP \fP"
.ti -1c
.RI "struct \fBstd::is_rvalue_reference< typename >\fP"
.br
.RI "\fI\fBis_rvalue_reference\fP \fP"
.ti -1c
.RI "struct \fBstd::is_same< typename, typename >\fP"
.br
.RI "\fI\fBis_same\fP \fP"
.ti -1c
.RI "struct \fBstd::is_scalar< _Tp >\fP"
.br
.RI "\fI\fBis_scalar\fP \fP"
.ti -1c
.RI "struct \fBstd::is_union< _Tp >\fP"
.br
.RI "\fI\fBis_union\fP \fP"
.ti -1c
.RI "struct \fBstd::is_void< _Tp >\fP"
.br
.RI "\fI\fBis_void\fP \fP"
.ti -1c
.RI "struct \fBstd::is_volatile< typename >\fP"
.br
.RI "\fI\fBis_volatile\fP \fP"
.ti -1c
.RI "struct \fBstd::rank< typename >\fP"
.br
.RI "\fI\fBrank\fP \fP"
.ti -1c
.RI "struct \fBstd::remove_all_extents< _Tp >\fP"
.br
.RI "\fI\fBremove_all_extents\fP \fP"
.ti -1c
.RI "struct \fBstd::remove_const< _Tp >\fP"
.br
.RI "\fI\fBremove_const\fP \fP"
.ti -1c
.RI "struct \fBstd::remove_cv< _Tp >\fP"
.br
.RI "\fI\fBremove_cv\fP \fP"
.ti -1c
.RI "struct \fBstd::remove_extent< _Tp >\fP"
.br
.RI "\fI\fBremove_extent\fP \fP"
.ti -1c
.RI "struct \fBstd::remove_pointer< _Tp >\fP"
.br
.RI "\fI\fBremove_pointer\fP \fP"
.ti -1c
.RI "struct \fBstd::remove_reference< _Tp >\fP"
.br
.RI "\fI\fBremove_reference\fP \fP"
.ti -1c
.RI "struct \fBstd::remove_volatile< _Tp >\fP"
.br
.RI "\fI\fBremove_volatile\fP \fP"
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB_DEFINE_SPEC\fP(_Order, _Trait, _Type, _Value)"
.br
.ti -1c
.RI "#define \fB_DEFINE_SPEC_0_HELPER\fP"
.br
.ti -1c
.RI "#define \fB_DEFINE_SPEC_1_HELPER\fP"
.br
.ti -1c
.RI "#define \fB_DEFINE_SPEC_2_HELPER\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef integral_constant< bool, false > \fBstd::false_type\fP"
.br
.ti -1c
.RI "typedef integral_constant< bool, true > \fBstd::true_type\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const _Tp \fBstd::integral_constant::value\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Compile time type transformation and information. 
.SH "Typedef Documentation"
.PP 
.SS "typedef integral_constant<bool, false> \fBstd::false_type\fP"
.PP
typedef for false_type 
.PP
Definition at line 78 of file tr1_impl/type_traits.
.SS "typedef integral_constant<bool, true> \fBstd::true_type\fP"
.PP
typedef for true_type 
.PP
Definition at line 75 of file tr1_impl/type_traits.
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
