.TH "Numerics" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Numerics \- 
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBComplex Numbers\fP"
.br
.ti -1c
.RI "\fBNumeric Arrays\fP"
.br
.ti -1c
.RI "\fBMathematical Special Functions\fP"
.br
.ti -1c
.RI "\fBRandom Number Generation\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Components for performing numeric operations. Includes support for for complex number types, random number generation, numeric (n-at-a-time) arrays, generalized numeric algorithms, and special math functions. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
