.TH "ostream" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ostream \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBstd::basic_ostream< _CharT, _Traits >\fP"
.br
.RI "\fIControlling output.
.PP
This is the base class for all output streams. It provides text formatting of all builtin types, and communicates with any class derived from \fBbasic_streambuf\fP to do the actual output. \fP"
.ti -1c
.RI "class \fBstd::basic_ostream< _CharT, _Traits >::basic_ostream::sentry\fP"
.br
.RI "\fIPerforms setup work for output streams. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBstd\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB_GLIBCXX_OSTREAM\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename _CharT , typename _Traits > basic_ostream< _CharT, _Traits > & \fBstd::endl\fP (basic_ostream< _CharT, _Traits > &__os)"
.br
.ti -1c
.RI "template<typename _CharT , typename _Traits > basic_ostream< _CharT, _Traits > & \fBstd::ends\fP (basic_ostream< _CharT, _Traits > &__os)"
.br
.ti -1c
.RI "template<typename _CharT , typename _Traits > basic_ostream< _CharT, _Traits > & \fBstd::flush\fP (basic_ostream< _CharT, _Traits > &__os)"
.br
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "template<class _Traits > basic_ostream< char, _Traits > & \fBstd::operator<<\fP (basic_ostream< char, _Traits > &__out, const unsigned char *__s)"
.br
.ti -1c
.RI "template<class _Traits > basic_ostream< char, _Traits > & \fBstd::operator<<\fP (basic_ostream< char, _Traits > &__out, const signed char *__s)"
.br
.ti -1c
.RI "template<class _Traits > basic_ostream< char, _Traits > & \fBstd::operator<<\fP (basic_ostream< char, _Traits > &__out, const char *__s)"
.br
.ti -1c
.RI "template<typename _CharT , typename _Traits > basic_ostream< _CharT, _Traits > & \fBstd::operator<<\fP (basic_ostream< _CharT, _Traits > &__out, const char *__s)"
.br
.ti -1c
.RI "template<typename _CharT , typename _Traits > basic_ostream< _CharT, _Traits > & \fBstd::operator<<\fP (basic_ostream< _CharT, _Traits > &__out, const _CharT *__s)"
.br
.in -1c
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "template<class _Traits > basic_ostream< char, _Traits > & \fBstd::operator<<\fP (basic_ostream< char, _Traits > &__out, unsigned char __c)"
.br
.ti -1c
.RI "template<class _Traits > basic_ostream< char, _Traits > & \fBstd::operator<<\fP (basic_ostream< char, _Traits > &__out, signed char __c)"
.br
.ti -1c
.RI "template<class _Traits > basic_ostream< char, _Traits > & \fBstd::operator<<\fP (basic_ostream< char, _Traits > &__out, char __c)"
.br
.ti -1c
.RI "template<typename _CharT , typename _Traits > basic_ostream< _CharT, _Traits > & \fBstd::operator<<\fP (basic_ostream< _CharT, _Traits > &__out, char __c)"
.br
.ti -1c
.RI "template<typename _CharT , typename _Traits > basic_ostream< _CharT, _Traits > & \fBstd::operator<<\fP (basic_ostream< _CharT, _Traits > &__out, _CharT __c)"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
This is a Standard C++ Library header. 
.PP
Definition in file \fBostream\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
