.TH "Pointer Abstractions" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pointer Abstractions \- 
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBstd::default_delete< _Tp >\fP"
.br
.RI "\fIPrimary template, \fBdefault_delete\fP. \fP"
.ti -1c
.RI "struct \fBstd::default_delete< _Tp[]>\fP"
.br
.RI "\fISpecialization, \fBdefault_delete\fP. \fP"
.ti -1c
.RI "class \fBstd::unique_ptr< _Tp, _Tp_Deleter >\fP"
.br
.RI "\fI20.7.12.2 \fBunique_ptr\fP for single objects. \fP"
.ti -1c
.RI "class \fBstd::unique_ptr< _Tp[], _Tp_Deleter >\fP"
.br
.RI "\fI20.7.12.3 \fBunique_ptr\fP for \fBarray\fP objects with a runtime length \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename _Tp , typename _Tp_Deleter , typename _Up , typename _Up_Deleter > bool \fBstd::operator!=\fP (const unique_ptr< _Tp, _Tp_Deleter > &__x, const unique_ptr< _Up, _Up_Deleter > &__y)"
.br
.ti -1c
.RI "template<typename _Tp , typename _Tp_Deleter , typename _Up , typename _Up_Deleter > bool \fBstd::operator<\fP (const unique_ptr< _Tp, _Tp_Deleter > &__x, const unique_ptr< _Up, _Up_Deleter > &__y)"
.br
.ti -1c
.RI "template<typename _Tp , typename _Tp_Deleter , typename _Up , typename _Up_Deleter > bool \fBstd::operator<=\fP (const unique_ptr< _Tp, _Tp_Deleter > &__x, const unique_ptr< _Up, _Up_Deleter > &__y)"
.br
.ti -1c
.RI "template<typename _Tp , typename _Tp_Deleter , typename _Up , typename _Up_Deleter > bool \fBstd::operator==\fP (const unique_ptr< _Tp, _Tp_Deleter > &__x, const unique_ptr< _Up, _Up_Deleter > &__y)"
.br
.ti -1c
.RI "template<typename _Tp , typename _Tp_Deleter , typename _Up , typename _Up_Deleter > bool \fBstd::operator>\fP (const unique_ptr< _Tp, _Tp_Deleter > &__x, const unique_ptr< _Up, _Up_Deleter > &__y)"
.br
.ti -1c
.RI "template<typename _Tp , typename _Tp_Deleter , typename _Up , typename _Up_Deleter > bool \fBstd::operator>=\fP (const unique_ptr< _Tp, _Tp_Deleter > &__x, const unique_ptr< _Up, _Up_Deleter > &__y)"
.br
.ti -1c
.RI "template<typename _Tp , typename _Tp_Deleter > void \fBstd::swap\fP (unique_ptr< _Tp, _Tp_Deleter > &__x, unique_ptr< _Tp, _Tp_Deleter > &&__y)"
.br
.ti -1c
.RI "template<typename _Tp , typename _Tp_Deleter > void \fBstd::swap\fP (unique_ptr< _Tp, _Tp_Deleter > &&__x, unique_ptr< _Tp, _Tp_Deleter > &__y)"
.br
.ti -1c
.RI "template<typename _Tp , typename _Tp_Deleter > void \fBstd::swap\fP (unique_ptr< _Tp, _Tp_Deleter > &__x, unique_ptr< _Tp, _Tp_Deleter > &__y)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Components for memory allocation, deallocation, and management. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
