.TH "random" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
random \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB_GLIBCXX_RANDOM\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is a Standard C++ Library header. 
.PP
Definition in file \fBrandom\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
