.TH "Discrete Distributions" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Discrete Distributions \- 
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBstd::bernoulli_distribution\fP"
.br
.RI "\fIA Bernoulli random number distribution. \fP"
.ti -1c
.RI "class \fBstd::binomial_distribution< _IntType, _RealType >\fP"
.br
.RI "\fIA discrete binomial random number distribution. \fP"
.ti -1c
.RI "class \fBstd::geometric_distribution< _IntType, _RealType >\fP"
.br
.RI "\fIA discrete geometric random number distribution. \fP"
.ti -1c
.RI "class \fBstd::poisson_distribution< _IntType, _RealType >\fP"
.br
.RI "\fIA discrete Poisson random number distribution. \fP"
.ti -1c
.RI "class \fBstd::uniform_int< _IntType >\fP"
.br
.RI "\fIUniform discrete distribution for random numbers. A discrete random distribution on the range $[min, max]$ with equal probability throughout the range. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
