.TH "Continuous Distributions" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Continuous Distributions \- 
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBstd::exponential_distribution< _RealType >\fP"
.br
.RI "\fIAn exponential continuous distribution for random numbers. \fP"
.ti -1c
.RI "class \fBstd::gamma_distribution< _RealType >\fP"
.br
.RI "\fIA gamma continuous distribution for random numbers. \fP"
.ti -1c
.RI "class \fBstd::normal_distribution< _RealType >\fP"
.br
.RI "\fIA normal continuous distribution for random numbers. \fP"
.ti -1c
.RI "class \fBstd::uniform_real< _RealType >\fP"
.br
.RI "\fIUniform continuous distribution for random numbers. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
