.TH "Rational Arithmetic" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Rational Arithmetic \- 
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBstd::ratio< _Num, _Den >\fP"
.br
.RI "\fIProvides compile-time rational arithmetic. \fP"
.ti -1c
.RI "struct \fBstd::ratio_add< _R1, _R2 >\fP"
.br
.RI "\fI\fBratio_add\fP \fP"
.ti -1c
.RI "struct \fBstd::ratio_divide< _R1, _R2 >\fP"
.br
.RI "\fI\fBratio_divide\fP \fP"
.ti -1c
.RI "struct \fBstd::ratio_equal< _R1, _R2 >\fP"
.br
.RI "\fI\fBratio_equal\fP \fP"
.ti -1c
.RI "struct \fBstd::ratio_greater< _R1, _R2 >\fP"
.br
.RI "\fI\fBratio_greater\fP \fP"
.ti -1c
.RI "struct \fBstd::ratio_greater_equal< _R1, _R2 >\fP"
.br
.RI "\fI\fBratio_greater_equal\fP \fP"
.ti -1c
.RI "struct \fBstd::ratio_less< _R1, _R2 >\fP"
.br
.RI "\fI\fBratio_less\fP \fP"
.ti -1c
.RI "struct \fBstd::ratio_less_equal< _R1, _R2 >\fP"
.br
.RI "\fI\fBratio_less_equal\fP \fP"
.ti -1c
.RI "struct \fBstd::ratio_multiply< _R1, _R2 >\fP"
.br
.RI "\fI\fBratio_multiply\fP \fP"
.ti -1c
.RI "struct \fBstd::ratio_not_equal< _R1, _R2 >\fP"
.br
.RI "\fI\fBratio_not_equal\fP \fP"
.ti -1c
.RI "struct \fBstd::ratio_subtract< _R1, _R2 >\fP"
.br
.RI "\fI\fBratio_subtract\fP \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef ratio< 1, 1000000000000000000 > \fBstd::atto\fP"
.br
.ti -1c
.RI "typedef ratio< 1, 100 > \fBstd::centi\fP"
.br
.ti -1c
.RI "typedef ratio< 10, 1 > \fBstd::deca\fP"
.br
.ti -1c
.RI "typedef ratio< 1, 10 > \fBstd::deci\fP"
.br
.ti -1c
.RI "typedef ratio< 1000000000000000000, 1 > \fBstd::exa\fP"
.br
.ti -1c
.RI "typedef ratio< 1, 1000000000000000 > \fBstd::femto\fP"
.br
.ti -1c
.RI "typedef ratio< 1000000000, 1 > \fBstd::giga\fP"
.br
.ti -1c
.RI "typedef ratio< 100, 1 > \fBstd::hecto\fP"
.br
.ti -1c
.RI "typedef ratio< 1000, 1 > \fBstd::kilo\fP"
.br
.ti -1c
.RI "typedef ratio< 1000000, 1 > \fBstd::mega\fP"
.br
.ti -1c
.RI "typedef ratio< 1, 1000000 > \fBstd::micro\fP"
.br
.ti -1c
.RI "typedef ratio< 1, 1000 > \fBstd::milli\fP"
.br
.ti -1c
.RI "typedef ratio< 1, 1000000000 > \fBstd::nano\fP"
.br
.ti -1c
.RI "typedef ratio< 1000000000000000, 1 > \fBstd::peta\fP"
.br
.ti -1c
.RI "typedef ratio< 1, 1000000000000 > \fBstd::pico\fP"
.br
.ti -1c
.RI "typedef ratio< 1000000000000, 1 > \fBstd::tera\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const intmax_t \fBstd::ratio::den\fP"
.br
.ti -1c
.RI "static const intmax_t \fBstd::ratio::num\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Compile time representation of fininte rational numbers. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
