.TH "rb_tree" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rb_tree \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fB__gnu_cxx::rb_tree< _Key, _Value, _KeyOfValue, _Compare, _Alloc >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fB__gnu_cxx\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB_RB_TREE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file is a GNU extension to the Standard C++ Library (possibly containing extensions from the HP/SGI STL subset). 
.PP
Definition in file \fBrb_tree\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
