.TH "rope" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rope \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB__gnu_cxx::rope< _CharT, _Alloc >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fB__gnu_cxx\fP"
.br
.ti -1c
.RI "namespace \fB__gnu_cxx::__detail\fP"
.br
.ti -1c
.RI "namespace \fBstd\fP"
.br
.ti -1c
.RI "namespace \fBstd::tr1\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB__GC_CONST\fP"
.br
.ti -1c
.RI "#define \fB__ROPE_DEFINE_ALLOC\fP(_Tp, __name)"
.br
.ti -1c
.RI "#define \fB__ROPE_DEFINE_ALLOC\fP(_Tp, __name)"
.br
.ti -1c
.RI "#define \fB__ROPE_DEFINE_ALLOCS\fP(__a)"
.br
.ti -1c
.RI "#define \fB__STATIC_IF_SGI_ALLOC\fP"
.br
.ti -1c
.RI "#define \fB__STL_FREE_STRING\fP(__s, __l, __a)"
.br
.ti -1c
.RI "#define \fB__STL_ROPE_FROM_UNOWNED_CHAR_PTR\fP(__s, __size, __a)"
.br
.ti -1c
.RI "#define \fB_ROPE\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef rope< char > \fB__gnu_cxx::crope\fP"
.br
.ti -1c
.RI "typedef rope< wchar_t > \fB__gnu_cxx::wrope\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fB_S_max_rope_depth\fP }"
.br
.ti -1c
.RI "enum \fB_Tag\fP { \fB_S_leaf\fP, \fB_S_concat\fP, \fB_S_substringfn\fP, \fB_S_function\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "crope::reference \fB__gnu_cxx::__mutable_reference_at\fP (crope &__c, size_t __i)"
.br
.ti -1c
.RI "template<typename _ForwardIterator , typename _Tp > void \fB__gnu_cxx::_Destroy_const\fP (_ForwardIterator __first, _ForwardIterator __last, allocator< _Tp >)"
.br
.ti -1c
.RI "template<typename _ForwardIterator , typename _Allocator > void \fB__gnu_cxx::_Destroy_const\fP (_ForwardIterator __first, _ForwardIterator __last, _Allocator __alloc)"
.br
.ti -1c
.RI "void \fB__gnu_cxx::_S_cond_store_eos\fP (wchar_t &__c)"
.br
.ti -1c
.RI "void \fB__gnu_cxx::_S_cond_store_eos\fP (char &__c)"
.br
.ti -1c
.RI "template<class _CharT > void \fB__gnu_cxx::_S_cond_store_eos\fP (_CharT &)"
.br
.ti -1c
.RI "template<class _CharT > _CharT \fB__gnu_cxx::_S_eos\fP (_CharT *)"
.br
.ti -1c
.RI "bool \fB__gnu_cxx::_S_is_basic_char_type\fP (wchar_t *)"
.br
.ti -1c
.RI "bool \fB__gnu_cxx::_S_is_basic_char_type\fP (char *)"
.br
.ti -1c
.RI "template<class _CharT > bool \fB__gnu_cxx::_S_is_basic_char_type\fP (_CharT *)"
.br
.ti -1c
.RI "bool \fB__gnu_cxx::_S_is_one_byte_char_type\fP (char *)"
.br
.ti -1c
.RI "template<class _CharT > bool \fB__gnu_cxx::_S_is_one_byte_char_type\fP (_CharT *)"
.br
.ti -1c
.RI "template<class _CharT , class _Alloc > bool \fB__gnu_cxx::operator!=\fP (const _Rope_char_ptr_proxy< _CharT, _Alloc > &__x, const _Rope_char_ptr_proxy< _CharT, _Alloc > &__y)"
.br
.ti -1c
.RI "template<class _CharT , class _Alloc > bool \fB__gnu_cxx::operator!=\fP (const rope< _CharT, _Alloc > &__x, const rope< _CharT, _Alloc > &__y)"
.br
.ti -1c
.RI "template<class _CharT , class _Alloc > bool \fB__gnu_cxx::operator!=\fP (const _Rope_iterator< _CharT, _Alloc > &__x, const _Rope_iterator< _CharT, _Alloc > &__y)"
.br
.ti -1c
.RI "template<class _CharT , class _Alloc > bool \fB__gnu_cxx::operator!=\fP (const _Rope_const_iterator< _CharT, _Alloc > &__x, const _Rope_const_iterator< _CharT, _Alloc > &__y)"
.br
.ti -1c
.RI "template<class _CharT , class _Alloc > rope< _CharT, _Alloc > \fB__gnu_cxx::operator+\fP (const rope< _CharT, _Alloc > &__left, _CharT __right)"
.br
.ti -1c
.RI "template<class _CharT , class _Alloc > rope< _CharT, _Alloc > \fB__gnu_cxx::operator+\fP (const rope< _CharT, _Alloc > &__left, const _CharT *__right)"
.br
.ti -1c
.RI "template<class _CharT , class _Alloc > rope< _CharT, _Alloc > \fB__gnu_cxx::operator+\fP (const rope< _CharT, _Alloc > &__left, const rope< _CharT, _Alloc > &__right)"
.br
.ti -1c
.RI "template<class _CharT , class _Alloc > _Rope_iterator< _CharT, _Alloc > \fB__gnu_cxx::operator+\fP (ptrdiff_t __n, const _Rope_iterator< _CharT, _Alloc > &__x)"
.br
.ti -1c
.RI "template<class _CharT , class _Alloc > _Rope_iterator< _CharT, _Alloc > \fB__gnu_cxx::operator+\fP (const _Rope_iterator< _CharT, _Alloc > &__x, ptrdiff_t __n)"
.br
.ti -1c
.RI "template<class _CharT , class _Alloc > _Rope_const_iterator< _CharT, _Alloc > \fB__gnu_cxx::operator+\fP (ptrdiff_t __n, const _Rope_const_iterator< _CharT, _Alloc > &__x)"
.br
.ti -1c
.RI "template<class _CharT , class _Alloc > _Rope_const_iterator< _CharT, _Alloc > \fB__gnu_cxx::operator+\fP (const _Rope_const_iterator< _CharT, _Alloc > &__x, ptrdiff_t __n)"
.br
.ti -1c
.RI "template<class _CharT , class _Alloc > rope< _CharT, _Alloc > & \fB__gnu_cxx::operator+=\fP (rope< _CharT, _Alloc > &__left, _CharT __right)"
.br
.ti -1c
.RI "template<class _CharT , class _Alloc > rope< _CharT, _Alloc > & \fB__gnu_cxx::operator+=\fP (rope< _CharT, _Alloc > &__left, const _CharT *__right)"
.br
.ti -1c
.RI "template<class _CharT , class _Alloc > rope< _CharT, _Alloc > & \fB__gnu_cxx::operator+=\fP (rope< _CharT, _Alloc > &__left, const rope< _CharT, _Alloc > &__right)"
.br
.ti -1c
.RI "template<class _CharT , class _Alloc > ptrdiff_t \fB__gnu_cxx::operator-\fP (const _Rope_iterator< _CharT, _Alloc > &__x, const _Rope_iterator< _CharT, _Alloc > &__y)"
.br
.ti -1c
.RI "template<class _CharT , class _Alloc > _Rope_iterator< _CharT, _Alloc > \fB__gnu_cxx::operator-\fP (const _Rope_iterator< _CharT, _Alloc > &__x, ptrdiff_t __n)"
.br
.ti -1c
.RI "template<class _CharT , class _Alloc > ptrdiff_t \fB__gnu_cxx::operator-\fP (const _Rope_const_iterator< _CharT, _Alloc > &__x, const _Rope_const_iterator< _CharT, _Alloc > &__y)"
.br
.ti -1c
.RI "template<class _CharT , class _Alloc > _Rope_const_iterator< _CharT, _Alloc > \fB__gnu_cxx::operator-\fP (const _Rope_const_iterator< _CharT, _Alloc > &__x, ptrdiff_t __n)"
.br
.ti -1c
.RI "template<class _CharT , class _Alloc > bool \fB__gnu_cxx::operator<\fP (const rope< _CharT, _Alloc > &__left, const rope< _CharT, _Alloc > &__right)"
.br
.ti -1c
.RI "template<class _CharT , class _Alloc > bool \fB__gnu_cxx::operator<\fP (const _Rope_iterator< _CharT, _Alloc > &__x, const _Rope_iterator< _CharT, _Alloc > &__y)"
.br
.ti -1c
.RI "template<class _CharT , class _Alloc > bool \fB__gnu_cxx::operator<\fP (const _Rope_const_iterator< _CharT, _Alloc > &__x, const _Rope_const_iterator< _CharT, _Alloc > &__y)"
.br
.ti -1c
.RI "template<class _CharT , class _Traits , class _Alloc > \fBstd::basic_ostream\fP< _CharT, _Traits > & \fB__gnu_cxx::operator<<\fP (\fBstd::basic_ostream\fP< _CharT, _Traits > &__o, const rope< _CharT, _Alloc > &__r)"
.br
.ti -1c
.RI "template<class _CharT , class _Alloc > bool \fB__gnu_cxx::operator<=\fP (const rope< _CharT, _Alloc > &__x, const rope< _CharT, _Alloc > &__y)"
.br
.ti -1c
.RI "template<class _CharT , class _Alloc > bool \fB__gnu_cxx::operator<=\fP (const _Rope_iterator< _CharT, _Alloc > &__x, const _Rope_iterator< _CharT, _Alloc > &__y)"
.br
.ti -1c
.RI "template<class _CharT , class _Alloc > bool \fB__gnu_cxx::operator<=\fP (const _Rope_const_iterator< _CharT, _Alloc > &__x, const _Rope_const_iterator< _CharT, _Alloc > &__y)"
.br
.ti -1c
.RI "template<class _CharT , class _Alloc > bool \fB__gnu_cxx::operator==\fP (const rope< _CharT, _Alloc > &__left, const rope< _CharT, _Alloc > &__right)"
.br
.ti -1c
.RI "template<class _CharT , class _Alloc > bool \fB__gnu_cxx::operator==\fP (const _Rope_iterator< _CharT, _Alloc > &__x, const _Rope_iterator< _CharT, _Alloc > &__y)"
.br
.ti -1c
.RI "template<class _CharT , class _Alloc > bool \fB__gnu_cxx::operator==\fP (const _Rope_const_iterator< _CharT, _Alloc > &__x, const _Rope_const_iterator< _CharT, _Alloc > &__y)"
.br
.ti -1c
.RI "template<class _CharT , class _Alloc > bool \fB__gnu_cxx::operator==\fP (const _Rope_char_ptr_proxy< _CharT, _Alloc > &__x, const _Rope_char_ptr_proxy< _CharT, _Alloc > &__y)"
.br
.ti -1c
.RI "template<class _CharT , class _Alloc > bool \fB__gnu_cxx::operator>\fP (const rope< _CharT, _Alloc > &__x, const rope< _CharT, _Alloc > &__y)"
.br
.ti -1c
.RI "template<class _CharT , class _Alloc > bool \fB__gnu_cxx::operator>\fP (const _Rope_iterator< _CharT, _Alloc > &__x, const _Rope_iterator< _CharT, _Alloc > &__y)"
.br
.ti -1c
.RI "template<class _CharT , class _Alloc > bool \fB__gnu_cxx::operator>\fP (const _Rope_const_iterator< _CharT, _Alloc > &__x, const _Rope_const_iterator< _CharT, _Alloc > &__y)"
.br
.ti -1c
.RI "template<class _CharT , class _Alloc > bool \fB__gnu_cxx::operator>=\fP (const rope< _CharT, _Alloc > &__x, const rope< _CharT, _Alloc > &__y)"
.br
.ti -1c
.RI "template<class _CharT , class _Alloc > bool \fB__gnu_cxx::operator>=\fP (const _Rope_iterator< _CharT, _Alloc > &__x, const _Rope_iterator< _CharT, _Alloc > &__y)"
.br
.ti -1c
.RI "template<class _CharT , class _Alloc > bool \fB__gnu_cxx::operator>=\fP (const _Rope_const_iterator< _CharT, _Alloc > &__x, const _Rope_const_iterator< _CharT, _Alloc > &__y)"
.br
.ti -1c
.RI "template<class _CharT , class _Alloc > void \fB__gnu_cxx::swap\fP (rope< _CharT, _Alloc > &__x, rope< _CharT, _Alloc > &__y)"
.br
.ti -1c
.RI "template<class _CharT , class __Alloc > void \fB__gnu_cxx::swap\fP (_Rope_char_ref_proxy< _CharT, __Alloc > __a, _Rope_char_ref_proxy< _CharT, __Alloc > __b)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "rope< _CharT, _Alloc > \fB__gnu_cxx::identity_element\fP (_Rope_Concat_fn< _CharT, _Alloc >)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file is a GNU extension to the Standard C++ Library (possibly containing extensions from the HP/SGI STL subset). 
.PP
Definition in file \fBrope\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
