.TH "sstream" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sstream \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBstd::basic_istringstream< _CharT, _Traits, _Alloc >\fP"
.br
.RI "\fIControlling input for std::string.
.PP
This class supports reading from objects of type \fBstd::basic_string\fP, using the inherited functions from \fBstd::basic_istream\fP. To control the associated sequence, an instance of \fBstd::basic_stringbuf\fP is used, which this page refers to as \fCsb\fP. \fP"
.ti -1c
.RI "class \fBstd::basic_ostringstream< _CharT, _Traits, _Alloc >\fP"
.br
.RI "\fIControlling output for std::string.
.PP
This class supports writing to objects of type \fBstd::basic_string\fP, using the inherited functions from \fBstd::basic_ostream\fP. To control the associated sequence, an instance of \fBstd::basic_stringbuf\fP is used, which this page refers to as \fCsb\fP. \fP"
.ti -1c
.RI "class \fBstd::basic_stringbuf< _CharT, _Traits, _Alloc >\fP"
.br
.RI "\fIThe actual work of input and output (for std::string).
.PP
This class associates either or both of its input and output sequences with a sequence of characters, which can be initialized from, or made available as, a \fC\fBstd::basic_string\fP\fP. (Paraphrased from [27.7.1]/1.). \fP"
.ti -1c
.RI "class \fBstd::basic_stringstream< _CharT, _Traits, _Alloc >\fP"
.br
.RI "\fIControlling input and output for std::string.
.PP
This class supports reading from and writing to objects of type \fBstd::basic_string\fP, using the inherited functions from \fBstd::basic_iostream\fP. To control the associated sequence, an instance of \fBstd::basic_stringbuf\fP is used, which this page refers to as \fCsb\fP. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBstd\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB_GLIBCXX_SSTREAM\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is a Standard C++ Library header. 
.PP
Definition in file \fBsstream\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
