.TH "std::_Base_bitset" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::_Base_bitset \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef unsigned long \fB_WordT\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB_Base_bitset\fP (unsigned long __val)"
.br
.ti -1c
.RI "size_t \fB_M_are_all_aux\fP () const "
.br
.ti -1c
.RI "void \fB_M_do_and\fP (const \fB_Base_bitset\fP< _Nw > &__x)"
.br
.ti -1c
.RI "size_t \fB_M_do_count\fP () const "
.br
.ti -1c
.RI "size_t \fB_M_do_find_first\fP (size_t __not_found) const "
.br
.ti -1c
.RI "size_t \fB_M_do_find_next\fP (size_t __prev, size_t __not_found) const "
.br
.ti -1c
.RI "void \fB_M_do_flip\fP ()"
.br
.ti -1c
.RI "void \fB_M_do_left_shift\fP (size_t __shift)"
.br
.ti -1c
.RI "void \fB_M_do_or\fP (const \fB_Base_bitset\fP< _Nw > &__x)"
.br
.ti -1c
.RI "void \fB_M_do_reset\fP ()"
.br
.ti -1c
.RI "void \fB_M_do_right_shift\fP (size_t __shift)"
.br
.ti -1c
.RI "void \fB_M_do_set\fP ()"
.br
.ti -1c
.RI "unsigned long \fB_M_do_to_ulong\fP () const "
.br
.ti -1c
.RI "void \fB_M_do_xor\fP (const \fB_Base_bitset\fP< _Nw > &__x)"
.br
.ti -1c
.RI "_WordT \fB_M_getword\fP (size_t __pos) const "
.br
.ti -1c
.RI "_WordT & \fB_M_getword\fP (size_t __pos)"
.br
.ti -1c
.RI "_WordT \fB_M_hiword\fP () const "
.br
.ti -1c
.RI "_WordT & \fB_M_hiword\fP ()"
.br
.ti -1c
.RI "bool \fB_M_is_any\fP () const "
.br
.ti -1c
.RI "bool \fB_M_is_equal\fP (const \fB_Base_bitset\fP< _Nw > &__x) const "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static _WordT \fB_S_maskbit\fP (size_t __pos)"
.br
.ti -1c
.RI "static size_t \fB_S_whichbit\fP (size_t __pos)"
.br
.ti -1c
.RI "static size_t \fB_S_whichbyte\fP (size_t __pos)"
.br
.ti -1c
.RI "static size_t \fB_S_whichword\fP (size_t __pos)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "_WordT \fB_M_w\fP [_Nw]"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<size_t _Nw> struct std::_Base_bitset< _Nw >"
Base class, general case. It is a class invariant that _Nw will be nonnegative.
.PP
See documentation for \fBbitset\fP. 
.PP
Definition at line 69 of file bitset.
.SH "Member Data Documentation"
.PP 
.SS "template<size_t _Nw> _WordT \fBstd::_Base_bitset\fP< _Nw >::\fB_M_w\fP[_Nw]"
.PP
0 is the least significant word. 
.PP
Definition at line 74 of file bitset.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
