.TH "std::ratio_subtract" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::ratio_subtract \- \fBratio_subtract\fP  

.PP
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SS "template<typename _R1, typename _R2> struct std::ratio_subtract< _R1, _R2 >"
\fBratio_subtract\fP 
.PP
Definition at line 189 of file ratio.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
