.TH "std::codecvt_base" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::codecvt_base \- Empty base class for \fBcodecvt\fP facet [22.2.1.5].  

.PP
.SH SYNOPSIS
.br
.PP
Inherited by \fBstd::__codecvt_abstract_base< _InternT, _ExternT, _StateT >\fP, \fBstd::__codecvt_abstract_base< _InternT, _ExternT, encoding_state >\fP, \fBstd::__codecvt_abstract_base< char, char, mbstate_t >\fP, \fBstd::__codecvt_abstract_base< wchar_t, char, mbstate_t >\fP, and \fBstd::__codecvt_abstract_base< _InternT, _ExternT, _StateT >\fP.
.PP
.SS "Public Types"
.SH "Detailed Description"
.PP 
Empty base class for \fBcodecvt\fP facet [22.2.1.5]. 
.PP
Definition at line 45 of file codecvt.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
