.TH "std::ctype_base" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::ctype_base \- Base class for \fBctype\fP.  

.PP
.SH SYNOPSIS
.br
.PP
Inherited by \fBstd::__ctype_abstract_base< _CharT >\fP, \fBstd::__ctype_abstract_base< wchar_t >\fP, \fBstd::__ctype_abstract_base< _CharT >\fP, and \fBstd::ctype< char >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef const int * \fB__to_type\fP"
.br
.ti -1c
.RI "typedef unsigned short \fBmask\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const mask \fBalnum\fP"
.br
.ti -1c
.RI "static const mask \fBalpha\fP"
.br
.ti -1c
.RI "static const mask \fBcntrl\fP"
.br
.ti -1c
.RI "static const mask \fBdigit\fP"
.br
.ti -1c
.RI "static const mask \fBgraph\fP"
.br
.ti -1c
.RI "static const mask \fBlower\fP"
.br
.ti -1c
.RI "static const mask \fBprint\fP"
.br
.ti -1c
.RI "static const mask \fBpunct\fP"
.br
.ti -1c
.RI "static const mask \fBspace\fP"
.br
.ti -1c
.RI "static const mask \fBupper\fP"
.br
.ti -1c
.RI "static const mask \fBxdigit\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Base class for \fBctype\fP. 
.PP
Definition at line 40 of file ctype_base.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
