.TH "std::tuple" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::tuple \- \fBtuple\fP  

.PP
.SH SYNOPSIS
.br
.PP
Inherits _Tuple_impl<0, _Elements...>.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename... _UElements> \fBtuple\fP & \fBoperator=\fP (\fBtuple\fP< _UElements...> &&__in)"
.br
.ti -1c
.RI "template<typename... _UElements> \fBtuple\fP & \fBoperator=\fP (const \fBtuple\fP< _UElements...> &__in)"
.br
.ti -1c
.RI "\fBtuple\fP & \fBoperator=\fP (\fBtuple\fP &&__in)"
.br
.ti -1c
.RI "\fBtuple\fP & \fBoperator=\fP (const \fBtuple\fP &__in)"
.br
.ti -1c
.RI "void \fBswap\fP (\fBtuple\fP &&__in)"
.br
.ti -1c
.RI "template<typename... _UElements> \fBtuple\fP (\fBtuple\fP< _UElements...> &__in)"
.br
.ti -1c
.RI "template<typename... _UElements> \fBtuple\fP (\fBtuple\fP< _UElements...> &&__in)"
.br
.ti -1c
.RI "template<typename... _UElements> \fBtuple\fP (const \fBtuple\fP< _UElements...> &__in)"
.br
.ti -1c
.RI "\fBtuple\fP (\fBtuple\fP &&__in)"
.br
.ti -1c
.RI "\fBtuple\fP (const \fBtuple\fP &__in)"
.br
.ti -1c
.RI "template<typename... _UElements> \fBtuple\fP (_UElements &&...__elements)"
.br
.ti -1c
.RI "\fBtuple\fP (const _Elements &...__elements)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename... _Elements> class std::tuple< _Elements >"
\fBtuple\fP 
.PP
Definition at line 226 of file tuple.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
