.TH "std::out_of_range" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::out_of_range \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBstd::logic_error\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBout_of_range\fP (const \fBstring\fP &__arg)"
.br
.ti -1c
.RI "virtual const char * \fBwhat\fP () const   throw ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This represents an argument whose value is not within the expected range (e.g., boundary checks in \fBbasic_string\fP). 
.PP
Definition at line 96 of file stdexcept.
.SH "Member Function Documentation"
.PP 
.SS "virtual const char* std::logic_error::what () const  throw ()\fC [virtual, inherited]\fP"
.PP
Returns a C-style character string describing the general cause of the current error (the same string passed to the ctor). 
.PP
Reimplemented from \fBstd::exception\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
