.TH "std::thread::id" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::thread::id \- \fBthread::id\fP  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBid\fP (native_handle_type __id)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator<\fP (\fBthread::id\fP __x, \fBthread::id\fP __y)"
.br
.ti -1c
.RI "template<class _CharT , class _Traits > \fBbasic_ostream\fP< _CharT, _Traits > & \fBoperator<<\fP (\fBbasic_ostream\fP< _CharT, _Traits > &&__out, \fBthread::id\fP __id)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBthread::id\fP __x, \fBthread::id\fP __y)"
.br
.ti -1c
.RI "class \fBthread\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBthread::id\fP 
.PP
Definition at line 68 of file thread.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
