.TH "std::tr1::__detail::__numeric_constants" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::tr1::__detail::__numeric_constants \- A structure for numeric constants.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static _Tp \fB__1_pi\fP ()  throw ()"
.br
.ti -1c
.RI "static _Tp \fB__2_sqrtpi\fP ()  throw ()"
.br
.ti -1c
.RI "static _Tp \fB__euler\fP ()  throw ()"
.br
.ti -1c
.RI "static _Tp \fB__gamma_e\fP ()  throw ()"
.br
.ti -1c
.RI "static _Tp \fB__lnpi\fP ()  throw ()"
.br
.ti -1c
.RI "static _Tp \fB__pi\fP ()  throw ()"
.br
.ti -1c
.RI "static _Tp \fB__pi_2\fP ()  throw ()"
.br
.ti -1c
.RI "static _Tp \fB__pi_3\fP ()  throw ()"
.br
.ti -1c
.RI "static _Tp \fB__pi_4\fP ()  throw ()"
.br
.ti -1c
.RI "static _Tp \fB__sqrt1_2\fP ()  throw ()"
.br
.ti -1c
.RI "static _Tp \fB__sqrt2\fP ()  throw ()"
.br
.ti -1c
.RI "static _Tp \fB__sqrt3\fP ()  throw ()"
.br
.ti -1c
.RI "static _Tp \fB__sqrtpio2\fP ()  throw ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> struct std::tr1::__detail::__numeric_constants< _Tp >"
A structure for numeric constants. 
.PP
Definition at line 60 of file special_function_util.h.
.SH "Member Function Documentation"
.PP 
.SS "template<typename _Tp > static _Tp \fBstd::tr1::__detail::__numeric_constants\fP< _Tp >::__1_pi ()  throw ()\fC [inline, static]\fP"
.PP
Constant $ 1 / \pi $. 
.PP
Definition at line 75 of file special_function_util.h.
.SS "template<typename _Tp > static _Tp \fBstd::tr1::__detail::__numeric_constants\fP< _Tp >::__2_sqrtpi ()  throw ()\fC [inline, static]\fP"
.PP
Constant $ 2 / \sqrt(\pi) $. 
.PP
Definition at line 78 of file special_function_util.h.
.SS "template<typename _Tp > static _Tp \fBstd::tr1::__detail::__numeric_constants\fP< _Tp >::__euler ()  throw ()\fC [inline, static]\fP"
.PP
Constant Euler-Mascheroni $ e $. 
.PP
Definition at line 99 of file special_function_util.h.
.PP
Referenced by std::tr1::__detail::__log_gamma_lanczos().
.SS "template<typename _Tp > static _Tp \fBstd::tr1::__detail::__numeric_constants\fP< _Tp >::__gamma_e ()  throw ()\fC [inline, static]\fP"
.PP
Constant Euler's constant $ \gamma_E $. 
.PP
Definition at line 96 of file special_function_util.h.
.PP
Referenced by std::tr1::__detail::__expint_E1_series(), std::tr1::__detail::__expint_Ei_series(), std::tr1::__detail::__expint_En_series(), std::tr1::__detail::__hyperg_reflect(), and std::tr1::__detail::__psi_series().
.SS "template<typename _Tp > static _Tp \fBstd::tr1::__detail::__numeric_constants\fP< _Tp >::__lnpi ()  throw ()\fC [inline, static]\fP"
.PP
Constant $ \log(\pi) $. 
.PP
Definition at line 93 of file special_function_util.h.
.PP
Referenced by std::tr1::__detail::__log_gamma(), and std::tr1::__detail::__sph_legendre().
.SS "template<typename _Tp > static _Tp \fBstd::tr1::__detail::__numeric_constants\fP< _Tp >::__pi ()  throw ()\fC [inline, static]\fP"
.PP
Constant $ \pi $. 
.PP
Definition at line 63 of file special_function_util.h.
.PP
Referenced by std::tr1::__detail::__airy(), std::tr1::__detail::__bessel_ik(), std::tr1::__detail::__bessel_jn(), std::tr1::__detail::__ellint_1(), std::tr1::__detail::__ellint_2(), std::tr1::__detail::__ellint_3(), std::tr1::__detail::__psi(), std::tr1::__detail::__riemann_zeta(), and std::tr1::__detail::__riemann_zeta_glob().
.SS "template<typename _Tp > static _Tp \fBstd::tr1::__detail::__numeric_constants\fP< _Tp >::__pi_2 ()  throw ()\fC [inline, static]\fP"
.PP
Constant $ \pi / 2 $. 
.PP
Definition at line 66 of file special_function_util.h.
.PP
Referenced by std::tr1::__detail::__comp_ellint_1_series(), std::tr1::__detail::__comp_ellint_2_series(), and std::tr1::__detail::__poly_laguerre_large_n().
.SS "template<typename _Tp > static _Tp \fBstd::tr1::__detail::__numeric_constants\fP< _Tp >::__pi_3 ()  throw ()\fC [inline, static]\fP"
.PP
Constant $ \pi / 3 $. 
.PP
Definition at line 69 of file special_function_util.h.
.SS "template<typename _Tp > static _Tp \fBstd::tr1::__detail::__numeric_constants\fP< _Tp >::__pi_4 ()  throw ()\fC [inline, static]\fP"
.PP
Constant $ \pi / 4 $. 
.PP
Definition at line 72 of file special_function_util.h.
.SS "template<typename _Tp > static _Tp \fBstd::tr1::__detail::__numeric_constants\fP< _Tp >::__sqrt1_2 ()  throw ()\fC [inline, static]\fP"
.PP
Constant $ 1 / sqrt(2) $. 
.PP
Definition at line 90 of file special_function_util.h.
.SS "template<typename _Tp > static _Tp \fBstd::tr1::__detail::__numeric_constants\fP< _Tp >::__sqrt2 ()  throw ()\fC [inline, static]\fP"
.PP
Constant $ \sqrt(2) $. 
.PP
Definition at line 81 of file special_function_util.h.
.SS "template<typename _Tp > static _Tp \fBstd::tr1::__detail::__numeric_constants\fP< _Tp >::__sqrt3 ()  throw ()\fC [inline, static]\fP"
.PP
Constant $ \sqrt(3) $. 
.PP
Definition at line 84 of file special_function_util.h.
.PP
Referenced by std::tr1::__detail::__airy().
.SS "template<typename _Tp > static _Tp \fBstd::tr1::__detail::__numeric_constants\fP< _Tp >::__sqrtpio2 ()  throw ()\fC [inline, static]\fP"
.PP
Constant $ \sqrt(\pi/2) $. 
.PP
Definition at line 87 of file special_function_util.h.
.PP
Referenced by std::tr1::__detail::__sph_bessel_ik(), and std::tr1::__detail::__sph_bessel_jn().

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
