.TH "std::geometric_distribution" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::geometric_distribution \- A discrete geometric random number distribution.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _RealType \fBinput_type\fP"
.br
.ti -1c
.RI "typedef _IntType \fBresult_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgeometric_distribution\fP (const _RealType &__p=_RealType(0.5))"
.br
.ti -1c
.RI "template<class _UniformRandomNumberGenerator > result_type \fBoperator()\fP (_UniformRandomNumberGenerator &__urng)"
.br
.ti -1c
.RI "_RealType \fBp\fP () const "
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "template<typename _IntType1 , typename _RealType1 , typename _CharT , typename _Traits > \fBstd::basic_ostream\fP< _CharT, _Traits > & \fBoperator<<\fP (\fBstd::basic_ostream\fP< _CharT, _Traits > &__os, const \fBgeometric_distribution\fP< _IntType1, _RealType1 > &__x)"
.br
.ti -1c
.RI "template<typename _CharT , typename _Traits > \fBstd::basic_istream\fP< _CharT, _Traits > & \fBoperator>>\fP (\fBstd::basic_istream\fP< _CharT, _Traits > &__is, \fBgeometric_distribution\fP &__x)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _IntType = int, typename _RealType = double> class std::geometric_distribution< _IntType, _RealType >"
A discrete geometric random number distribution. 

The formula for the geometric probability mass function is $ p(i) = (1 - p)p^{i-1} $ where $ p $ is the parameter of the distribution. 
.PP
Definition at line 1778 of file tr1_impl/random.
.SH "Member Function Documentation"
.PP 
.SS "template<typename _IntType = int, typename _RealType  = double> _RealType \fBstd::geometric_distribution\fP< _IntType, _RealType >::p () const\fC [inline]\fP"
.PP
Gets the distribution parameter \fCp\fP. 
.PP
Definition at line 1798 of file tr1_impl/random.
.SH "Friends And Related Function Documentation"
.PP 
.SS "template<typename _IntType = int, typename _RealType  = double> template<typename _IntType1 , typename _RealType1 , typename _CharT , typename _Traits > \fBstd::basic_ostream\fP<_CharT, _Traits>& operator<< (\fBstd::basic_ostream\fP< _CharT, _Traits > & __os, const \fBgeometric_distribution\fP< _IntType1, _RealType1 > & __x)\fC [friend]\fP"
.PP
Inserts a geometric_distribution random number distribution \fC__x\fP into the output stream \fC__os\fP.
.PP
\fBParameters:\fP
.RS 4
\fI__os\fP An output stream. 
.br
\fI__x\fP A geometric_distribution random number distribution.
.RE
.PP
\fBReturns:\fP
.RS 4
The output stream with the state of \fC__x\fP inserted or in an error state. 
.RE
.PP

.SS "template<typename _IntType = int, typename _RealType  = double> template<typename _CharT , typename _Traits > \fBstd::basic_istream\fP<_CharT, _Traits>& operator>> (\fBstd::basic_istream\fP< _CharT, _Traits > & __is, \fBgeometric_distribution\fP< _IntType, _RealType > & __x)\fC [friend]\fP"
.PP
Extracts a geometric_distribution random number distribution \fC__x\fP from the input stream \fC__is\fP.
.PP
\fBParameters:\fP
.RS 4
\fI__is\fP An input stream. 
.br
\fI__x\fP A geometric_distribution random number generator engine.
.RE
.PP
\fBReturns:\fP
.RS 4
The input stream with \fC__x\fP extracted or in an error state. 
.RE
.PP

.PP
Definition at line 1835 of file tr1_impl/random.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
