.TH "std::negate" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::negate \- One of the \fBmath functors\fP.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fBunary_function< _Tp, _Tp >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _Tp \fBargument_type\fP"
.br
.ti -1c
.RI "typedef _Tp \fBresult_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "_Tp \fBoperator()\fP (const _Tp &__x) const "
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> struct std::negate< _Tp >"
One of the \fBmath functors\fP. 
.PP
Definition at line 180 of file stl_function.h.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef _Tp  \fBstd::unary_function\fP< _Tp , _Tp  >::\fBargument_type\fP\fC [inherited]\fP"
.PP
\fCargument_type\fP is the type of the argument (no surprises here) 
.PP
Definition at line 102 of file stl_function.h.
.SS "typedef _Tp  \fBstd::unary_function\fP< _Tp , _Tp  >::\fBresult_type\fP\fC [inherited]\fP"
.PP
\fCresult_type\fP is the return type 
.PP
Definition at line 105 of file stl_function.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
