.TH "std::bitset::reference" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::bitset::reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBreference\fP & \fBflip\fP ()"
.br
.ti -1c
.RI "\fBoperator bool\fP () const "
.br
.ti -1c
.RI "\fBreference\fP & \fBoperator=\fP (const \fBreference\fP &__j)"
.br
.ti -1c
.RI "\fBreference\fP & \fBoperator=\fP (bool __x)"
.br
.ti -1c
.RI "bool \fBoperator~\fP () const "
.br
.ti -1c
.RI "\fBreference\fP (\fBbitset\fP &__b, size_t __pos)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBbitset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<size_t _Nb> class std::bitset< _Nb >::reference"
This encapsulates the concept of a single bit. An instance of this class is a proxy for an actual bit; this way the individual bit operations are done as faster word-size bitwise instructions.
.PP
Most users will never need to use this class directly; conversions to and from bool are automatic and should be transparent. Overloaded operators help to preserve the illusion.
.PP
(On a typical system, this 'bit %reference' is 64 times the size of an actual bit. Ha.) 
.PP
Definition at line 673 of file bitset.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
