.TH "std::integral_constant" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::integral_constant \- \fBintegral_constant\fP  

.PP
.SH SYNOPSIS
.br
.PP
Inherited by std::__is_member_object_pointer_helper< typename >, std::__is_pointer_helper< typename >, std::chrono::__is_duration< _Tp >, \fBstd::is_array< typename >\fP, \fBstd::is_const< typename >\fP, \fBstd::is_function< typename >\fP, \fBstd::is_rvalue_reference< typename >\fP, and std::tr1::__is_signed_helper< typename >.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBintegral_constant\fP< _Tp, __v > \fBtype\fP"
.br
.ti -1c
.RI "typedef _Tp \fBvalue_type\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const _Tp \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp, _Tp __v> struct std::integral_constant< _Tp, __v >"
\fBintegral_constant\fP 
.PP
Definition at line 67 of file tr1_impl/type_traits.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
