.TH "std::bad_alloc" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::bad_alloc \- Exception possibly thrown by \fCnew\fP.
.PP
\fC\fBbad_alloc\fP\fP (or classes derived from it) is used to report allocation errors from the throwing forms of \fCnew\fP.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fBstd::exception\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual const char * \fBwhat\fP () const   throw ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Exception possibly thrown by \fCnew\fP.
.PP
\fC\fBbad_alloc\fP\fP (or classes derived from it) is used to report allocation errors from the throwing forms of \fCnew\fP. 
.PP
Definition at line 54 of file new.
.SH "Member Function Documentation"
.PP 
.SS "virtual const char* std::bad_alloc::what () const  throw ()\fC [virtual]\fP"
.PP
Returns a C-style character string describing the general cause of the current error. 
.PP
Reimplemented from \fBstd::exception\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
