.TH "std::reference_wrapper" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::reference_wrapper \- \fBreference_wrapper\fP  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fB_Reference_wrapper_base< remove_cv< _Tp >::type >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _Tp \fBtype\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "_Tp & \fBget\fP () const "
.br
.ti -1c
.RI "\fBoperator _Tp &\fP () const "
.br
.ti -1c
.RI "template<typename... _Args> result_of< _M_func_type(_Args...)>::type \fBoperator()\fP (_Args &...__args) const "
.br
.ti -1c
.RI "\fBreference_wrapper\fP & \fBoperator=\fP (const \fBreference_wrapper\fP< _Tp > &__inref)"
.br
.ti -1c
.RI "\fBreference_wrapper\fP (const \fBreference_wrapper\fP< _Tp > &__inref)"
.br
.ti -1c
.RI "\fBreference_wrapper\fP (_Tp &__indata)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> class std::reference_wrapper< _Tp >"
\fBreference_wrapper\fP 
.PP
Definition at line 426 of file tr1_impl/functional.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
