.TH "std::tr1::__detail::__floating_point_constant" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::tr1::__detail::__floating_point_constant \- A class to encapsulate type dependent floating point constants. Not everything will be able to be expressed as type logic.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const _Tp \fB__value\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> struct std::tr1::__detail::__floating_point_constant< _Tp >"
A class to encapsulate type dependent floating point constants. Not everything will be able to be expressed as type logic. 
.PP
Definition at line 52 of file special_function_util.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
