.TH "std::messages_byname" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::messages_byname \- class \fBmessages_byname\fP [22.2.7.2].  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fBmessages< _CharT >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef int \fBcatalog\fP"
.br
.ti -1c
.RI "typedef _CharT \fBchar_type\fP"
.br
.ti -1c
.RI "typedef \fBbasic_string\fP< _CharT > \fBstring_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBclose\fP (catalog __c) const"
.br
.ti -1c
.RI "\fBstring_type\fP \fBget\fP (catalog __c, int __set, int __msgid, const \fBstring_type\fP &__s) const"
.br
.ti -1c
.RI "\fBmessages_byname\fP (const char *__s, size_t __refs=0)"
.br
.ti -1c
.RI "catalog \fBopen\fP (const \fBbasic_string\fP< char > &, const \fBlocale\fP &, const char *) const"
.br
.ti -1c
.RI "catalog \fBopen\fP (const \fBbasic_string\fP< char > &__s, const \fBlocale\fP &__loc) const"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBlocale::id\fP \fBid\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBstring_type\fP \fB_M_convert_from_char\fP (char *) const"
.br
.ti -1c
.RI "char * \fB_M_convert_to_char\fP (const \fBstring_type\fP &__msg) const"
.br
.ti -1c
.RI "virtual void \fBdo_close\fP (catalog) const"
.br
.ti -1c
.RI "virtual \fBstring_type\fP \fBdo_get\fP (catalog, int, int, const \fBstring_type\fP &__dfault) const"
.br
.ti -1c
.RI "virtual catalog \fBdo_open\fP (const \fBbasic_string\fP< char > &, const \fBlocale\fP &) const"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static __c_locale \fB_S_clone_c_locale\fP (__c_locale &__cloc)"
.br
.ti -1c
.RI "static void \fB_S_create_c_locale\fP (__c_locale &__cloc, const char *__s, __c_locale __old=0)"
.br
.ti -1c
.RI "static void \fB_S_destroy_c_locale\fP (__c_locale &__cloc)"
.br
.ti -1c
.RI "static __c_locale \fB_S_get_c_locale\fP ()"
.br
.ti -1c
.RI "static const char * \fB_S_get_c_name\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "__c_locale \fB_M_c_locale_messages\fP"
.br
.ti -1c
.RI "const char * \fB_M_name_messages\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBlocale::_Impl\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _CharT> class std::messages_byname< _CharT >"
class \fBmessages_byname\fP [22.2.7.2]. 
.PP
Definition at line 1887 of file locale_facets_nonio.h.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename _CharT > typedef _CharT \fBstd::messages_byname\fP< _CharT >::\fBchar_type\fP"
.PP
Public typedefs. 
.PP
Reimplemented from \fBstd::messages< _CharT >\fP.
.PP
Definition at line 1890 of file locale_facets_nonio.h.
.SS "template<typename _CharT > typedef \fBbasic_string\fP<_CharT> \fBstd::messages_byname\fP< _CharT >::\fBstring_type\fP"
.PP
Public typedefs. 
.PP
Reimplemented from \fBstd::messages< _CharT >\fP.
.PP
Definition at line 1891 of file locale_facets_nonio.h.
.SH "Member Data Documentation"
.PP 
.SS "\fBlocale::id\fP \fBstd::messages\fP< _CharT  >::\fBid\fP\fC [static, inherited]\fP"
.PP
Numpunct facet id. 
.PP
Definition at line 1688 of file locale_facets_nonio.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
