.TH "std::_Derives_from_unary_function" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::_Derives_from_unary_function \- Determines if the type _Tp derives from \fBunary_function\fP.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits std::__sfinae_types.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef char \fB__one\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> struct std::_Derives_from_unary_function< _Tp >"
Determines if the type _Tp derives from \fBunary_function\fP. 
.PP
Definition at line 210 of file tr1_impl/functional.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
