std::deque
NAME
std::deque - A standard container using fixed-size memory allocation and constant-time manipulation of elements at either end.
SYNOPSIS
Inherits _Deque_base< _Tp, _Alloc >.
Public Types
typedef _Alloc allocator_type
typedef _Base::const_iterator const_iterator
typedef _Tp_alloc_type::const_pointer const_pointer
typedef _Tp_alloc_type::const_reference const_reference
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
typedef ptrdiff_t difference_type
typedef _Base::iterator iterator
typedef _Tp_alloc_type::pointer pointer
typedef _Tp_alloc_type::reference reference
typedef std::reverse_iterator< iterator > reverse_iterator
typedef size_t size_type
typedef _Tp value_type
Public Member Functions
void assign (initializer_list< value_type > __l)
template<typename _InputIterator > void assign (_InputIterator __first, _InputIterator __last)
void assign (size_type __n, const value_type &__val)
const_reference at (size_type __n) const
reference at (size_type __n)
const_reference back () const
reference back ()
const_iterator begin () const
iterator begin ()
const_iterator cbegin () const
const_iterator cend () const
void clear ()
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
template<typename _InputIterator > deque (_InputIterator __first, _InputIterator __last, const allocator_type &__a=allocator_type())
deque (initializer_list< value_type > __l, const allocator_type &__a=allocator_type())
deque (deque &&__x)
deque (const deque &__x)
deque (size_type __n, const value_type &__value=value_type(), const allocator_type &__a=allocator_type())
deque (const allocator_type &__a)
deque ()
template<typename... _Args> iterator emplace (iterator __position, _Args &&...__args)
template<typename... _Args> void emplace_back (_Args &&...__args)
template<typename... _Args> void emplace_front (_Args &&...__args)
bool empty () const
const_iterator end () const
iterator end ()
iterator erase (iterator __first, iterator __last)
iterator erase (iterator __position)
const_reference front () const
reference front ()
allocator_type get_allocator () const
template<typename _InputIterator > void insert (iterator __position, _InputIterator __first, _InputIterator __last)
void insert (iterator __position, size_type __n, const value_type &__x)
void insert (iterator __p, initializer_list< value_type > __l)
iterator insert (iterator __position, value_type &&__x)
iterator insert (iterator __position, const value_type &__x)
size_type max_size () const
deque & operator= (initializer_list< value_type > __l)
deque & operator= (deque &&__x)
deque & operator= (const deque &__x)
const_reference operator[] (size_type __n) const
reference operator[] (size_type __n)
void pop_back ()
void pop_front ()
void push_back (value_type &&__x)
void push_back (const value_type &__x)
void push_front (value_type &&__x)
void push_front (const value_type &__x)
const_reverse_iterator rbegin () const
reverse_iterator rbegin ()
const_reverse_iterator rend () const
reverse_iterator rend ()
void resize (size_type __new_size, value_type __x=value_type())
size_type size () const
void swap (deque &&__x)
~deque ()
Protected Types
enum
typedef _Alloc::template rebind< _Tp * >::other _Map_alloc_type
typedef pointer * _Map_pointer
Protected Member Functions
_Tp ** _M_allocate_map (size_t __n)
_Tp * _M_allocate_node ()
template<typename _ForwardIterator > void _M_assign_aux (_ForwardIterator __first, _ForwardIterator __last, std::forward_iterator_tag)
template<typename _InputIterator > void _M_assign_aux (_InputIterator __first, _InputIterator __last, std::input_iterator_tag)
template<typename _InputIterator > void _M_assign_dispatch (_InputIterator __first, _InputIterator __last, __false_type)
template<typename _Integer > void _M_assign_dispatch (_Integer __n, _Integer __val, __true_type)
void _M_create_nodes (_Tp **__nstart, _Tp **__nfinish)
void _M_deallocate_map (_Tp **__p, size_t __n)
void _M_deallocate_node (_Tp *__p)
void _M_destroy_data (iterator __first, iterator __last, const std::allocator< _Tp > &)
template<typename _Alloc1 > void _M_destroy_data (iterator __first, iterator __last, const _Alloc1 &)
void _M_destroy_data_aux (iterator __first, iterator __last)
void _M_destroy_nodes (_Tp **__nstart, _Tp **__nfinish)
void _M_erase_at_begin (iterator __pos)
void _M_erase_at_end (iterator __pos)
void _M_fill_assign (size_type __n, const value_type &__val)
void _M_fill_initialize (const value_type &__value)
void _M_fill_insert (iterator __pos, size_type __n, const value_type &__x)
_Map_alloc_type _M_get_map_allocator () const
const _Tp_alloc_type & _M_get_Tp_allocator () const
_Tp_alloc_type & _M_get_Tp_allocator ()
template<typename _InputIterator > void _M_initialize_dispatch (_InputIterator __first, _InputIterator __last, __false_type)
template<typename _Integer > void _M_initialize_dispatch (_Integer __n, _Integer __x, __true_type)
void _M_initialize_map (size_t)
template<typename _ForwardIterator > void _M_insert_aux (iterator __pos, _ForwardIterator __first, _ForwardIterator __last, size_type __n)
void _M_insert_aux (iterator __pos, size_type __n, const value_type &__x)
template<typename... _Args> iterator _M_insert_aux (iterator __pos, _Args &&...__args)
template<typename _InputIterator > void _M_insert_dispatch (iterator __pos, _InputIterator __first, _InputIterator __last, __false_type)
template<typename _Integer > void _M_insert_dispatch (iterator __pos, _Integer __n, _Integer __x, __true_type)
void _M_range_check (size_type __n) const
template<typename _ForwardIterator > void _M_range_insert_aux (iterator __pos, _ForwardIterator __first, _ForwardIterator __last, std::forward_iterator_tag)
template<typename _InputIterator > void _M_range_insert_aux (iterator __pos, _InputIterator __first, _InputIterator __last, std::input_iterator_tag)
void _M_new_elements_at_back (size_type __new_elements)
void _M_new_elements_at_front (size_type __new_elements)
iterator _M_reserve_elements_at_back (size_type __n)
iterator _M_reserve_elements_at_front (size_type __n)
void _M_pop_back_aux ()
void _M_pop_front_aux ()
template<typename... _Args> void _M_push_back_aux (_Args &&...__args)
template<typename... _Args> void _M_push_front_aux (_Args &&...__args)
template<typename _ForwardIterator > void _M_range_initialize (_ForwardIterator __first, _ForwardIterator __last, std::forward_iterator_tag)
template<typename _InputIterator > void _M_range_initialize (_InputIterator __first, _InputIterator __last, std::input_iterator_tag)
void _M_reallocate_map (size_type __nodes_to_add, bool __add_at_front)
void _M_reserve_map_at_back (size_type __nodes_to_add=1)
void _M_reserve_map_at_front (size_type __nodes_to_add=1)
Static Protected Member Functions
static size_t _S_buffer_size ()
Protected Attributes
_Deque_impl _M_impl
Detailed Description
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> class std::deque< _Tp, _Alloc >
A standard container using fixed-size memory allocation and constant-time manipulation of elements at either end.
Meets the requirements of a container, a reversible container, and a sequence, including the optional sequence requirements.
In previous HP/SGI versions of deque, there was an extra template parameter so users could control the node size. This extension turned out to violate the C++ standard (it can be detected using template template parameters), and it was removed.
Here's how a deque<Tp> manages memory. Each deque has 4 members:
Tp** _M_map
size_t _M_map_size
iterator _M_start, _M_finish
map_size is at least 8. map is an array of map_size pointers-to-'nodes'. (The name map has nothing to do with the std::map class, and 'nodes' should not be confused with std::list's usage of 'node'.)
A 'node' has no specific type name as such, but it is referred to as 'node' in this file. It is a simple array-of-Tp. If Tp is very large, there will be one Tp element per node (i.e., an 'array' of one). For non-huge Tp's, node size is inversely related to Tp size: the larger the Tp, the fewer Tp's will fit in a node. The goal here is to keep the total size of a node relatively small and constant over different Tp's, to improve allocator efficiency.
Not every pointer in the map array will point to a node. If the initial number of elements in the deque is small, the /middle/ map pointers will be valid, and the ones at the edges will be unused. This same situation will arise as the map grows: available map pointers, if any, will be on the ends. As new nodes are created, only a subset of the map's pointers need to be copied 'outward'.
Class invariants:
For any nonsingular iterator i:
i.node points to a member of the map array. (Yes, you read that correctly: i.node does not actually point to a node.) The member of the map array is what actually points to the node.
i.first == *(i.node) (This points to the node (first Tp element).)
i.last == i.first + node_size
i.cur is a pointer in the range [i.first, i.last). NOTE: the implication of this is that i.cur is always a dereferenceable pointer, even if i is a past-the-end iterator.
Start and Finish are always nonsingular iterators. NOTE: this means that an empty deque must have one node, a deque with <N elements (where N is the node buffer size) must have one node, a deque with N through (2N-1) elements must have two nodes, etc.
For every node other than start.node and finish.node, every element in the node is an initialized object. If start.node == finish.node, then [start.cur, finish.cur) are initialized objects, and the elements outside that range are uninitialized storage. Otherwise, [start.cur, start.last) and [finish.first, finish.cur) are initialized objects, and [start.first, start.cur) and [finish.cur, finish.last) are uninitialized storage.
[map, map + map_size) is a valid, non-empty range.
[start.node, finish.node] is a valid range contained within [map, map + map_size).
A pointer in the range [map, map + map_size) points to an allocated node if and only if the pointer is in the range [start.node, finish.node].
Here's the magic: nothing in deque is 'aware' of the discontiguous storage!
The memory setup and layout occurs in the parent, _Base, and the iterator class is entirely responsible for 'leaping' from one node to the next. All the implementation routines for deque itself work only through the start and finish iterators. This keeps the routines simple and sane, and we can use other standard algorithms as well.
Definition at line 638 of file stl_deque.h.
Constructor & Destructor Documentation
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> std::deque< _Tp, _Alloc >::deque () [inline]
Default constructor creates no elements.
Definition at line 690 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> std::deque< _Tp, _Alloc >::deque (const allocator_type & __a) [inline, explicit]
Creates a deque with no elements.
Parameters:
a An allocator object.
Definition at line 698 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> std::deque< _Tp, _Alloc >::deque (size_type __n, const value_type & __value = value_type(), const allocator_type & __a = allocator_type()) [inline, explicit]
Creates a deque with copies of an exemplar element.
Parameters:
n The number of elements to initially create.
value An element to copy.
a An allocator.
This constructor fills the deque with n copies of value.
Definition at line 710 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> std::deque< _Tp, _Alloc >::deque (const deque< _Tp, _Alloc > & __x) [inline]
Deque copy constructor.
Parameters:
x A deque of identical element and allocator types.
The newly-created deque uses a copy of the allocation object used by x.
Definition at line 722 of file stl_deque.h.
References std::deque< _Tp, _Alloc >::begin(), and std::deque< _Tp, _Alloc >::end().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> std::deque< _Tp, _Alloc >::deque (deque< _Tp, _Alloc > && __x) [inline]
Deque move constructor.
Parameters:
x A deque of identical element and allocator types.
The newly-created deque contains the exact contents of x. The contents of x are a valid, but unspecified deque.
Definition at line 736 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> std::deque< _Tp, _Alloc >::deque (initializer_list< value_type > __l, const allocator_type & __a = allocator_type()) [inline]
Builds a deque from an initializer list.
Parameters:
l An initializer_list.
a An allocator object.
Create a deque consisting of copies of the elements in the initializer_list l.
This will call the element type's copy constructor N times (where N is l.size()) and do no memory reallocation.
Definition at line 750 of file stl_deque.h.
References std::initializer_list< _E >::begin(), and std::initializer_list< _E >::end().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> template<typename _InputIterator > std::deque< _Tp, _Alloc >::deque (_InputIterator __first, _InputIterator __last, const allocator_type & __a = allocator_type()) [inline]
Builds a deque from a range.
Parameters:
first An input iterator.
last An input iterator.
a An allocator object.
Create a deque consisting of copies of the elements from [first, last).
If the iterators are forward, bidirectional, or random-access, then this will call the elements' copy constructor N times (where N is distance(first,last)) and do no memory reallocation. But if only input iterators are used, then this will do at most 2N calls to the copy constructor, and logN memory reallocations.
Definition at line 775 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> std::deque< _Tp, _Alloc >::~deque () [inline]
The dtor only erases the elements, and note that if the elements themselves are pointers, the pointed-to memory is not touched in any way. Managing the pointer is the user's responsibility.
Definition at line 789 of file stl_deque.h.
Member Function Documentation
template<typename _Tp , typename _Alloc > void deque::_M_fill_initialize (const value_type & __value) [inline, protected]
Fills the deque with copies of value.
Parameters:
value Initial value.
Returns:
Nothing.
Precondition:
_M_start and _M_finish have already been initialized, but none of the deque's elements have yet been constructed.
This function is called only when the user provides an explicit size (with or without an explicit exemplar value).
Definition at line 277 of file deque.tcc.
References std::_Destroy().
template<typename _Tp , typename _Alloc > void deque::_M_new_elements_at_back (size_type __new_elements) [inline, protected]
Memory-handling helpers for the previous internal insert functions.
Definition at line 771 of file deque.tcc.
References std::deque< _Tp, _Alloc >::_M_reserve_map_at_back(), std::deque< _Tp, _Alloc >::max_size(), and std::deque< _Tp, _Alloc >::size().
template<typename _Tp , typename _Alloc > void deque::_M_new_elements_at_front (size_type __new_elements) [inline, protected]
Memory-handling helpers for the previous internal insert functions.
Definition at line 746 of file deque.tcc.
References std::deque< _Tp, _Alloc >::_M_reserve_map_at_front(), std::deque< _Tp, _Alloc >::max_size(), and std::deque< _Tp, _Alloc >::size().
template<typename _Tp , typename _Alloc > void deque::_M_pop_back_aux () [inline, protected]
Helper functions for push_* and pop_*.
Definition at line 427 of file deque.tcc.
template<typename _Tp , typename _Alloc > void deque::_M_pop_front_aux () [inline, protected]
Helper functions for push_* and pop_*.
Definition at line 442 of file deque.tcc.
template<typename _Tp , typename _Alloc > template<typename... _Args> void deque::_M_push_back_aux (_Args &&... __args) [inline, protected]
Helper functions for push_* and pop_*.
Definition at line 361 of file deque.tcc.
template<typename _Tp , typename _Alloc > template<typename... _Args> void deque::_M_push_front_aux (_Args &&... __args) [inline, protected]
Helper functions for push_* and pop_*.
Definition at line 395 of file deque.tcc.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::deque< _Tp, _Alloc >::_M_range_check (size_type __n) const [inline, protected]
Safety check used only from at().
Definition at line 1076 of file stl_deque.h.
template<typename _Tp , typename _Alloc > template<typename _ForwardIterator > void deque::_M_range_initialize (_ForwardIterator __first, _ForwardIterator __last, std::forward_iterator_tag) [inline, protected]
Fills the deque with whatever is in [first,last).
Parameters:
first An input iterator.
last An input iterator.
Returns:
Nothing.
If the iterators are actually forward iterators (or better), then the memory layout can be done all at once. Else we move forward using push_back on each value from the iterator.
Definition at line 323 of file deque.tcc.
References std::_Destroy(), std::_Deque_base< _Tp, _Alloc >::_M_initialize_map(), std::advance(), and std::distance().
template<typename _Tp , typename _Alloc > template<typename _InputIterator > void deque::_M_range_initialize (_InputIterator __first, _InputIterator __last, std::input_iterator_tag) [inline, protected]
Fills the deque with whatever is in [first,last).
Parameters:
first An input iterator.
last An input iterator.
Returns:
Nothing.
If the iterators are actually forward iterators (or better), then the memory layout can be done all at once. Else we move forward using push_back on each value from the iterator.
Definition at line 303 of file deque.tcc.
References std::_Deque_base< _Tp, _Alloc >::_M_initialize_map(), std::deque< _Tp, _Alloc >::clear(), and std::deque< _Tp, _Alloc >::push_back().
template<typename _Tp , typename _Alloc > void deque::_M_reallocate_map (size_type __nodes_to_add, bool __add_at_front) [inline, protected]
Memory-handling helpers for the major map.
Makes sure the _M_map has space for new nodes. Does not actually add the nodes. Can invalidate _M_map pointers. (And consequently, deque iterators.)
Definition at line 796 of file deque.tcc.
References std::copy_backward(), and std::max().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> iterator std::deque< _Tp, _Alloc >::_M_reserve_elements_at_back (size_type __n) [inline, protected]
Memory-handling helpers for the previous internal insert functions.
Definition at line 1689 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> iterator std::deque< _Tp, _Alloc >::_M_reserve_elements_at_front (size_type __n) [inline, protected]
Memory-handling helpers for the previous internal insert functions.
Definition at line 1679 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::deque< _Tp, _Alloc >::_M_reserve_map_at_back (size_type __nodes_to_add = 1) [inline, protected]
Memory-handling helpers for the major map.
Makes sure the _M_map has space for new nodes. Does not actually add the nodes. Can invalidate _M_map pointers. (And consequently, deque iterators.)
Definition at line 1715 of file stl_deque.h.
Referenced by std::deque< _Tp, _Alloc >::_M_new_elements_at_back().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::deque< _Tp, _Alloc >::_M_reserve_map_at_front (size_type __nodes_to_add = 1) [inline, protected]
Memory-handling helpers for the major map.
Makes sure the _M_map has space for new nodes. Does not actually add the nodes. Can invalidate _M_map pointers. (And consequently, deque iterators.)
Definition at line 1723 of file stl_deque.h.
Referenced by std::deque< _Tp, _Alloc >::_M_new_elements_at_front().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::deque< _Tp, _Alloc >::assign (initializer_list< value_type > __l) [inline]
Assigns an initializer list to a deque.
Parameters:
l An initializer_list.
This function fills a deque with copies of the elements in the initializer_list l.
Note that the assignment completely changes the deque and that the resulting deque's size is the same as the number of elements assigned. Old data may be lost.
Definition at line 885 of file stl_deque.h.
References std::deque< _Tp, _Alloc >::assign(), std::initializer_list< _E >::begin(), and std::initializer_list< _E >::end().
Referenced by std::deque< _Tp, _Alloc >::assign().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> template<typename _InputIterator > void std::deque< _Tp, _Alloc >::assign (_InputIterator __first, _InputIterator __last) [inline]
Assigns a range to a deque.
Parameters:
first An input iterator.
last An input iterator.
This function fills a deque with copies of the elements in the range [first,last).
Note that the assignment completely changes the deque and that the resulting deque's size is the same as the number of elements assigned. Old data may be lost.
Definition at line 866 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::deque< _Tp, _Alloc >::assign (size_type __n, const value_type & __val) [inline]
Assigns a given value to a deque.
Parameters:
n Number of elements to be assigned.
val Value to be assigned.
This function fills a deque with n copies of the given value. Note that the assignment completely changes the deque and that the resulting deque's size is the same as the number of elements assigned. Old data may be lost.
Definition at line 849 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_reference std::deque< _Tp, _Alloc >::at (size_type __n) const [inline]
Provides access to the data contained in the deque.
Parameters:
n The index of the element for which data should be accessed.
Returns:
Read-only (constant) reference to data.
Exceptions:
std::out_of_range If n is an invalid index.
This function provides for safer data access. The parameter is first checked that it is in the range of the deque. The function throws out_of_range if the check fails.
Definition at line 1113 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> reference std::deque< _Tp, _Alloc >::at (size_type __n) [inline]
Provides access to the data contained in the deque.
Parameters:
n The index of the element for which data should be accessed.
Returns:
Read/write reference to data.
Exceptions:
std::out_of_range If n is an invalid index.
This function provides for safer data access. The parameter is first checked that it is in the range of the deque. The function throws out_of_range if the check fails.
Definition at line 1095 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_reference std::deque< _Tp, _Alloc >::back () const [inline]
Returns a read-only (constant) reference to the data at the last element of the deque.
Definition at line 1152 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> reference std::deque< _Tp, _Alloc >::back () [inline]
Returns a read/write reference to the data at the last element of the deque.
Definition at line 1140 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_iterator std::deque< _Tp, _Alloc >::begin () const [inline]
Returns a read-only (constant) iterator that points to the first element in the deque. Iteration is done in ordinary element order.
Definition at line 908 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> iterator std::deque< _Tp, _Alloc >::begin () [inline]
Returns a read/write iterator that points to the first element in the deque. Iteration is done in ordinary element order.
Definition at line 900 of file stl_deque.h.
Referenced by std::deque< _Tp, _Alloc >::deque(), std::deque< _Tp, _Alloc >::erase(), and std::operator==().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_iterator std::deque< _Tp, _Alloc >::cbegin () const [inline]
Returns a read-only (constant) iterator that points to the first element in the deque. Iteration is done in ordinary element order.
Definition at line 971 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_iterator std::deque< _Tp, _Alloc >::cend () const [inline]
Returns a read-only (constant) iterator that points one past the last element in the deque. Iteration is done in ordinary element order.
Definition at line 980 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::deque< _Tp, _Alloc >::clear () [inline]
Erases all the elements. Note that this function only erases the elements, and that if the elements themselves are pointers, the pointed-to memory is not touched in any way. Managing the pointer is the user's responsibility.
Definition at line 1422 of file stl_deque.h.
Referenced by std::deque< _Tp, _Alloc >::_M_range_initialize(), and std::deque< _Tp, _Alloc >::erase().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_reverse_iterator std::deque< _Tp, _Alloc >::crbegin () const [inline]
Returns a read-only (constant) reverse iterator that points to the last element in the deque. Iteration is done in reverse element order.
Definition at line 989 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_reverse_iterator std::deque< _Tp, _Alloc >::crend () const [inline]
Returns a read-only (constant) reverse iterator that points to one before the first element in the deque. Iteration is done in reverse element order.
Definition at line 998 of file stl_deque.h.
template<typename _Tp , typename _Alloc > template<typename... _Args> deque< _Tp, _Alloc >::iterator deque::emplace (iterator __position, _Args &&... __args) [inline]
Inserts an object in deque before specified iterator.
Parameters:
position An iterator into the deque.
args Arguments.
Returns:
An iterator that points to the inserted data.
This function will insert an object of type T constructed with T(std::forward<Args>(args)...) before the specified location.
Definition at line 144 of file deque.tcc.
References std::_Deque_iterator< _Tp, _Ref, _Ptr >::_M_cur, std::deque< _Tp, _Alloc >::push_back(), and std::deque< _Tp, _Alloc >::push_front().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> bool std::deque< _Tp, _Alloc >::empty () const [inline]
Returns true if the deque is empty. (Thus begin() would equal end().)
Definition at line 1039 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_iterator std::deque< _Tp, _Alloc >::end () const [inline]
Returns a read-only (constant) iterator that points one past the last element in the deque. Iteration is done in ordinary element order.
Definition at line 926 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> iterator std::deque< _Tp, _Alloc >::end () [inline]
Returns a read/write iterator that points one past the last element in the deque. Iteration is done in ordinary element order.
Definition at line 917 of file stl_deque.h.
Referenced by std::deque< _Tp, _Alloc >::deque(), std::deque< _Tp, _Alloc >::erase(), and std::operator==().
template<typename _Tp , typename _Alloc > deque< _Tp, _Alloc >::iterator deque::erase (iterator __first, iterator __last) [inline]
Remove a range of elements.
Parameters:
first Iterator pointing to the first element to be erased.
last Iterator pointing to one past the last element to be erased.
Returns:
An iterator pointing to the element pointed to by last prior to erasing (or end()).
This function will erase the elements in the range [first,last) and shorten the deque accordingly.
The user is cautioned that this function only erases the elements, and that if the elements themselves are pointers, the pointed-to memory is not touched in any way. Managing the pointer is the user's responsibility.
Definition at line 189 of file deque.tcc.
References std::deque< _Tp, _Alloc >::begin(), std::deque< _Tp, _Alloc >::clear(), std::deque< _Tp, _Alloc >::end(), and std::deque< _Tp, _Alloc >::size().
template<typename _Tp , typename _Alloc > deque< _Tp, _Alloc >::iterator deque::erase (iterator __position) [inline]
Remove element at given position.
Parameters:
position Iterator pointing to element to be erased.
Returns:
An iterator pointing to the next element (or end()).
This function will erase the element at the given position and thus shorten the deque by one.
The user is cautioned that this function only erases the element, and that if the element is itself a pointer, the pointed-to memory is not touched in any way. Managing the pointer is the user's responsibility.
Definition at line 166 of file deque.tcc.
References std::deque< _Tp, _Alloc >::begin(), std::deque< _Tp, _Alloc >::end(), std::deque< _Tp, _Alloc >::pop_back(), std::deque< _Tp, _Alloc >::pop_front(), and std::deque< _Tp, _Alloc >::size().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_reference std::deque< _Tp, _Alloc >::front () const [inline]
Returns a read-only (constant) reference to the data at the first element of the deque.
Definition at line 1132 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> reference std::deque< _Tp, _Alloc >::front () [inline]
Returns a read/write reference to the data at the first element of the deque.
Definition at line 1124 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> allocator_type std::deque< _Tp, _Alloc >::get_allocator () const [inline]
Get a copy of the memory allocation object.
Reimplemented from std::_Deque_base< _Tp, _Alloc >.
Definition at line 891 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> template<typename _InputIterator > void std::deque< _Tp, _Alloc >::insert (iterator __position, _InputIterator __first, _InputIterator __last) [inline]
Inserts a range into the deque.
Parameters:
position An iterator into the deque.
first An input iterator.
last An input iterator.
This function will insert copies of the data in the range [first,last) into the deque before the location specified by pos. This is known as 'range insert.'
Definition at line 1345 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::deque< _Tp, _Alloc >::insert (iterator __position, size_type __n, const value_type & __x) [inline]
Inserts a number of copies of given data into the deque.
Parameters:
position An iterator into the deque.
n Number of elements to be inserted.
x Data to be inserted.
This function will insert a specified number of copies of the given data before the location specified by position.
Definition at line 1330 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::deque< _Tp, _Alloc >::insert (iterator __p, initializer_list< value_type > __l) [inline]
Inserts an initializer list into the deque.
Parameters:
p An iterator into the deque.
l An initializer_list.
This function will insert copies of the data in the initializer_list l into the deque before the location specified by p. This is known as 'list insert.'
Definition at line 1316 of file stl_deque.h.
References std::initializer_list< _E >::begin(), std::initializer_list< _E >::end(), and std::deque< _Tp, _Alloc >::insert().
Referenced by std::deque< _Tp, _Alloc >::insert().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> iterator std::deque< _Tp, _Alloc >::insert (iterator __position, value_type && __x) [inline]
Inserts given rvalue into deque before specified iterator.
Parameters:
position An iterator into the deque.
x Data to be inserted.
Returns:
An iterator that points to the inserted data.
This function will insert a copy of the given rvalue before the specified location.
Definition at line 1303 of file stl_deque.h.
References std::move().
template<typename _Tp , typename _Alloc > deque< _Tp, _Alloc >::iterator deque::insert (iterator __position, const value_type & __x) [inline]
Inserts given value into deque before specified iterator.
Parameters:
position An iterator into the deque.
x Data to be inserted.
Returns:
An iterator that points to the inserted data.
This function will insert a copy of the given value before the specified location.
Definition at line 121 of file deque.tcc.
References std::_Deque_iterator< _Tp, _Ref, _Ptr >::_M_cur, std::deque< _Tp, _Alloc >::push_back(), and std::deque< _Tp, _Alloc >::push_front().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> size_type std::deque< _Tp, _Alloc >::max_size () const [inline]
Returns the size() of the largest possible deque.
Definition at line 1010 of file stl_deque.h.
Referenced by std::deque< _Tp, _Alloc >::_M_new_elements_at_back(), and std::deque< _Tp, _Alloc >::_M_new_elements_at_front().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> deque& std::deque< _Tp, _Alloc >::operator= (initializer_list< value_type > __l) [inline]
Assigns an initializer list to a deque.
Parameters:
l An initializer_list.
This function fills a deque with copies of the elements in the initializer_list l.
Note that the assignment completely changes the deque and that the resulting deque's size is the same as the number of elements assigned. Old data may be lost.
Definition at line 831 of file stl_deque.h.
References std::initializer_list< _E >::begin(), and std::initializer_list< _E >::end().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> deque& std::deque< _Tp, _Alloc >::operator= (deque< _Tp, _Alloc > && __x) [inline]
Deque move assignment operator.
Parameters:
x A deque of identical element and allocator types.
The contents of x are moved into this deque (without copying). x is a valid, but unspecified deque.
Definition at line 811 of file stl_deque.h.
template<typename _Tp , typename _Alloc > deque< _Tp, _Alloc > & deque::operator= (const deque< _Tp, _Alloc > & __x) [inline]
Deque assignment operator.
Parameters:
x A deque of identical element and allocator types.
All the elements of x are copied, but unlike the copy constructor, the allocator object is not copied.
Definition at line 65 of file deque.tcc.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_reference std::deque< _Tp, _Alloc >::operator[] (size_type __n) const [inline]
Subscript access to the data contained in the deque.
Parameters:
n The index of the element for which data should be accessed.
Returns:
Read-only (constant) reference to data.
This operator allows for easy, array-style, data access. Note that data access with this operator is unchecked and out_of_range lookups are not defined. (For checked lookups see at().)
Definition at line 1070 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> reference std::deque< _Tp, _Alloc >::operator[] (size_type __n) [inline]
Subscript access to the data contained in the deque.
Parameters:
n The index of the element for which data should be accessed.
Returns:
Read/write reference to data.
This operator allows for easy, array-style, data access. Note that data access with this operator is unchecked and out_of_range lookups are not defined. (For checked lookups see at().)
Definition at line 1055 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::deque< _Tp, _Alloc >::pop_back () [inline]
Removes last element.
This is a typical stack operation. It shrinks the deque by one.
Note that no data is returned, and if the last element's data is needed, it should be retrieved before pop_back() is called.
Definition at line 1253 of file stl_deque.h.
Referenced by std::deque< _Tp, _Alloc >::erase().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::deque< _Tp, _Alloc >::pop_front () [inline]
Removes first element.
This is a typical stack operation. It shrinks the deque by one.
Note that no data is returned, and if the first element's data is needed, it should be retrieved before pop_front() is called.
Definition at line 1232 of file stl_deque.h.
Referenced by std::deque< _Tp, _Alloc >::erase().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::deque< _Tp, _Alloc >::push_back (const value_type & __x) [inline]
Add data to the end of the deque.
Parameters:
x Data to be added.
This is a typical stack operation. The function creates an element at the end of the deque and assigns the given data to it. Due to the nature of a deque this operation can be done in constant time.
Definition at line 1201 of file stl_deque.h.
Referenced by std::deque< _Tp, _Alloc >::_M_range_initialize(), std::deque< _Tp, _Alloc >::emplace(), and std::deque< _Tp, _Alloc >::insert().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::deque< _Tp, _Alloc >::push_front (const value_type & __x) [inline]
Add data to the front of the deque.
Parameters:
x Data to be added.
This is a typical stack operation. The function creates an element at the front of the deque and assigns the given data to it. Due to the nature of a deque this operation can be done in constant time.
Definition at line 1170 of file stl_deque.h.
References std::_Deque_iterator< _Tp, _Ref, _Ptr >::_M_cur.
Referenced by std::deque< _Tp, _Alloc >::emplace(), and std::deque< _Tp, _Alloc >::insert().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_reverse_iterator std::deque< _Tp, _Alloc >::rbegin () const [inline]
Returns a read-only (constant) reverse iterator that points to the last element in the deque. Iteration is done in reverse element order.
Definition at line 944 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> reverse_iterator std::deque< _Tp, _Alloc >::rbegin () [inline]
Returns a read/write reverse iterator that points to the last element in the deque. Iteration is done in reverse element order.
Definition at line 935 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_reverse_iterator std::deque< _Tp, _Alloc >::rend () const [inline]
Returns a read-only (constant) reverse iterator that points to one before the first element in the deque. Iteration is done in reverse element order.
Definition at line 962 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> reverse_iterator std::deque< _Tp, _Alloc >::rend () [inline]
Returns a read/write reverse iterator that points to one before the first element in the deque. Iteration is done in reverse element order.
Definition at line 953 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::deque< _Tp, _Alloc >::resize (size_type __new_size, value_type __x = value_type()) [inline]
Resizes the deque to the specified number of elements.
Parameters:
new_size Number of elements the deque should contain.
x Data with which new elements should be populated.
This function will resize the deque to the specified number of elements. If the number is smaller than the deque's current size the deque is truncated, otherwise the deque is extended and new elements are populated with given data.
Definition at line 1025 of file stl_deque.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> size_type std::deque< _Tp, _Alloc >::size () const [inline]
Returns the number of elements in the deque.
Definition at line 1005 of file stl_deque.h.
Referenced by std::deque< _Tp, _Alloc >::_M_new_elements_at_back(), std::deque< _Tp, _Alloc >::_M_new_elements_at_front(), std::deque< _Tp, _Alloc >::erase(), and std::operator==().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::deque< _Tp, _Alloc >::swap (deque< _Tp, _Alloc > && __x) [inline]
Swaps data with another deque.
Parameters:
x A deque of the same element and allocator types.
This exchanges the elements between two deques in constant time. (Four pointers, so it should be quite fast.) Note that the global std::swap() function is specialized such that std::swap(d1,d2) will feed to this function.
Definition at line 1399 of file stl_deque.h.
References std::_Deque_base< _Tp, _Alloc >::_M_get_Tp_allocator(), and std::_Deque_base< _Tp, _Alloc >::_M_impl.
Referenced by std::swap().
Author
Generated automatically by Doxygen for libstdc++ from the source code.