.TH "std::_Safe_tuple_element" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::_Safe_tuple_element \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBstd::_Safe_tuple_element_impl<__i, _Tuple, (__i >= 0 && __i < tuple_size<_Tuple>::value)>\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<int __i, typename _Tuple> struct std::_Safe_tuple_element< __i, _Tuple >"
Like tuple_element, but returns \fC_No_tuple_element\fP when tuple_element would return an error. 
.PP
Definition at line 934 of file tr1_impl/functional.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
