.TH "std::bad_function_call" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::bad_function_call \- Exception class thrown when class template function's operator() is called with an empty target.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fBstd::exception\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual const char * \fBwhat\fP () const   throw ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Exception class thrown when class template function's operator() is called with an empty target. 
.PP
Definition at line 1370 of file tr1_impl/functional.
.SH "Member Function Documentation"
.PP 
.SS "virtual const char* std::exception::what () const  throw ()\fC [virtual, inherited]\fP"
.PP
Returns a C-style character string describing the general cause of the current error. 
.PP
Reimplemented in \fBstd::bad_exception\fP, \fBstd::bad_alloc\fP, \fBstd::bad_cast\fP, \fBstd::bad_typeid\fP, \fBstd::lock_error\fP, \fBstd::logic_error\fP, \fBstd::runtime_error\fP, and \fBstd::ios_base::ios_base::failure\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
