.TH "std::collate" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::collate \- Facet for localized string comparison.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fBstd::locale::facet\fP.
.PP
.SS "Public Types"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "typedef _CharT \fBchar_type\fP"
.br
.ti -1c
.RI "typedef \fBbasic_string\fP< _CharT > \fBstring_type\fP"
.br
.in -1c
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<> int \fB_M_compare\fP (const wchar_t *, const wchar_t *) const"
.br
.ti -1c
.RI "template<> int \fB_M_compare\fP (const char *, const char *) const"
.br
.ti -1c
.RI "int \fB_M_compare\fP (const _CharT *, const _CharT *) const "
.br
.ti -1c
.RI "template<> size_t \fB_M_transform\fP (wchar_t *, const wchar_t *, size_t) const"
.br
.ti -1c
.RI "template<> size_t \fB_M_transform\fP (char *, const char *, size_t) const"
.br
.ti -1c
.RI "size_t \fB_M_transform\fP (_CharT *, const _CharT *, size_t) const "
.br
.ti -1c
.RI "\fBcollate\fP (__c_locale __cloc, size_t __refs=0)"
.br
.ti -1c
.RI "\fBcollate\fP (size_t __refs=0)"
.br
.ti -1c
.RI "int \fBcompare\fP (const _CharT *__lo1, const _CharT *__hi1, const _CharT *__lo2, const _CharT *__hi2) const "
.br
.ti -1c
.RI "long \fBhash\fP (const _CharT *__lo, const _CharT *__hi) const "
.br
.ti -1c
.RI "\fBstring_type\fP \fBtransform\fP (const _CharT *__lo, const _CharT *__hi) const "
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBlocale::id\fP \fBid\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBdo_compare\fP (const _CharT *__lo1, const _CharT *__hi1, const _CharT *__lo2, const _CharT *__hi2) const "
.br
.ti -1c
.RI "virtual long \fBdo_hash\fP (const _CharT *__lo, const _CharT *__hi) const "
.br
.ti -1c
.RI "virtual \fBstring_type\fP \fBdo_transform\fP (const _CharT *__lo, const _CharT *__hi) const "
.br
.ti -1c
.RI "virtual \fB~collate\fP ()"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static __c_locale \fB_S_clone_c_locale\fP (__c_locale &__cloc)"
.br
.ti -1c
.RI "static void \fB_S_create_c_locale\fP (__c_locale &__cloc, const char *__s, __c_locale __old=0)"
.br
.ti -1c
.RI "static void \fB_S_destroy_c_locale\fP (__c_locale &__cloc)"
.br
.ti -1c
.RI "static __c_locale \fB_S_get_c_locale\fP ()"
.br
.ti -1c
.RI "static const char * \fB_S_get_c_name\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "__c_locale \fB_M_c_locale_collate\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBlocale::_Impl\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _CharT> class std::collate< _CharT >"
Facet for localized string comparison. 

This facet encapsulates the code to compare strings in a localized manner.
.PP
The \fBcollate\fP template uses protected virtual functions to provide the actual results. The public accessors forward the call to the virtual functions. These virtual functions are hooks for developers to implement the behavior they require from the \fBcollate\fP facet. 
.PP
Definition at line 604 of file locale_classes.h.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename _CharT> typedef _CharT \fBstd::collate\fP< _CharT >::\fBchar_type\fP"
.PP
Public typedefs. 
.PP
Reimplemented in \fBstd::collate_byname< _CharT >\fP.
.PP
Definition at line 610 of file locale_classes.h.
.SS "template<typename _CharT> typedef \fBbasic_string\fP<_CharT> \fBstd::collate\fP< _CharT >::\fBstring_type\fP"
.PP
Public typedefs. 
.PP
Reimplemented in \fBstd::collate_byname< _CharT >\fP.
.PP
Definition at line 611 of file locale_classes.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename _CharT> \fBstd::collate\fP< _CharT >::\fBcollate\fP (size_t __refs = \fC0\fP)\fC [inline, explicit]\fP"
.PP
Constructor performs initialization. 
.PP
This is the constructor provided by the standard.
.PP
\fBParameters:\fP
.RS 4
\fIrefs\fP Passed to the base facet class. 
.RE
.PP

.PP
Definition at line 631 of file locale_classes.h.
.SS "template<typename _CharT> \fBstd::collate\fP< _CharT >::\fBcollate\fP (__c_locale __cloc, size_t __refs = \fC0\fP)\fC [inline, explicit]\fP"
.PP
Internal constructor. Not for general use. 
.PP
This is a constructor for use by the library itself to \fBset\fP up new locales.
.PP
\fBParameters:\fP
.RS 4
\fIcloc\fP The 'C' \fBlocale\fP. 
.br
\fIrefs\fP Passed to the base facet class. 
.RE
.PP

.PP
Definition at line 645 of file locale_classes.h.
.SS "template<typename _CharT> virtual \fBstd::collate\fP< _CharT >::~\fBcollate\fP ()\fC [inline, protected, virtual]\fP"
.PP
Destructor. 
.PP
Definition at line 708 of file locale_classes.h.
.SH "Member Function Documentation"
.PP 
.SS "template<typename _CharT> int \fBstd::collate\fP< _CharT >::compare (const _CharT * __lo1, const _CharT * __hi1, const _CharT * __lo2, const _CharT * __hi2) const\fC [inline]\fP"
.PP
Compare two strings. 
.PP
This function compares two strings and returns the result by calling \fBcollate::do_compare()\fP.
.PP
\fBParameters:\fP
.RS 4
\fIlo1\fP Start of string 1. 
.br
\fIhi1\fP End of string 1. 
.br
\fIlo2\fP Start of string 2. 
.br
\fIhi2\fP End of string 2. 
.RE
.PP
\fBReturns:\fP
.RS 4
1 if string1 > string2, -1 if string1 < string2, else 0. 
.RE
.PP

.PP
Definition at line 662 of file locale_classes.h.
.SS "template<typename _CharT> int \fBstd::collate\fP< _CharT >::do_compare (const _CharT * __lo1, const _CharT * __hi1, const _CharT * __lo2, const _CharT * __hi2) const\fC [inline, protected, virtual]\fP"
.PP
Compare two strings. 
.PP
This function is a hook for derived classes to change the value returned. 
.PP
\fBSee also:\fP
.RS 4
\fBcompare()\fP.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIlo1\fP Start of string 1. 
.br
\fIhi1\fP End of string 1. 
.br
\fIlo2\fP Start of string 2. 
.br
\fIhi2\fP End of string 2. 
.RE
.PP
\fBReturns:\fP
.RS 4
1 if string1 > string2, -1 if string1 < string2, else 0. 
.RE
.PP

.PP
Definition at line 134 of file locale_classes.tcc.
.PP
References std::basic_string< _CharT, _Traits, _Alloc >::c_str(), std::basic_string< _CharT, _Traits, _Alloc >::data(), and std::basic_string< _CharT, _Traits, _Alloc >::length().
.SS "template<typename _CharT> long \fBstd::collate\fP< _CharT >::do_hash (const _CharT * __lo, const _CharT * __hi) const\fC [inline, protected, virtual]\fP"
.PP
Return \fBhash\fP of a string. 
.PP
This function computes and returns a \fBhash\fP on the input string. This function is a hook for derived classes to change the value returned.
.PP
\fBParameters:\fP
.RS 4
\fIlo\fP Start of string. 
.br
\fIhi\fP End of string. 
.RE
.PP
\fBReturns:\fP
.RS 4
Hash value. 
.RE
.PP

.PP
Definition at line 229 of file locale_classes.tcc.
.SS "template<typename _CharT> \fBcollate\fP< _CharT >::\fBstring_type\fP \fBstd::collate\fP< _CharT >::do_transform (const _CharT * __lo, const _CharT * __hi) const\fC [inline, protected, virtual]\fP"
.PP
Transform string to comparable form. 
.PP
This function is a hook for derived classes to change the value returned.
.PP
\fBParameters:\fP
.RS 4
\fIlo1\fP Start of string 1. 
.br
\fIhi1\fP End of string 1. 
.br
\fIlo2\fP Start of string 2. 
.br
\fIhi2\fP End of string 2. 
.RE
.PP
\fBReturns:\fP
.RS 4
1 if string1 > string2, -1 if string1 < string2, else 0. 
.RE
.PP

.PP
Definition at line 173 of file locale_classes.tcc.
.PP
References std::basic_string< _CharT, _Traits, _Alloc >::append(), std::basic_string< _CharT, _Traits, _Alloc >::c_str(), std::basic_string< _CharT, _Traits, _Alloc >::data(), std::basic_string< _CharT, _Traits, _Alloc >::length(), and std::basic_string< _CharT, _Traits, _Alloc >::push_back().
.SS "template<typename _CharT> long \fBstd::collate\fP< _CharT >::\fBhash\fP (const _CharT * __lo, const _CharT * __hi) const\fC [inline]\fP"
.PP
Return \fBhash\fP of a string. 
.PP
This function computes and returns a \fBhash\fP on the input string. It does so by returning \fBcollate::do_hash()\fP.
.PP
\fBParameters:\fP
.RS 4
\fIlo\fP Start of string. 
.br
\fIhi\fP End of string. 
.RE
.PP
\fBReturns:\fP
.RS 4
Hash value. 
.RE
.PP

.PP
Definition at line 695 of file locale_classes.h.
.SS "template<typename _CharT> \fBstring_type\fP \fBstd::collate\fP< _CharT >::transform (const _CharT * __lo, const _CharT * __hi) const\fC [inline]\fP"
.PP
Transform string to comparable form. 
.PP
This function is a wrapper for strxfrm functionality. It takes the input string and returns a modified string that can be directly compared to other transformed strings. In the 'C' \fBlocale\fP, this function just returns a copy of the input string. In some other locales, it may replace two chars with one, change a char for another, etc. It does so by returning \fBcollate::do_transform()\fP.
.PP
\fBParameters:\fP
.RS 4
\fIlo\fP Start of string. 
.br
\fIhi\fP End of string. 
.RE
.PP
\fBReturns:\fP
.RS 4
Transformed string_type. 
.RE
.PP

.PP
Definition at line 681 of file locale_classes.h.
.PP
Referenced by std::regex_traits< _Ch_type >::transform().
.SH "Member Data Documentation"
.PP 
.SS "template<typename _CharT> \fBlocale::id\fP \fBstd::collate\fP< _CharT >::\fBid\fP\fC [inline, static]\fP"
.PP
Numpunct facet id. 
.PP
Definition at line 621 of file locale_classes.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
