.TH "std::forward_iterator_tag" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::forward_iterator_tag \- Forward iterators support a superset of input \fBiterator\fP operations.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fBstd::input_iterator_tag\fP.
.PP
Inherited by \fBstd::bidirectional_iterator_tag\fP.
.PP
.SH "Detailed Description"
.PP 
Forward iterators support a superset of input \fBiterator\fP operations. 
.PP
Definition at line 83 of file stl_iterator_base_types.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
