.TH "std::unary_negate" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::unary_negate \- One of the \fBnegation functors\fP.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fBunary_function< _Predicate::argument_type, bool >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _Predicate::argument_type \fBargument_type\fP"
.br
.ti -1c
.RI "typedef bool \fBresult_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const typename _Predicate::argument_type &__x) const "
.br
.ti -1c
.RI "\fBunary_negate\fP (const _Predicate &__x)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "_Predicate \fB_M_pred\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Predicate> class std::unary_negate< _Predicate >"
One of the \fBnegation functors\fP. 
.PP
Definition at line 346 of file stl_function.h.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef _Predicate::argument_type  \fBstd::unary_function\fP< _Predicate::argument_type , bool  >::\fBargument_type\fP\fC [inherited]\fP"
.PP
\fCargument_type\fP is the type of the argument (no surprises here) 
.PP
Definition at line 102 of file stl_function.h.
.SS "typedef bool  \fBstd::unary_function\fP< _Predicate::argument_type , bool  >::\fBresult_type\fP\fC [inherited]\fP"
.PP
\fCresult_type\fP is the return type 
.PP
Definition at line 105 of file stl_function.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
