.TH "std::add_lvalue_reference" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::add_lvalue_reference \- \fBadd_lvalue_reference\fP  

.PP
.SH SYNOPSIS
.br
.PP
Inherits std::__add_lvalue_reference_helper<_Tp>.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _Tp \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> struct std::add_lvalue_reference< _Tp >"
\fBadd_lvalue_reference\fP 
.PP
Definition at line 124 of file type_traits.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
