.TH "std::is_array" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::is_array \- \fBis_array\fP  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fBstd::integral_constant< bool, false >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBintegral_constant\fP< _Tp, __v > \fBtype\fP"
.br
.ti -1c
.RI "typedef _Tp \fBvalue_type\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const _Tp \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename> struct std::is_array< typename >"
\fBis_array\fP 
.PP
Definition at line 147 of file tr1_impl/type_traits.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
