.TH "std::remove_pointer" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::remove_pointer \- \fBremove_pointer\fP  

.PP
.SH SYNOPSIS
.br
.PP
Inherits std::__remove_pointer_helper<_Tp, remove_cv<_Tp>::type>.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _Tp \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> struct std::remove_pointer< _Tp >"
\fBremove_pointer\fP 
.PP
Definition at line 482 of file tr1_impl/type_traits.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
