.TH "std::_Fnv_hash" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::_Fnv_hash \- Dummy generic implementation (for sizeof(size_t) != 4, 8).  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static size_t \fBhash\fP (const char *__first, size_t __length)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<size_t = sizeof(size_t)> struct std::_Fnv_hash< size_t >"
Dummy generic implementation (for sizeof(size_t) != 4, 8). 
.PP
Definition at line 85 of file tr1_impl/functional_hash.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
