.TH "std::ratio_multiply" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::ratio_multiply \- \fBratio_multiply\fP  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBratio\fP< __safe_multiply<(_R1::num/__gcd1),(_R2::num/__gcd2)>::value, __safe_multiply<(_R1::den/__gcd2),(_R2::den/__gcd1)>::value > \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _R1, typename _R2> struct std::ratio_multiply< _R1, _R2 >"
\fBratio_multiply\fP 
.PP
Definition at line 198 of file ratio.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
