.TH "std::is_placeholder" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::is_placeholder \- Determines if the given type _Tp is a placeholder in a \fBbind()\fP expression and, if so, which placeholder it is. [TR1 3.6.2].  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> struct std::is_placeholder< _Tp >"
Determines if the given type _Tp is a placeholder in a \fBbind()\fP expression and, if so, which placeholder it is. [TR1 3.6.2]. 
.PP
Definition at line 816 of file tr1_impl/functional.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
