.TH "std::error_category" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::error_category \- \fBerror_category\fP  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBerror_condition\fP \fBdefault_error_condition\fP (int __i) const "
.br
.ti -1c
.RI "virtual bool \fBequivalent\fP (const \fBerror_code\fP &__code, int __i) const "
.br
.ti -1c
.RI "virtual bool \fBequivalent\fP (int __i, const \fBerror_condition\fP &__cond) const "
.br
.ti -1c
.RI "\fBerror_category\fP (const \fBerror_category\fP &)"
.br
.ti -1c
.RI "virtual \fBstring\fP \fBmessage\fP (int) const =0"
.br
.ti -1c
.RI "virtual const char * \fBname\fP () const =0"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBerror_category\fP &__other) const "
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBerror_category\fP &__other) const "
.br
.ti -1c
.RI "\fBerror_category\fP & \fBoperator=\fP (const \fBerror_category\fP &)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBerror_category\fP &__other) const "
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBerror_category\fP 
.PP
Definition at line 68 of file system_error.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
