.TH "std::_Function_base" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::_Function_base \- Base class of all polymorphic function object wrappers.  

.PP
.SH SYNOPSIS
.br
.PP
Inherited by \fBstd::function< _Res(_ArgTypes...)>\fP\fC [private]\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef bool(* \fB_Manager_type\fP )(_Any_data &, const _Any_data &, _Manager_operation)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fB_M_empty\fP () const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "_Any_data \fB_M_functor\fP"
.br
.ti -1c
.RI "_Manager_type \fB_M_manager\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const std::size_t \fB_M_max_align\fP"
.br
.ti -1c
.RI "static const std::size_t \fB_M_max_size\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Base class of all polymorphic function object wrappers. 
.PP
Definition at line 1466 of file tr1_impl/functional.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
