.TH "std::pair" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::pair \- \fBpair\fP holds two objects of arbitrary type.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _T1 \fBfirst_type\fP"
.br
.ti -1c
.RI "typedef _T2 \fBsecond_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<class _U1 , class _U2 > \fBpair\fP & \fBoperator=\fP (\fBpair\fP< _U1, _U2 > &&__p)"
.br
.ti -1c
.RI "\fBpair\fP & \fBoperator=\fP (\fBpair\fP &&__p)"
.br
.ti -1c
.RI "template<class _U1 , class _Arg0 , class... _Args> \fBpair\fP (_U1 &&__x, _Arg0 &&__arg0, _Args &&...__args)"
.br
.ti -1c
.RI "template<class _U1 , class _U2 > \fBpair\fP (\fBpair\fP< _U1, _U2 > &&__p)"
.br
.ti -1c
.RI "template<class _U1 , class _U2 > \fBpair\fP (const \fBpair\fP< _U1, _U2 > &__p)"
.br
.ti -1c
.RI "\fBpair\fP (\fBpair\fP &&__p)"
.br
.ti -1c
.RI "template<class _U1 , class _U2 > \fBpair\fP (_U1 &&__x, _U2 &&__y)"
.br
.ti -1c
.RI "\fBpair\fP (const _T1 &__a, const _T2 &__b)"
.br
.ti -1c
.RI "\fBpair\fP ()"
.br
.ti -1c
.RI "void \fBswap\fP (\fBpair\fP &&__p)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "_T1 \fBfirst\fP"
.br
.ti -1c
.RI "_T2 \fBsecond\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class _T1, class _T2> struct std::pair< _T1, _T2 >"
\fBpair\fP holds two objects of arbitrary type. 
.PP
Definition at line 67 of file stl_pair.h.
.SH "Member Typedef Documentation"
.PP 
.SS "template<class _T1, class _T2> typedef _T1 \fBstd::pair\fP< _T1, _T2 >::\fBfirst_type\fP"
.PP
\fCfirst_type\fP is the first bound type 
.PP
Definition at line 69 of file stl_pair.h.
.SS "template<class _T1, class _T2> typedef _T2 \fBstd::pair\fP< _T1, _T2 >::\fBsecond_type\fP"
.PP
\fCsecond_type\fP is the second bound type 
.PP
Definition at line 70 of file stl_pair.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class _T1, class _T2> \fBstd::pair\fP< _T1, _T2 >::\fBpair\fP ()\fC [inline]\fP"
.PP
The default constructor creates \fCfirst\fP and \fCsecond\fP using their respective default constructors. 
.PP
Definition at line 79 of file stl_pair.h.
.SS "template<class _T1, class _T2> \fBstd::pair\fP< _T1, _T2 >::\fBpair\fP (const _T1 & __a, const _T2 & __b)\fC [inline]\fP"
.PP
Two objects may be passed to a \fC\fBpair\fP\fP constructor to be copied. 
.PP
Definition at line 83 of file stl_pair.h.
.SS "template<class _T1, class _T2> template<class _U1 , class _U2 > \fBstd::pair\fP< _T1, _T2 >::\fBpair\fP (const \fBpair\fP< _U1, _U2 > & __p)\fC [inline]\fP"
.PP
There is also a templated copy ctor for the \fC\fBpair\fP\fP class itself. 
.PP
Definition at line 99 of file stl_pair.h.
.SH "Member Data Documentation"
.PP 
.SS "template<class _T1, class _T2> _T1 \fBstd::pair\fP< _T1, _T2 >::\fBfirst\fP"
.PP
\fCfirst\fP is a copy of the first object 
.PP
Definition at line 72 of file stl_pair.h.
.PP
Referenced by std::_Temporary_buffer< _ForwardIterator, _Tp >::_Temporary_buffer(), std::set< _Key, _Compare, _Alloc >::insert(), and std::operator==().
.SS "template<class _T1, class _T2> _T2 \fBstd::pair\fP< _T1, _T2 >::\fBsecond\fP"
.PP
\fCsecond\fP is a copy of the second object 
.PP
Definition at line 73 of file stl_pair.h.
.PP
Referenced by std::_Temporary_buffer< _ForwardIterator, _Tp >::_Temporary_buffer(), std::set< _Key, _Compare, _Alloc >::insert(), and std::operator==().

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
