.TH "std::binary_negate" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::binary_negate \- One of the \fBnegation functors\fP.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fBbinary_function< _Predicate::first_argument_type, _Predicate::second_argument_type, bool >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _Predicate::first_argument_type \fBfirst_argument_type\fP"
.br
.ti -1c
.RI "typedef bool \fBresult_type\fP"
.br
.ti -1c
.RI "typedef _Predicate::second_argument_type \fBsecond_argument_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbinary_negate\fP (const _Predicate &__x)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (const typename _Predicate::first_argument_type &__x, const typename _Predicate::second_argument_type &__y) const "
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "_Predicate \fB_M_pred\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Predicate> class std::binary_negate< _Predicate >"
One of the \fBnegation functors\fP. 
.PP
Definition at line 369 of file stl_function.h.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef _Predicate::first_argument_type  \fBstd::binary_function\fP< _Predicate::first_argument_type , _Predicate::second_argument_type , bool  >::\fBfirst_argument_type\fP\fC [inherited]\fP"
.PP
the type of the first argument (no surprises here) 
.PP
Definition at line 114 of file stl_function.h.
.SS "typedef bool  \fBstd::binary_function\fP< _Predicate::first_argument_type , _Predicate::second_argument_type , bool  >::\fBresult_type\fP\fC [inherited]\fP"
.PP
type of the return type 
.PP
Definition at line 118 of file stl_function.h.
.SS "typedef _Predicate::second_argument_type  \fBstd::binary_function\fP< _Predicate::first_argument_type , _Predicate::second_argument_type , bool  >::\fBsecond_argument_type\fP\fC [inherited]\fP"
.PP
the type of the second argument 
.PP
Definition at line 117 of file stl_function.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
