.TH "std::pointer_to_unary_function" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::pointer_to_unary_function \- One of the \fBadaptors for function pointers\fP.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fBunary_function< _Arg, _Result >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _Arg \fBargument_type\fP"
.br
.ti -1c
.RI "typedef _Result \fBresult_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "_Result \fBoperator()\fP (_Arg __x) const "
.br
.ti -1c
.RI "\fBpointer_to_unary_function\fP (_Result(*__x)(_Arg))"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "_Result(* \fB_M_ptr\fP )(_Arg)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Arg, typename _Result> class std::pointer_to_unary_function< _Arg, _Result >"
One of the \fBadaptors for function pointers\fP. 
.PP
Definition at line 417 of file stl_function.h.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef _Arg  \fBstd::unary_function\fP< _Arg , _Result  >::\fBargument_type\fP\fC [inherited]\fP"
.PP
\fCargument_type\fP is the type of the argument (no surprises here) 
.PP
Definition at line 102 of file stl_function.h.
.SS "typedef _Result  \fBstd::unary_function\fP< _Arg , _Result  >::\fBresult_type\fP\fC [inherited]\fP"
.PP
\fCresult_type\fP is the return type 
.PP
Definition at line 105 of file stl_function.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
