.TH "std::plus" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::plus \- One of the \fBmath functors\fP.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fBbinary_function< _Tp, _Tp, _Tp >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _Tp \fBfirst_argument_type\fP"
.br
.ti -1c
.RI "typedef _Tp \fBresult_type\fP"
.br
.ti -1c
.RI "typedef _Tp \fBsecond_argument_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "_Tp \fBoperator()\fP (const _Tp &__x, const _Tp &__y) const "
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> struct std::plus< _Tp >"
One of the \fBmath functors\fP. 
.PP
Definition at line 135 of file stl_function.h.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef _Tp  \fBstd::binary_function\fP< _Tp , _Tp , _Tp  >::\fBfirst_argument_type\fP\fC [inherited]\fP"
.PP
the type of the first argument (no surprises here) 
.PP
Definition at line 114 of file stl_function.h.
.SS "typedef _Tp  \fBstd::binary_function\fP< _Tp , _Tp , _Tp  >::\fBresult_type\fP\fC [inherited]\fP"
.PP
type of the return type 
.PP
Definition at line 118 of file stl_function.h.
.SS "typedef _Tp  \fBstd::binary_function\fP< _Tp , _Tp , _Tp  >::\fBsecond_argument_type\fP\fC [inherited]\fP"
.PP
the type of the second argument 
.PP
Definition at line 117 of file stl_function.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
