.TH "std::unary_function" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::unary_function \- 
.SH SYNOPSIS
.br
.PP
Inherited by \fB__gnu_cxx::binary_compose< _Operation1, _Operation2, _Operation3 >\fP, \fB__gnu_cxx::subtractive_rng\fP, and \fB__gnu_cxx::unary_compose< _Operation1, _Operation2 >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _Arg \fBargument_type\fP"
.br
.ti -1c
.RI "typedef _Result \fBresult_type\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Arg, typename _Result> struct std::unary_function< _Arg, _Result >"
This is one of the \fBfunctor base classes\fP. 
.PP
Definition at line 100 of file stl_function.h.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename _Arg, typename _Result> typedef _Arg \fBstd::unary_function\fP< _Arg, _Result >::\fBargument_type\fP"
.PP
\fCargument_type\fP is the type of the argument (no surprises here) 
.PP
Definition at line 102 of file stl_function.h.
.SS "template<typename _Arg, typename _Result> typedef _Result \fBstd::unary_function\fP< _Arg, _Result >::\fBresult_type\fP"
.PP
\fCresult_type\fP is the return type 
.PP
Definition at line 105 of file stl_function.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
