.TH "std::is_compound" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::is_compound \- \fBis_compound\fP  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fBintegral_constant< bool,!is_fundamental< _Tp >::value >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBintegral_constant\fP< bool, __v > \fBtype\fP"
.br
.ti -1c
.RI "typedef bool \fBvalue_type\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> struct std::is_compound< _Tp >"
\fBis_compound\fP 
.PP
Definition at line 290 of file tr1_impl/type_traits.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
