.TH "std::messages_base" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::messages_base \- Messages facet base class providing catalog typedef.  

.PP
.SH SYNOPSIS
.br
.PP
Inherited by \fBstd::messages< _CharT >\fP, and \fBstd::messages< _CharT >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef int \fBcatalog\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Messages facet base class providing catalog typedef. 
.PP
Definition at line 1644 of file locale_facets_nonio.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
