.TH "std::is_bind_expression" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::is_bind_expression \- Determines if the given type _Tp is a function object should be treated as a subexpression when evaluating calls to function objects returned by \fBbind()\fP. [TR1 3.6.1].  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> struct std::is_bind_expression< _Tp >"
Determines if the given type _Tp is a function object should be treated as a subexpression when evaluating calls to function objects returned by \fBbind()\fP. [TR1 3.6.1]. 
.PP
Definition at line 805 of file tr1_impl/functional.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
