.TH "std::_Placeholder" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::_Placeholder \- The type of placeholder objects defined by libstdc++.  

.PP
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SS "template<int _Num> struct std::_Placeholder< _Num >"
The type of placeholder objects defined by libstdc++. 
.PP
Definition at line 823 of file tr1_impl/functional.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
