.TH "std::_Vector_base" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::_Vector_base \- See \fBbits/stl_deque.h\fP's \fB_Deque_base\fP for an explanation.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _Alloc::template rebind< _Tp >::other \fB_Tp_alloc_type\fP"
.br
.ti -1c
.RI "typedef _Alloc \fBallocator_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "_Tp_alloc_type::pointer \fB_M_allocate\fP (size_t __n)"
.br
.ti -1c
.RI "void \fB_M_deallocate\fP (typename _Tp_alloc_type::pointer __p, size_t __n)"
.br
.ti -1c
.RI "const _Tp_alloc_type & \fB_M_get_Tp_allocator\fP () const "
.br
.ti -1c
.RI "_Tp_alloc_type & \fB_M_get_Tp_allocator\fP ()"
.br
.ti -1c
.RI "\fB_Vector_base\fP (\fB_Vector_base\fP &&__x)"
.br
.ti -1c
.RI "\fB_Vector_base\fP (size_t __n, const allocator_type &__a)"
.br
.ti -1c
.RI "\fB_Vector_base\fP (const allocator_type &__a)"
.br
.ti -1c
.RI "allocator_type \fBget_allocator\fP () const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "_Vector_impl \fB_M_impl\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp, typename _Alloc> struct std::_Vector_base< _Tp, _Alloc >"
See \fBbits/stl_deque.h\fP's \fB_Deque_base\fP for an explanation. 
.PP
Definition at line 69 of file stl_vector.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
