.TH "std::recursive_mutex" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::recursive_mutex \- \fBrecursive_mutex\fP  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef __native_type * \fBnative_handle_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBlock\fP ()"
.br
.ti -1c
.RI "native_handle_type \fBnative_handle\fP ()"
.br
.ti -1c
.RI "\fBrecursive_mutex\fP & \fBoperator=\fP (const \fBrecursive_mutex\fP &)"
.br
.ti -1c
.RI "\fBrecursive_mutex\fP (const \fBrecursive_mutex\fP &)"
.br
.ti -1c
.RI "bool \fBtry_lock\fP ()"
.br
.ti -1c
.RI "void \fBunlock\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBrecursive_mutex\fP 
.PP
Definition at line 115 of file mutex.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
