.TH "std::_Temporary_buffer" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::_Temporary_buffer \- 
.SH SYNOPSIS
.br
.PP
Inherited by \fB__gnu_cxx::temporary_buffer< _ForwardIterator, _Tp >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef pointer \fBiterator\fP"
.br
.ti -1c
.RI "typedef value_type * \fBpointer\fP"
.br
.ti -1c
.RI "typedef ptrdiff_t \fBsize_type\fP"
.br
.ti -1c
.RI "typedef _Tp \fBvalue_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB_Temporary_buffer\fP (_ForwardIterator __first, _ForwardIterator __last)"
.br
.ti -1c
.RI "iterator \fBbegin\fP ()"
.br
.ti -1c
.RI "iterator \fBend\fP ()"
.br
.ti -1c
.RI "size_type \fBrequested_size\fP () const "
.br
.ti -1c
.RI "size_type \fBsize\fP () const "
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "pointer \fB_M_buffer\fP"
.br
.ti -1c
.RI "size_type \fB_M_len\fP"
.br
.ti -1c
.RI "size_type \fB_M_original_len\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _ForwardIterator, typename _Tp> class std::_Temporary_buffer< _ForwardIterator, _Tp >"
This class is used in two places: \fBstl_algo.h\fP and ext/memory, where it is wrapped as the temporary_buffer class. See temporary_buffer docs for more notes. 
.PP
Definition at line 122 of file stl_tempbuf.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename _ForwardIterator, typename _Tp > \fBstd::_Temporary_buffer\fP< _ForwardIterator, _Tp >::\fB_Temporary_buffer\fP (_ForwardIterator __first, _ForwardIterator __last)\fC [inline]\fP"
.PP
Constructs a temporary buffer of a size somewhere between zero and the size of the given range. 
.PP
Definition at line 181 of file stl_tempbuf.h.
.PP
References std::pair< _T1, _T2 >::first, std::get_temporary_buffer(), std::return_temporary_buffer(), std::pair< _T1, _T2 >::second, and std::uninitialized_fill_n().
.SH "Member Function Documentation"
.PP 
.SS "template<typename _ForwardIterator, typename _Tp> iterator \fBstd::_Temporary_buffer\fP< _ForwardIterator, _Tp >::begin ()\fC [inline]\fP"
.PP
As per Table mumble. 
.PP
Definition at line 151 of file stl_tempbuf.h.
.PP
Referenced by std::inplace_merge(), std::stable_partition(), and std::stable_sort().
.SS "template<typename _ForwardIterator, typename _Tp> iterator \fBstd::_Temporary_buffer\fP< _ForwardIterator, _Tp >::end ()\fC [inline]\fP"
.PP
As per Table mumble. 
.PP
Definition at line 156 of file stl_tempbuf.h.
.SS "template<typename _ForwardIterator, typename _Tp> size_type \fBstd::_Temporary_buffer\fP< _ForwardIterator, _Tp >::requested_size () const\fC [inline]\fP"
.PP
Returns the size requested by the constructor; may be >\fBsize()\fP. 
.PP
Definition at line 146 of file stl_tempbuf.h.
.PP
Referenced by std::stable_partition().
.SS "template<typename _ForwardIterator, typename _Tp> size_type \fBstd::_Temporary_buffer\fP< _ForwardIterator, _Tp >::size () const\fC [inline]\fP"
.PP
As per Table mumble. 
.PP
Definition at line 141 of file stl_tempbuf.h.
.PP
Referenced by std::inplace_merge(), std::stable_partition(), and std::stable_sort().

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
