.TH "std::unique_ptr" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::unique_ptr \- 20.7.12.2 \fBunique_ptr\fP for single objects.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _Tp_Deleter \fBdeleter_type\fP"
.br
.ti -1c
.RI "typedef _Tp \fBelement_type\fP"
.br
.ti -1c
.RI "typedef _Tp * \fBpointer\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "pointer \fBget\fP () const "
.br
.ti -1c
.RI "\fBstd::add_lvalue_reference\fP< typename \fBstd::add_const\fP< deleter_type >::type >::type \fBget_deleter\fP () const "
.br
.ti -1c
.RI "\fBstd::add_lvalue_reference\fP< deleter_type >::type \fBget_deleter\fP ()"
.br
.ti -1c
.RI "\fBoperator __unspecified_bool_type\fP () const "
.br
.ti -1c
.RI "\fBstd::add_lvalue_reference\fP< element_type >::type \fBoperator*\fP () const "
.br
.ti -1c
.RI "pointer \fBoperator->\fP () const "
.br
.ti -1c
.RI "template<typename _Up , typename _Up_Deleter > \fBunique_ptr\fP & \fBoperator=\fP (const \fBunique_ptr\fP< _Up, _Up_Deleter > &)"
.br
.ti -1c
.RI "\fBunique_ptr\fP & \fBoperator=\fP (const \fBunique_ptr\fP &)"
.br
.ti -1c
.RI "\fBunique_ptr\fP & \fBoperator=\fP (__unspecified_pointer_type)"
.br
.ti -1c
.RI "template<typename _Up , typename _Up_Deleter > \fBunique_ptr\fP & \fBoperator=\fP (\fBunique_ptr\fP< _Up, _Up_Deleter > &&__u)"
.br
.ti -1c
.RI "\fBunique_ptr\fP & \fBoperator=\fP (\fBunique_ptr\fP &&__u)"
.br
.ti -1c
.RI "pointer \fBrelease\fP ()"
.br
.ti -1c
.RI "void \fBreset\fP (pointer __p=pointer())"
.br
.ti -1c
.RI "void \fBswap\fP (\fBunique_ptr\fP &&__u)"
.br
.ti -1c
.RI "template<typename _Up , typename _Up_Deleter > \fBunique_ptr\fP (const \fBunique_ptr\fP< _Up, _Up_Deleter > &)"
.br
.ti -1c
.RI "\fBunique_ptr\fP (const \fBunique_ptr\fP &)"
.br
.ti -1c
.RI "template<typename _Up , typename _Up_Deleter > \fBunique_ptr\fP (\fBunique_ptr\fP< _Up, _Up_Deleter > &&__u)"
.br
.ti -1c
.RI "\fBunique_ptr\fP (\fBunique_ptr\fP &&__u)"
.br
.ti -1c
.RI "\fBunique_ptr\fP (pointer __p, typename \fBstd::remove_reference\fP< deleter_type >::type &&__d)"
.br
.ti -1c
.RI "\fBunique_ptr\fP (pointer __p, typename std::conditional< \fBstd::is_reference\fP< deleter_type >::value, deleter_type, const deleter_type & >::type __d)"
.br
.ti -1c
.RI "\fBunique_ptr\fP (pointer __p)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp, typename _Tp_Deleter = default_delete<_Tp>> class std::unique_ptr< _Tp, _Tp_Deleter >"
20.7.12.2 \fBunique_ptr\fP for single objects. 
.PP
Definition at line 85 of file unique_ptr.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
