.TH "std::_Fwd_list_const_iterator" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::_Fwd_list_const_iterator \- A forward_list::const_iterator.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef const \fB_Fwd_list_node\fP< _Tp, _Alloc > \fB_Node\fP"
.br
.ti -1c
.RI "typedef const \fB_Fwd_list_node_base\fP< _Alloc > \fB_Node_base\fP"
.br
.ti -1c
.RI "typedef \fB_Fwd_list_const_iterator\fP< _Tp, _Alloc > \fB_Self\fP"
.br
.ti -1c
.RI "typedef _Alloc::difference_type \fBdifference_type\fP"
.br
.ti -1c
.RI "typedef \fB_Fwd_list_iterator\fP< _Tp, _Alloc > \fBiterator\fP"
.br
.ti -1c
.RI "typedef \fBstd::forward_iterator_tag\fP \fBiterator_category\fP"
.br
.ti -1c
.RI "typedef _Alloc::const_pointer \fBpointer\fP"
.br
.ti -1c
.RI "typedef _Alloc::const_reference \fBreference\fP"
.br
.ti -1c
.RI "typedef _Tp \fBvalue_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB_Fwd_list_const_iterator\fP (const \fBiterator\fP &__iter)"
.br
.ti -1c
.RI "\fB_Fwd_list_const_iterator\fP (typename _Node_base::_Const_pointer __n)"
.br
.ti -1c
.RI "\fB_Self\fP \fB_M_next\fP () const "
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fB_Self\fP &__x) const "
.br
.ti -1c
.RI "reference \fBoperator*\fP () const "
.br
.ti -1c
.RI "\fB_Self\fP \fBoperator++\fP (int)"
.br
.ti -1c
.RI "\fB_Self\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "pointer \fBoperator->\fP () const "
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fB_Self\fP &__x) const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "_Node_base::_Const_pointer \fB_M_node\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp, typename _Alloc> struct std::_Fwd_list_const_iterator< _Tp, _Alloc >"
A forward_list::const_iterator. 

All the functions are op overloads. 
.PP
Definition at line 175 of file forward_list.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
