.TH "std::ratio_add" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::ratio_add \- \fBratio_add\fP  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBratio\fP< __safe_add< __safe_multiply< _R1::num,(_R2::den/__gcd)>::value, __safe_multiply< _R2::num,(_R1::den/__gcd)>::value >::value, __safe_multiply< _R1::den,(_R2::den/__gcd)>::value > \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _R1, typename _R2> struct std::ratio_add< _R1, _R2 >"
\fBratio_add\fP 
.PP
Definition at line 173 of file ratio.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
