.TH "std::_Safe_tuple_element_impl" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::_Safe_tuple_element_impl \- 
.SH SYNOPSIS
.br
.PP
Inherits tuple_element<__i, _Tuple>.
.PP
Inherited by \fBstd::_Safe_tuple_element< __i, _Tuple >\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<int __i, typename _Tuple, bool _IsSafe> struct std::_Safe_tuple_element_impl< __i, _Tuple, _IsSafe >"
Implementation helper for \fB_Safe_tuple_element\fP. This primary template handles the case where it is safe to use \fCtuple_element\fP. 
.PP
Definition at line 915 of file tr1_impl/functional.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
