.TH "std::time_get" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::time_get \- Facet for parsing dates and times.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fBstd::locale::facet\fP, and \fBstd::time_base\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBbasic_string\fP< _CharT > \fB__string_type\fP"
.br
.ti -1c
.RI "enum \fBdateorder\fP { \fBno_order\fP, \fBdmy\fP, \fBmdy\fP, \fBymd\fP, \fBydm\fP }"
.br
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "typedef _CharT \fBchar_type\fP"
.br
.ti -1c
.RI "typedef _InIter \fBiter_type\fP"
.br
.in -1c
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "dateorder \fBdate_order\fP () const "
.br
.ti -1c
.RI "\fBiter_type\fP \fBget_date\fP (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, tm *__tm) const "
.br
.ti -1c
.RI "\fBiter_type\fP \fBget_monthname\fP (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, tm *__tm) const "
.br
.ti -1c
.RI "\fBiter_type\fP \fBget_time\fP (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, tm *__tm) const "
.br
.ti -1c
.RI "\fBiter_type\fP \fBget_weekday\fP (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, tm *__tm) const "
.br
.ti -1c
.RI "\fBiter_type\fP \fBget_year\fP (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, tm *__tm) const "
.br
.ti -1c
.RI "\fBtime_get\fP (size_t __refs=0)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBlocale::id\fP \fBid\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBiter_type\fP \fB_M_extract_name\fP (\fBiter_type\fP __beg, \fBiter_type\fP __end, int &__member, const _CharT **__names, size_t __indexlen, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err) const "
.br
.ti -1c
.RI "\fBiter_type\fP \fB_M_extract_num\fP (\fBiter_type\fP __beg, \fBiter_type\fP __end, int &__member, int __min, int __max, size_t __len, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err) const "
.br
.ti -1c
.RI "\fBiter_type\fP \fB_M_extract_via_format\fP (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, tm *__tm, const _CharT *__format) const "
.br
.ti -1c
.RI "virtual dateorder \fBdo_date_order\fP () const "
.br
.ti -1c
.RI "virtual \fBiter_type\fP \fBdo_get_date\fP (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, tm *__tm) const "
.br
.ti -1c
.RI "virtual \fBiter_type\fP \fBdo_get_monthname\fP (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP &, \fBios_base::iostate\fP &__err, tm *__tm) const "
.br
.ti -1c
.RI "virtual \fBiter_type\fP \fBdo_get_time\fP (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, tm *__tm) const "
.br
.ti -1c
.RI "virtual \fBiter_type\fP \fBdo_get_weekday\fP (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP &, \fBios_base::iostate\fP &__err, tm *__tm) const "
.br
.ti -1c
.RI "virtual \fBiter_type\fP \fBdo_get_year\fP (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, tm *__tm) const "
.br
.ti -1c
.RI "virtual \fB~time_get\fP ()"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static __c_locale \fB_S_clone_c_locale\fP (__c_locale &__cloc)"
.br
.ti -1c
.RI "static void \fB_S_create_c_locale\fP (__c_locale &__cloc, const char *__s, __c_locale __old=0)"
.br
.ti -1c
.RI "static void \fB_S_destroy_c_locale\fP (__c_locale &__cloc)"
.br
.ti -1c
.RI "static __c_locale \fB_S_get_c_locale\fP ()"
.br
.ti -1c
.RI "static const char * \fB_S_get_c_name\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBlocale::_Impl\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _CharT, typename _InIter> class std::time_get< _CharT, _InIter >"
Facet for parsing dates and times. 

This facet encapsulates the code to parse and return a date or time from a string. It is used by the istream numeric extraction operators.
.PP
The \fBtime_get\fP template uses protected virtual functions to provide the actual results. The public accessors forward the call to the virtual functions. These virtual functions are hooks for developers to implement the behavior they require from the \fBtime_get\fP facet. 
.PP
Definition at line 361 of file locale_facets_nonio.h.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename _CharT, typename _InIter> typedef _CharT \fBstd::time_get\fP< _CharT, _InIter >::\fBchar_type\fP"
.PP
Public typedefs. 
.PP
Reimplemented in \fBstd::time_get_byname< _CharT, _InIter >\fP.
.PP
Definition at line 367 of file locale_facets_nonio.h.
.SS "template<typename _CharT, typename _InIter> typedef _InIter \fBstd::time_get\fP< _CharT, _InIter >::\fBiter_type\fP"
.PP
Public typedefs. 
.PP
Reimplemented in \fBstd::time_get_byname< _CharT, _InIter >\fP.
.PP
Definition at line 368 of file locale_facets_nonio.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename _CharT, typename _InIter> \fBstd::time_get\fP< _CharT, _InIter >::\fBtime_get\fP (size_t __refs = \fC0\fP)\fC [inline, explicit]\fP"
.PP
Constructor performs initialization. 
.PP
This is the constructor provided by the standard.
.PP
\fBParameters:\fP
.RS 4
\fIrefs\fP Passed to the base facet class. 
.RE
.PP

.PP
Definition at line 383 of file locale_facets_nonio.h.
.SS "template<typename _CharT, typename _InIter> virtual \fBstd::time_get\fP< _CharT, _InIter >::~\fBtime_get\fP ()\fC [inline, protected, virtual]\fP"
.PP
Destructor. 
.PP
Definition at line 539 of file locale_facets_nonio.h.
.SH "Member Function Documentation"
.PP 
.SS "template<typename _CharT, typename _InIter> dateorder \fBstd::time_get\fP< _CharT, _InIter >::date_order () const\fC [inline]\fP"
.PP
Return preferred order of month, day, and year. 
.PP
This function returns an enum from timebase::dateorder giving the preferred ordering if the format 'x' given to \fBtime_put::put()\fP only uses month, day, and year. If the format 'x' for the associated \fBlocale\fP uses other fields, this function returns timebase::dateorder::noorder.
.PP
NOTE: The library always returns noorder at the moment.
.PP
\fBReturns:\fP
.RS 4
A member of timebase::dateorder. 
.RE
.PP

.PP
Definition at line 400 of file locale_facets_nonio.h.
.SS "template<typename _CharT , typename _InIter > _GLIBCXX_END_LDBL_NAMESPACE time_base::dateorder \fBstd::time_get\fP< _CharT, _InIter >::do_date_order () const\fC [inline, protected, virtual]\fP"
.PP
Return preferred order of month, day, and year. 
.PP
This function returns an enum from timebase::dateorder giving the preferred ordering if the format 'x' given to \fBtime_put::put()\fP only uses month, day, and year. This function is a hook for derived classes to change the value returned.
.PP
\fBReturns:\fP
.RS 4
A member of timebase::dateorder. 
.RE
.PP

.PP
Definition at line 603 of file locale_facets_nonio.tcc.
.SS "template<typename _CharT , typename _InIter > _InIter \fBstd::time_get\fP< _CharT, _InIter >::do_get_date (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP & __io, \fBios_base::iostate\fP & __err, tm * __tm) const\fC [inline, protected, virtual]\fP"
.PP
Parse input date string. 
.PP
This function parses a date according to the format 'X' and puts the results into a user-supplied struct tm. This function is a hook for derived classes to change the value returned. 
.PP
\fBSee also:\fP
.RS 4
\fBget_date()\fP for details.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIbeg\fP Start of string to parse. 
.br
\fIend\fP End of string to parse. 
.br
\fIio\fP Source of the \fBlocale\fP. 
.br
\fIerr\fP Error flags to \fBset\fP. 
.br
\fItm\fP Pointer to struct tm to fill in. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator to first char beyond date string. 
.RE
.PP

.PP
Definition at line 955 of file locale_facets_nonio.tcc.
.PP
References std::ios_base::_M_getloc(), and std::ios_base::eofbit.
.SS "template<typename _CharT , typename _InIter > _InIter \fBstd::time_get\fP< _CharT, _InIter >::do_get_monthname (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP & __io, \fBios_base::iostate\fP & __err, tm * __tm) const\fC [inline, protected, virtual]\fP"
.PP
Parse input month string. 
.PP
This function parses a month name and puts the results into a user-supplied struct tm. This function is a hook for derived classes to change the value returned. 
.PP
\fBSee also:\fP
.RS 4
\fBget_monthname()\fP for details.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIbeg\fP Start of string to parse. 
.br
\fIend\fP End of string to parse. 
.br
\fIio\fP Source of the \fBlocale\fP. 
.br
\fIerr\fP Error flags to \fBset\fP. 
.br
\fItm\fP Pointer to struct tm to fill in. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator to first char beyond month name. 
.RE
.PP

.PP
Definition at line 1021 of file locale_facets_nonio.tcc.
.PP
References std::ios_base::_M_getloc(), std::ios_base::eofbit, std::ios_base::failbit, and std::ios_base::goodbit.
.SS "template<typename _CharT , typename _InIter > _InIter \fBstd::time_get\fP< _CharT, _InIter >::do_get_time (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP & __io, \fBios_base::iostate\fP & __err, tm * __tm) const\fC [inline, protected, virtual]\fP"
.PP
Parse input time string. 
.PP
This function parses a time according to the format 'x' and puts the results into a user-supplied struct tm. This function is a hook for derived classes to change the value returned. 
.PP
\fBSee also:\fP
.RS 4
\fBget_time()\fP for details.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIbeg\fP Start of string to parse. 
.br
\fIend\fP End of string to parse. 
.br
\fIio\fP Source of the \fBlocale\fP. 
.br
\fIerr\fP Error flags to \fBset\fP. 
.br
\fItm\fP Pointer to struct tm to fill in. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator to first char beyond time string. 
.RE
.PP

.PP
Definition at line 938 of file locale_facets_nonio.tcc.
.PP
References std::ios_base::_M_getloc().
.SS "template<typename _CharT , typename _InIter > _InIter \fBstd::time_get\fP< _CharT, _InIter >::do_get_weekday (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP & __io, \fBios_base::iostate\fP & __err, tm * __tm) const\fC [inline, protected, virtual]\fP"
.PP
Parse input weekday string. 
.PP
This function parses a weekday name and puts the results into a user-supplied struct tm. This function is a hook for derived classes to change the value returned. 
.PP
\fBSee also:\fP
.RS 4
\fBget_weekday()\fP for details.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIbeg\fP Start of string to parse. 
.br
\fIend\fP End of string to parse. 
.br
\fIio\fP Source of the \fBlocale\fP. 
.br
\fIerr\fP Error flags to \fBset\fP. 
.br
\fItm\fP Pointer to struct tm to fill in. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator to first char beyond weekday name. 
.RE
.PP

.PP
Definition at line 972 of file locale_facets_nonio.tcc.
.PP
References std::ios_base::_M_getloc().
.SS "template<typename _CharT , typename _InIter > _InIter \fBstd::time_get\fP< _CharT, _InIter >::do_get_year (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP & __io, \fBios_base::iostate\fP & __err, tm * __tm) const\fC [inline, protected, virtual]\fP"
.PP
Parse input year string. 
.PP
This function reads up to 4 characters to parse a year string and puts the results into a user-supplied struct tm. This function is a hook for derived classes to change the value returned. 
.PP
\fBSee also:\fP
.RS 4
\fBget_year()\fP for details.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIbeg\fP Start of string to parse. 
.br
\fIend\fP End of string to parse. 
.br
\fIio\fP Source of the \fBlocale\fP. 
.br
\fIerr\fP Error flags to \fBset\fP. 
.br
\fItm\fP Pointer to struct tm to fill in. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator to first char beyond year. 
.RE
.PP

.PP
Definition at line 1070 of file locale_facets_nonio.tcc.
.PP
References std::ios_base::_M_getloc(), and std::__ctype_abstract_base< _CharT >::narrow().
.SS "template<typename _CharT, typename _InIter> \fBiter_type\fP \fBstd::time_get\fP< _CharT, _InIter >::get_date (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP & __io, \fBios_base::iostate\fP & __err, tm * __tm) const\fC [inline]\fP"
.PP
Parse input date string. 
.PP
This function parses a date according to the format 'X' and puts the results into a user-supplied struct tm. The result is returned by calling \fBtime_get::do_get_date()\fP.
.PP
If there is a valid date string according to format 'X', \fItm\fP will be filled in accordingly and the returned \fBiterator\fP will point to the first character beyond the date string. If an error occurs before the end, err |= \fBios_base::failbit\fP. If parsing reads all the characters, err |= \fBios_base::eofbit\fP.
.PP
\fBParameters:\fP
.RS 4
\fIbeg\fP Start of string to parse. 
.br
\fIend\fP End of string to parse. 
.br
\fIio\fP Source of the \fBlocale\fP. 
.br
\fIerr\fP Error flags to \fBset\fP. 
.br
\fItm\fP Pointer to struct tm to fill in. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator to first char beyond date string. 
.RE
.PP

.PP
Definition at line 449 of file locale_facets_nonio.h.
.SS "template<typename _CharT, typename _InIter> \fBiter_type\fP \fBstd::time_get\fP< _CharT, _InIter >::get_monthname (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP & __io, \fBios_base::iostate\fP & __err, tm * __tm) const\fC [inline]\fP"
.PP
Parse input month string. 
.PP
This function parses a month name and puts the results into a user-supplied struct tm. The result is returned by calling \fBtime_get::do_get_monthname()\fP.
.PP
Parsing starts by parsing an abbreviated month name. If a valid abbreviation is followed by a character that would lead to the full month name, parsing continues until the full name is found or an error occurs. Otherwise parsing finishes at the end of the abbreviated name.
.PP
If an error occurs before the end, err |= \fBios_base::failbit\fP. If parsing reads all the characters, err |= \fBios_base::eofbit\fP.
.PP
\fBParameters:\fP
.RS 4
\fIbeg\fP Start of string to parse. 
.br
\fIend\fP End of string to parse. 
.br
\fIio\fP Source of the \fBlocale\fP. 
.br
\fIerr\fP Error flags to \fBset\fP. 
.br
\fItm\fP Pointer to struct tm to fill in. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator to first char beyond month name. 
.RE
.PP

.PP
Definition at line 506 of file locale_facets_nonio.h.
.SS "template<typename _CharT, typename _InIter> \fBiter_type\fP \fBstd::time_get\fP< _CharT, _InIter >::get_time (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP & __io, \fBios_base::iostate\fP & __err, tm * __tm) const\fC [inline]\fP"
.PP
Parse input time string. 
.PP
This function parses a time according to the format 'x' and puts the results into a user-supplied struct tm. The result is returned by calling \fBtime_get::do_get_time()\fP.
.PP
If there is a valid time string according to format 'x', \fItm\fP will be filled in accordingly and the returned \fBiterator\fP will point to the first character beyond the time string. If an error occurs before the end, err |= \fBios_base::failbit\fP. If parsing reads all the characters, err |= \fBios_base::eofbit\fP.
.PP
\fBParameters:\fP
.RS 4
\fIbeg\fP Start of string to parse. 
.br
\fIend\fP End of string to parse. 
.br
\fIio\fP Source of the \fBlocale\fP. 
.br
\fIerr\fP Error flags to \fBset\fP. 
.br
\fItm\fP Pointer to struct tm to fill in. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator to first char beyond time string. 
.RE
.PP

.PP
Definition at line 424 of file locale_facets_nonio.h.
.SS "template<typename _CharT, typename _InIter> \fBiter_type\fP \fBstd::time_get\fP< _CharT, _InIter >::get_weekday (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP & __io, \fBios_base::iostate\fP & __err, tm * __tm) const\fC [inline]\fP"
.PP
Parse input weekday string. 
.PP
This function parses a weekday name and puts the results into a user-supplied struct tm. The result is returned by calling \fBtime_get::do_get_weekday()\fP.
.PP
Parsing starts by parsing an abbreviated weekday name. If a valid abbreviation is followed by a character that would lead to the full weekday name, parsing continues until the full name is found or an error occurs. Otherwise parsing finishes at the end of the abbreviated name.
.PP
If an error occurs before the end, err |= \fBios_base::failbit\fP. If parsing reads all the characters, err |= \fBios_base::eofbit\fP.
.PP
\fBParameters:\fP
.RS 4
\fIbeg\fP Start of string to parse. 
.br
\fIend\fP End of string to parse. 
.br
\fIio\fP Source of the \fBlocale\fP. 
.br
\fIerr\fP Error flags to \fBset\fP. 
.br
\fItm\fP Pointer to struct tm to fill in. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator to first char beyond weekday name. 
.RE
.PP

.PP
Definition at line 477 of file locale_facets_nonio.h.
.SS "template<typename _CharT, typename _InIter> \fBiter_type\fP \fBstd::time_get\fP< _CharT, _InIter >::get_year (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP & __io, \fBios_base::iostate\fP & __err, tm * __tm) const\fC [inline]\fP"
.PP
Parse input year string. 
.PP
This function reads up to 4 characters to parse a year string and puts the results into a user-supplied struct tm. The result is returned by calling \fBtime_get::do_get_year()\fP.
.PP
4 consecutive digits are interpreted as a full year. If there are exactly 2 consecutive digits, the library interprets this as the number of years since 1900.
.PP
If an error occurs before the end, err |= \fBios_base::failbit\fP. If parsing reads all the characters, err |= \fBios_base::eofbit\fP.
.PP
\fBParameters:\fP
.RS 4
\fIbeg\fP Start of string to parse. 
.br
\fIend\fP End of string to parse. 
.br
\fIio\fP Source of the \fBlocale\fP. 
.br
\fIerr\fP Error flags to \fBset\fP. 
.br
\fItm\fP Pointer to struct tm to fill in. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator to first char beyond year. 
.RE
.PP

.PP
Definition at line 532 of file locale_facets_nonio.h.
.SH "Member Data Documentation"
.PP 
.SS "template<typename _CharT, typename _InIter> \fBlocale::id\fP \fBstd::time_get\fP< _CharT, _InIter >::\fBid\fP\fC [inline, static]\fP"
.PP
Numpunct facet id. 
.PP
Definition at line 373 of file locale_facets_nonio.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
