.TH "std::lock_guard" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::lock_guard \- Scoped lock idiom.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _Mutex \fBmutex_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlock_guard\fP (const \fBlock_guard\fP &)"
.br
.ti -1c
.RI "\fBlock_guard\fP (mutex_type &__m, \fBadopt_lock_t\fP __a)"
.br
.ti -1c
.RI "\fBlock_guard\fP (mutex_type &__m)"
.br
.ti -1c
.RI "\fBlock_guard\fP & \fBoperator=\fP (const \fBlock_guard\fP &)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Mutex> class std::lock_guard< _Mutex >"
Scoped lock idiom. 
.PP
Definition at line 405 of file mutex.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
