.TH "std::once_flag" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::once_flag \- \fBonce_flag\fP  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBonce_flag\fP (const \fBonce_flag\fP &)"
.br
.ti -1c
.RI "\fBonce_flag\fP & \fBoperator=\fP (const \fBonce_flag\fP &)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "template<typename _Callable , typename... _Args> void \fBcall_once\fP (\fBonce_flag\fP &__once, _Callable __f, _Args &&...__args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBonce_flag\fP 
.PP
Definition at line 698 of file mutex.
.SH "Friends And Related Function Documentation"
.PP 
.SS "template<typename _Callable , typename... _Args> void call_once (\fBonce_flag\fP & __once, _Callable __f, _Args &&... __args)\fC [friend]\fP"
.PP
call_once 
.PP
Definition at line 741 of file mutex.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
