.TH "std::chrono" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::chrono \- ISO C++ 0x entities sub namespace for time and date.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBduration\fP"
.br
.RI "\fI\fBduration\fP \fP"
.ti -1c
.RI "struct \fBduration_values\fP"
.br
.RI "\fI\fBduration_values\fP \fP"
.ti -1c
.RI "struct \fBtreat_as_floating_point\fP"
.br
.RI "\fI\fBtreat_as_floating_point\fP \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename _ToDuration , typename _Rep , typename _Period > _ToDuration \fBduration_cast\fP (const \fBduration\fP< _Rep, _Period > &__d)"
.br
.in -1c
.SH "Detailed Description"
.PP 
ISO C++ 0x entities sub namespace for time and date. 
.PP
.SH "Function Documentation"
.PP 
.SS "template<typename _ToDuration , typename _Rep , typename _Period > _ToDuration std::chrono::duration_cast (const duration< _Rep, _Period > & __d)\fC [inline]\fP"
.PP
duration_cast 
.PP
Definition at line 144 of file chrono.
.PP
Referenced by std::this_thread::sleep_for().
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
