.TH "std::output_iterator_tag" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::output_iterator_tag \- Marking output iterators.  

.PP
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Marking output iterators. 
.PP
Definition at line 81 of file stl_iterator_base_types.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
