.TH "std::tr1" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::tr1 \- ISO C++ TR1 entities toplevel namespace is \fBstd::tr1\fP.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fB__detail\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fB_Tuple_impl< _Idx >\fP"
.br
.ti -1c
.RI "struct \fB_Tuple_impl< _Idx, _Head, _Tail...>\fP"
.br
.ti -1c
.RI "struct \fBtuple_element< 0, tuple< _Head, _Tail...> >\fP"
.br
.ti -1c
.RI "struct \fBtuple_element< __i, tuple< _Head, _Tail...> >\fP"
.br
.ti -1c
.RI "struct \fBtuple_size< tuple< _Elements...> >\fP"
.br
.RI "\fIclass tuple_size \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<int __i, typename _Head , typename... _Tail> __add_c_ref< _Head >::type \fB__get_helper\fP (const _Tuple_impl< __i, _Head, _Tail...> &__t)"
.br
.ti -1c
.RI "template<int __i, typename _Head , typename... _Tail> __add_ref< _Head >::type \fB__get_helper\fP (_Tuple_impl< __i, _Head, _Tail...> &__t)"
.br
.ti -1c
.RI "template<typename _Tp > __gnu_cxx::__promote< _Tp >::__type \fBassoc_laguerre\fP (unsigned int __n, unsigned int __m, _Tp __x)"
.br
.ti -1c
.RI "float \fBassoc_laguerref\fP (unsigned int __n, unsigned int __m, float __x)"
.br
.ti -1c
.RI "long double \fBassoc_laguerrel\fP (unsigned int __n, unsigned int __m, long double __x)"
.br
.ti -1c
.RI "template<typename _Tp > __gnu_cxx::__promote< _Tp >::__type \fBassoc_legendre\fP (unsigned int __l, unsigned int __m, _Tp __x)"
.br
.ti -1c
.RI "float \fBassoc_legendref\fP (unsigned int __l, unsigned int __m, float __x)"
.br
.ti -1c
.RI "long double \fBassoc_legendrel\fP (unsigned int __l, unsigned int __m, long double __x)"
.br
.ti -1c
.RI "template<typename _Tpx , typename _Tpy > __gnu_cxx::__promote_2< _Tpx, _Tpy >::__type \fBbeta\fP (_Tpx __x, _Tpy __y)"
.br
.ti -1c
.RI "float \fBbetaf\fP (float __x, float __y)"
.br
.ti -1c
.RI "long double \fBbetal\fP (long double __x, long double __y)"
.br
.ti -1c
.RI "template<typename _Tp > __gnu_cxx::__promote< _Tp >::__type \fBcomp_ellint_1\fP (_Tp __k)"
.br
.ti -1c
.RI "float \fBcomp_ellint_1f\fP (float __k)"
.br
.ti -1c
.RI "long double \fBcomp_ellint_1l\fP (long double __k)"
.br
.ti -1c
.RI "template<typename _Tp > __gnu_cxx::__promote< _Tp >::__type \fBcomp_ellint_2\fP (_Tp __k)"
.br
.ti -1c
.RI "float \fBcomp_ellint_2f\fP (float __k)"
.br
.ti -1c
.RI "long double \fBcomp_ellint_2l\fP (long double __k)"
.br
.ti -1c
.RI "template<typename _Tp , typename _Tpn > __gnu_cxx::__promote_2< _Tp, _Tpn >::__type \fBcomp_ellint_3\fP (_Tp __k, _Tpn __nu)"
.br
.ti -1c
.RI "float \fBcomp_ellint_3f\fP (float __k, float __nu)"
.br
.ti -1c
.RI "long double \fBcomp_ellint_3l\fP (long double __k, long double __nu)"
.br
.ti -1c
.RI "template<typename _Tpa , typename _Tpc , typename _Tp > __gnu_cxx::__promote_3< _Tpa, _Tpc, _Tp >::__type \fBconf_hyperg\fP (_Tpa __a, _Tpc __c, _Tp __x)"
.br
.ti -1c
.RI "float \fBconf_hypergf\fP (float __a, float __c, float __x)"
.br
.ti -1c
.RI "long double \fBconf_hypergl\fP (long double __a, long double __c, long double __x)"
.br
.ti -1c
.RI "template<typename _Tpnu , typename _Tp > __gnu_cxx::__promote_2< _Tpnu, _Tp >::__type \fBcyl_bessel_i\fP (_Tpnu __nu, _Tp __x)"
.br
.ti -1c
.RI "float \fBcyl_bessel_if\fP (float __nu, float __x)"
.br
.ti -1c
.RI "long double \fBcyl_bessel_il\fP (long double __nu, long double __x)"
.br
.ti -1c
.RI "template<typename _Tpnu , typename _Tp > __gnu_cxx::__promote_2< _Tpnu, _Tp >::__type \fBcyl_bessel_j\fP (_Tpnu __nu, _Tp __x)"
.br
.ti -1c
.RI "float \fBcyl_bessel_jf\fP (float __nu, float __x)"
.br
.ti -1c
.RI "long double \fBcyl_bessel_jl\fP (long double __nu, long double __x)"
.br
.ti -1c
.RI "template<typename _Tpnu , typename _Tp > __gnu_cxx::__promote_2< _Tpnu, _Tp >::__type \fBcyl_bessel_k\fP (_Tpnu __nu, _Tp __x)"
.br
.ti -1c
.RI "float \fBcyl_bessel_kf\fP (float __nu, float __x)"
.br
.ti -1c
.RI "long double \fBcyl_bessel_kl\fP (long double __nu, long double __x)"
.br
.ti -1c
.RI "template<typename _Tpnu , typename _Tp > __gnu_cxx::__promote_2< _Tpnu, _Tp >::__type \fBcyl_neumann\fP (_Tpnu __nu, _Tp __x)"
.br
.ti -1c
.RI "float \fBcyl_neumannf\fP (float __nu, float __x)"
.br
.ti -1c
.RI "long double \fBcyl_neumannl\fP (long double __nu, long double __x)"
.br
.ti -1c
.RI "template<typename _Tp , typename _Tpp > __gnu_cxx::__promote_2< _Tp, _Tpp >::__type \fBellint_1\fP (_Tp __k, _Tpp __phi)"
.br
.ti -1c
.RI "float \fBellint_1f\fP (float __k, float __phi)"
.br
.ti -1c
.RI "long double \fBellint_1l\fP (long double __k, long double __phi)"
.br
.ti -1c
.RI "template<typename _Tp , typename _Tpp > __gnu_cxx::__promote_2< _Tp, _Tpp >::__type \fBellint_2\fP (_Tp __k, _Tpp __phi)"
.br
.ti -1c
.RI "float \fBellint_2f\fP (float __k, float __phi)"
.br
.ti -1c
.RI "long double \fBellint_2l\fP (long double __k, long double __phi)"
.br
.ti -1c
.RI "template<typename _Tp , typename _Tpn , typename _Tpp > __gnu_cxx::__promote_3< _Tp, _Tpn, _Tpp >::__type \fBellint_3\fP (_Tp __k, _Tpn __nu, _Tpp __phi)"
.br
.ti -1c
.RI "float \fBellint_3f\fP (float __k, float __nu, float __phi)"
.br
.ti -1c
.RI "long double \fBellint_3l\fP (long double __k, long double __nu, long double __phi)"
.br
.ti -1c
.RI "template<typename _Tp > __gnu_cxx::__promote< _Tp >::__type \fBexpint\fP (_Tp __x)"
.br
.ti -1c
.RI "float \fBexpintf\fP (float __x)"
.br
.ti -1c
.RI "long double \fBexpintl\fP (long double __x)"
.br
.ti -1c
.RI "template<int __i, typename... _Elements> __add_c_ref< typename tuple_element< __i, tuple< _Elements...> >::type >::type \fBget\fP (const tuple< _Elements...> &__t)"
.br
.ti -1c
.RI "template<int __i, typename... _Elements> __add_ref< typename tuple_element< __i, tuple< _Elements...> >::type >::type \fBget\fP (tuple< _Elements...> &__t)"
.br
.ti -1c
.RI "template<typename _Tp > __gnu_cxx::__promote< _Tp >::__type \fBhermite\fP (unsigned int __n, _Tp __x)"
.br
.ti -1c
.RI "float \fBhermitef\fP (unsigned int __n, float __x)"
.br
.ti -1c
.RI "long double \fBhermitel\fP (unsigned int __n, long double __x)"
.br
.ti -1c
.RI "template<typename _Tpa , typename _Tpb , typename _Tpc , typename _Tp > __gnu_cxx::__promote_4< _Tpa, _Tpb, _Tpc, _Tp >::__type \fBhyperg\fP (_Tpa __a, _Tpb __b, _Tpc __c, _Tp __x)"
.br
.ti -1c
.RI "float \fBhypergf\fP (float __a, float __b, float __c, float __x)"
.br
.ti -1c
.RI "long double \fBhypergl\fP (long double __a, long double __b, long double __c, long double __x)"
.br
.ti -1c
.RI "template<typename _Tp > __gnu_cxx::__promote< _Tp >::__type \fBlaguerre\fP (unsigned int __n, _Tp __x)"
.br
.ti -1c
.RI "float \fBlaguerref\fP (unsigned int __n, float __x)"
.br
.ti -1c
.RI "long double \fBlaguerrel\fP (unsigned int __n, long double __x)"
.br
.ti -1c
.RI "template<typename _Tp > __gnu_cxx::__promote< _Tp >::__type \fBlegendre\fP (unsigned int __n, _Tp __x)"
.br
.ti -1c
.RI "float \fBlegendref\fP (unsigned int __n, float __x)"
.br
.ti -1c
.RI "long double \fBlegendrel\fP (unsigned int __n, long double __x)"
.br
.ti -1c
.RI "template<typename... _Elements> tuple< typename __strip_reference_wrapper< _Elements >::__type...> \fBmake_tuple\fP (_Elements...__args)"
.br
.ti -1c
.RI "template<typename... _TElements, typename... _UElements> bool \fBoperator!=\fP (const tuple< _TElements...> &__t, const tuple< _UElements...> &__u)"
.br
.ti -1c
.RI "template<typename... _TElements, typename... _UElements> bool \fBoperator<\fP (const tuple< _TElements...> &__t, const tuple< _UElements...> &__u)"
.br
.ti -1c
.RI "template<typename... _TElements, typename... _UElements> bool \fBoperator<=\fP (const tuple< _TElements...> &__t, const tuple< _UElements...> &__u)"
.br
.ti -1c
.RI "template<typename... _TElements, typename... _UElements> bool \fBoperator==\fP (const tuple< _TElements...> &__t, const tuple< _UElements...> &__u)"
.br
.ti -1c
.RI "template<typename... _TElements, typename... _UElements> bool \fBoperator>\fP (const tuple< _TElements...> &__t, const tuple< _UElements...> &__u)"
.br
.ti -1c
.RI "template<typename... _TElements, typename... _UElements> bool \fBoperator>=\fP (const tuple< _TElements...> &__t, const tuple< _UElements...> &__u)"
.br
.ti -1c
.RI "template<typename _Tp , typename _Up > \fBstd::complex\fP< typename __gnu_cxx::__promote_2< _Tp, _Up >::__type > \fBpolar\fP (const _Tp &__rho, const _Up &__theta)"
.br
.ti -1c
.RI "template<typename _Tp > \fBstd::complex\fP< _Tp > \fBpow\fP (const \fBstd::complex\fP< _Tp > &__x, const \fBstd::complex\fP< _Tp > &__y)"
.br
.ti -1c
.RI "template<typename _Tp > \fBstd::complex\fP< _Tp > \fBpow\fP (const _Tp &__x, const \fBstd::complex\fP< _Tp > &__y)"
.br
.ti -1c
.RI "template<typename _Tp > \fBstd::complex\fP< _Tp > \fBpow\fP (const \fBstd::complex\fP< _Tp > &__x, const _Tp &__y)"
.br
.ti -1c
.RI "template<typename _Tp , typename _Up > __gnu_cxx::__promote_2< _Tp, _Up >::__type \fBpow\fP (_Tp __x, _Up __y)"
.br
.ti -1c
.RI "long double \fBpow\fP (long double __x, long double __y)"
.br
.ti -1c
.RI "float \fBpow\fP (float __x, float __y)"
.br
.ti -1c
.RI "double \fBpow\fP (double __x, double __y)"
.br
.ti -1c
.RI "template<typename _Tp > __gnu_cxx::__promote< _Tp >::__type \fBriemann_zeta\fP (_Tp __x)"
.br
.ti -1c
.RI "float \fBriemann_zetaf\fP (float __x)"
.br
.ti -1c
.RI "long double \fBriemann_zetal\fP (long double __x)"
.br
.ti -1c
.RI "template<typename _Tp > __gnu_cxx::__promote< _Tp >::__type \fBsph_bessel\fP (unsigned int __n, _Tp __x)"
.br
.ti -1c
.RI "float \fBsph_besself\fP (unsigned int __n, float __x)"
.br
.ti -1c
.RI "long double \fBsph_bessell\fP (unsigned int __n, long double __x)"
.br
.ti -1c
.RI "template<typename _Tp > __gnu_cxx::__promote< _Tp >::__type \fBsph_legendre\fP (unsigned int __l, unsigned int __m, _Tp __theta)"
.br
.ti -1c
.RI "float \fBsph_legendref\fP (unsigned int __l, unsigned int __m, float __theta)"
.br
.ti -1c
.RI "long double \fBsph_legendrel\fP (unsigned int __l, unsigned int __m, long double __theta)"
.br
.ti -1c
.RI "template<typename _Tp > __gnu_cxx::__promote< _Tp >::__type \fBsph_neumann\fP (unsigned int __n, _Tp __x)"
.br
.ti -1c
.RI "float \fBsph_neumannf\fP (unsigned int __n, float __x)"
.br
.ti -1c
.RI "long double \fBsph_neumannl\fP (unsigned int __n, long double __x)"
.br
.ti -1c
.RI "template<typename... _Elements> tuple< _Elements &...> \fBtie\fP (_Elements &...__args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
ISO C++ TR1 entities toplevel namespace is \fBstd::tr1\fP. 
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
