.TH "std::_List_node_base" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::_List_node_base \- Common part of a node in the list.  

.PP
.SH SYNOPSIS
.br
.PP
Inherited by \fBstd::_List_node< _Tp >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBhook\fP (\fB_List_node_base\fP *const __position)"
.br
.ti -1c
.RI "void \fBreverse\fP ()"
.br
.ti -1c
.RI "void \fBtransfer\fP (\fB_List_node_base\fP *const __first, \fB_List_node_base\fP *const __last)"
.br
.ti -1c
.RI "void \fBunhook\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBswap\fP (\fB_List_node_base\fP &__x, \fB_List_node_base\fP &__y)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB_List_node_base\fP * \fB_M_next\fP"
.br
.ti -1c
.RI "\fB_List_node_base\fP * \fB_M_prev\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Common part of a node in the list. 
.PP
Definition at line 71 of file stl_list.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
