.TH "std::_Index_tuple" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::_Index_tuple \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SS "template<int... _Indexes> struct std::_Index_tuple< _Indexes >"
Stores a \fBtuple\fP of indices. Used by \fBbind()\fP to extract the elements in a \fBtuple\fP. 
.PP
Definition at line 884 of file tr1_impl/functional.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
