.TH "std::istream_iterator" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::istream_iterator \- Provides input \fBiterator\fP semantics for streams.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fBiterator< input_iterator_tag, _Tp, _Dist, const _Tp *, const _Tp & >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _CharT \fBchar_type\fP"
.br
.ti -1c
.RI "typedef _Dist \fBdifference_type\fP"
.br
.ti -1c
.RI "typedef \fBbasic_istream\fP< _CharT, _Traits > \fBistream_type\fP"
.br
.ti -1c
.RI "typedef \fBinput_iterator_tag\fP \fBiterator_category\fP"
.br
.ti -1c
.RI "typedef const _Tp * \fBpointer\fP"
.br
.ti -1c
.RI "typedef const _Tp & \fBreference\fP"
.br
.ti -1c
.RI "typedef _Traits \fBtraits_type\fP"
.br
.ti -1c
.RI "typedef _Tp \fBvalue_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fB_M_equal\fP (const \fBistream_iterator\fP &__x) const "
.br
.ti -1c
.RI "\fBistream_iterator\fP (const \fBistream_iterator\fP &__obj)"
.br
.ti -1c
.RI "\fBistream_iterator\fP (\fBistream_type\fP &__s)"
.br
.ti -1c
.RI "\fBistream_iterator\fP ()"
.br
.ti -1c
.RI "const _Tp & \fBoperator*\fP () const "
.br
.ti -1c
.RI "\fBistream_iterator\fP \fBoperator++\fP (int)"
.br
.ti -1c
.RI "\fBistream_iterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "const _Tp * \fBoperator->\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp, typename _CharT = char, typename _Traits = char_traits<_CharT>, typename _Dist = ptrdiff_t> class std::istream_iterator< _Tp, _CharT, _Traits, _Dist >"
Provides input \fBiterator\fP semantics for streams. 
.PP
Definition at line 42 of file stream_iterator.h.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef _Dist  \fBstd::iterator\fP< \fBinput_iterator_tag\fP , _Tp , _Dist , const _Tp * , const _Tp &  >::\fBdifference_type\fP\fC [inherited]\fP"
.PP
Distance between iterators is represented as this type. 
.PP
Definition at line 111 of file stl_iterator_base_types.h.
.SS "typedef \fBinput_iterator_tag\fP  \fBstd::iterator\fP< \fBinput_iterator_tag\fP , _Tp , _Dist , const _Tp * , const _Tp &  >::\fBiterator_category\fP\fC [inherited]\fP"
.PP
One of the \fBtag types\fP. 
.PP
Definition at line 107 of file stl_iterator_base_types.h.
.SS "typedef const _Tp *  \fBstd::iterator\fP< \fBinput_iterator_tag\fP , _Tp , _Dist , const _Tp * , const _Tp &  >::\fBpointer\fP\fC [inherited]\fP"
.PP
This type represents a pointer-to-value_type. 
.PP
Definition at line 113 of file stl_iterator_base_types.h.
.SS "typedef const _Tp &  \fBstd::iterator\fP< \fBinput_iterator_tag\fP , _Tp , _Dist , const _Tp * , const _Tp &  >::\fBreference\fP\fC [inherited]\fP"
.PP
This type represents a reference-to-value_type. 
.PP
Definition at line 115 of file stl_iterator_base_types.h.
.SS "typedef _Tp  \fBstd::iterator\fP< \fBinput_iterator_tag\fP , _Tp , _Dist , const _Tp * , const _Tp &  >::\fBvalue_type\fP\fC [inherited]\fP"
.PP
The type 'pointed to' by the iterator. 
.PP
Definition at line 109 of file stl_iterator_base_types.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename _Tp, typename _CharT = char, typename _Traits = char_traits<_CharT>, typename _Dist = ptrdiff_t> \fBstd::istream_iterator\fP< _Tp, _CharT, _Traits, _Dist >::\fBistream_iterator\fP ()\fC [inline]\fP"
.PP
Construct end of input stream \fBiterator\fP. 
.PP
Definition at line 57 of file stream_iterator.h.
.SS "template<typename _Tp, typename _CharT = char, typename _Traits = char_traits<_CharT>, typename _Dist = ptrdiff_t> \fBstd::istream_iterator\fP< _Tp, _CharT, _Traits, _Dist >::\fBistream_iterator\fP (\fBistream_type\fP & __s)\fC [inline]\fP"
.PP
Construct start of input stream \fBiterator\fP. 
.PP
Definition at line 61 of file stream_iterator.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
