.TH "std::chrono::duration_values" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::chrono::duration_values \- \fBduration_values\fP  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const _Rep \fBmax\fP ()"
.br
.ti -1c
.RI "static const _Rep \fBmin\fP ()"
.br
.ti -1c
.RI "static const _Rep \fBzero\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Rep> struct std::chrono::duration_values< _Rep >"
\fBduration_values\fP 
.PP
Definition at line 163 of file chrono.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
