.TH "std::slice" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::slice \- Class defining one-dimensional subset of an \fBarray\fP.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "size_t \fBsize\fP () const "
.br
.ti -1c
.RI "\fBslice\fP (size_t, size_t, size_t)"
.br
.ti -1c
.RI "\fBslice\fP ()"
.br
.ti -1c
.RI "size_t \fBstart\fP () const "
.br
.ti -1c
.RI "size_t \fBstride\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Class defining one-dimensional subset of an \fBarray\fP. 

The \fBslice\fP class represents a one-dimensional subset of an \fBarray\fP, specified by three parameters: start offset, size, and stride. The start offset is the index of the first element of the \fBarray\fP that is part of the subset. The size is the total number of elements in the subset. Stride is the distance between each successive \fBarray\fP element to include in the subset.
.PP
For example, with an \fBarray\fP of size 10, and a \fBslice\fP with offset 1, size 3 and stride 2, the subset consists of \fBarray\fP elements 1, 3, and 5. 
.PP
Definition at line 58 of file slice_array.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
