.TH "std::runtime_error" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::runtime_error \- One of two subclasses of \fBexception\fP.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fBstd::exception\fP.
.PP
Inherited by \fBstd::overflow_error\fP, \fBstd::range_error\fP, \fBstd::regex_error\fP, \fBstd::system_error\fP, and \fBstd::underflow_error\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBruntime_error\fP (const \fBstring\fP &__arg)"
.br
.ti -1c
.RI "virtual const char * \fBwhat\fP () const   throw ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
One of two subclasses of \fBexception\fP. 

Runtime errors represent problems outside the scope of a program; they cannot be easily predicted and can generally only be caught as the program executes. 
.PP
Definition at line 107 of file stdexcept.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "std::runtime_error::runtime_error (const \fBstring\fP & __arg)\fC [explicit]\fP"
.PP
Takes a character string describing the error. 
.SH "Member Function Documentation"
.PP 
.SS "virtual const char* std::runtime_error::what () const  throw ()\fC [virtual]\fP"
.PP
Returns a C-style character string describing the general cause of the current error (the same string passed to the ctor). 
.PP
Reimplemented from \fBstd::exception\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
