.TH "__atomic2::atomic_bool" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__atomic2::atomic_bool \- \fBatomic_bool\fP  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBatomic_bool\fP (bool __i)"
.br
.ti -1c
.RI "\fBatomic_bool\fP (const \fBatomic_bool\fP &)"
.br
.ti -1c
.RI "bool \fBcompare_exchange_strong\fP (bool &__i1, bool __i2, memory_order __m=memory_order_seq_cst) volatile"
.br
.ti -1c
.RI "bool \fBcompare_exchange_strong\fP (bool &__i1, bool __i2, memory_order __m1, memory_order __m2) volatile"
.br
.ti -1c
.RI "bool \fBcompare_exchange_weak\fP (bool &__i1, bool __i2, memory_order __m=memory_order_seq_cst) volatile"
.br
.ti -1c
.RI "bool \fBcompare_exchange_weak\fP (bool &__i1, bool __i2, memory_order __m1, memory_order __m2) volatile"
.br
.ti -1c
.RI "bool \fBexchange\fP (bool __i, memory_order __m=memory_order_seq_cst) volatile"
.br
.ti -1c
.RI "bool \fBis_lock_free\fP () const volatile"
.br
.ti -1c
.RI "bool \fBload\fP (memory_order __m=memory_order_seq_cst) const volatile"
.br
.ti -1c
.RI "\fBoperator bool\fP () const volatile"
.br
.ti -1c
.RI "bool \fBoperator=\fP (bool __i)"
.br
.ti -1c
.RI "\fBatomic_bool\fP & \fBoperator=\fP (const \fBatomic_bool\fP &)"
.br
.ti -1c
.RI "void \fBstore\fP (bool __i, memory_order __m=memory_order_seq_cst) volatile"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBatomic_bool\fP 
.PP
Definition at line 388 of file atomic_2.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
