.TH "std::placeholders" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::placeholders \- ISO C++ 0x entities sub namespace for functional.  

.PP
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
ISO C++ 0x entities sub namespace for functional. 

Define a large number of \fBplaceholders\fP. There is no way to simplify this with variadic templates, because we're introducing unique names for each. 
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
