std::tr1::__detail::__numeric_constants
NAME
std::tr1::__detail::__numeric_constants - A structure for numeric constants.
SYNOPSIS
Static Public Member Functions
static _Tp __1_pi () throw ()
static _Tp __2_sqrtpi () throw ()
static _Tp __euler () throw ()
static _Tp __gamma_e () throw ()
static _Tp __lnpi () throw ()
static _Tp __pi () throw ()
static _Tp __pi_2 () throw ()
static _Tp __pi_3 () throw ()
static _Tp __pi_4 () throw ()
static _Tp __sqrt1_2 () throw ()
static _Tp __sqrt2 () throw ()
static _Tp __sqrt3 () throw ()
static _Tp __sqrtpio2 () throw ()
Detailed Description
template<typename _Tp> struct std::tr1::__detail::__numeric_constants< _Tp >
A structure for numeric constants.
Definition at line 60 of file special_function_util.h.
Member Function Documentation
template<typename _Tp > static _Tp std::tr1::__detail::__numeric_constants< _Tp >::__1_pi () throw () [inline, static]
Constant $ 1 / \pi $.
Definition at line 75 of file special_function_util.h.
template<typename _Tp > static _Tp std::tr1::__detail::__numeric_constants< _Tp >::__2_sqrtpi () throw () [inline, static]
Constant $ 2 / \sqrt(\pi) $.
Definition at line 78 of file special_function_util.h.
template<typename _Tp > static _Tp std::tr1::__detail::__numeric_constants< _Tp >::__euler () throw () [inline, static]
Constant Euler-Mascheroni $ e $.
Definition at line 99 of file special_function_util.h.
Referenced by std::tr1::__detail::__log_gamma_lanczos().
template<typename _Tp > static _Tp std::tr1::__detail::__numeric_constants< _Tp >::__gamma_e () throw () [inline, static]
Constant Euler's constant $ \gamma_E $.
Definition at line 96 of file special_function_util.h.
Referenced by std::tr1::__detail::__expint_E1_series(), std::tr1::__detail::__expint_Ei_series(), std::tr1::__detail::__expint_En_series(), std::tr1::__detail::__hyperg_reflect(), and std::tr1::__detail::__psi_series().
template<typename _Tp > static _Tp std::tr1::__detail::__numeric_constants< _Tp >::__lnpi () throw () [inline, static]
Constant $ \log(\pi) $.
Definition at line 93 of file special_function_util.h.
Referenced by std::tr1::__detail::__log_gamma(), and std::tr1::__detail::__sph_legendre().
template<typename _Tp > static _Tp std::tr1::__detail::__numeric_constants< _Tp >::__pi () throw () [inline, static]
Constant $ \pi $.
Definition at line 63 of file special_function_util.h.
Referenced by std::tr1::__detail::__airy(), std::tr1::__detail::__bessel_ik(), std::tr1::__detail::__bessel_jn(), std::tr1::__detail::__ellint_1(), std::tr1::__detail::__ellint_2(), std::tr1::__detail::__ellint_3(), std::tr1::__detail::__psi(), std::tr1::__detail::__riemann_zeta(), and std::tr1::__detail::__riemann_zeta_glob().
template<typename _Tp > static _Tp std::tr1::__detail::__numeric_constants< _Tp >::__pi_2 () throw () [inline, static]
Constant $ \pi / 2 $.
Definition at line 66 of file special_function_util.h.
Referenced by std::tr1::__detail::__comp_ellint_1_series(), std::tr1::__detail::__comp_ellint_2_series(), and std::tr1::__detail::__poly_laguerre_large_n().
template<typename _Tp > static _Tp std::tr1::__detail::__numeric_constants< _Tp >::__pi_3 () throw () [inline, static]
Constant $ \pi / 3 $.
Definition at line 69 of file special_function_util.h.
template<typename _Tp > static _Tp std::tr1::__detail::__numeric_constants< _Tp >::__pi_4 () throw () [inline, static]
Constant $ \pi / 4 $.
Definition at line 72 of file special_function_util.h.
template<typename _Tp > static _Tp std::tr1::__detail::__numeric_constants< _Tp >::__sqrt1_2 () throw () [inline, static]
Constant $ 1 / sqrt(2) $.
Definition at line 90 of file special_function_util.h.
template<typename _Tp > static _Tp std::tr1::__detail::__numeric_constants< _Tp >::__sqrt2 () throw () [inline, static]
Constant $ \sqrt(2) $.
Definition at line 81 of file special_function_util.h.
template<typename _Tp > static _Tp std::tr1::__detail::__numeric_constants< _Tp >::__sqrt3 () throw () [inline, static]
Constant $ \sqrt(3) $.
Definition at line 84 of file special_function_util.h.
Referenced by std::tr1::__detail::__airy().
template<typename _Tp > static _Tp std::tr1::__detail::__numeric_constants< _Tp >::__sqrtpio2 () throw () [inline, static]
Constant $ \sqrt(\pi/2) $.
Definition at line 87 of file special_function_util.h.
Referenced by std::tr1::__detail::__sph_bessel_ik(), and std::tr1::__detail::__sph_bessel_jn().
Author
Generated automatically by Doxygen for libstdc++ from the source code.