std::list
NAME
std::list - A standard container with linear time access to elements, and fixed time insertion/deletion at any point in the sequence.
SYNOPSIS
Inherits _List_base< _Tp, _Alloc >.
Public Types
typedef _Alloc allocator_type
typedef _List_const_iterator< _Tp > const_iterator
typedef _Tp_alloc_type::const_pointer const_pointer
typedef _Tp_alloc_type::const_reference const_reference
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
typedef ptrdiff_t difference_type
typedef _List_iterator< _Tp > iterator
typedef _Tp_alloc_type::pointer pointer
typedef _Tp_alloc_type::reference reference
typedef std::reverse_iterator< iterator > reverse_iterator
typedef size_t size_type
typedef _Tp value_type
Public Member Functions
void assign (initializer_list< value_type > __l)
template<typename _InputIterator > void assign (_InputIterator __first, _InputIterator __last)
void assign (size_type __n, const value_type &__val)
const_reference back () const
reference back ()
const_iterator begin () const
iterator begin ()
const_iterator cbegin () const
const_iterator cend () const
void clear ()
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
template<typename... _Args> iterator emplace (iterator __position, _Args &&...__args)
template<typename... _Args> void emplace_back (_Args &&...__args)
template<typename... _Args> void emplace_front (_Args &&...__args)
bool empty () const
const_iterator end () const
iterator end ()
iterator erase (iterator __first, iterator __last)
iterator erase (iterator __position)
const_reference front () const
reference front ()
allocator_type get_allocator () const
template<typename _InputIterator > void insert (iterator __position, _InputIterator __first, _InputIterator __last)
void insert (iterator __position, size_type __n, const value_type &__x)
void insert (iterator __p, initializer_list< value_type > __l)
iterator insert (iterator __position, value_type &&__x)
iterator insert (iterator __position, const value_type &__x)
template<typename _InputIterator > list (_InputIterator __first, _InputIterator __last, const allocator_type &__a=allocator_type())
list (initializer_list< value_type > __l, const allocator_type &__a=allocator_type())
list (list &&__x)
list (const list &__x)
list (size_type __n, const value_type &__value=value_type(), const allocator_type &__a=allocator_type())
list (const allocator_type &__a)
list ()
size_type max_size () const
template<typename _StrictWeakOrdering > void merge (list &&, _StrictWeakOrdering)
void merge (list &&__x)
list & operator= (initializer_list< value_type > __l)
list & operator= (list &&__x)
list & operator= (const list &__x)
void pop_back ()
void pop_front ()
void push_back (value_type &&__x)
void push_back (const value_type &__x)
void push_front (value_type &&__x)
void push_front (const value_type &__x)
const_reverse_iterator rbegin () const
reverse_iterator rbegin ()
void remove (const _Tp &__value)
template<typename _Predicate > void remove_if (_Predicate)
const_reverse_iterator rend () const
reverse_iterator rend ()
void resize (size_type __new_size, value_type __x=value_type())
void reverse ()
size_type size () const
template<typename _StrictWeakOrdering > void sort (_StrictWeakOrdering)
void sort ()
void splice (iterator __position, list &&__x, iterator __first, iterator __last)
void splice (iterator __position, list &&__x, iterator __i)
void splice (iterator __position, list &&__x)
void swap (list &&__x)
template<typename _BinaryPredicate > void unique (_BinaryPredicate)
void unique ()
Protected Types
typedef _List_node< _Tp > _Node
typedef _Alloc::template rebind< _List_node< _Tp > >::other _Node_alloc_type
Protected Member Functions
template<typename _InputIterator > void _M_assign_dispatch (_InputIterator __first, _InputIterator __last, __false_type)
template<typename _Integer > void _M_assign_dispatch (_Integer __n, _Integer __val, __true_type)
void _M_check_equal_allocators (list &__x)
void _M_clear ()
template<typename... _Args> _Node * _M_create_node (_Args &&...__args)
void _M_erase (iterator __position)
void _M_fill_assign (size_type __n, const value_type &__val)
void _M_fill_initialize (size_type __n, const value_type &__x)
_List_node< _Tp > * _M_get_node ()
const _Node_alloc_type & _M_get_Node_allocator () const
_Node_alloc_type & _M_get_Node_allocator ()
_Tp_alloc_type _M_get_Tp_allocator () const
void _M_init ()
template<typename _InputIterator > void _M_initialize_dispatch (_InputIterator __first, _InputIterator __last, __false_type)
template<typename _Integer > void _M_initialize_dispatch (_Integer __n, _Integer __x, __true_type)
template<typename... _Args> void _M_insert (iterator __position, _Args &&...__args)
void _M_put_node (_List_node< _Tp > *__p)
void _M_transfer (iterator __position, iterator __first, iterator __last)
Protected Attributes
_List_impl _M_impl
Detailed Description
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> class std::list< _Tp, _Alloc >
A standard container with linear time access to elements, and fixed time insertion/deletion at any point in the sequence.
Meets the requirements of a container, a reversible container, and a sequence, including the optional sequence requirements with the exception of at and operator[].
This is a doubly linked list. Traversal up and down the list requires linear time, but adding and removing elements (or nodes) is done in constant time, regardless of where the change takes place. Unlike std::vector and std::deque, random-access iterators are not provided, so subscripting ( [] ) access is not allowed. For algorithms which only need sequential access, this lack makes no difference.
Also unlike the other standard containers, std::list provides specialized algorithms unique to linked lists, such as splicing, sorting, and in-place reversal.
A couple points on memory allocation for list<Tp>:
First, we never actually allocate a Tp, we allocate List_node<Tp>'s and trust [20.1.5]/4 to DTRT. This is to ensure that after elements from list<X,Alloc1> are spliced into list<X,Alloc2>, destroying the memory of the second list is a valid operation, i.e., Alloc1 giveth and Alloc2 taketh away.
Second, a list conceptually represented as
    A <---> B <---> C <---> D
 is actually circular; a link exists between A and D. The list class holds (as its only data member) a private list::iterator pointing to D, not to A! To get to the head of the list, we start at the tail and move forward by one. When this member iterator's next/previous pointers refer to itself, the list is empty.
Definition at line 417 of file stl_list.h.
Constructor & Destructor Documentation
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> std::list< _Tp, _Alloc >::list () [inline]
Default constructor creates no elements.
Definition at line 499 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> std::list< _Tp, _Alloc >::list (const allocator_type & __a) [inline, explicit]
Creates a list with no elements.
Parameters:
a An allocator object.
Definition at line 507 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> std::list< _Tp, _Alloc >::list (size_type __n, const value_type & __value = value_type(), const allocator_type & __a = allocator_type()) [inline, explicit]
Creates a list with copies of an exemplar element.
Parameters:
n The number of elements to initially create.
value An element to copy.
a An allocator object.
This constructor fills the list with n copies of value.
Definition at line 519 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> std::list< _Tp, _Alloc >::list (const list< _Tp, _Alloc > & __x) [inline]
List copy constructor.
Parameters:
x A list of identical element and allocator types.
The newly-created list uses a copy of the allocation object used by x.
Definition at line 531 of file stl_list.h.
References std::list< _Tp, _Alloc >::begin(), and std::list< _Tp, _Alloc >::end().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> std::list< _Tp, _Alloc >::list (list< _Tp, _Alloc > && __x) [inline]
List move constructor.
Parameters:
x A list of identical element and allocator types.
The newly-created list contains the exact contents of x. The contents of x are a valid, but unspecified list.
Definition at line 543 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> std::list< _Tp, _Alloc >::list (initializer_list< value_type > __l, const allocator_type & __a = allocator_type()) [inline]
Builds a list from an initializer_list.
Parameters:
l An initializer_list of value_type.
a An allocator object.
Create a list consisting of copies of the elements in the initializer_list l. This is linear in l.size().
Definition at line 554 of file stl_list.h.
References std::initializer_list< _E >::begin(), and std::initializer_list< _E >::end().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> template<typename _InputIterator > std::list< _Tp, _Alloc >::list (_InputIterator __first, _InputIterator __last, const allocator_type & __a = allocator_type()) [inline]
Builds a list from a range.
Parameters:
first An input iterator.
last An input iterator.
a An allocator object.
Create a list consisting of copies of the elements from [first,last). This is linear in N (where N is distance(first,last)).
Definition at line 571 of file stl_list.h.
Member Function Documentation
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> template<typename... _Args> _Node* std::list< _Tp, _Alloc >::_M_create_node (_Args &&... __args) [inline, protected]
Parameters:
x An instance of user data.
Allocates space for a new node and constructs a copy of x in it.
Definition at line 476 of file stl_list.h.
Referenced by std::list< _Tp, _Alloc >::emplace(), and std::list< _Tp, _Alloc >::insert().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::list< _Tp, _Alloc >::assign (initializer_list< value_type > __l) [inline]
Assigns an initializer_list to a list.
Parameters:
l An initializer_list of value_type.
Replace the contents of the list with copies of the elements in the initializer_list l. This is linear in l.size().
Definition at line 674 of file stl_list.h.
References std::list< _Tp, _Alloc >::assign(), std::initializer_list< _E >::begin(), and std::initializer_list< _E >::end().
Referenced by std::list< _Tp, _Alloc >::assign().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> template<typename _InputIterator > void std::list< _Tp, _Alloc >::assign (_InputIterator __first, _InputIterator __last) [inline]
Assigns a range to a list.
Parameters:
first An input iterator.
last An input iterator.
This function fills a list with copies of the elements in the range [first,last).
Note that the assignment completely changes the list and that the resulting list's size is the same as the number of elements assigned. Old data may be lost.
Definition at line 658 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::list< _Tp, _Alloc >::assign (size_type __n, const value_type & __val) [inline]
Assigns a given value to a list.
Parameters:
n Number of elements to be assigned.
val Value to be assigned.
This function fills a list with n copies of the given value. Note that the assignment completely changes the list and that the resulting list's size is the same as the number of elements assigned. Old data may be lost.
Definition at line 641 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_reference std::list< _Tp, _Alloc >::back () const [inline]
Returns a read-only (constant) reference to the data at the last element of the list.
Definition at line 859 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> reference std::list< _Tp, _Alloc >::back () [inline]
Returns a read/write reference to the data at the last element of the list.
Definition at line 847 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_iterator std::list< _Tp, _Alloc >::begin () const [inline]
Returns a read-only (constant) iterator that points to the first element in the list. Iteration is done in ordinary element order.
Definition at line 698 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> iterator std::list< _Tp, _Alloc >::begin () [inline]
Returns a read/write iterator that points to the first element in the list. Iteration is done in ordinary element order.
Definition at line 689 of file stl_list.h.
Referenced by std::list< _Tp, _Alloc >::list(), std::list< _Tp, _Alloc >::merge(), std::list< _Tp, _Alloc >::operator=(), std::operator==(), std::list< _Tp, _Alloc >::remove(), std::list< _Tp, _Alloc >::remove_if(), std::list< _Tp, _Alloc >::resize(), std::list< _Tp, _Alloc >::sort(), std::list< _Tp, _Alloc >::splice(), and std::list< _Tp, _Alloc >::unique().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_iterator std::list< _Tp, _Alloc >::cbegin () const [inline]
Returns a read-only (constant) iterator that points to the first element in the list. Iteration is done in ordinary element order.
Definition at line 762 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_iterator std::list< _Tp, _Alloc >::cend () const [inline]
Returns a read-only (constant) iterator that points one past the last element in the list. Iteration is done in ordinary element order.
Definition at line 771 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::list< _Tp, _Alloc >::clear () [inline]
Erases all the elements. Note that this function only erases the elements, and that if the elements themselves are pointers, the pointed-to memory is not touched in any way. Managing the pointer is the user's responsibility.
Definition at line 1130 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_reverse_iterator std::list< _Tp, _Alloc >::crbegin () const [inline]
Returns a read-only (constant) reverse iterator that points to the last element in the list. Iteration is done in reverse element order.
Definition at line 780 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_reverse_iterator std::list< _Tp, _Alloc >::crend () const [inline]
Returns a read-only (constant) reverse iterator that points to one before the first element in the list. Iteration is done in reverse element order.
Definition at line 789 of file stl_list.h.
template<typename _Tp , typename _Alloc > template<typename... _Args> list< _Tp, _Alloc >::iterator list::emplace (iterator __position, _Args &&... __args) [inline]
Constructs object in list before specified iterator.
Parameters:
position A const_iterator into the list.
args Arguments.
Returns:
An iterator that points to the inserted data.
This function will insert an object of type T constructed with T(std::forward<Args>(args)...) before the specified location. Due to the nature of a list this operation can be done in constant time, and does not invalidate iterators and references.
Definition at line 87 of file list.tcc.
References std::list< _Tp, _Alloc >::_M_create_node(), std::_List_iterator< _Tp >::_M_node, and std::_List_node_base::hook().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> bool std::list< _Tp, _Alloc >::empty () const [inline]
Returns true if the list is empty. (Thus begin() would equal end().)
Definition at line 799 of file stl_list.h.
Referenced by std::list< _Tp, _Alloc >::sort(), and std::list< _Tp, _Alloc >::splice().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_iterator std::list< _Tp, _Alloc >::end () const [inline]
Returns a read-only (constant) iterator that points one past the last element in the list. Iteration is done in ordinary element order.
Definition at line 716 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> iterator std::list< _Tp, _Alloc >::end () [inline]
Returns a read/write iterator that points one past the last element in the list. Iteration is done in ordinary element order.
Definition at line 707 of file stl_list.h.
Referenced by std::list< _Tp, _Alloc >::list(), std::list< _Tp, _Alloc >::merge(), std::list< _Tp, _Alloc >::operator=(), std::operator==(), std::list< _Tp, _Alloc >::remove(), std::list< _Tp, _Alloc >::remove_if(), std::list< _Tp, _Alloc >::resize(), std::list< _Tp, _Alloc >::splice(), and std::list< _Tp, _Alloc >::unique().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> iterator std::list< _Tp, _Alloc >::erase (iterator __first, iterator __last) [inline]
Remove a range of elements.
Parameters:
first Iterator pointing to the first element to be erased.
last Iterator pointing to one past the last element to be erased.
Returns:
An iterator pointing to the element pointed to by last prior to erasing (or end()).
This function will erase the elements in the range [first,last) and shorten the list accordingly.
This operation is linear time in the size of the range and only invalidates iterators/references to the element being removed. The user is also cautioned that this function only erases the elements, and that if the elements themselves are pointers, the pointed-to memory is not touched in any way. Managing the pointer is the user's responsibility.
Definition at line 1092 of file stl_list.h.
template<typename _Tp , typename _Alloc > list< _Tp, _Alloc >::iterator list::erase (iterator __position) [inline]
Remove element at given position.
Parameters:
position Iterator pointing to element to be erased.
Returns:
An iterator pointing to the next element (or end()).
This function will erase the element at the given position and thus shorten the list by one.
Due to the nature of a list this operation can be done in constant time, and only invalidates iterators/references to the element being removed. The user is also cautioned that this function only erases the element, and that if the element is itself a pointer, the pointed-to memory is not touched in any way. Managing the pointer is the user's responsibility.
Definition at line 108 of file list.tcc.
References std::_List_node_base::_M_next, and std::_List_iterator< _Tp >::_M_node.
Referenced by std::list< _Tp, _Alloc >::operator=(), and std::list< _Tp, _Alloc >::resize().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_reference std::list< _Tp, _Alloc >::front () const [inline]
Returns a read-only (constant) reference to the data at the first element of the list.
Definition at line 839 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> reference std::list< _Tp, _Alloc >::front () [inline]
Returns a read/write reference to the data at the first element of the list.
Definition at line 831 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> allocator_type std::list< _Tp, _Alloc >::get_allocator () const [inline]
Get a copy of the memory allocation object.
Reimplemented from std::_List_base< _Tp, _Alloc >.
Definition at line 680 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> template<typename _InputIterator > void std::list< _Tp, _Alloc >::insert (iterator __position, _InputIterator __first, _InputIterator __last) [inline]
Inserts a range into the list.
Parameters:
position An iterator into the list.
first An input iterator.
last An input iterator.
This function will insert copies of the data in the range [first,last) into the list before the location specified by position.
This operation is linear in the number of elements inserted and does not invalidate iterators and references.
Definition at line 1048 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::list< _Tp, _Alloc >::insert (iterator __position, size_type __n, const value_type & __x) [inline]
Inserts a number of copies of given data into the list.
Parameters:
position An iterator into the list.
n Number of elements to be inserted.
x Data to be inserted.
This function will insert a specified number of copies of the given data before the location specified by position.
This operation is linear in the number of elements inserted and does not invalidate iterators and references.
Definition at line 1027 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::list< _Tp, _Alloc >::insert (iterator __p, initializer_list< value_type > __l) [inline]
Inserts the contents of an initializer_list into list before specified iterator.
Parameters:
p An iterator into the list.
l An initializer_list of value_type.
This function will insert copies of the data in the initializer_list l into the list before the location specified by p.
This operation is linear in the number of elements inserted and does not invalidate iterators and references.
Definition at line 1010 of file stl_list.h.
References std::initializer_list< _E >::begin(), std::initializer_list< _E >::end(), and std::list< _Tp, _Alloc >::insert().
Referenced by std::list< _Tp, _Alloc >::insert().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> iterator std::list< _Tp, _Alloc >::insert (iterator __position, value_type && __x) [inline]
Inserts given rvalue into list before specified iterator.
Parameters:
position An iterator into the list.
x Data to be inserted.
Returns:
An iterator that points to the inserted data.
This function will insert a copy of the given rvalue before the specified location. Due to the nature of a list this operation can be done in constant time, and does not invalidate iterators and references.
Definition at line 993 of file stl_list.h.
References std::move().
template<typename _Tp , typename _Alloc > list< _Tp, _Alloc >::iterator list::insert (iterator __position, const value_type & __x) [inline]
Inserts given value into list before specified iterator.
Parameters:
position An iterator into the list.
x Data to be inserted.
Returns:
An iterator that points to the inserted data.
This function will insert a copy of the given value before the specified location. Due to the nature of a list this operation can be done in constant time, and does not invalidate iterators and references.
Definition at line 98 of file list.tcc.
References std::list< _Tp, _Alloc >::_M_create_node(), std::_List_iterator< _Tp >::_M_node, and std::_List_node_base::hook().
Referenced by std::list< _Tp, _Alloc >::operator=(), and std::list< _Tp, _Alloc >::resize().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> size_type std::list< _Tp, _Alloc >::max_size () const [inline]
Returns the size() of the largest possible list.
Definition at line 809 of file stl_list.h.
template<typename _Tp , typename _Alloc > template<typename _StrictWeakOrdering > void list::merge (list< _Tp, _Alloc > && __x, _StrictWeakOrdering __comp) [inline]
Merge sorted lists according to comparison function.
Parameters:
x Sorted list to merge.
StrictWeakOrdering Comparison function defining sort order.
Assumes that both x and this list are sorted according to StrictWeakOrdering. Merges elements of x into this list in sorted order, leaving x empty when complete. Elements in this list precede elements in x that are equivalent according to StrictWeakOrdering().
Definition at line 270 of file list.tcc.
References std::list< _Tp, _Alloc >::begin(), and std::list< _Tp, _Alloc >::end().
template<typename _Tp , typename _Alloc > void list::merge (list< _Tp, _Alloc > && __x) [inline]
Merge sorted lists.
Parameters:
x Sorted list to merge.
Assumes that both x and this list are sorted according to operator<(). Merges elements of x into this list in sorted order, leaving x empty when complete. Elements in this list precede elements in x that are equal.
Definition at line 236 of file list.tcc.
References std::list< _Tp, _Alloc >::begin(), and std::list< _Tp, _Alloc >::end().
Referenced by std::list< _Tp, _Alloc >::sort().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> list& std::list< _Tp, _Alloc >::operator= (initializer_list< value_type > __l) [inline]
List initializer list assignment operator.
Parameters:
l An initializer_list of value_type.
Replace the contents of the list with copies of the elements in the initializer_list l. This is linear in l.size().
Definition at line 623 of file stl_list.h.
References std::initializer_list< _E >::begin(), and std::initializer_list< _E >::end().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> list& std::list< _Tp, _Alloc >::operator= (list< _Tp, _Alloc > && __x) [inline]
List move assignment operator.
Parameters:
x A list of identical element and allocator types.
The contents of x are moved into this list (without copying). x is a valid, but unspecified list
Definition at line 607 of file stl_list.h.
template<typename _Tp , typename _Alloc > list< _Tp, _Alloc > & list::operator= (const list< _Tp, _Alloc > & __x) [inline]
List assignment operator.
No explicit dtor needed as the _Base dtor takes care of things. The _Base dtor only erases the elements, and note that if the elements themselves are pointers, the pointed-to memory is not touched in any way. Managing the pointer is the user's responsibility.
Parameters:
x A list of identical element and allocator types.
All the elements of x are copied, but unlike the copy constructor, the allocator object is not copied.
Definition at line 133 of file list.tcc.
References std::list< _Tp, _Alloc >::begin(), std::list< _Tp, _Alloc >::end(), std::list< _Tp, _Alloc >::erase(), and std::list< _Tp, _Alloc >::insert().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::list< _Tp, _Alloc >::pop_back () [inline]
Removes last element.
This is a typical stack operation. It shrinks the list by one. Due to the nature of a list this operation can be done in constant time, and only invalidates iterators/references to the element being removed.
Note that no data is returned, and if the last element's data is needed, it should be retrieved before pop_back() is called.
Definition at line 945 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::list< _Tp, _Alloc >::pop_front () [inline]
Removes first element.
This is a typical stack operation. It shrinks the list by one. Due to the nature of a list this operation can be done in constant time, and only invalidates iterators/references to the element being removed.
Note that no data is returned, and if the first element's data is needed, it should be retrieved before pop_front() is called.
Definition at line 905 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::list< _Tp, _Alloc >::push_back (const value_type & __x) [inline]
Add data to the end of the list.
Parameters:
x Data to be added.
This is a typical stack operation. The function creates an element at the end of the list and assigns the given data to it. Due to the nature of a list this operation can be done in constant time, and does not invalidate iterators and references.
Definition at line 919 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::list< _Tp, _Alloc >::push_front (const value_type & __x) [inline]
Add data to the front of the list.
Parameters:
x Data to be added.
This is a typical stack operation. The function creates an element at the front of the list and assigns the given data to it. Due to the nature of a list this operation can be done in constant time, and does not invalidate iterators and references.
Definition at line 878 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_reverse_iterator std::list< _Tp, _Alloc >::rbegin () const [inline]
Returns a read-only (constant) reverse iterator that points to the last element in the list. Iteration is done in reverse element order.
Definition at line 734 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> reverse_iterator std::list< _Tp, _Alloc >::rbegin () [inline]
Returns a read/write reverse iterator that points to the last element in the list. Iteration is done in reverse element order.
Definition at line 725 of file stl_list.h.
template<typename _Tp, typename _Alloc > void list::remove (const _Tp & __value) [inline]
Remove all elements equal to value.
Parameters:
value The value to remove.
Removes every element in the list equal to value. Remaining elements stay in list order. Note that this function only erases the elements, and that if the elements themselves are pointers, the pointed-to memory is not touched in any way. Managing the pointer is the user's responsibility.
Definition at line 187 of file list.tcc.
References std::list< _Tp, _Alloc >::begin(), and std::list< _Tp, _Alloc >::end().
template<typename _Tp , typename _Alloc > template<typename _Predicate > void list::remove_if (_Predicate __pred) [inline]
Remove all elements satisfying a predicate.
Parameters:
Predicate Unary predicate function or object.
Removes every element in the list for which the predicate returns true. Remaining elements stay in list order. Note that this function only erases the elements, and that if the elements themselves are pointers, the pointed-to memory is not touched in any way. Managing the pointer is the user's responsibility.
Definition at line 340 of file list.tcc.
References std::list< _Tp, _Alloc >::begin(), and std::list< _Tp, _Alloc >::end().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> const_reverse_iterator std::list< _Tp, _Alloc >::rend () const [inline]
Returns a read-only (constant) reverse iterator that points to one before the first element in the list. Iteration is done in reverse element order.
Definition at line 752 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> reverse_iterator std::list< _Tp, _Alloc >::rend () [inline]
Returns a read/write reverse iterator that points to one before the first element in the list. Iteration is done in reverse element order.
Definition at line 743 of file stl_list.h.
template<typename _Tp , typename _Alloc > void list::resize (size_type __new_size, value_type __x = value_type()) [inline]
Resizes the list to the specified number of elements.
Parameters:
new_size Number of elements the list should contain.
x Data with which new elements should be populated.
This function will resize the list to the specified number of elements. If the number is smaller than the list's current size the list is truncated, otherwise the list is extended and new elements are populated with given data.
Definition at line 118 of file list.tcc.
References std::list< _Tp, _Alloc >::begin(), std::list< _Tp, _Alloc >::end(), std::list< _Tp, _Alloc >::erase(), and std::list< _Tp, _Alloc >::insert().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::list< _Tp, _Alloc >::reverse () [inline]
Reverse the elements in list.
Reverse the order of elements in the list in linear time.
Definition at line 1320 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> size_type std::list< _Tp, _Alloc >::size () const [inline]
Returns the number of elements in the list.
Definition at line 804 of file stl_list.h.
References std::distance().
template<typename _Tp , typename _Alloc > template<typename _StrictWeakOrdering > void list::sort (_StrictWeakOrdering __comp) [inline]
Sort the elements according to comparison function.
Sorts the elements of this list in NlogN time. Equivalent elements remain in list order.
Definition at line 379 of file list.tcc.
References std::list< _Tp, _Alloc >::begin(), std::list< _Tp, _Alloc >::empty(), std::list< _Tp, _Alloc >::merge(), std::list< _Tp, _Alloc >::splice(), and std::list< _Tp, _Alloc >::swap().
template<typename _Tp , typename _Alloc > void list::sort () [inline]
Sort the elements.
Sorts the elements of this list in NlogN time. Equivalent elements remain in list order.
Definition at line 302 of file list.tcc.
References std::list< _Tp, _Alloc >::begin(), std::list< _Tp, _Alloc >::empty(), std::list< _Tp, _Alloc >::merge(), std::list< _Tp, _Alloc >::splice(), and std::list< _Tp, _Alloc >::swap().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::list< _Tp, _Alloc >::splice (iterator __position, list< _Tp, _Alloc > && __x, iterator __first, iterator __last) [inline]
Insert range from another list.
Parameters:
position Iterator referencing the element to insert before.
x Source list.
first Iterator referencing the start of range in x.
last Iterator referencing the end of range in x.
Removes elements in the range [first,last) and inserts them before position in constant time.
Undefined if position is in [first,last).
Definition at line 1204 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::list< _Tp, _Alloc >::splice (iterator __position, list< _Tp, _Alloc > && __x, iterator __i) [inline]
Insert element from another list.
Parameters:
position Iterator referencing the element to insert before.
x Source list.
i Iterator referencing the element to move.
Removes the element in list x referenced by i and inserts it into the current list before position.
Definition at line 1174 of file stl_list.h.
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::list< _Tp, _Alloc >::splice (iterator __position, list< _Tp, _Alloc > && __x) [inline]
Insert contents of another list.
Parameters:
position Iterator referencing the element to insert before.
x Source list.
The elements of x are inserted in constant time in front of the element referenced by position. x becomes an empty list.
Requires this != x.
Definition at line 1150 of file stl_list.h.
References std::list< _Tp, _Alloc >::begin(), std::list< _Tp, _Alloc >::empty(), and std::list< _Tp, _Alloc >::end().
Referenced by std::list< _Tp, _Alloc >::sort().
template<typename _Tp, typename _Alloc = std::allocator<_Tp>> void std::list< _Tp, _Alloc >::swap (list< _Tp, _Alloc > && __x) [inline]
Swaps data with another list.
Parameters:
x A list of the same element and allocator types.
This exchanges the elements between two lists in constant time. Note that the global std::swap() function is specialized such that std::swap(l1,l2) will feed to this function.
Definition at line 1110 of file stl_list.h.
References std::_List_base< _Tp, _Alloc >::_M_get_Node_allocator(), and std::_List_base< _Tp, _Alloc >::_M_impl.
Referenced by std::list< _Tp, _Alloc >::sort(), and std::swap().
template<typename _Tp , typename _Alloc > template<typename _BinaryPredicate > void list::unique (_BinaryPredicate __binary_pred) [inline]
Remove consecutive elements satisfying a predicate.
Parameters:
BinaryPredicate Binary predicate function or object.
For each consecutive set of elements [first,last) that satisfy predicate(first,i) where i is an iterator in [first,last), remove all but the first one. Remaining elements stay in list order. Note that this function only erases the elements, and that if the elements themselves are pointers, the pointed-to memory is not touched in any way. Managing the pointer is the user's responsibility.
Definition at line 358 of file list.tcc.
References std::list< _Tp, _Alloc >::begin(), and std::list< _Tp, _Alloc >::end().
template<typename _Tp , typename _Alloc > void list::unique () [inline]
Remove consecutive duplicate elements.
For each consecutive set of elements with the same value, remove all but the first one. Remaining elements stay in list order. Note that this function only erases the elements, and that if the elements themselves are pointers, the pointed-to memory is not touched in any way. Managing the pointer is the user's responsibility.
Definition at line 215 of file list.tcc.
References std::list< _Tp, _Alloc >::begin(), and std::list< _Tp, _Alloc >::end().
Author
Generated automatically by Doxygen for libstdc++ from the source code.