.TH "std::num_get" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::num_get \- Facet for parsing number strings.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fBstd::locale::facet\fP.
.PP
.SS "Public Types"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "typedef _CharT \fBchar_type\fP"
.br
.ti -1c
.RI "typedef _InIter \fBiter_type\fP"
.br
.in -1c
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBiter_type\fP \fBget\fP (\fBiter_type\fP __in, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, void *&__v) const "
.br
.ti -1c
.RI "\fBiter_type\fP \fBget\fP (\fBiter_type\fP __in, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, bool &__v) const "
.br
.ti -1c
.RI "\fBnum_get\fP (size_t __refs=0)"
.br
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "\fBiter_type\fP \fBget\fP (\fBiter_type\fP __in, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, long double &__v) const "
.br
.ti -1c
.RI "\fBiter_type\fP \fBget\fP (\fBiter_type\fP __in, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, double &__v) const "
.br
.ti -1c
.RI "\fBiter_type\fP \fBget\fP (\fBiter_type\fP __in, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, float &__v) const "
.br
.in -1c
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "\fBiter_type\fP \fBget\fP (\fBiter_type\fP __in, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, unsigned long long &__v) const "
.br
.ti -1c
.RI "\fBiter_type\fP \fBget\fP (\fBiter_type\fP __in, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, long long &__v) const "
.br
.ti -1c
.RI "\fBiter_type\fP \fBget\fP (\fBiter_type\fP __in, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, unsigned long &__v) const "
.br
.ti -1c
.RI "\fBiter_type\fP \fBget\fP (\fBiter_type\fP __in, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, unsigned int &__v) const "
.br
.ti -1c
.RI "\fBiter_type\fP \fBget\fP (\fBiter_type\fP __in, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, unsigned short &__v) const "
.br
.ti -1c
.RI "\fBiter_type\fP \fBget\fP (\fBiter_type\fP __in, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, long &__v) const "
.br
.in -1c
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBlocale::id\fP \fBid\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBiter_type\fP \fB_M_extract_float\fP (\fBiter_type\fP, \fBiter_type\fP, \fBios_base\fP &, \fBios_base::iostate\fP &, \fBstring\fP &) const "
.br
.ti -1c
.RI "template<typename _ValueT > \fBiter_type\fP \fB_M_extract_int\fP (\fBiter_type\fP, \fBiter_type\fP, \fBios_base\fP &, \fBios_base::iostate\fP &, _ValueT &) const "
.br
.ti -1c
.RI "template<typename _CharT2 > __gnu_cxx::__enable_if<!__is_char< _CharT2 >::__value, int >::__type \fB_M_find\fP (const _CharT2 *__zero, size_t __len, _CharT2 __c) const "
.br
.ti -1c
.RI "template<typename _CharT2 > __gnu_cxx::__enable_if< __is_char< _CharT2 >::__value, int >::__type \fB_M_find\fP (const _CharT2 *, size_t __len, _CharT2 __c) const "
.br
.ti -1c
.RI "virtual \fB~num_get\fP ()"
.br
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "virtual \fBiter_type\fP \fBdo_get\fP (\fBiter_type\fP, \fBiter_type\fP, \fBios_base\fP &, \fBios_base::iostate\fP &__err, void *&) const "
.br
.ti -1c
.RI "virtual \fBiter_type\fP \fBdo_get\fP (\fBiter_type\fP, \fBiter_type\fP, \fBios_base\fP &, \fBios_base::iostate\fP &__err, long double &) const "
.br
.ti -1c
.RI "virtual \fBiter_type\fP \fBdo_get\fP (\fBiter_type\fP, \fBiter_type\fP, \fBios_base\fP &, \fBios_base::iostate\fP &__err, double &) const "
.br
.ti -1c
.RI "virtual \fBiter_type\fP \fBdo_get\fP (\fBiter_type\fP, \fBiter_type\fP, \fBios_base\fP &, \fBios_base::iostate\fP &__err, float &) const "
.br
.ti -1c
.RI "virtual \fBiter_type\fP \fBdo_get\fP (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, unsigned long long &__v) const "
.br
.ti -1c
.RI "virtual \fBiter_type\fP \fBdo_get\fP (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, long long &__v) const "
.br
.ti -1c
.RI "virtual \fBiter_type\fP \fBdo_get\fP (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, unsigned long &__v) const "
.br
.ti -1c
.RI "virtual \fBiter_type\fP \fBdo_get\fP (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, unsigned int &__v) const "
.br
.ti -1c
.RI "virtual \fBiter_type\fP \fBdo_get\fP (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, unsigned short &__v) const "
.br
.ti -1c
.RI "virtual \fBiter_type\fP \fBdo_get\fP (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, long &__v) const "
.br
.ti -1c
.RI "virtual \fBiter_type\fP \fBdo_get\fP (\fBiter_type\fP, \fBiter_type\fP, \fBios_base\fP &, \fBios_base::iostate\fP &, bool &) const "
.br
.in -1c
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static __c_locale \fB_S_clone_c_locale\fP (__c_locale &__cloc)"
.br
.ti -1c
.RI "static void \fB_S_create_c_locale\fP (__c_locale &__cloc, const char *__s, __c_locale __old=0)"
.br
.ti -1c
.RI "static void \fB_S_destroy_c_locale\fP (__c_locale &__cloc)"
.br
.ti -1c
.RI "static __c_locale \fB_S_get_c_locale\fP ()"
.br
.ti -1c
.RI "static const char * \fB_S_get_c_name\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBlocale::_Impl\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _CharT, typename _InIter> class std::num_get< _CharT, _InIter >"
Facet for parsing number strings. 

This facet encapsulates the code to parse and return a number from a string. It is used by the istream numeric extraction operators.
.PP
The \fBnum_get\fP template uses protected virtual functions to provide the actual results. The public accessors forward the call to the virtual functions. These virtual functions are hooks for developers to implement the behavior they require from the \fBnum_get\fP facet. 
.PP
Definition at line 1908 of file locale_facets.h.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename _CharT , typename _InIter > typedef _CharT \fBstd::num_get\fP< _CharT, _InIter >::\fBchar_type\fP"
.PP
Public typedefs. 
.PP
Definition at line 1914 of file locale_facets.h.
.SS "template<typename _CharT , typename _InIter > typedef _InIter \fBstd::num_get\fP< _CharT, _InIter >::\fBiter_type\fP"
.PP
Public typedefs. 
.PP
Definition at line 1915 of file locale_facets.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename _CharT , typename _InIter > \fBstd::num_get\fP< _CharT, _InIter >::\fBnum_get\fP (size_t __refs = \fC0\fP)\fC [inline, explicit]\fP"
.PP
Constructor performs initialization. 
.PP
This is the constructor provided by the standard.
.PP
\fBParameters:\fP
.RS 4
\fIrefs\fP Passed to the base facet class. 
.RE
.PP

.PP
Definition at line 1929 of file locale_facets.h.
.SS "template<typename _CharT , typename _InIter > virtual \fBstd::num_get\fP< _CharT, _InIter >::~\fBnum_get\fP ()\fC [inline, protected, virtual]\fP"
.PP
Destructor. 
.PP
Definition at line 2098 of file locale_facets.h.
.SH "Member Function Documentation"
.PP 
.SS "template<typename _CharT , typename _InIter > _InIter \fBstd::num_get\fP< _CharT, _InIter >::do_get (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP & __io, \fBios_base::iostate\fP & __err, void *& __v) const\fC [inline, protected, virtual]\fP"
.PP
Numeric parsing. 
.PP
Parses the input stream into the variable \fIv\fP. This function is a hook for derived classes to change the value returned. 
.PP
\fBSee also:\fP
.RS 4
\fBget()\fP for more details.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIin\fP Start of input stream. 
.br
\fIend\fP End of input stream. 
.br
\fIio\fP Source of \fBlocale\fP and flags. 
.br
\fIerr\fP Error flags to \fBset\fP. 
.br
\fIv\fP Value to format and insert. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator after reading. 
.RE
.PP

.PP
Definition at line 732 of file locale_facets.tcc.
.PP
References std::ios_base::basefield, std::ios_base::flags(), and std::ios_base::hex.
.SS "template<typename _CharT , typename _InIter > _InIter \fBstd::num_get\fP< _CharT, _InIter >::do_get (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP & __io, \fBios_base::iostate\fP & __err, long double & __v) const\fC [inline, protected, virtual]\fP"
.PP
Numeric parsing. 
.PP
Parses the input stream into the variable \fIv\fP. This function is a hook for derived classes to change the value returned. 
.PP
\fBSee also:\fP
.RS 4
\fBget()\fP for more details.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIin\fP Start of input stream. 
.br
\fIend\fP End of input stream. 
.br
\fIio\fP Source of \fBlocale\fP and flags. 
.br
\fIerr\fP Error flags to \fBset\fP. 
.br
\fIv\fP Value to format and insert. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator after reading. 
.RE
.PP

.PP
Definition at line 717 of file locale_facets.tcc.
.PP
References std::basic_string< _CharT, _Traits, _Alloc >::c_str(), std::ios_base::eofbit, and std::basic_string< _CharT, _Traits, _Alloc >::reserve().
.SS "template<typename _CharT , typename _InIter > _InIter \fBstd::num_get\fP< _CharT, _InIter >::do_get (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP & __io, \fBios_base::iostate\fP & __err, double & __v) const\fC [inline, protected, virtual]\fP"
.PP
Numeric parsing. 
.PP
Parses the input stream into the variable \fIv\fP. This function is a hook for derived classes to change the value returned. 
.PP
\fBSee also:\fP
.RS 4
\fBget()\fP for more details.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIin\fP Start of input stream. 
.br
\fIend\fP End of input stream. 
.br
\fIio\fP Source of \fBlocale\fP and flags. 
.br
\fIerr\fP Error flags to \fBset\fP. 
.br
\fIv\fP Value to format and insert. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator after reading. 
.RE
.PP

.PP
Definition at line 685 of file locale_facets.tcc.
.PP
References std::basic_string< _CharT, _Traits, _Alloc >::c_str(), std::ios_base::eofbit, and std::basic_string< _CharT, _Traits, _Alloc >::reserve().
.SS "template<typename _CharT , typename _InIter > _InIter \fBstd::num_get\fP< _CharT, _InIter >::do_get (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP & __io, \fBios_base::iostate\fP & __err, float & __v) const\fC [inline, protected, virtual]\fP"
.PP
Numeric parsing. 
.PP
Parses the input stream into the variable \fIv\fP. This function is a hook for derived classes to change the value returned. 
.PP
\fBSee also:\fP
.RS 4
\fBget()\fP for more details.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIin\fP Start of input stream. 
.br
\fIend\fP End of input stream. 
.br
\fIio\fP Source of \fBlocale\fP and flags. 
.br
\fIerr\fP Error flags to \fBset\fP. 
.br
\fIv\fP Value to format and insert. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator after reading. 
.RE
.PP

.PP
Definition at line 670 of file locale_facets.tcc.
.PP
References std::basic_string< _CharT, _Traits, _Alloc >::c_str(), std::ios_base::eofbit, and std::basic_string< _CharT, _Traits, _Alloc >::reserve().
.SS "template<typename _CharT , typename _InIter > virtual \fBiter_type\fP \fBstd::num_get\fP< _CharT, _InIter >::do_get (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP & __io, \fBios_base::iostate\fP & __err, unsigned long long & __v) const\fC [inline, protected, virtual]\fP"
.PP
Numeric parsing. 
.PP
Parses the input stream into the variable \fIv\fP. This function is a hook for derived classes to change the value returned. 
.PP
\fBSee also:\fP
.RS 4
\fBget()\fP for more details.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIin\fP Start of input stream. 
.br
\fIend\fP End of input stream. 
.br
\fIio\fP Source of \fBlocale\fP and flags. 
.br
\fIerr\fP Error flags to \fBset\fP. 
.br
\fIv\fP Value to format and insert. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator after reading. 
.RE
.PP

.PP
Definition at line 2192 of file locale_facets.h.
.SS "template<typename _CharT , typename _InIter > virtual \fBiter_type\fP \fBstd::num_get\fP< _CharT, _InIter >::do_get (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP & __io, \fBios_base::iostate\fP & __err, long long & __v) const\fC [inline, protected, virtual]\fP"
.PP
Numeric parsing. 
.PP
Parses the input stream into the variable \fIv\fP. This function is a hook for derived classes to change the value returned. 
.PP
\fBSee also:\fP
.RS 4
\fBget()\fP for more details.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIin\fP Start of input stream. 
.br
\fIend\fP End of input stream. 
.br
\fIio\fP Source of \fBlocale\fP and flags. 
.br
\fIerr\fP Error flags to \fBset\fP. 
.br
\fIv\fP Value to format and insert. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator after reading. 
.RE
.PP

.PP
Definition at line 2187 of file locale_facets.h.
.SS "template<typename _CharT , typename _InIter > virtual \fBiter_type\fP \fBstd::num_get\fP< _CharT, _InIter >::do_get (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP & __io, \fBios_base::iostate\fP & __err, unsigned long & __v) const\fC [inline, protected, virtual]\fP"
.PP
Numeric parsing. 
.PP
Parses the input stream into the variable \fIv\fP. This function is a hook for derived classes to change the value returned. 
.PP
\fBSee also:\fP
.RS 4
\fBget()\fP for more details.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIin\fP Start of input stream. 
.br
\fIend\fP End of input stream. 
.br
\fIio\fP Source of \fBlocale\fP and flags. 
.br
\fIerr\fP Error flags to \fBset\fP. 
.br
\fIv\fP Value to format and insert. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator after reading. 
.RE
.PP

.PP
Definition at line 2181 of file locale_facets.h.
.SS "template<typename _CharT , typename _InIter > virtual \fBiter_type\fP \fBstd::num_get\fP< _CharT, _InIter >::do_get (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP & __io, \fBios_base::iostate\fP & __err, unsigned int & __v) const\fC [inline, protected, virtual]\fP"
.PP
Numeric parsing. 
.PP
Parses the input stream into the variable \fIv\fP. This function is a hook for derived classes to change the value returned. 
.PP
\fBSee also:\fP
.RS 4
\fBget()\fP for more details.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIin\fP Start of input stream. 
.br
\fIend\fP End of input stream. 
.br
\fIio\fP Source of \fBlocale\fP and flags. 
.br
\fIerr\fP Error flags to \fBset\fP. 
.br
\fIv\fP Value to format and insert. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator after reading. 
.RE
.PP

.PP
Definition at line 2176 of file locale_facets.h.
.SS "template<typename _CharT , typename _InIter > virtual \fBiter_type\fP \fBstd::num_get\fP< _CharT, _InIter >::do_get (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP & __io, \fBios_base::iostate\fP & __err, unsigned short & __v) const\fC [inline, protected, virtual]\fP"
.PP
Numeric parsing. 
.PP
Parses the input stream into the variable \fIv\fP. This function is a hook for derived classes to change the value returned. 
.PP
\fBSee also:\fP
.RS 4
\fBget()\fP for more details.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIin\fP Start of input stream. 
.br
\fIend\fP End of input stream. 
.br
\fIio\fP Source of \fBlocale\fP and flags. 
.br
\fIerr\fP Error flags to \fBset\fP. 
.br
\fIv\fP Value to format and insert. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator after reading. 
.RE
.PP

.PP
Definition at line 2171 of file locale_facets.h.
.SS "template<typename _CharT , typename _InIter > virtual \fBiter_type\fP \fBstd::num_get\fP< _CharT, _InIter >::do_get (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP & __io, \fBios_base::iostate\fP & __err, long & __v) const\fC [inline, protected, virtual]\fP"
.PP
Numeric parsing. 
.PP
Parses the input stream into the variable \fIv\fP. This function is a hook for derived classes to change the value returned. 
.PP
\fBSee also:\fP
.RS 4
\fBget()\fP for more details.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIin\fP Start of input stream. 
.br
\fIend\fP End of input stream. 
.br
\fIio\fP Source of \fBlocale\fP and flags. 
.br
\fIerr\fP Error flags to \fBset\fP. 
.br
\fIv\fP Value to format and insert. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator after reading. 
.RE
.PP

.PP
Definition at line 2166 of file locale_facets.h.
.SS "template<typename _CharT , typename _InIter > _InIter \fBstd::num_get\fP< _CharT, _InIter >::do_get (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP & __io, \fBios_base::iostate\fP & __err, bool & __v) const\fC [inline, protected, virtual]\fP"
.PP
Numeric parsing. 
.PP
Parses the input stream into the variable \fIv\fP. This function is a hook for derived classes to change the value returned. 
.PP
\fBSee also:\fP
.RS 4
\fBget()\fP for more details.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIin\fP Start of input stream. 
.br
\fIend\fP End of input stream. 
.br
\fIio\fP Source of \fBlocale\fP and flags. 
.br
\fIerr\fP Error flags to \fBset\fP. 
.br
\fIv\fP Value to format and insert. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator after reading. 
.RE
.PP

.PP
Definition at line 574 of file locale_facets.tcc.
.PP
References std::ios_base::_M_getloc(), std::ios_base::boolalpha, std::ios_base::eofbit, std::ios_base::failbit, std::ios_base::flags(), and std::ios_base::goodbit.
.PP
Referenced by std::num_get< _CharT, _InIter >::get().
.SS "template<typename _CharT , typename _InIter > \fBiter_type\fP \fBstd::num_get\fP< _CharT, _InIter >::get (\fBiter_type\fP __in, \fBiter_type\fP __end, \fBios_base\fP & __io, \fBios_base::iostate\fP & __err, void *& __v) const\fC [inline]\fP"
.PP
Numeric parsing. 
.PP
Parses the input stream into the pointer variable \fIv\fP. It does so by calling \fBnum_get::do_get()\fP.
.PP
The input characters are parsed like the scanf p specifier.
.PP
Digit grouping is interpreted according to \fBnumpunct::grouping()\fP and \fBnumpunct::thousands_sep()\fP. If the pattern of digit groups isn't consistent, sets err to \fBios_base::failbit\fP.
.PP
Note that the digit grouping effect for pointers is a bit ambiguous in the standard and shouldn't be relied on. See DR 344.
.PP
If parsing the string yields a valid value for \fIv\fP, \fIv\fP is \fBset\fP. Otherwise, sets err to \fBios_base::failbit\fP and leaves \fIv\fP unaltered. Sets err to \fBios_base::eofbit\fP if the stream is emptied.
.PP
\fBParameters:\fP
.RS 4
\fIin\fP Start of input stream. 
.br
\fIend\fP End of input stream. 
.br
\fIio\fP Source of \fBlocale\fP and flags. 
.br
\fIerr\fP Error flags to \fBset\fP. 
.br
\fIv\fP Value to format and insert. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator after reading. 
.RE
.PP

.PP
Definition at line 2092 of file locale_facets.h.
.PP
References std::num_get< _CharT, _InIter >::do_get().
.SS "template<typename _CharT , typename _InIter > \fBiter_type\fP \fBstd::num_get\fP< _CharT, _InIter >::get (\fBiter_type\fP __in, \fBiter_type\fP __end, \fBios_base\fP & __io, \fBios_base::iostate\fP & __err, long double & __v) const\fC [inline]\fP"
.PP
Numeric parsing. 
.PP
Parses the input stream into the integral variable \fIv\fP. It does so by calling \fBnum_get::do_get()\fP.
.PP
The input characters are parsed like the scanf g specifier. The matching type length modifier is also used.
.PP
The decimal point character used is \fBnumpunct::decimal_point()\fP. Digit grouping is interpreted according to \fBnumpunct::grouping()\fP and \fBnumpunct::thousands_sep()\fP. If the pattern of digit groups isn't consistent, sets err to \fBios_base::failbit\fP.
.PP
If parsing the string yields a valid value for \fIv\fP, \fIv\fP is \fBset\fP. Otherwise, sets err to \fBios_base::failbit\fP and leaves \fIv\fP unaltered. Sets err to \fBios_base::eofbit\fP if the stream is emptied.
.PP
\fBParameters:\fP
.RS 4
\fIin\fP Start of input stream. 
.br
\fIend\fP End of input stream. 
.br
\fIio\fP Source of \fBlocale\fP and flags. 
.br
\fIerr\fP Error flags to \fBset\fP. 
.br
\fIv\fP Value to format and insert. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator after reading. 
.RE
.PP

.PP
Definition at line 2060 of file locale_facets.h.
.PP
References std::num_get< _CharT, _InIter >::do_get().
.SS "template<typename _CharT , typename _InIter > \fBiter_type\fP \fBstd::num_get\fP< _CharT, _InIter >::get (\fBiter_type\fP __in, \fBiter_type\fP __end, \fBios_base\fP & __io, \fBios_base::iostate\fP & __err, double & __v) const\fC [inline]\fP"
.PP
Numeric parsing. 
.PP
Parses the input stream into the integral variable \fIv\fP. It does so by calling \fBnum_get::do_get()\fP.
.PP
The input characters are parsed like the scanf g specifier. The matching type length modifier is also used.
.PP
The decimal point character used is \fBnumpunct::decimal_point()\fP. Digit grouping is interpreted according to \fBnumpunct::grouping()\fP and \fBnumpunct::thousands_sep()\fP. If the pattern of digit groups isn't consistent, sets err to \fBios_base::failbit\fP.
.PP
If parsing the string yields a valid value for \fIv\fP, \fIv\fP is \fBset\fP. Otherwise, sets err to \fBios_base::failbit\fP and leaves \fIv\fP unaltered. Sets err to \fBios_base::eofbit\fP if the stream is emptied.
.PP
\fBParameters:\fP
.RS 4
\fIin\fP Start of input stream. 
.br
\fIend\fP End of input stream. 
.br
\fIio\fP Source of \fBlocale\fP and flags. 
.br
\fIerr\fP Error flags to \fBset\fP. 
.br
\fIv\fP Value to format and insert. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator after reading. 
.RE
.PP

.PP
Definition at line 2055 of file locale_facets.h.
.PP
References std::num_get< _CharT, _InIter >::do_get().
.SS "template<typename _CharT , typename _InIter > \fBiter_type\fP \fBstd::num_get\fP< _CharT, _InIter >::get (\fBiter_type\fP __in, \fBiter_type\fP __end, \fBios_base\fP & __io, \fBios_base::iostate\fP & __err, float & __v) const\fC [inline]\fP"
.PP
Numeric parsing. 
.PP
Parses the input stream into the integral variable \fIv\fP. It does so by calling \fBnum_get::do_get()\fP.
.PP
The input characters are parsed like the scanf g specifier. The matching type length modifier is also used.
.PP
The decimal point character used is \fBnumpunct::decimal_point()\fP. Digit grouping is interpreted according to \fBnumpunct::grouping()\fP and \fBnumpunct::thousands_sep()\fP. If the pattern of digit groups isn't consistent, sets err to \fBios_base::failbit\fP.
.PP
If parsing the string yields a valid value for \fIv\fP, \fIv\fP is \fBset\fP. Otherwise, sets err to \fBios_base::failbit\fP and leaves \fIv\fP unaltered. Sets err to \fBios_base::eofbit\fP if the stream is emptied.
.PP
\fBParameters:\fP
.RS 4
\fIin\fP Start of input stream. 
.br
\fIend\fP End of input stream. 
.br
\fIio\fP Source of \fBlocale\fP and flags. 
.br
\fIerr\fP Error flags to \fBset\fP. 
.br
\fIv\fP Value to format and insert. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator after reading. 
.RE
.PP

.PP
Definition at line 2050 of file locale_facets.h.
.PP
References std::num_get< _CharT, _InIter >::do_get().
.SS "template<typename _CharT , typename _InIter > \fBiter_type\fP \fBstd::num_get\fP< _CharT, _InIter >::get (\fBiter_type\fP __in, \fBiter_type\fP __end, \fBios_base\fP & __io, \fBios_base::iostate\fP & __err, unsigned long long & __v) const\fC [inline]\fP"
.PP
Numeric parsing. 
.PP
Parses the input stream into the integral variable \fIv\fP. It does so by calling \fBnum_get::do_get()\fP.
.PP
Parsing is affected by the flag settings in \fIio\fP.
.PP
The basic parse is affected by the value of io.flags() & \fBios_base::basefield\fP. If equal to \fBios_base::oct\fP, parses like the scanf o specifier. Else if equal to \fBios_base::hex\fP, parses like X specifier. Else if basefield equal to 0, parses like the i specifier. Otherwise, parses like d for signed and u for unsigned types. The matching type length modifier is also used.
.PP
Digit grouping is interpreted according to \fBnumpunct::grouping()\fP and \fBnumpunct::thousands_sep()\fP. If the pattern of digit groups isn't consistent, sets err to \fBios_base::failbit\fP.
.PP
If parsing the string yields a valid value for \fIv\fP, \fIv\fP is \fBset\fP. Otherwise, sets err to \fBios_base::failbit\fP and leaves \fIv\fP unaltered. Sets err to \fBios_base::eofbit\fP if the stream is emptied.
.PP
\fBParameters:\fP
.RS 4
\fIin\fP Start of input stream. 
.br
\fIend\fP End of input stream. 
.br
\fIio\fP Source of \fBlocale\fP and flags. 
.br
\fIerr\fP Error flags to \fBset\fP. 
.br
\fIv\fP Value to format and insert. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator after reading. 
.RE
.PP

.PP
Definition at line 2017 of file locale_facets.h.
.PP
References std::num_get< _CharT, _InIter >::do_get().
.SS "template<typename _CharT , typename _InIter > \fBiter_type\fP \fBstd::num_get\fP< _CharT, _InIter >::get (\fBiter_type\fP __in, \fBiter_type\fP __end, \fBios_base\fP & __io, \fBios_base::iostate\fP & __err, long long & __v) const\fC [inline]\fP"
.PP
Numeric parsing. 
.PP
Parses the input stream into the integral variable \fIv\fP. It does so by calling \fBnum_get::do_get()\fP.
.PP
Parsing is affected by the flag settings in \fIio\fP.
.PP
The basic parse is affected by the value of io.flags() & \fBios_base::basefield\fP. If equal to \fBios_base::oct\fP, parses like the scanf o specifier. Else if equal to \fBios_base::hex\fP, parses like X specifier. Else if basefield equal to 0, parses like the i specifier. Otherwise, parses like d for signed and u for unsigned types. The matching type length modifier is also used.
.PP
Digit grouping is interpreted according to \fBnumpunct::grouping()\fP and \fBnumpunct::thousands_sep()\fP. If the pattern of digit groups isn't consistent, sets err to \fBios_base::failbit\fP.
.PP
If parsing the string yields a valid value for \fIv\fP, \fIv\fP is \fBset\fP. Otherwise, sets err to \fBios_base::failbit\fP and leaves \fIv\fP unaltered. Sets err to \fBios_base::eofbit\fP if the stream is emptied.
.PP
\fBParameters:\fP
.RS 4
\fIin\fP Start of input stream. 
.br
\fIend\fP End of input stream. 
.br
\fIio\fP Source of \fBlocale\fP and flags. 
.br
\fIerr\fP Error flags to \fBset\fP. 
.br
\fIv\fP Value to format and insert. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator after reading. 
.RE
.PP

.PP
Definition at line 2012 of file locale_facets.h.
.PP
References std::num_get< _CharT, _InIter >::do_get().
.SS "template<typename _CharT , typename _InIter > \fBiter_type\fP \fBstd::num_get\fP< _CharT, _InIter >::get (\fBiter_type\fP __in, \fBiter_type\fP __end, \fBios_base\fP & __io, \fBios_base::iostate\fP & __err, unsigned long & __v) const\fC [inline]\fP"
.PP
Numeric parsing. 
.PP
Parses the input stream into the integral variable \fIv\fP. It does so by calling \fBnum_get::do_get()\fP.
.PP
Parsing is affected by the flag settings in \fIio\fP.
.PP
The basic parse is affected by the value of io.flags() & \fBios_base::basefield\fP. If equal to \fBios_base::oct\fP, parses like the scanf o specifier. Else if equal to \fBios_base::hex\fP, parses like X specifier. Else if basefield equal to 0, parses like the i specifier. Otherwise, parses like d for signed and u for unsigned types. The matching type length modifier is also used.
.PP
Digit grouping is interpreted according to \fBnumpunct::grouping()\fP and \fBnumpunct::thousands_sep()\fP. If the pattern of digit groups isn't consistent, sets err to \fBios_base::failbit\fP.
.PP
If parsing the string yields a valid value for \fIv\fP, \fIv\fP is \fBset\fP. Otherwise, sets err to \fBios_base::failbit\fP and leaves \fIv\fP unaltered. Sets err to \fBios_base::eofbit\fP if the stream is emptied.
.PP
\fBParameters:\fP
.RS 4
\fIin\fP Start of input stream. 
.br
\fIend\fP End of input stream. 
.br
\fIio\fP Source of \fBlocale\fP and flags. 
.br
\fIerr\fP Error flags to \fBset\fP. 
.br
\fIv\fP Value to format and insert. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator after reading. 
.RE
.PP

.PP
Definition at line 2006 of file locale_facets.h.
.PP
References std::num_get< _CharT, _InIter >::do_get().
.SS "template<typename _CharT , typename _InIter > \fBiter_type\fP \fBstd::num_get\fP< _CharT, _InIter >::get (\fBiter_type\fP __in, \fBiter_type\fP __end, \fBios_base\fP & __io, \fBios_base::iostate\fP & __err, unsigned int & __v) const\fC [inline]\fP"
.PP
Numeric parsing. 
.PP
Parses the input stream into the integral variable \fIv\fP. It does so by calling \fBnum_get::do_get()\fP.
.PP
Parsing is affected by the flag settings in \fIio\fP.
.PP
The basic parse is affected by the value of io.flags() & \fBios_base::basefield\fP. If equal to \fBios_base::oct\fP, parses like the scanf o specifier. Else if equal to \fBios_base::hex\fP, parses like X specifier. Else if basefield equal to 0, parses like the i specifier. Otherwise, parses like d for signed and u for unsigned types. The matching type length modifier is also used.
.PP
Digit grouping is interpreted according to \fBnumpunct::grouping()\fP and \fBnumpunct::thousands_sep()\fP. If the pattern of digit groups isn't consistent, sets err to \fBios_base::failbit\fP.
.PP
If parsing the string yields a valid value for \fIv\fP, \fIv\fP is \fBset\fP. Otherwise, sets err to \fBios_base::failbit\fP and leaves \fIv\fP unaltered. Sets err to \fBios_base::eofbit\fP if the stream is emptied.
.PP
\fBParameters:\fP
.RS 4
\fIin\fP Start of input stream. 
.br
\fIend\fP End of input stream. 
.br
\fIio\fP Source of \fBlocale\fP and flags. 
.br
\fIerr\fP Error flags to \fBset\fP. 
.br
\fIv\fP Value to format and insert. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator after reading. 
.RE
.PP

.PP
Definition at line 2001 of file locale_facets.h.
.PP
References std::num_get< _CharT, _InIter >::do_get().
.SS "template<typename _CharT , typename _InIter > \fBiter_type\fP \fBstd::num_get\fP< _CharT, _InIter >::get (\fBiter_type\fP __in, \fBiter_type\fP __end, \fBios_base\fP & __io, \fBios_base::iostate\fP & __err, unsigned short & __v) const\fC [inline]\fP"
.PP
Numeric parsing. 
.PP
Parses the input stream into the integral variable \fIv\fP. It does so by calling \fBnum_get::do_get()\fP.
.PP
Parsing is affected by the flag settings in \fIio\fP.
.PP
The basic parse is affected by the value of io.flags() & \fBios_base::basefield\fP. If equal to \fBios_base::oct\fP, parses like the scanf o specifier. Else if equal to \fBios_base::hex\fP, parses like X specifier. Else if basefield equal to 0, parses like the i specifier. Otherwise, parses like d for signed and u for unsigned types. The matching type length modifier is also used.
.PP
Digit grouping is interpreted according to \fBnumpunct::grouping()\fP and \fBnumpunct::thousands_sep()\fP. If the pattern of digit groups isn't consistent, sets err to \fBios_base::failbit\fP.
.PP
If parsing the string yields a valid value for \fIv\fP, \fIv\fP is \fBset\fP. Otherwise, sets err to \fBios_base::failbit\fP and leaves \fIv\fP unaltered. Sets err to \fBios_base::eofbit\fP if the stream is emptied.
.PP
\fBParameters:\fP
.RS 4
\fIin\fP Start of input stream. 
.br
\fIend\fP End of input stream. 
.br
\fIio\fP Source of \fBlocale\fP and flags. 
.br
\fIerr\fP Error flags to \fBset\fP. 
.br
\fIv\fP Value to format and insert. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator after reading. 
.RE
.PP

.PP
Definition at line 1996 of file locale_facets.h.
.PP
References std::num_get< _CharT, _InIter >::do_get().
.SS "template<typename _CharT , typename _InIter > \fBiter_type\fP \fBstd::num_get\fP< _CharT, _InIter >::get (\fBiter_type\fP __in, \fBiter_type\fP __end, \fBios_base\fP & __io, \fBios_base::iostate\fP & __err, long & __v) const\fC [inline]\fP"
.PP
Numeric parsing. 
.PP
Parses the input stream into the integral variable \fIv\fP. It does so by calling \fBnum_get::do_get()\fP.
.PP
Parsing is affected by the flag settings in \fIio\fP.
.PP
The basic parse is affected by the value of io.flags() & \fBios_base::basefield\fP. If equal to \fBios_base::oct\fP, parses like the scanf o specifier. Else if equal to \fBios_base::hex\fP, parses like X specifier. Else if basefield equal to 0, parses like the i specifier. Otherwise, parses like d for signed and u for unsigned types. The matching type length modifier is also used.
.PP
Digit grouping is interpreted according to \fBnumpunct::grouping()\fP and \fBnumpunct::thousands_sep()\fP. If the pattern of digit groups isn't consistent, sets err to \fBios_base::failbit\fP.
.PP
If parsing the string yields a valid value for \fIv\fP, \fIv\fP is \fBset\fP. Otherwise, sets err to \fBios_base::failbit\fP and leaves \fIv\fP unaltered. Sets err to \fBios_base::eofbit\fP if the stream is emptied.
.PP
\fBParameters:\fP
.RS 4
\fIin\fP Start of input stream. 
.br
\fIend\fP End of input stream. 
.br
\fIio\fP Source of \fBlocale\fP and flags. 
.br
\fIerr\fP Error flags to \fBset\fP. 
.br
\fIv\fP Value to format and insert. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator after reading. 
.RE
.PP

.PP
Definition at line 1991 of file locale_facets.h.
.PP
References std::num_get< _CharT, _InIter >::do_get().
.SS "template<typename _CharT , typename _InIter > \fBiter_type\fP \fBstd::num_get\fP< _CharT, _InIter >::get (\fBiter_type\fP __in, \fBiter_type\fP __end, \fBios_base\fP & __io, \fBios_base::iostate\fP & __err, bool & __v) const\fC [inline]\fP"
.PP
Numeric parsing. 
.PP
Parses the input stream into the bool \fIv\fP. It does so by calling \fBnum_get::do_get()\fP.
.PP
If \fBios_base::boolalpha\fP is \fBset\fP, attempts to read ctype<CharT>::truename() or ctype<CharT>::falsename(). Sets \fIv\fP to true or false if successful. Sets err to \fBios_base::failbit\fP if reading the string fails. Sets err to \fBios_base::eofbit\fP if the stream is emptied.
.PP
If \fBios_base::boolalpha\fP is not \fBset\fP, proceeds as with reading a long, except if the value is 1, sets \fIv\fP to true, if the value is 0, sets \fIv\fP to false, and otherwise \fBset\fP err to \fBios_base::failbit\fP.
.PP
\fBParameters:\fP
.RS 4
\fIin\fP Start of input stream. 
.br
\fIend\fP End of input stream. 
.br
\fIio\fP Source of \fBlocale\fP and flags. 
.br
\fIerr\fP Error flags to \fBset\fP. 
.br
\fIv\fP Value to format and insert. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator after reading. 
.RE
.PP

.PP
Definition at line 1955 of file locale_facets.h.
.PP
References std::num_get< _CharT, _InIter >::do_get().
.SH "Member Data Documentation"
.PP 
.SS "template<typename _CharT , typename _InIter > \fBlocale::id\fP \fBstd::num_get\fP< _CharT, _InIter >::\fBid\fP\fC [inline, static]\fP"
.PP
Numpunct facet id. 
.PP
Definition at line 1919 of file locale_facets.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
