.TH "std::add_cv" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::add_cv \- \fBadd_cv\fP  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBadd_const\fP< typename \fBadd_volatile\fP< _Tp >::type >::type \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> struct std::add_cv< _Tp >"
\fBadd_cv\fP 
.PP
Definition at line 436 of file tr1_impl/type_traits.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
