.TH "std::rel_ops" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::rel_ops \- The generated relational operators are sequestered here.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<class _Tp > bool \fBoperator!=\fP (const _Tp &__x, const _Tp &__y)"
.br
.ti -1c
.RI "template<class _Tp > bool \fBoperator<=\fP (const _Tp &__x, const _Tp &__y)"
.br
.ti -1c
.RI "template<class _Tp > bool \fBoperator>\fP (const _Tp &__x, const _Tp &__y)"
.br
.ti -1c
.RI "template<class _Tp > bool \fBoperator>=\fP (const _Tp &__x, const _Tp &__y)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The generated relational operators are sequestered here. 
.PP
.SH "Function Documentation"
.PP 
.SS "template<class _Tp > bool std::rel_ops::operator!= (const _Tp & __x, const _Tp & __y)\fC [inline]\fP"
.PP
Defines \fC!=\fP for arbitrary types, in terms of \fC==\fP. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP A thing. 
.br
\fIy\fP Another thing. 
.RE
.PP
\fBReturns:\fP
.RS 4
x != y
.RE
.PP
This function uses \fC==\fP to determine its result. 
.PP
Definition at line 85 of file stl_relops.h.
.SS "template<class _Tp > bool std::rel_ops::operator<= (const _Tp & __x, const _Tp & __y)\fC [inline]\fP"
.PP
Defines \fC<=\fP for arbitrary types, in terms of \fC<\fP. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP A thing. 
.br
\fIy\fP Another thing. 
.RE
.PP
\fBReturns:\fP
.RS 4
x <= y
.RE
.PP
This function uses \fC<\fP to determine its result. 
.PP
Definition at line 111 of file stl_relops.h.
.SS "template<class _Tp > bool std::rel_ops::operator> (const _Tp & __x, const _Tp & __y)\fC [inline]\fP"
.PP
Defines \fC>\fP for arbitrary types, in terms of \fC<\fP. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP A thing. 
.br
\fIy\fP Another thing. 
.RE
.PP
\fBReturns:\fP
.RS 4
x > y
.RE
.PP
This function uses \fC<\fP to determine its result. 
.PP
Definition at line 98 of file stl_relops.h.
.SS "template<class _Tp > bool std::rel_ops::operator>= (const _Tp & __x, const _Tp & __y)\fC [inline]\fP"
.PP
Defines \fC>=\fP for arbitrary types, in terms of \fC<\fP. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP A thing. 
.br
\fIy\fP Another thing. 
.RE
.PP
\fBReturns:\fP
.RS 4
x >= y
.RE
.PP
This function uses \fC<\fP to determine its result. 
.PP
Definition at line 124 of file stl_relops.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
