std::variate_generator
NAME
std::variate_generator -
SYNOPSIS
Public Types
typedef __gnu_cxx::__enable_if< is_arithmetic< result_type >::value, result_type >::__type _IsValidType
typedef _Dist distribution_type
typedef _Engine engine_type
typedef __detail::_Adaptor< _Engine, _Dist > engine_value_type
typedef _Dist::result_type result_type
Public Member Functions
const distribution_type & distribution () const
distribution_type & distribution ()
const engine_value_type & engine () const
engine_value_type & engine ()
result_type max () const
result_type min () const
template<typename _Tp > result_type operator() (_Tp __value)
result_type operator() ()
variate_generator (engine_type __eng, distribution_type __dist)
Detailed Description
template<typename _Engine, typename _Dist> class std::variate_generator< _Engine, _Dist >
Produces random numbers on a given distribution function using a non-uniform random number generation engine.
Todo
the engine_value_type needs to be studied more carefully.
Definition at line 218 of file tr1_impl/random.
Constructor & Destructor Documentation
template<typename _Engine , typename _Dist > std::variate_generator< _Engine, _Dist >::variate_generator (engine_type __eng, distribution_type __dist) [inline]
Constructs a variate generator with the uniform random number generator __eng for the random distribution __dist.
Exceptions:
Any exceptions which may thrown by the copy constructors of the _Engine or _Dist objects.
Definition at line 242 of file tr1_impl/random.
Member Function Documentation
template<typename _Engine , typename _Dist > const distribution_type& std::variate_generator< _Engine, _Dist >::distribution () const [inline]
Gets a const reference to the underlying random distribution.
Definition at line 287 of file tr1_impl/random.
template<typename _Engine , typename _Dist > distribution_type& std::variate_generator< _Engine, _Dist >::distribution () [inline]
Gets a reference to the underlying random distribution.
Definition at line 280 of file tr1_impl/random.
Referenced by std::variate_generator< _Engine, _Dist >::max(), and std::variate_generator< _Engine, _Dist >::min().
template<typename _Engine , typename _Dist > const engine_value_type& std::variate_generator< _Engine, _Dist >::engine () const [inline]
Gets a const reference to the underlying uniform random number generator object.
Definition at line 273 of file tr1_impl/random.
template<typename _Engine , typename _Dist > engine_value_type& std::variate_generator< _Engine, _Dist >::engine () [inline]
Gets a reference to the underlying uniform random number generator object.
Definition at line 265 of file tr1_impl/random.
template<typename _Engine , typename _Dist > result_type std::variate_generator< _Engine, _Dist >::max () const [inline]
Gets the closed upper bound of the distribution interval.
Definition at line 301 of file tr1_impl/random.
References std::variate_generator< _Engine, _Dist >::distribution().
template<typename _Engine , typename _Dist > result_type std::variate_generator< _Engine, _Dist >::min () const [inline]
Gets the closed lower bound of the distribution interval.
Definition at line 294 of file tr1_impl/random.
References std::variate_generator< _Engine, _Dist >::distribution().
template<typename _Engine , typename _Dist > template<typename _Tp > result_type std::variate_generator< _Engine, _Dist >::operator() (_Tp __value) [inline]
WTF?
Definition at line 257 of file tr1_impl/random.
template<typename _Engine , typename _Dist > result_type std::variate_generator< _Engine, _Dist >::operator() () [inline]
Gets the next generated value on the distribution.
Definition at line 249 of file tr1_impl/random.
Author
Generated automatically by Doxygen for libstdc++ from the source code.