.TH "std::initializer_list" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::initializer_list \- \fBinitializer_list\fP  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const _E * \fBbegin\fP () const "
.br
.ti -1c
.RI "const _E * \fBend\fP () const "
.br
.ti -1c
.RI "size_t \fBsize\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class _E> class std::initializer_list< _E >"
\fBinitializer_list\fP 
.PP
Definition at line 43 of file initializer_list.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
