.TH "std::ratio" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::ratio \- Provides compile-time rational arithmetic.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic_assert\fP (_Num >=-__INTMAX_MAX__ &&_Den >=-__INTMAX_MAX__,'out of range')"
.br
.ti -1c
.RI "\fBstatic_assert\fP (_Den!=0,'denominator cannot be zero')"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const intmax_t \fBden\fP"
.br
.ti -1c
.RI "static const intmax_t \fBnum\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<intmax_t _Num, intmax_t _Den = 1> struct std::ratio< _Num, _Den >"
Provides compile-time rational arithmetic. 

This class template represents any finite rational number with a numerator and denominator representable by compile-time constants of type intmax_t. The \fBratio\fP is simplified when instantiated.
.PP
For example: 
.PP
.nf
    std::ratio<7,-21>::num == -1;
    std::ratio<7,-21>::den == 3;

.fi
.PP
 
.PP
Definition at line 151 of file ratio.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
