.TH "std::default_delete" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::default_delete \- Primary template, \fBdefault_delete\fP.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename _Up > \fBdefault_delete\fP (const \fBdefault_delete\fP< _Up > &)"
.br
.ti -1c
.RI "void \fBoperator()\fP (_Tp *__ptr) const "
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> struct std::default_delete< _Tp >"
Primary template, \fBdefault_delete\fP. 
.PP
Definition at line 52 of file unique_ptr.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
