.TH "std::poisson_distribution" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::poisson_distribution \- A discrete Poisson random number distribution.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _RealType \fBinput_type\fP"
.br
.ti -1c
.RI "typedef _IntType \fBresult_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "_RealType \fBmean\fP () const "
.br
.ti -1c
.RI "template<class _UniformRandomNumberGenerator > result_type \fBoperator()\fP (_UniformRandomNumberGenerator &__urng)"
.br
.ti -1c
.RI "\fBpoisson_distribution\fP (const _RealType &__mean=_RealType(1))"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "template<typename _IntType1 , typename _RealType1 , typename _CharT , typename _Traits > \fBstd::basic_ostream\fP< _CharT, _Traits > & \fBoperator<<\fP (\fBstd::basic_ostream\fP< _CharT, _Traits > &__os, const \fBpoisson_distribution\fP< _IntType1, _RealType1 > &__x)"
.br
.ti -1c
.RI "template<typename _IntType1 , typename _RealType1 , typename _CharT , typename _Traits > \fBstd::basic_istream\fP< _CharT, _Traits > & \fBoperator>>\fP (\fBstd::basic_istream\fP< _CharT, _Traits > &__is, \fBpoisson_distribution\fP< _IntType1, _RealType1 > &__x)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _IntType = int, typename _RealType = double> class std::poisson_distribution< _IntType, _RealType >"
A discrete Poisson random number distribution. 

The formula for the Poisson probability mass function is $ p(i) = \frac{mean^i}{i!} e^{-mean} $ where $ mean $ is the parameter of the distribution. 
.PP
Definition at line 1864 of file tr1_impl/random.
.SH "Member Function Documentation"
.PP 
.SS "template<typename _IntType = int, typename _RealType  = double> _RealType \fBstd::poisson_distribution\fP< _IntType, _RealType >::mean () const\fC [inline]\fP"
.PP
Gets the distribution parameter \fCmean\fP. 
.PP
Definition at line 1884 of file tr1_impl/random.
.SS "template<typename _IntType , typename _RealType > template<class _UniformRandomNumberGenerator > \fBpoisson_distribution\fP< _IntType, _RealType >::result_type \fBstd::poisson_distribution\fP< _IntType, _RealType >::operator() (_UniformRandomNumberGenerator & __urng)\fC [inline]\fP"
.PP
A rejection algorithm when mean >= 12 and a simple method based upon the multiplication of uniform random variates otherwise. NB: The former is available only if _GLIBCXX_USE_C99_MATH_TR1 is defined.
.PP
Reference: Devroye, L. 'Non-Uniform Random Variates Generation.' Springer-Verlag, New York, 1986, Ch. X, Sects. 3.3 & 3.4 (+ Errata!). 
.PP
Definition at line 936 of file random.tcc.
.PP
References std::abs(), std::log(), and std::max().
.SH "Friends And Related Function Documentation"
.PP 
.SS "template<typename _IntType = int, typename _RealType  = double> template<typename _IntType1 , typename _RealType1 , typename _CharT , typename _Traits > \fBstd::basic_ostream\fP<_CharT, _Traits>& operator<< (\fBstd::basic_ostream\fP< _CharT, _Traits > & __os, const \fBpoisson_distribution\fP< _IntType1, _RealType1 > & __x)\fC [friend]\fP"
.PP
Inserts a poisson_distribution random number distribution \fC__x\fP into the output stream \fC__os\fP.
.PP
\fBParameters:\fP
.RS 4
\fI__os\fP An output stream. 
.br
\fI__x\fP A poisson_distribution random number distribution.
.RE
.PP
\fBReturns:\fP
.RS 4
The output stream with the state of \fC__x\fP inserted or in an error state. 
.RE
.PP

.SS "template<typename _IntType = int, typename _RealType  = double> template<typename _IntType1 , typename _RealType1 , typename _CharT , typename _Traits > \fBstd::basic_istream\fP<_CharT, _Traits>& operator>> (\fBstd::basic_istream\fP< _CharT, _Traits > & __is, \fBpoisson_distribution\fP< _IntType1, _RealType1 > & __x)\fC [friend]\fP"
.PP
Extracts a poisson_distribution random number distribution \fC__x\fP from the input stream \fC__is\fP.
.PP
\fBParameters:\fP
.RS 4
\fI__is\fP An input stream. 
.br
\fI__x\fP A poisson_distribution random number generator engine.
.RE
.PP
\fBReturns:\fP
.RS 4
The input stream with \fC__x\fP extracted or in an error state. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
