.TH "std::gslice" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::gslice \- Class defining multi-dimensional subset of an \fBarray\fP.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgslice\fP (const \fBgslice\fP &)"
.br
.ti -1c
.RI "\fBgslice\fP (size_t, const \fBvalarray\fP< size_t > &, const \fBvalarray\fP< size_t > &)"
.br
.ti -1c
.RI "\fBgslice\fP ()"
.br
.ti -1c
.RI "\fBgslice\fP & \fBoperator=\fP (const \fBgslice\fP &)"
.br
.ti -1c
.RI "\fBvalarray\fP< size_t > \fBsize\fP () const "
.br
.ti -1c
.RI "size_t \fBstart\fP () const "
.br
.ti -1c
.RI "\fBvalarray\fP< size_t > \fBstride\fP () const "
.br
.ti -1c
.RI "\fB~gslice\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBvalarray\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class defining multi-dimensional subset of an \fBarray\fP. 

The \fBslice\fP class represents a multi-dimensional subset of an \fBarray\fP, specified by three parameter sets: start offset, size \fBarray\fP, and stride \fBarray\fP. The start offset is the index of the first element of the \fBarray\fP that is part of the subset. The size and stride \fBarray\fP describe each dimension of the \fBslice\fP. Size is the number of elements in that dimension, and stride is the distance in the \fBarray\fP between successive elements in that dimension. Each dimension's size and stride is taken to begin at an \fBarray\fP element described by the previous dimension. The size \fBarray\fP and stride \fBarray\fP must be the same size.
.PP
For example, if you have offset==3, stride[0]==11, size[1]==3, stride[1]==3, then \fBslice\fP[0,0]==array[3], \fBslice\fP[0,1]==array[6], \fBslice\fP[0,2]==array[9], \fBslice\fP[1,0]==array[14], \fBslice\fP[1,1]==array[17], \fBslice\fP[1,2]==array[20]. 
.PP
Definition at line 63 of file gslice.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
