.TH "std::lock_error" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::lock_error \- Thrown to indicate errors with lock operations.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fBstd::exception\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual const char * \fBwhat\fP () const   throw ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Thrown to indicate errors with lock operations. 
.PP
Definition at line 394 of file mutex.
.SH "Member Function Documentation"
.PP 
.SS "virtual const char* std::lock_error::what () const  throw ()\fC [virtual]\fP"
.PP
Returns a C-style character string describing the general cause of the current error. 
.PP
Reimplemented from \fBstd::exception\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
