.TH "std::random_access_iterator_tag" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::random_access_iterator_tag \- Random-access iterators support a superset of bidirectional \fBiterator\fP operations.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fBstd::bidirectional_iterator_tag\fP.
.PP
.SH "Detailed Description"
.PP 
Random-access iterators support a superset of bidirectional \fBiterator\fP operations. 
.PP
Definition at line 89 of file stl_iterator_base_types.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
