.TH "std::istreambuf_iterator" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::istreambuf_iterator \- Provides input \fBiterator\fP semantics for streambufs.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fBiterator< input_iterator_tag, _CharT, _Traits::off_type, _CharT *, _CharT & >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _Traits::off_type \fBdifference_type\fP"
.br
.ti -1c
.RI "typedef \fBinput_iterator_tag\fP \fBiterator_category\fP"
.br
.ti -1c
.RI "typedef _CharT * \fBpointer\fP"
.br
.ti -1c
.RI "typedef _CharT & \fBreference\fP"
.br
.ti -1c
.RI "typedef _CharT \fBvalue_type\fP"
.br
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "typedef _CharT \fBchar_type\fP"
.br
.ti -1c
.RI "typedef _Traits::int_type \fBint_type\fP"
.br
.ti -1c
.RI "typedef \fBbasic_istream\fP< _CharT, _Traits > \fBistream_type\fP"
.br
.ti -1c
.RI "typedef \fBbasic_streambuf\fP< _CharT, _Traits > \fBstreambuf_type\fP"
.br
.ti -1c
.RI "typedef _Traits \fBtraits_type\fP"
.br
.in -1c
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBequal\fP (const \fBistreambuf_iterator\fP &__b) const "
.br
.ti -1c
.RI "\fBistreambuf_iterator\fP (\fBstreambuf_type\fP *__s)  throw ()"
.br
.ti -1c
.RI "\fBistreambuf_iterator\fP (\fBistream_type\fP &__s)  throw ()"
.br
.ti -1c
.RI "\fBistreambuf_iterator\fP ()  throw ()"
.br
.ti -1c
.RI "\fBchar_type\fP \fBoperator*\fP () const "
.br
.ti -1c
.RI "\fBistreambuf_iterator\fP \fBoperator++\fP (int)"
.br
.ti -1c
.RI "\fBistreambuf_iterator\fP & \fBoperator++\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "template<bool _IsMove, typename _CharT2 > __gnu_cxx::__enable_if< __is_char< _CharT2 >::__value, _CharT2 * >::__type \fB__copy_move_a2\fP (\fBistreambuf_iterator\fP< _CharT2 >, \fBistreambuf_iterator\fP< _CharT2 >, _CharT2 *)"
.br
.ti -1c
.RI "template<typename _CharT2 > __gnu_cxx::__enable_if< __is_char< _CharT2 >::__value, \fBostreambuf_iterator\fP< _CharT2 > >::__type \fBcopy\fP (\fBistreambuf_iterator\fP< _CharT2 >, \fBistreambuf_iterator\fP< _CharT2 >, \fBostreambuf_iterator\fP< _CharT2 >)"
.br
.ti -1c
.RI "template<typename _CharT2 > __gnu_cxx::__enable_if< __is_char< _CharT2 >::__value, \fBistreambuf_iterator\fP< _CharT2 > >::__type \fBfind\fP (\fBistreambuf_iterator\fP< _CharT2 >, \fBistreambuf_iterator\fP< _CharT2 >, const _CharT2 &)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _CharT, typename _Traits> class std::istreambuf_iterator< _CharT, _Traits >"
Provides input \fBiterator\fP semantics for streambufs. 
.PP
Definition at line 45 of file streambuf_iterator.h.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename _CharT , typename _Traits > typedef _CharT \fBstd::istreambuf_iterator\fP< _CharT, _Traits >::\fBchar_type\fP"
.PP
Public typedefs. 
.PP
Definition at line 53 of file streambuf_iterator.h.
.SS "typedef _Traits::off_type  \fBstd::iterator\fP< \fBinput_iterator_tag\fP , _CharT , _Traits::off_type , _CharT * , _CharT &  >::\fBdifference_type\fP\fC [inherited]\fP"
.PP
Distance between iterators is represented as this type. 
.PP
Definition at line 111 of file stl_iterator_base_types.h.
.SS "template<typename _CharT , typename _Traits > typedef _Traits::int_type \fBstd::istreambuf_iterator\fP< _CharT, _Traits >::\fBint_type\fP"
.PP
Public typedefs. 
.PP
Definition at line 55 of file streambuf_iterator.h.
.SS "template<typename _CharT , typename _Traits > typedef \fBbasic_istream\fP<_CharT, _Traits> \fBstd::istreambuf_iterator\fP< _CharT, _Traits >::\fBistream_type\fP"
.PP
Public typedefs. 
.PP
Definition at line 57 of file streambuf_iterator.h.
.SS "typedef \fBinput_iterator_tag\fP  \fBstd::iterator\fP< \fBinput_iterator_tag\fP , _CharT , _Traits::off_type , _CharT * , _CharT &  >::\fBiterator_category\fP\fC [inherited]\fP"
.PP
One of the \fBtag types\fP. 
.PP
Definition at line 107 of file stl_iterator_base_types.h.
.SS "typedef _CharT *  \fBstd::iterator\fP< \fBinput_iterator_tag\fP , _CharT , _Traits::off_type , _CharT * , _CharT &  >::\fBpointer\fP\fC [inherited]\fP"
.PP
This type represents a pointer-to-value_type. 
.PP
Definition at line 113 of file stl_iterator_base_types.h.
.SS "typedef _CharT &  \fBstd::iterator\fP< \fBinput_iterator_tag\fP , _CharT , _Traits::off_type , _CharT * , _CharT &  >::\fBreference\fP\fC [inherited]\fP"
.PP
This type represents a reference-to-value_type. 
.PP
Definition at line 115 of file stl_iterator_base_types.h.
.SS "template<typename _CharT , typename _Traits > typedef \fBbasic_streambuf\fP<_CharT, _Traits> \fBstd::istreambuf_iterator\fP< _CharT, _Traits >::\fBstreambuf_type\fP"
.PP
Public typedefs. 
.PP
Definition at line 56 of file streambuf_iterator.h.
.SS "template<typename _CharT , typename _Traits > typedef _Traits \fBstd::istreambuf_iterator\fP< _CharT, _Traits >::\fBtraits_type\fP"
.PP
Public typedefs. 
.PP
Definition at line 54 of file streambuf_iterator.h.
.SS "typedef _CharT  \fBstd::iterator\fP< \fBinput_iterator_tag\fP , _CharT , _Traits::off_type , _CharT * , _CharT &  >::\fBvalue_type\fP\fC [inherited]\fP"
.PP
The type 'pointed to' by the iterator. 
.PP
Definition at line 109 of file stl_iterator_base_types.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename _CharT , typename _Traits > \fBstd::istreambuf_iterator\fP< _CharT, _Traits >::\fBistreambuf_iterator\fP ()  throw ()\fC [inline]\fP"
.PP
Construct end of input stream \fBiterator\fP. 
.PP
Definition at line 91 of file streambuf_iterator.h.
.SS "template<typename _CharT , typename _Traits > \fBstd::istreambuf_iterator\fP< _CharT, _Traits >::\fBistreambuf_iterator\fP (\fBistream_type\fP & __s)  throw ()\fC [inline]\fP"
.PP
Construct start of input stream \fBiterator\fP. 
.PP
Definition at line 95 of file streambuf_iterator.h.
.SS "template<typename _CharT , typename _Traits > \fBstd::istreambuf_iterator\fP< _CharT, _Traits >::\fBistreambuf_iterator\fP (\fBstreambuf_type\fP * __s)  throw ()\fC [inline]\fP"
.PP
Construct start of streambuf \fBiterator\fP. 
.PP
Definition at line 99 of file streambuf_iterator.h.
.SH "Member Function Documentation"
.PP 
.SS "template<typename _CharT , typename _Traits > bool \fBstd::istreambuf_iterator\fP< _CharT, _Traits >::equal (const \fBistreambuf_iterator\fP< _CharT, _Traits > & __b) const\fC [inline]\fP"
.PP
Return true both iterators are end or both are not end. 
.PP
Definition at line 155 of file streambuf_iterator.h.
.PP
References std::istreambuf_iterator< _CharT, _Traits >::_M_at_eof().
.SS "template<typename _CharT , typename _Traits > \fBchar_type\fP \fBstd::istreambuf_iterator\fP< _CharT, _Traits >::operator* () const\fC [inline]\fP"
.PP
Return the current character pointed to by \fBiterator\fP. This returns \fBstreambuf.sgetc()\fP. It cannot be assigned. NB: The result of \fBoperator*()\fP on an end of stream is undefined. 
.PP
Definition at line 106 of file streambuf_iterator.h.
.PP
References std::operator*().
.SS "template<typename _CharT , typename _Traits > \fBistreambuf_iterator\fP \fBstd::istreambuf_iterator\fP< _CharT, _Traits >::operator++ (int)\fC [inline]\fP"
.PP
Advance the \fBiterator\fP. Calls \fBstreambuf.sbumpc()\fP. 
.PP
Definition at line 135 of file streambuf_iterator.h.
.PP
References std::istreambuf_iterator< _CharT, _Traits >::_M_c, and std::basic_streambuf< _CharT, _Traits >::sbumpc().
.SS "template<typename _CharT , typename _Traits > \fBistreambuf_iterator\fP& \fBstd::istreambuf_iterator\fP< _CharT, _Traits >::operator++ ()\fC [inline]\fP"
.PP
Advance the \fBiterator\fP. Calls \fBstreambuf.sbumpc()\fP. 
.PP
Definition at line 120 of file streambuf_iterator.h.
.PP
References std::basic_streambuf< _CharT, _Traits >::sbumpc().

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
