.TH "std::chrono::duration" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::chrono::duration \- \fBduration\fP  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _Period \fBperiod\fP"
.br
.ti -1c
.RI "typedef _Rep \fBrep\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "rep \fBcount\fP () const "
.br
.ti -1c
.RI "\fBduration\fP (const \fBduration\fP &)"
.br
.ti -1c
.RI "template<typename _Rep2 , typename _Period2 > \fBduration\fP (const \fBduration\fP< _Rep2, _Period2 > &__d)"
.br
.ti -1c
.RI "template<typename _Rep2 > \fBduration\fP (_Rep2 const &__rep)"
.br
.ti -1c
.RI "\fBduration\fP & \fBoperator*=\fP (const rep &__rhs)"
.br
.ti -1c
.RI "\fBduration\fP \fBoperator+\fP () const "
.br
.ti -1c
.RI "\fBduration\fP \fBoperator++\fP (int)"
.br
.ti -1c
.RI "\fBduration\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBduration\fP & \fBoperator+=\fP (const \fBduration\fP &__d)"
.br
.ti -1c
.RI "\fBduration\fP \fBoperator-\fP () const "
.br
.ti -1c
.RI "\fBduration\fP \fBoperator--\fP (int)"
.br
.ti -1c
.RI "\fBduration\fP & \fBoperator--\fP ()"
.br
.ti -1c
.RI "\fBduration\fP & \fBoperator-=\fP (const \fBduration\fP &__d)"
.br
.ti -1c
.RI "\fBduration\fP & \fBoperator/=\fP (const rep &__rhs)"
.br
.ti -1c
.RI "\fBduration\fP & \fBoperator=\fP (const \fBduration\fP &)"
.br
.ti -1c
.RI "\fBstatic_assert\fP (_Period::num > 0,'period must be positive')"
.br
.ti -1c
.RI "\fBstatic_assert\fP (__is_ratio< _Period >::value,'period must be a specialization of \fBratio\fP')"
.br
.ti -1c
.RI "\fBstatic_assert\fP (!__is_duration< _Rep >::value,'rep cannot be a \fBduration\fP')"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const \fBduration\fP \fBmax\fP ()"
.br
.ti -1c
.RI "static const \fBduration\fP \fBmin\fP ()"
.br
.ti -1c
.RI "static const \fBduration\fP \fBzero\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Rep, typename _Period> struct std::chrono::duration< _Rep, _Period >"
\fBduration\fP 
.PP
Definition at line 200 of file chrono.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
