.TH "std::_Reference_wrapper_base" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::_Reference_wrapper_base \- 
.SH SYNOPSIS
.br
.PP
Inherits _Reference_wrapper_base_impl< _Derives_from_unary_function<_Tp>::value, _Derives_from_binary_function<_Tp>::value, _Tp>.
.PP
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> struct std::_Reference_wrapper_base< _Tp >"
Derives from \fBunary_function\fP or \fBbinary_function\fP when it can. Specializations handle all of the easy cases. The primary template determines what to do with a class type, which may derive from both \fBunary_function\fP and \fBbinary_function\fP. 
.PP
Definition at line 345 of file tr1_impl/functional.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
