.TH "std::iterator_traits" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::iterator_traits \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _Iterator::difference_type \fBdifference_type\fP"
.br
.ti -1c
.RI "typedef _Iterator::iterator_category \fBiterator_category\fP"
.br
.ti -1c
.RI "typedef _Iterator::pointer \fBpointer\fP"
.br
.ti -1c
.RI "typedef _Iterator::reference \fBreference\fP"
.br
.ti -1c
.RI "typedef _Iterator::value_type \fBvalue_type\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Iterator> struct std::iterator_traits< _Iterator >"
This class does nothing but define nested typedefs. The general version simply 'forwards' the nested typedefs from the Iterator argument. Specialized versions for pointers and pointers-to-const provide tighter, more correct semantics. 
.PP
Definition at line 125 of file stl_iterator_base_types.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
