.TH "std::__parallel::c_rand_number" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::__parallel::c_rand_number \- Functor wrapper for std::rand().  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBoperator()\fP (int limit)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename must_be_int = int> struct std::__parallel::c_rand_number< must_be_int >"
Functor wrapper for std::rand(). 
.PP
Definition at line 1632 of file algo.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
