.TH "std::_Maybe_wrap_member_pointer" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::_Maybe_wrap_member_pointer \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _Tp \fBtype\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const _Tp & \fB__do_wrap\fP (const _Tp &__x)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> struct std::_Maybe_wrap_member_pointer< _Tp >"
Maps member pointers into instances of _Mem_fn but leaves all other function objects untouched. Used by \fBtr1::bind()\fP. The primary template handles the non--member-pointer case. 
.PP
Definition at line 1089 of file tr1_impl/functional.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
