.TH "std::atomic" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::atomic \- \fBatomic\fP 29.4.3, Generic \fBatomic\fP type, primary class template.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBatomic\fP (_Tp __i)"
.br
.ti -1c
.RI "\fBatomic\fP (const \fBatomic\fP &)"
.br
.ti -1c
.RI "bool \fBcompare_exchange_strong\fP (_Tp &, _Tp, \fBmemory_order\fP=memory_order_seq_cst) volatile"
.br
.ti -1c
.RI "bool \fBcompare_exchange_strong\fP (_Tp &, _Tp, \fBmemory_order\fP, \fBmemory_order\fP) volatile"
.br
.ti -1c
.RI "bool \fBcompare_exchange_weak\fP (_Tp &, _Tp, \fBmemory_order\fP=memory_order_seq_cst) volatile"
.br
.ti -1c
.RI "bool \fBcompare_exchange_weak\fP (_Tp &, _Tp, \fBmemory_order\fP, \fBmemory_order\fP) volatile"
.br
.ti -1c
.RI "_Tp \fBexchange\fP (_Tp __i, \fBmemory_order\fP=memory_order_seq_cst) volatile"
.br
.ti -1c
.RI "bool \fBis_lock_free\fP () const volatile"
.br
.ti -1c
.RI "_Tp \fBload\fP (\fBmemory_order\fP=memory_order_seq_cst) const volatile"
.br
.ti -1c
.RI "\fBoperator _Tp\fP () const volatile"
.br
.ti -1c
.RI "_Tp \fBoperator=\fP (_Tp __i) volatile"
.br
.ti -1c
.RI "\fBatomic\fP & \fBoperator=\fP (const \fBatomic\fP &)"
.br
.ti -1c
.RI "void \fBstore\fP (_Tp, \fBmemory_order\fP=memory_order_seq_cst) volatile"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> struct std::atomic< _Tp >"
\fBatomic\fP 29.4.3, Generic \fBatomic\fP type, primary class template. 
.PP
Definition at line 93 of file cstdatomic.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
