.TH "std::system_error" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::system_error \- Thrown to indicate error code of underlying system.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fBstd::runtime_error\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const \fBerror_code\fP & \fBcode\fP () const   throw ()"
.br
.ti -1c
.RI "\fBsystem_error\fP (int __v, const \fBerror_category\fP &__ecat, const \fBstring\fP &__what)"
.br
.ti -1c
.RI "\fBsystem_error\fP (int __v, const \fBerror_category\fP &__ecat)"
.br
.ti -1c
.RI "\fBsystem_error\fP (\fBerror_code\fP __ec, const \fBstring\fP &__what)"
.br
.ti -1c
.RI "\fBsystem_error\fP (\fBerror_code\fP __ec=\fBerror_code\fP())"
.br
.ti -1c
.RI "virtual const char * \fBwhat\fP () const   throw ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Thrown to indicate error code of underlying system. 
.PP
Definition at line 321 of file system_error.
.SH "Member Function Documentation"
.PP 
.SS "virtual const char* std::runtime_error::what () const  throw ()\fC [virtual, inherited]\fP"
.PP
Returns a C-style character string describing the general cause of the current error (the same string passed to the ctor). 
.PP
Reimplemented from \fBstd::exception\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
