.TH "std::this_thread" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::this_thread \- ISO C++ 0x entities sub namespace for \fBthread\fP. 30.2.2 Namespace \fBthis_thread\fP.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBthread::id\fP \fBget_id\fP ()"
.br
.ti -1c
.RI "template<typename _Rep , typename _Period > void \fBsleep_for\fP (const \fBchrono::duration\fP< _Rep, _Period > &__rtime)"
.br
.ti -1c
.RI "template<typename _Clock , typename _Duration > void \fBsleep_until\fP (const chrono::time_point< _Clock, _Duration > &__atime)"
.br
.ti -1c
.RI "void \fByield\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
ISO C++ 0x entities sub namespace for \fBthread\fP. 30.2.2 Namespace \fBthis_thread\fP. 
.PP
.SH "Function Documentation"
.PP 
.SS "\fBthread::id\fP std::this_thread::get_id ()\fC [inline]\fP"
.PP
get_id 
.PP
Definition at line 239 of file thread.
.SS "template<typename _Rep , typename _Period > void std::this_thread::sleep_for (const chrono::duration< _Rep, _Period > & __rtime)\fC [inline]\fP"
.PP
sleep_for 
.PP
Definition at line 258 of file thread.
.PP
References std::chrono::duration_cast().
.PP
Referenced by sleep_until().
.SS "template<typename _Clock , typename _Duration > void std::this_thread::sleep_until (const chrono::time_point< _Clock, _Duration > & __atime)\fC [inline]\fP"
.PP
sleep_until 
.PP
Definition at line 252 of file thread.
.PP
References sleep_for().
.SS "void std::this_thread::yield ()\fC [inline]\fP"
.PP
yield 
.PP
Definition at line 244 of file thread.
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
