.TH "std::auto_ptr_ref" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::auto_ptr_ref \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBauto_ptr_ref\fP (_Tp1 *__p)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "_Tp1 * \fB_M_ptr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp1> struct std::auto_ptr_ref< _Tp1 >"
A wrapper class to provide \fBauto_ptr\fP with reference semantics. For example, an \fBauto_ptr\fP can be assigned (or constructed from) the result of a function which returns an \fBauto_ptr\fP by value.
.PP
All the \fBauto_ptr_ref\fP stuff should happen behind the scenes. 
.PP
Definition at line 46 of file auto_ptr.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
