.TH "std::bidirectional_iterator_tag" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::bidirectional_iterator_tag \- Bidirectional iterators support a superset of forward \fBiterator\fP operations.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fBstd::forward_iterator_tag\fP.
.PP
Inherited by \fBstd::random_access_iterator_tag\fP.
.PP
.SH "Detailed Description"
.PP 
Bidirectional iterators support a superset of forward \fBiterator\fP operations. 
.PP
Definition at line 86 of file stl_iterator_base_types.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
