.TH "std::is_lvalue_reference" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::is_lvalue_reference \- \fBis_lvalue_reference\fP  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fBintegral_constant< bool, false >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBintegral_constant\fP< bool, __v > \fBtype\fP"
.br
.ti -1c
.RI "typedef bool \fBvalue_type\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename> struct std::is_lvalue_reference< typename >"
\fBis_lvalue_reference\fP 
.PP
Definition at line 68 of file type_traits.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
