.TH "std::time_base" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::time_base \- Time format ordering data.  

.PP
.SH SYNOPSIS
.br
.PP
Inherited by \fBstd::time_get< _CharT, _InIter >\fP, and \fBstd::time_get< _CharT, _InIter >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBdateorder\fP { \fBno_order\fP, \fBdmy\fP, \fBmdy\fP, \fBymd\fP, \fBydm\fP }"
.br
.SH "Detailed Description"
.PP 
Time format ordering data. 

This class provides an enum representing different orderings of day, month, and year. 
.PP
Definition at line 49 of file locale_facets_nonio.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
