.TH "std::money_base" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::money_base \- Money format ordering data.  

.PP
.SH SYNOPSIS
.br
.PP
Inherited by \fBstd::moneypunct< _CharT, _Intl >\fP, and \fBstd::moneypunct< _CharT, _Intl >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fB_S_minus\fP, \fB_S_zero\fP, \fB_S_end\fP }"
.br
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static pattern \fB_S_construct_pattern\fP (char __precedes, char __space, char __posn)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const char * \fB_S_atoms\fP"
.br
.ti -1c
.RI "static const pattern \fB_S_default_pattern\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Money format ordering data. 

This class contains an ordered \fBarray\fP of 4 fields to represent the pattern for formatting a money amount. Each field may contain one entry from the part enum. symbol, sign, and value must be present and the remaining field must contain either none or space. 
.PP
\fBSee also:\fP
.RS 4
\fBmoneypunct::pos_format()\fP and \fBmoneypunct::neg_format()\fP for details of how these fields are interpreted. 
.RE
.PP

.PP
Definition at line 826 of file locale_facets_nonio.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
