.TH "std::random_device" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::random_device \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef unsigned int \fBresult_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBentropy\fP () const "
.br
.ti -1c
.RI "result_type \fBmax\fP () const "
.br
.ti -1c
.RI "result_type \fBmin\fP () const "
.br
.ti -1c
.RI "result_type \fBoperator()\fP ()"
.br
.ti -1c
.RI "\fBrandom_device\fP (const \fBstd::string\fP &__token='mt19937')"
.br
.in -1c
.SH "Detailed Description"
.PP 
A standard interface to a platform-specific non-deterministic random number generator (if any are available). 
.PP
Definition at line 1455 of file tr1_impl/random.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
