.TH "std::pointer_to_binary_function" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::pointer_to_binary_function \- One of the \fBadaptors for function pointers\fP.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fBbinary_function< _Arg1, _Arg2, _Result >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _Arg1 \fBfirst_argument_type\fP"
.br
.ti -1c
.RI "typedef _Result \fBresult_type\fP"
.br
.ti -1c
.RI "typedef _Arg2 \fBsecond_argument_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "_Result \fBoperator()\fP (_Arg1 __x, _Arg2 __y) const "
.br
.ti -1c
.RI "\fBpointer_to_binary_function\fP (_Result(*__x)(_Arg1, _Arg2))"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "_Result(* \fB_M_ptr\fP )(_Arg1, _Arg2)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Arg1, typename _Arg2, typename _Result> class std::pointer_to_binary_function< _Arg1, _Arg2, _Result >"
One of the \fBadaptors for function pointers\fP. 
.PP
Definition at line 442 of file stl_function.h.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef _Arg1  \fBstd::binary_function\fP< _Arg1 , _Arg2 , _Result  >::\fBfirst_argument_type\fP\fC [inherited]\fP"
.PP
the type of the first argument (no surprises here) 
.PP
Definition at line 114 of file stl_function.h.
.SS "typedef _Result  \fBstd::binary_function\fP< _Arg1 , _Arg2 , _Result  >::\fBresult_type\fP\fC [inherited]\fP"
.PP
type of the return type 
.PP
Definition at line 118 of file stl_function.h.
.SS "typedef _Arg2  \fBstd::binary_function\fP< _Arg1 , _Arg2 , _Result  >::\fBsecond_argument_type\fP\fC [inherited]\fP"
.PP
the type of the second argument 
.PP
Definition at line 117 of file stl_function.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
