.TH "std::input_iterator_tag" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::input_iterator_tag \- Marking input iterators.  

.PP
.SH SYNOPSIS
.br
.PP
Inherited by \fBstd::forward_iterator_tag\fP.
.PP
.SH "Detailed Description"
.PP 
Marking input iterators. 
.PP
Definition at line 79 of file stl_iterator_base_types.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
