.TH "std::_Fwd_list_node_base" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::_Fwd_list_node_base \- A helper basic node class for forward_list. This is just a linked \fBlist\fP with nothing inside it. There are purely \fBlist\fP shuffling utility methods here.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _Alloc::template rebind< \fB_Fwd_list_node_base\fP< _Alloc > >::other::const_pointer \fB_Const_pointer\fP"
.br
.ti -1c
.RI "typedef _Alloc::template rebind< \fB_Fwd_list_node_base\fP< _Alloc > >::other::pointer \fB_Pointer\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fB_M_reverse_after\fP ()"
.br
.ti -1c
.RI "void \fB_M_transfer_after\fP (_Pointer __bbegin, _Pointer __bend)"
.br
.ti -1c
.RI "void \fB_M_transfer_after\fP (_Pointer __bbegin)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBswap\fP (\fB_Fwd_list_node_base\fP &__x, \fB_Fwd_list_node_base\fP &__y)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "_Pointer \fB_M_next\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Alloc> struct std::_Fwd_list_node_base< _Alloc >"
A helper basic node class for forward_list. This is just a linked \fBlist\fP with nothing inside it. There are purely \fBlist\fP shuffling utility methods here. 
.PP
Definition at line 53 of file forward_list.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
