.TH "std::ratio_less" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::ratio_less \- \fBratio_less\fP  

.PP
.SH SYNOPSIS
.br
.PP
Inherits __ratio_less_impl::type<_R1, _R2>.
.PP
.SH "Detailed Description"
.PP 

.SS "template<typename _R1, typename _R2> struct std::ratio_less< _R1, _R2 >"
\fBratio_less\fP 
.PP
Definition at line 257 of file ratio.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
