.TH "std::time_get_byname" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::time_get_byname \- class \fBtime_get_byname\fP [22.2.5.2].  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fBtime_get< _CharT, _InIter >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBbasic_string\fP< _CharT > \fB__string_type\fP"
.br
.ti -1c
.RI "typedef _CharT \fBchar_type\fP"
.br
.ti -1c
.RI "enum \fBdateorder\fP { \fBno_order\fP, \fBdmy\fP, \fBmdy\fP, \fBymd\fP, \fBydm\fP }"
.br
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "dateorder \fBdate_order\fP () const"
.br
.ti -1c
.RI "\fBiter_type\fP \fBget_date\fP (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, tm *__tm) const"
.br
.ti -1c
.RI "\fBiter_type\fP \fBget_monthname\fP (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, tm *__tm) const"
.br
.ti -1c
.RI "\fBiter_type\fP \fBget_time\fP (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, tm *__tm) const"
.br
.ti -1c
.RI "\fBiter_type\fP \fBget_weekday\fP (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, tm *__tm) const"
.br
.ti -1c
.RI "\fBiter_type\fP \fBget_year\fP (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, tm *__tm) const"
.br
.ti -1c
.RI "\fBtime_get_byname\fP (const char *, size_t __refs=0)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBlocale::id\fP \fBid\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBiter_type\fP \fB_M_extract_name\fP (\fBiter_type\fP __beg, \fBiter_type\fP __end, int &__member, const _CharT **__names, size_t __indexlen, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err) const"
.br
.ti -1c
.RI "\fBiter_type\fP \fB_M_extract_num\fP (\fBiter_type\fP __beg, \fBiter_type\fP __end, int &__member, int __min, int __max, size_t __len, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err) const"
.br
.ti -1c
.RI "\fBiter_type\fP \fB_M_extract_via_format\fP (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, tm *__tm, const _CharT *__format) const"
.br
.ti -1c
.RI "virtual dateorder \fBdo_date_order\fP () const"
.br
.ti -1c
.RI "virtual \fBiter_type\fP \fBdo_get_date\fP (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, tm *__tm) const"
.br
.ti -1c
.RI "virtual \fBiter_type\fP \fBdo_get_monthname\fP (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP &, \fBios_base::iostate\fP &__err, tm *__tm) const"
.br
.ti -1c
.RI "virtual \fBiter_type\fP \fBdo_get_time\fP (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, tm *__tm) const"
.br
.ti -1c
.RI "virtual \fBiter_type\fP \fBdo_get_weekday\fP (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP &, \fBios_base::iostate\fP &__err, tm *__tm) const"
.br
.ti -1c
.RI "virtual \fBiter_type\fP \fBdo_get_year\fP (\fBiter_type\fP __beg, \fBiter_type\fP __end, \fBios_base\fP &__io, \fBios_base::iostate\fP &__err, tm *__tm) const"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static __c_locale \fB_S_clone_c_locale\fP (__c_locale &__cloc)"
.br
.ti -1c
.RI "static void \fB_S_create_c_locale\fP (__c_locale &__cloc, const char *__s, __c_locale __old=0)"
.br
.ti -1c
.RI "static void \fB_S_destroy_c_locale\fP (__c_locale &__cloc)"
.br
.ti -1c
.RI "static __c_locale \fB_S_get_c_locale\fP ()"
.br
.ti -1c
.RI "static const char * \fB_S_get_c_name\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBlocale::_Impl\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _CharT, typename _InIter> class std::time_get_byname< _CharT, _InIter >"
class \fBtime_get_byname\fP [22.2.5.2]. 
.PP
Definition at line 674 of file locale_facets_nonio.h.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename _CharT , typename _InIter > typedef _CharT \fBstd::time_get_byname\fP< _CharT, _InIter >::\fBchar_type\fP"
.PP
Public typedefs. 
.PP
Reimplemented from \fBstd::time_get< _CharT, _InIter >\fP.
.PP
Definition at line 678 of file locale_facets_nonio.h.
.SS "template<typename _CharT , typename _InIter > typedef _InIter \fBstd::time_get_byname\fP< _CharT, _InIter >::\fBiter_type\fP"
.PP
Public typedefs. 
.PP
Reimplemented from \fBstd::time_get< _CharT, _InIter >\fP.
.PP
Definition at line 679 of file locale_facets_nonio.h.
.SH "Member Function Documentation"
.PP 
.SS "dateorder \fBstd::time_get\fP< _CharT , _InIter  >::date_order () const\fC [inline, inherited]\fP"
.PP
Return preferred order of month, day, and year. 
.PP
This function returns an enum from timebase::dateorder giving the preferred ordering if the format 'x' given to time_put::put() only uses month, day, and year. If the format 'x' for the associated locale uses other fields, this function returns timebase::dateorder::noorder.
.PP
NOTE: The library always returns noorder at the moment.
.PP
\fBReturns:\fP
.RS 4
A member of timebase::dateorder. 
.RE
.PP

.PP
Definition at line 400 of file locale_facets_nonio.h.
.SS "virtual dateorder \fBstd::time_get\fP< _CharT , _InIter  >::do_date_order () const\fC [protected, virtual, inherited]\fP"
.PP
Return preferred order of month, day, and year. 
.PP
This function returns an enum from timebase::dateorder giving the preferred ordering if the format 'x' given to time_put::put() only uses month, day, and year. This function is a hook for derived classes to change the value returned.
.PP
\fBReturns:\fP
.RS 4
A member of timebase::dateorder. 
.RE
.PP

.SS "virtual \fBiter_type\fP \fBstd::time_get\fP< _CharT , _InIter  >::do_get_date (iter_type __beg, iter_type __end, \fBios_base\fP & __io, ios_base::iostate & __err, tm * __tm) const\fC [protected, virtual, inherited]\fP"
.PP
Parse input date string. 
.PP
This function parses a date according to the format 'X' and puts the results into a user-supplied struct tm. This function is a hook for derived classes to change the value returned. 
.PP
\fBSee also:\fP
.RS 4
get_date() for details.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIbeg\fP Start of string to parse. 
.br
\fIend\fP End of string to parse. 
.br
\fIio\fP Source of the locale. 
.br
\fIerr\fP Error flags to set. 
.br
\fItm\fP Pointer to struct tm to fill in. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator to first char beyond date string. 
.RE
.PP

.SS "virtual \fBiter_type\fP \fBstd::time_get\fP< _CharT , _InIter  >::do_get_monthname (iter_type __beg, iter_type __end, \fBios_base\fP &, ios_base::iostate & __err, tm * __tm) const\fC [protected, virtual, inherited]\fP"
.PP
Parse input month string. 
.PP
This function parses a month name and puts the results into a user-supplied struct tm. This function is a hook for derived classes to change the value returned. 
.PP
\fBSee also:\fP
.RS 4
get_monthname() for details.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIbeg\fP Start of string to parse. 
.br
\fIend\fP End of string to parse. 
.br
\fIio\fP Source of the locale. 
.br
\fIerr\fP Error flags to set. 
.br
\fItm\fP Pointer to struct tm to fill in. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator to first char beyond month name. 
.RE
.PP

.SS "virtual \fBiter_type\fP \fBstd::time_get\fP< _CharT , _InIter  >::do_get_time (iter_type __beg, iter_type __end, \fBios_base\fP & __io, ios_base::iostate & __err, tm * __tm) const\fC [protected, virtual, inherited]\fP"
.PP
Parse input time string. 
.PP
This function parses a time according to the format 'x' and puts the results into a user-supplied struct tm. This function is a hook for derived classes to change the value returned. 
.PP
\fBSee also:\fP
.RS 4
get_time() for details.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIbeg\fP Start of string to parse. 
.br
\fIend\fP End of string to parse. 
.br
\fIio\fP Source of the locale. 
.br
\fIerr\fP Error flags to set. 
.br
\fItm\fP Pointer to struct tm to fill in. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator to first char beyond time string. 
.RE
.PP

.SS "virtual \fBiter_type\fP \fBstd::time_get\fP< _CharT , _InIter  >::do_get_weekday (iter_type __beg, iter_type __end, \fBios_base\fP &, ios_base::iostate & __err, tm * __tm) const\fC [protected, virtual, inherited]\fP"
.PP
Parse input weekday string. 
.PP
This function parses a weekday name and puts the results into a user-supplied struct tm. This function is a hook for derived classes to change the value returned. 
.PP
\fBSee also:\fP
.RS 4
get_weekday() for details.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIbeg\fP Start of string to parse. 
.br
\fIend\fP End of string to parse. 
.br
\fIio\fP Source of the locale. 
.br
\fIerr\fP Error flags to set. 
.br
\fItm\fP Pointer to struct tm to fill in. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator to first char beyond weekday name. 
.RE
.PP

.SS "virtual \fBiter_type\fP \fBstd::time_get\fP< _CharT , _InIter  >::do_get_year (iter_type __beg, iter_type __end, \fBios_base\fP & __io, ios_base::iostate & __err, tm * __tm) const\fC [protected, virtual, inherited]\fP"
.PP
Parse input year string. 
.PP
This function reads up to 4 characters to parse a year string and puts the results into a user-supplied struct tm. This function is a hook for derived classes to change the value returned. 
.PP
\fBSee also:\fP
.RS 4
get_year() for details.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIbeg\fP Start of string to parse. 
.br
\fIend\fP End of string to parse. 
.br
\fIio\fP Source of the locale. 
.br
\fIerr\fP Error flags to set. 
.br
\fItm\fP Pointer to struct tm to fill in. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator to first char beyond year. 
.RE
.PP

.SS "\fBiter_type\fP \fBstd::time_get\fP< _CharT , _InIter  >::get_date (iter_type __beg, iter_type __end, \fBios_base\fP & __io, ios_base::iostate & __err, tm * __tm) const\fC [inline, inherited]\fP"
.PP
Parse input date string. 
.PP
This function parses a date according to the format 'X' and puts the results into a user-supplied struct tm. The result is returned by calling time_get::do_get_date().
.PP
If there is a valid date string according to format 'X', \fItm\fP will be filled in accordingly and the returned iterator will point to the first character beyond the date string. If an error occurs before the end, err |= ios_base::failbit. If parsing reads all the characters, err |= ios_base::eofbit.
.PP
\fBParameters:\fP
.RS 4
\fIbeg\fP Start of string to parse. 
.br
\fIend\fP End of string to parse. 
.br
\fIio\fP Source of the locale. 
.br
\fIerr\fP Error flags to set. 
.br
\fItm\fP Pointer to struct tm to fill in. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator to first char beyond date string. 
.RE
.PP

.PP
Definition at line 449 of file locale_facets_nonio.h.
.SS "\fBiter_type\fP \fBstd::time_get\fP< _CharT , _InIter  >::get_monthname (iter_type __beg, iter_type __end, \fBios_base\fP & __io, ios_base::iostate & __err, tm * __tm) const\fC [inline, inherited]\fP"
.PP
Parse input month string. 
.PP
This function parses a month name and puts the results into a user-supplied struct tm. The result is returned by calling time_get::do_get_monthname().
.PP
Parsing starts by parsing an abbreviated month name. If a valid abbreviation is followed by a character that would lead to the full month name, parsing continues until the full name is found or an error occurs. Otherwise parsing finishes at the end of the abbreviated name.
.PP
If an error occurs before the end, err |= ios_base::failbit. If parsing reads all the characters, err |= ios_base::eofbit.
.PP
\fBParameters:\fP
.RS 4
\fIbeg\fP Start of string to parse. 
.br
\fIend\fP End of string to parse. 
.br
\fIio\fP Source of the locale. 
.br
\fIerr\fP Error flags to set. 
.br
\fItm\fP Pointer to struct tm to fill in. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator to first char beyond month name. 
.RE
.PP

.PP
Definition at line 506 of file locale_facets_nonio.h.
.SS "\fBiter_type\fP \fBstd::time_get\fP< _CharT , _InIter  >::get_time (iter_type __beg, iter_type __end, \fBios_base\fP & __io, ios_base::iostate & __err, tm * __tm) const\fC [inline, inherited]\fP"
.PP
Parse input time string. 
.PP
This function parses a time according to the format 'x' and puts the results into a user-supplied struct tm. The result is returned by calling time_get::do_get_time().
.PP
If there is a valid time string according to format 'x', \fItm\fP will be filled in accordingly and the returned iterator will point to the first character beyond the time string. If an error occurs before the end, err |= ios_base::failbit. If parsing reads all the characters, err |= ios_base::eofbit.
.PP
\fBParameters:\fP
.RS 4
\fIbeg\fP Start of string to parse. 
.br
\fIend\fP End of string to parse. 
.br
\fIio\fP Source of the locale. 
.br
\fIerr\fP Error flags to set. 
.br
\fItm\fP Pointer to struct tm to fill in. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator to first char beyond time string. 
.RE
.PP

.PP
Definition at line 424 of file locale_facets_nonio.h.
.SS "\fBiter_type\fP \fBstd::time_get\fP< _CharT , _InIter  >::get_weekday (iter_type __beg, iter_type __end, \fBios_base\fP & __io, ios_base::iostate & __err, tm * __tm) const\fC [inline, inherited]\fP"
.PP
Parse input weekday string. 
.PP
This function parses a weekday name and puts the results into a user-supplied struct tm. The result is returned by calling time_get::do_get_weekday().
.PP
Parsing starts by parsing an abbreviated weekday name. If a valid abbreviation is followed by a character that would lead to the full weekday name, parsing continues until the full name is found or an error occurs. Otherwise parsing finishes at the end of the abbreviated name.
.PP
If an error occurs before the end, err |= ios_base::failbit. If parsing reads all the characters, err |= ios_base::eofbit.
.PP
\fBParameters:\fP
.RS 4
\fIbeg\fP Start of string to parse. 
.br
\fIend\fP End of string to parse. 
.br
\fIio\fP Source of the locale. 
.br
\fIerr\fP Error flags to set. 
.br
\fItm\fP Pointer to struct tm to fill in. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator to first char beyond weekday name. 
.RE
.PP

.PP
Definition at line 477 of file locale_facets_nonio.h.
.SS "\fBiter_type\fP \fBstd::time_get\fP< _CharT , _InIter  >::get_year (iter_type __beg, iter_type __end, \fBios_base\fP & __io, ios_base::iostate & __err, tm * __tm) const\fC [inline, inherited]\fP"
.PP
Parse input year string. 
.PP
This function reads up to 4 characters to parse a year string and puts the results into a user-supplied struct tm. The result is returned by calling time_get::do_get_year().
.PP
4 consecutive digits are interpreted as a full year. If there are exactly 2 consecutive digits, the library interprets this as the number of years since 1900.
.PP
If an error occurs before the end, err |= ios_base::failbit. If parsing reads all the characters, err |= ios_base::eofbit.
.PP
\fBParameters:\fP
.RS 4
\fIbeg\fP Start of string to parse. 
.br
\fIend\fP End of string to parse. 
.br
\fIio\fP Source of the locale. 
.br
\fIerr\fP Error flags to set. 
.br
\fItm\fP Pointer to struct tm to fill in. 
.RE
.PP
\fBReturns:\fP
.RS 4
Iterator to first char beyond year. 
.RE
.PP

.PP
Definition at line 532 of file locale_facets_nonio.h.
.SH "Member Data Documentation"
.PP 
.SS "\fBlocale::id\fP \fBstd::time_get\fP< _CharT , _InIter  >::\fBid\fP\fC [static, inherited]\fP"
.PP
Numpunct facet id. 
.PP
Definition at line 373 of file locale_facets_nonio.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
