.TH "std::condition_variable" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::condition_variable \- \fBcondition_variable\fP  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef __native_type * \fBnative_handle_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcondition_variable\fP (const \fBcondition_variable\fP &)"
.br
.ti -1c
.RI "native_handle_type \fBnative_handle\fP ()"
.br
.ti -1c
.RI "void \fBnotify_all\fP ()"
.br
.ti -1c
.RI "void \fBnotify_one\fP ()"
.br
.ti -1c
.RI "\fBcondition_variable\fP & \fBoperator=\fP (const \fBcondition_variable\fP &)"
.br
.ti -1c
.RI "template<typename _Predicate > void \fBwait\fP (\fBunique_lock\fP< \fBmutex\fP > &__lock, _Predicate __p)"
.br
.ti -1c
.RI "void \fBwait\fP (\fBunique_lock\fP< \fBmutex\fP > &__lock)"
.br
.ti -1c
.RI "template<typename _Rep , typename _Period , typename _Predicate > bool \fBwait_for\fP (\fBunique_lock\fP< \fBmutex\fP > &__lock, const \fBchrono::duration\fP< _Rep, _Period > &__rtime, _Predicate __p)"
.br
.ti -1c
.RI "template<typename _Rep , typename _Period > bool \fBwait_for\fP (\fBunique_lock\fP< \fBmutex\fP > &__lock, const \fBchrono::duration\fP< _Rep, _Period > &__rtime)"
.br
.ti -1c
.RI "template<typename _Clock , typename _Duration , typename _Predicate > bool \fBwait_until\fP (\fBunique_lock\fP< \fBmutex\fP > &__lock, const chrono::time_point< _Clock, _Duration > &__atime, _Predicate __p)"
.br
.ti -1c
.RI "template<typename _Clock , typename _Duration > bool \fBwait_until\fP (\fBunique_lock\fP< \fBmutex\fP > &__lock, const chrono::time_point< _Clock, _Duration > &__atime)"
.br
.ti -1c
.RI "template<typename _Duration > bool \fBwait_until\fP (\fBunique_lock\fP< \fBmutex\fP > &__lock, const chrono::time_point< __clock_t, _Duration > &__atime)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBcondition_variable\fP 
.PP
Definition at line 54 of file condition_variable.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
