.TH "std::binder2nd" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::binder2nd \- One of the \fBbinder functors\fP.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fBunary_function< _Operation::first_argument_type, _Operation::result_type >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _Operation::first_argument_type \fBargument_type\fP"
.br
.ti -1c
.RI "typedef _Operation::result_type \fBresult_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbinder2nd\fP (const _Operation &__x, const typename _Operation::second_argument_type &__y)"
.br
.ti -1c
.RI "_Operation::result_type \fBoperator()\fP (typename _Operation::first_argument_type &__x) const "
.br
.ti -1c
.RI "_Operation::result_type \fBoperator()\fP (const typename _Operation::first_argument_type &__x) const "
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "_Operation \fBop\fP"
.br
.ti -1c
.RI "_Operation::second_argument_type \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Operation> class std::binder2nd< _Operation >"
One of the \fBbinder functors\fP. 
.PP
Definition at line 132 of file binders.h.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef _Operation::first_argument_type  \fBstd::unary_function\fP< _Operation::first_argument_type , _Operation::result_type  >::\fBargument_type\fP\fC [inherited]\fP"
.PP
\fCargument_type\fP is the type of the argument (no surprises here) 
.PP
Definition at line 102 of file stl_function.h.
.SS "typedef _Operation::result_type  \fBstd::unary_function\fP< _Operation::first_argument_type , _Operation::result_type  >::\fBresult_type\fP\fC [inherited]\fP"
.PP
\fCresult_type\fP is the return type 
.PP
Definition at line 105 of file stl_function.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
