.TH "std::unique_lock" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::unique_lock \- \fBunique_lock\fP  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _Mutex \fBmutex_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBlock\fP ()"
.br
.ti -1c
.RI "mutex_type * \fBmutex\fP () const "
.br
.ti -1c
.RI "\fBoperator bool\fP () const "
.br
.ti -1c
.RI "\fBunique_lock\fP & \fBoperator=\fP (\fBunique_lock\fP &&__u)"
.br
.ti -1c
.RI "\fBunique_lock\fP & \fBoperator=\fP (const \fBunique_lock\fP &)"
.br
.ti -1c
.RI "bool \fBowns_lock\fP () const "
.br
.ti -1c
.RI "mutex_type * \fBrelease\fP ()"
.br
.ti -1c
.RI "void \fBswap\fP (\fBunique_lock\fP &&__u)"
.br
.ti -1c
.RI "bool \fBtry_lock\fP ()"
.br
.ti -1c
.RI "template<typename _Rep , typename _Period > bool \fBtry_lock_for\fP (const \fBchrono::duration\fP< _Rep, _Period > &__rtime)"
.br
.ti -1c
.RI "template<typename _Clock , typename _Duration > bool \fBtry_lock_until\fP (const chrono::time_point< _Clock, _Duration > &__atime)"
.br
.ti -1c
.RI "\fBunique_lock\fP (\fBunique_lock\fP &&__u)"
.br
.ti -1c
.RI "\fBunique_lock\fP (const \fBunique_lock\fP &)"
.br
.ti -1c
.RI "template<typename _Rep , typename _Period > \fBunique_lock\fP (mutex_type &__m, const \fBchrono::duration\fP< _Rep, _Period > &__rtime)"
.br
.ti -1c
.RI "template<typename _Clock , typename _Duration > \fBunique_lock\fP (mutex_type &__m, const chrono::time_point< _Clock, _Duration > &__atime)"
.br
.ti -1c
.RI "\fBunique_lock\fP (mutex_type &__m, \fBadopt_lock_t\fP)"
.br
.ti -1c
.RI "\fBunique_lock\fP (mutex_type &__m, \fBtry_to_lock_t\fP)"
.br
.ti -1c
.RI "\fBunique_lock\fP (mutex_type &__m, \fBdefer_lock_t\fP)"
.br
.ti -1c
.RI "\fBunique_lock\fP (mutex_type &__m)"
.br
.ti -1c
.RI "void \fBunlock\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Mutex> class std::unique_lock< _Mutex >"
\fBunique_lock\fP 
.PP
Definition at line 428 of file mutex.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
