.TH "std::_Maybe_unary_or_binary_function" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::_Maybe_unary_or_binary_function \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SS "template<typename _Res, typename... _ArgTypes> struct std::_Maybe_unary_or_binary_function< _Res, _ArgTypes >"
Derives from \fC\fBunary_function\fP\fP or \fC\fBbinary_function\fP\fP, or perhaps nothing, depending on the number of arguments provided. The primary template is the basis case, which derives nothing. 
.PP
Definition at line 509 of file tr1_impl/functional.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
