.TH "stdexcept" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stdexcept \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBstd::domain_error\fP"
.br
.ti -1c
.RI "class \fBstd::invalid_argument\fP"
.br
.ti -1c
.RI "class \fBstd::length_error\fP"
.br
.ti -1c
.RI "class \fBstd::logic_error\fP"
.br
.RI "\fIOne of two subclasses of \fBexception\fP. \fP"
.ti -1c
.RI "class \fBstd::out_of_range\fP"
.br
.ti -1c
.RI "class \fBstd::overflow_error\fP"
.br
.ti -1c
.RI "class \fBstd::range_error\fP"
.br
.ti -1c
.RI "class \fBstd::runtime_error\fP"
.br
.RI "\fIOne of two subclasses of \fBexception\fP. \fP"
.ti -1c
.RI "class \fBstd::underflow_error\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBstd\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB_GLIBCXX_STDEXCEPT\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is a Standard C++ Library header. 
.PP
Definition in file \fBstdexcept\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
