.TH "streambuf" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
streambuf \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBstd::basic_streambuf< _CharT, _Traits >\fP"
.br
.RI "\fIThe actual work of input and output (interface). \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBstd\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB_GLIBXX_STREAMBUF\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<> streamsize \fBstd::__copy_streambufs_eof\fP (basic_streambuf< wchar_t > *__sbin, basic_streambuf< wchar_t > *__sbout, bool &__ineof)"
.br
.ti -1c
.RI "template<> streamsize \fBstd::__copy_streambufs_eof\fP (basic_streambuf< char > *__sbin, basic_streambuf< char > *__sbout, bool &__ineof)"
.br
.ti -1c
.RI "template<typename _CharT , typename _Traits > streamsize \fBstd::__copy_streambufs_eof\fP (basic_streambuf< _CharT, _Traits > *, basic_streambuf< _CharT, _Traits > *, bool &)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is a Standard C++ Library header. 
.PP
Definition in file \fBstreambuf\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
