.TH "system_error" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
system_error \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBstd::error_category\fP"
.br
.RI "\fI\fBerror_category\fP \fP"
.ti -1c
.RI "struct \fBstd::error_code\fP"
.br
.RI "\fI\fBerror_code\fP \fP"
.ti -1c
.RI "struct \fBstd::error_condition\fP"
.br
.RI "\fI\fBerror_condition\fP \fP"
.ti -1c
.RI "struct \fBstd::is_error_code_enum< _Tp >\fP"
.br
.RI "\fI\fBis_error_code_enum\fP \fP"
.ti -1c
.RI "struct \fBstd::is_error_condition_enum< _Tp >\fP"
.br
.RI "\fI\fBis_error_condition_enum\fP \fP"
.ti -1c
.RI "class \fBstd::system_error\fP"
.br
.RI "\fIThrown to indicate error code of underlying system. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBstd\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB_GLIBCXX_SYSTEM_ERROR\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "const error_category & \fBstd::generic_category\fP ()"
.br
.ti -1c
.RI "error_code \fBstd::make_error_code\fP (errc __e)"
.br
.ti -1c
.RI "error_condition \fBstd::make_error_condition\fP (errc __e)"
.br
.ti -1c
.RI "bool \fBstd::operator!=\fP (const error_condition &__lhs, const error_condition &__rhs)"
.br
.ti -1c
.RI "bool \fBstd::operator!=\fP (const error_condition &__lhs, const error_code &__rhs)"
.br
.ti -1c
.RI "bool \fBstd::operator!=\fP (const error_code &__lhs, const error_condition &__rhs)"
.br
.ti -1c
.RI "bool \fBstd::operator!=\fP (const error_code &__lhs, const error_code &__rhs)"
.br
.ti -1c
.RI "bool \fBstd::operator<\fP (const error_condition &__lhs, const error_condition &__rhs)"
.br
.ti -1c
.RI "bool \fBstd::operator<\fP (const error_code &__lhs, const error_code &__rhs)"
.br
.ti -1c
.RI "template<typename _CharT , typename _Traits > basic_ostream< _CharT, _Traits > & \fBstd::operator<<\fP (basic_ostream< _CharT, _Traits > &__os, const error_code &__e)"
.br
.ti -1c
.RI "bool \fBstd::operator==\fP (const error_condition &__lhs, const error_condition &__rhs)"
.br
.ti -1c
.RI "bool \fBstd::operator==\fP (const error_condition &__lhs, const error_code &__rhs)"
.br
.ti -1c
.RI "bool \fBstd::operator==\fP (const error_code &__lhs, const error_condition &__rhs)"
.br
.ti -1c
.RI "bool \fBstd::operator==\fP (const error_code &__lhs, const error_code &__rhs)"
.br
.ti -1c
.RI "const error_category & \fBstd::system_category\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is a Standard C++ Library header. 
.PP
Definition in file \fBsystem_error\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
