.TH "thread" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
thread \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBstd::thread\fP"
.br
.RI "\fI\fBthread\fP \fP"
.ti -1c
.RI "class \fBstd::thread::thread::id\fP"
.br
.RI "\fI\fBthread::id\fP \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBstd\fP"
.br
.ti -1c
.RI "namespace \fBstd::this_thread\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB_GLIBCXX_THREAD\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "thread::id \fBstd::this_thread::get_id\fP ()"
.br
.ti -1c
.RI "bool \fBstd::operator!=\fP (thread::id __x, thread::id __y)"
.br
.ti -1c
.RI "template<class _CharT , class _Traits > basic_ostream< _CharT, _Traits > & \fBstd::operator<<\fP (basic_ostream< _CharT, _Traits > &&__out, thread::id __id)"
.br
.ti -1c
.RI "bool \fBstd::operator<=\fP (thread::id __x, thread::id __y)"
.br
.ti -1c
.RI "bool \fBstd::operator>\fP (thread::id __x, thread::id __y)"
.br
.ti -1c
.RI "bool \fBstd::operator>=\fP (thread::id __x, thread::id __y)"
.br
.ti -1c
.RI "template<typename _Rep , typename _Period > void \fBstd::this_thread::sleep_for\fP (const chrono::duration< _Rep, _Period > &__rtime)"
.br
.ti -1c
.RI "template<typename _Clock , typename _Duration > void \fBstd::this_thread::sleep_until\fP (const chrono::time_point< _Clock, _Duration > &__atime)"
.br
.ti -1c
.RI "void \fBstd::swap\fP (thread &__x, thread &&__y)"
.br
.ti -1c
.RI "void \fBstd::swap\fP (thread &&__x, thread &__y)"
.br
.ti -1c
.RI "void \fBstd::swap\fP (thread &__x, thread &__y)"
.br
.ti -1c
.RI "void \fBstd::this_thread::yield\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is a Standard C++ Library header. 
.PP
Definition in file \fBthread\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
