.TH "todo" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 
 
.IP "\fBClass \fB__gnu_cxx::hash_map< _Key, _Tp, _HashFn, _EqualKey, _Alloc >\fP \fP" 1c
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBClass \fB__gnu_cxx::hash_multimap< _Key, _Tp, _HashFn, _EqualKey, _Alloc >\fP \fP" 1c
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBClass \fB__gnu_cxx::hash_multiset< _Value, _HashFcn, _EqualKey, _Alloc >\fP \fP" 1c
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBClass \fB__gnu_cxx::hash_set< _Value, _HashFcn, _EqualKey, _Alloc >\fP \fP" 1c
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBClass \fB__gnu_cxx::rb_tree< _Key, _Value, _KeyOfValue, _Compare, _Alloc >\fP \fP" 1c
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBClass \fB__gnu_cxx::rope< _CharT, _Alloc >\fP \fP" 1c
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBClass \fB__gnu_cxx::slist< _Tp, _Alloc >\fP \fP" 1c
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBMember \fB__gnu_debug::_Safe_iterator::operator->\fP() const  \fP" 1c
Make this correct w.r.t. iterators that return proxies 
.PP
Use addressof() instead of & operator 
.PP
.PP
 
.IP "\fBClass \fBstd::basic_string< _CharT, _Traits, _Alloc >\fP \fP" 1c
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more.
.PP
.PP
.PP
 
.IP "\fBMember \fBstd::match_results::format\fP(const string_type &__fmt, regex_constants::match_flag_type __flags=regex_constantsformat_default) const  \fP" 1c
Implement this function. 
.PP
.PP
 
.IP "\fBMember \fBstd::match_results::format\fP(_Out_iter __out, const string_type &__fmt, regex_constants::match_flag_type __flags=regex_constantsformat_default) const  \fP" 1c
Implement this function. 
.PP
.PP
 
.IP "\fBMember \fBstd::regex_iterator::regex_iterator\fP() \fP" 1c
Implement this function. 
.PP
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBMember \fBstd::regex_iterator::regex_iterator\fP(_Bi_iter __a, _Bi_iter __b, const regex_type &__re, regex_constants::match_flag_type __m=regex_constantsmatch_default) \fP" 1c
Implement this function. 
.PP
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBMember \fBstd::regex_iterator::regex_iterator\fP(const regex_iterator &__rhs) \fP" 1c
Implement this function. 
.PP
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBMember \fBstd::regex_iterator::operator!=\fP(const regex_iterator &__rhs) \fP" 1c
Implement this function. 
.PP
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBMember \fBstd::regex_iterator::operator*\fP() \fP" 1c
Implement this function. 
.PP
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBMember \fBstd::regex_iterator::operator++\fP(int) \fP" 1c
Implement this function. 
.PP
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBMember \fBstd::regex_iterator::operator++\fP() \fP" 1c
Implement this function. 
.PP
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBMember \fBstd::regex_iterator::operator->\fP() \fP" 1c
Implement this function. 
.PP
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBMember \fBstd::regex_iterator::operator=\fP(const regex_iterator &__rhs) \fP" 1c
Implement this function. 
.PP
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBMember \fBstd::regex_iterator::operator==\fP(const regex_iterator &__rhs) \fP" 1c
Implement this function. 
.PP
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBMember \fBstd::regex_token_iterator::regex_token_iterator\fP() \fP" 1c
Implement this function.
.PP
.PP
.PP
 
.IP "\fBMember \fBstd::regex_token_iterator::regex_token_iterator\fP(_Bi_iter __a, _Bi_iter __b, const regex_type &__re, int __submatch=0, regex_constants::match_flag_type __m=regex_constantsmatch_default) \fP" 1c
Implement this function. 
.PP
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBMember \fBstd::regex_token_iterator::regex_token_iterator\fP(_Bi_iter __a, _Bi_iter __b, const regex_type &__re, const std::vector< int > &__submatches, regex_constants::match_flag_type __m=regex_constantsmatch_default) \fP" 1c
Implement this function. 
.PP
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBMember \fBstd::regex_token_iterator::regex_token_iterator\fP(_Bi_iter __a, _Bi_iter __b, const regex_type &__re, const int(&__submatches)[_Nm], regex_constants::match_flag_type __m=regex_constantsmatch_default) \fP" 1c
Implement this function. 
.PP
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBMember \fBstd::regex_token_iterator::regex_token_iterator\fP(const regex_token_iterator &__rhs) \fP" 1c
Implement this function. 
.PP
.PP
 
.IP "\fBMember \fBstd::regex_token_iterator::operator!=\fP(const regex_token_iterator &__rhs) \fP" 1c
Implement this function. 
.PP
.PP
 
.IP "\fBMember \fBstd::regex_token_iterator::operator*\fP() \fP" 1c
Implement this function. 
.PP
.PP
 
.IP "\fBMember \fBstd::regex_token_iterator::operator++\fP(int) \fP" 1c
Implement this function. 
.PP
.PP
 
.IP "\fBMember \fBstd::regex_token_iterator::operator++\fP() \fP" 1c
Implement this function. 
.PP
.PP
 
.IP "\fBMember \fBstd::regex_token_iterator::operator->\fP() \fP" 1c
Implement this function. 
.PP
.PP
 
.IP "\fBMember \fBstd::regex_token_iterator::operator=\fP(const regex_token_iterator &__rhs) \fP" 1c
Implement this function. 
.PP
.PP
 
.IP "\fBMember \fBstd::regex_token_iterator::operator==\fP(const regex_token_iterator &__rhs) \fP" 1c
Implement this function. 
.PP
.PP
 
.IP "\fBMember \fBstd::regex_traits::lookup_classname\fP(_Fwd_iter __first, _Fwd_iter __last) const  \fP" 1c
Implement this function. 
.PP
.PP
 
.IP "\fBMember \fBstd::regex_traits::lookup_collatename\fP(_Fwd_iter __first, _Fwd_iter __last) const  \fP" 1c
Implement this function. 
.PP
.PP
 
.IP "\fBMember \fBstd::regex_traits::transform_primary\fP(_Fwd_iter __first, _Fwd_iter __last) const  \fP" 1c
Implement this function. 
.PP
.PP
 
.IP "\fBMember \fBstd::reverse_iterator::operator*\fP() const  \fP" 1c
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBMember \fBstd::reverse_iterator::operator+\fP(difference_type __n) const  \fP" 1c
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBMember \fBstd::reverse_iterator::operator++\fP(int) \fP" 1c
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBMember \fBstd::reverse_iterator::operator++\fP() \fP" 1c
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBMember \fBstd::reverse_iterator::operator+=\fP(difference_type __n) \fP" 1c
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBMember \fBstd::reverse_iterator::operator-\fP(difference_type __n) const  \fP" 1c
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBMember \fBstd::reverse_iterator::operator--\fP(int) \fP" 1c
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBMember \fBstd::reverse_iterator::operator--\fP() \fP" 1c
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBMember \fBstd::reverse_iterator::operator-=\fP(difference_type __n) \fP" 1c
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBMember \fBstd::reverse_iterator::operator->\fP() const  \fP" 1c
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBMember \fBstd::reverse_iterator::operator[]\fP(difference_type __n) const  \fP" 1c
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBClass \fBstd::variate_generator< _Engine, _Dist >\fP \fP" 1c
the engine_value_type needs to be studied more carefully. 
.PP
.PP
 
.IP "\fBMember \fBstd::tr1::__detail::__conf_hyperg\fP(const _Tp __a, const _Tp __c, const _Tp __x) \fP" 1c
Handle b == nonpositive integer blowup - return NaN.
.PP
.PP
.PP
 
.IP "\fBMember \fB__gnu_cxx::distance\fP(_InputIterator __first, _InputIterator __last, _Distance &__n) \fP" 1c
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBMember \fB__gnu_cxx::iota\fP(_ForwardIter __first, _ForwardIter __last, _Tp __value) \fP" 1c
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBMember \fB__gnu_cxx::is_heap\fP(_RandomAccessIterator __first, _RandomAccessIterator __last, _StrictWeakOrdering __comp) \fP" 1c
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBMember \fB__gnu_cxx::is_heap\fP(_RandomAccessIterator __first, _RandomAccessIterator __last) \fP" 1c
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBMember \fB__gnu_cxx::is_sorted\fP(_ForwardIterator __first, _ForwardIterator __last, _StrictWeakOrdering __comp) \fP" 1c
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBMember \fB__gnu_cxx::is_sorted\fP(_ForwardIterator __first, _ForwardIterator __last) \fP" 1c
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBMember \fB__gnu_cxx::power\fP(_Tp __x, _Integer __n) \fP" 1c
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBMember \fB__gnu_cxx::power\fP(_Tp __x, _Integer __n, _MonoidOperation __monoid_op) \fP" 1c
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBMember \fB__gnu_cxx::random_sample\fP(_InputIterator __first, _InputIterator __last, _RandomAccessIterator __out_first, _RandomAccessIterator __out_last, _RandomNumberGenerator &__rand) \fP" 1c
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBMember \fB__gnu_cxx::random_sample\fP(_InputIterator __first, _InputIterator __last, _RandomAccessIterator __out_first, _RandomAccessIterator __out_last) \fP" 1c
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBMember \fB__gnu_cxx::random_sample_n\fP(_ForwardIterator __first, _ForwardIterator __last, _OutputIterator __out, const _Distance __n, _RandomNumberGenerator &__rand) \fP" 1c
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBMember \fB__gnu_cxx::random_sample_n\fP(_ForwardIterator __first, _ForwardIterator __last, _OutputIterator __out, const _Distance __n) \fP" 1c
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBMember \fBstd::regex_match\fP(_Bi_iter __first, _Bi_iter __last, match_results< _Bi_iter, _Allocator > &__m, const basic_regex< _Ch_type, _Rx_traits > &__re, regex_constants::match_flag_type __flags=regex_constantsmatch_default) \fP" 1c
Implement this function. 
.PP
.PP
 
.IP "\fBMember \fBstd::regex_replace\fP(const basic_string< _Ch_type > &__s, const basic_regex< _Ch_type, _Rx_traits > &__e, const basic_string< _Ch_type > &__fmt, regex_constants::match_flag_type __flags=regex_constantsmatch_default) \fP" 1c
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBMember \fBstd::regex_replace\fP(_Out_iter __out, _Bi_iter __first, _Bi_iter __last, const basic_regex< _Ch_type, _Rx_traits > &__e, const basic_string< _Ch_type > &__fmt, regex_constants::match_flag_type __flags=regex_constantsmatch_default) \fP" 1c
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more. 
.PP
.PP
 
.IP "\fBMember \fBstd::regex_replace\fP(_Out_iter __out, _Bi_iter __first, _Bi_iter __last, const basic_regex< _Ch_type, _Rx_traits > &__e, const basic_string< _Ch_type > &__fmt, regex_constants::match_flag_type __flags=regex_constantsmatch_default) \fP" 1c
Implement this function. 
.PP
.PP
 
.IP "\fBMember \fBstd::regex_search\fP(const basic_string< _Ch_type, _Ch_traits, _String_allocator > &__s, const basic_regex< _Ch_type, _Rx_traits > &__e, regex_constants::match_flag_type __flags=regex_constantsmatch_default) \fP" 1c
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more.
.PP
.PP
.PP
 
.IP "\fBMember \fBstd::regex_search\fP(const _Ch_type *__s, const basic_regex< _Ch_type, _Rx_traits > &__e, regex_constants::match_flag_type __f=regex_constantsmatch_default) \fP" 1c
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more.
.PP
.PP
.PP
 
.IP "\fBMember \fBstd::regex_search\fP(const _Ch_type *__s, match_results< const _Ch_type *, _Allocator > &__m, const basic_regex< _Ch_type, _Rx_traits > &__e, regex_constants::match_flag_type __f=regex_constantsmatch_default) \fP" 1c
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more.
.PP
.PP
.PP
 
.IP "\fBMember \fBstd::regex_search\fP(_Bi_iter __first, _Bi_iter __last, const basic_regex< _Ch_type, _Rx_traits > &__re, regex_constants::match_flag_type __flags=regex_constantsmatch_default) \fP" 1c
Doc me! See doc/doxygen/TODO and http://gcc.gnu.org/ml/libstdc++/2002-02/msg00003.html for more.
.PP
.PP
.PP
 
.IP "\fBMember \fBstd::regex_search\fP(_Bi_iter __first, _Bi_iter __last, match_results< _Bi_iter, _Allocator > &__m, const basic_regex< _Ch_type, _Rx_traits > &__re, regex_constants::match_flag_type __flags=regex_constantsmatch_default) \fP" 1c
Implement this function. 
.PP
.PP
 
.IP "\fBMember \fBstd::operator==\fP(const match_results< _Bi_iter, _Allocator > &__m1, const match_results< _Bi_iter, _Allocator > &__m2) \fP" 1c
Implement this function. 
.PP

