.TH "typeinfo" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
typeinfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBstd::bad_cast\fP"
.br
.RI "\fIThrown during incorrect typecasting.
.PP
If you attempt an invalid \fCdynamic_cast\fP expression, an instance of this class (or something derived from this class) is thrown. \fP"
.ti -1c
.RI "class \fBstd::bad_typeid\fP"
.br
.RI "\fIThrown when a NULL pointer in a \fCtypeid\fP expression is used. \fP"
.ti -1c
.RI "class \fBstd::type_info\fP"
.br
.RI "\fIPart of RTTI. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBstd\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB__GXX_MERGED_TYPEINFO_NAMES\fP"
.br
.ti -1c
.RI "#define \fB__GXX_TYPEINFO_EQUALITY_INLINE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is a Standard C++ Library header. 
.PP
Definition in file \fBtypeinfo\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
