.TH "type_traits" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
type_traits \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBstd::add_lvalue_reference< _Tp >\fP"
.br
.RI "\fI\fBadd_lvalue_reference\fP \fP"
.ti -1c
.RI "struct \fBstd::add_rvalue_reference< _Tp >\fP"
.br
.RI "\fI\fBadd_rvalue_reference\fP \fP"
.ti -1c
.RI "struct \fBstd::is_lvalue_reference< typename >\fP"
.br
.RI "\fI\fBis_lvalue_reference\fP \fP"
.ti -1c
.RI "struct \fBstd::is_reference< _Tp >\fP"
.br
.RI "\fI\fBis_reference\fP \fP"
.ti -1c
.RI "struct \fBstd::is_rvalue_reference< typename >\fP"
.br
.RI "\fI\fBis_rvalue_reference\fP \fP"
.ti -1c
.RI "struct \fBstd::remove_reference< _Tp >\fP"
.br
.RI "\fI\fBremove_reference\fP \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBstd\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB_GLIBCXX_TYPE_TRAITS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is a Standard C++ Library header. 
.PP
Definition in file \fBtype_traits\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
