.TH "Unordered Associative Containers" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Unordered Associative Containers \- 
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBstd::unordered_map< _Key, _Tp, _Hash, _Pred, _Alloc >\fP"
.br
.RI "\fIA standard container composed of unique keys (containing at most one of each key value) that associates values of another type with the keys. \fP"
.ti -1c
.RI "class \fBstd::unordered_multimap< _Key, _Tp, _Hash, _Pred, _Alloc >\fP"
.br
.RI "\fIA standard container composed of equivalent keys (possibly containing multiple of each key value) that associates values of another type with the keys. \fP"
.ti -1c
.RI "class \fBstd::unordered_multiset< _Value, _Hash, _Pred, _Alloc >\fP"
.br
.RI "\fIA standard container composed of equivalent keys (possibly containing multiple of each key value) in which the elements' keys are the elements themselves. \fP"
.ti -1c
.RI "class \fBstd::unordered_set< _Value, _Hash, _Pred, _Alloc >\fP"
.br
.RI "\fIA standard container composed of unique keys (containing at most one of each key value) in which the elements' keys are the elements themselves. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Unordered associative containers allow fast retrieval of data based on keys.
.PP
Each container type is parameterized on a \fCKey\fP type, a \fCHash\fP type providing a hashing functor, and an ordering relation used to sort the elements of the container.
.PP
All unordered associative containers must meet certain requirements, summarized in \fCtables\fP. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
