.TH "Utilities" 3 "21 Apr 2009" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Utilities \- 
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBTime\fP"
.br
.ti -1c
.RI "\fBMemory\fP"
.br
.ti -1c
.RI "\fBRational Arithmetic\fP"
.br
.ti -1c
.RI "\fBType Traits\fP"
.br
.ti -1c
.RI "\fBFunction Objects\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Components deemed generally useful. Includes pair, tuple, forward/move helpers, ratio, function object, metaprogramming and type traits, time, date, and memory functions. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
