# arg 1:  the new package version
# arg 2:  the old package version

KERNEL_NAME=-armv7-rc
KERNEL_VERSION=4.10.0-rc4-1-ARCH

post_install () {
  # updating module dependencies
  echo ">>> Updating module dependencies. Please wait ..."
  depmod ${KERNEL_VERSION}
}

post_upgrade() {
  # updating module dependencies
  echo ">>> Updating module dependencies. Please wait ..."
  depmod ${KERNEL_VERSION}
}

post_remove() {
  rm -f boot/initramfs-linux.img
}
