post_install() {
  if [ ! `/bin/grep osiris /etc/group` ]; then
    /usr/sbin/groupadd -g 18 osiris &>/dev/null;
  fi

  /usr/bin/id osiris &>/dev/null || \
    /usr/sbin/useradd -u 18 -g osiris -d /var/lib/osiris -s /bin/false osiris
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  /usr/sbin/userdel osiris &> /dev/null
  /usr/sbin/groupdel osiris &> /dev/null
}

post_remove() {
  /bin/true
}

op=$1
shift

$op $*
# vim: ts=2 sw=2 et ft=sh
