post_install() {
	if [ ! "`grep /usr/lib/libfakechroot etc/ld.so.conf`" ]; then
		echo -n "updating /etc/ld.so.conf... "
		echo "/usr/lib/libfakechroot" >>etc/ld.so.conf
		sbin/ldconfig -r .
		echo "done."
	fi
}

post_upgrade() {
	post_install $1
}

pre_remove() {
	echo -ne "\nupdating /etc/ld.so.conf... "
	sed -i -e '/\/usr\/lib\/libfakechroot/d' etc/ld.so.conf
	sbin/ldconfig -r .
	echo "done."
}
