infodir=/usr/share/info
filelist=(gcompris.info)

post_install() {
  for file in ${filelist[@]}; do
    install-info $infodir/$file $infodir/dir 2> /dev/null
  done
  update-desktop-database -q
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  for file in ${filelist[@]}; do
    install-info --delete $infodir/$file $infodir/dir 2> /dev/null
  done
}

post_remove() {
  update-desktop-database -q
}

# vim:set ts=2 sw=2 et:
