#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

PID=`pidof -o %PPID /usr/sbin/dansguardian`
case "$1" in
  start)
    stat_busy "Starting DansGuardian"
    [ -z "$PID" ] && /usr/sbin/dansguardian
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon dansguardian
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping DansGuardian"
    [ ! -z "$PID" ]  && /usr/sbin/dansguardian -q &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon dansguardian
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
