post_install () {
  echo "**********************************************************************"
  echo "To keep fake-hwclock up to date in case of a power failure, add the"
  echo "following job to root crontab: "
  echo "*/15 * * * * /usr/lib/systemd/scripts/fake-hwclock.sh set"
  echo "**********************************************************************"
}

post_upgrade () {
  post_install
}
