post_install(){
   echo " "
   echo "This is an experimental VDPAU implementation for sunxi SoCs.

Most features of full VDPAU are missing, only decoding of h264, mpeg1 and
mpeg2 will work. Output bypasses X video driver, hence don't try to use Xv
at the same time.
Only tested with mplayer, if other players need unimplemented functions
something will fail."
   echo "$ export VDPAU_DRIVER=sunxi"
   echo "$ mplayer -vo vdpau -vc ffmpeg12vdpau,ffh264vdpau [filename]"
   echo " "
}