post_install() {
  if [ ! `grep proxy /etc/group` ]; then
    groupadd -g 15 proxy &>/dev/null;
  fi

  id proxy &>/dev/null || \
    useradd -u 15 -g proxy -d /var/empty proxy

  chown proxy.proxy var/{cache,log}/squid

  cat << EOF
Release notes for version 2.7:
    http://www.squid-cache.org/Versions/v2/2.7/RELEASENOTES.html

EOF
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  userdel proxy &> /dev/null
  groupdel proxy &> /dev/null
}

op=$1
shift

$op $*
